/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dao;

import it.csi.rebus.anagraficasrv.integration.dto.RebusTVariazAutobusDTO;
import it.csi.rebus.anagraficasrv.integration.dto.RebusTVariazAutobusSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusTVariazAutobusDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus.rebus_t_variaz_autobus
	 * @mbg.generated  Thu Nov 12 12:00:31 CET 2020
	 */
	long countByExample(RebusTVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus.rebus_t_variaz_autobus
	 * @mbg.generated  Thu Nov 12 12:00:31 CET 2020
	 */
	int deleteByExample(RebusTVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus.rebus_t_variaz_autobus
	 * @mbg.generated  Thu Nov 12 12:00:31 CET 2020
	 */
	int deleteByPrimaryKey(Long idVariazAutobus);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus.rebus_t_variaz_autobus
	 * @mbg.generated  Thu Nov 12 12:00:31 CET 2020
	 */
	int insert(RebusTVariazAutobusDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus.rebus_t_variaz_autobus
	 * @mbg.generated  Thu Nov 12 12:00:31 CET 2020
	 */
	int insertSelective(RebusTVariazAutobusDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus.rebus_t_variaz_autobus
	 * @mbg.generated  Thu Nov 12 12:00:31 CET 2020
	 */
	List<RebusTVariazAutobusDTO> selectByExample(RebusTVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus.rebus_t_variaz_autobus
	 * @mbg.generated  Thu Nov 12 12:00:31 CET 2020
	 */
	RebusTVariazAutobusDTO selectByPrimaryKey(Long idVariazAutobus);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus.rebus_t_variaz_autobus
	 * @mbg.generated  Thu Nov 12 12:00:31 CET 2020
	 */
	int updateByExampleSelective(@Param("record") RebusTVariazAutobusDTO record,
			@Param("example") RebusTVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus.rebus_t_variaz_autobus
	 * @mbg.generated  Thu Nov 12 12:00:31 CET 2020
	 */
	int updateByExample(@Param("record") RebusTVariazAutobusDTO record,
			@Param("example") RebusTVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus.rebus_t_variaz_autobus
	 * @mbg.generated  Thu Nov 12 12:00:31 CET 2020
	 */
	int updateByPrimaryKeySelective(RebusTVariazAutobusDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus.rebus_t_variaz_autobus
	 * @mbg.generated  Thu Nov 12 12:00:31 CET 2020
	 */
	int updateByPrimaryKey(RebusTVariazAutobusDTO record);
}