/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dao;

import it.csi.rebus.anagraficasrv.integration.dto.SirtplaDNaturaGiuridicaDTO;
import it.csi.rebus.anagraficasrv.integration.dto.SirtplaDNaturaGiuridicaSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirtplaDNaturaGiuridicaDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_natura_giuridica
	 * @mbg.generated  Thu May 07 10:24:01 CEST 2020
	 */
	long countByExample(SirtplaDNaturaGiuridicaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_natura_giuridica
	 * @mbg.generated  Thu May 07 10:24:01 CEST 2020
	 */
	int deleteByExample(SirtplaDNaturaGiuridicaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_natura_giuridica
	 * @mbg.generated  Thu May 07 10:24:01 CEST 2020
	 */
	int deleteByPrimaryKey(Long idNaturaGiuridica);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_natura_giuridica
	 * @mbg.generated  Thu May 07 10:24:01 CEST 2020
	 */
	int insert(SirtplaDNaturaGiuridicaDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_natura_giuridica
	 * @mbg.generated  Thu May 07 10:24:01 CEST 2020
	 */
	int insertSelective(SirtplaDNaturaGiuridicaDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_natura_giuridica
	 * @mbg.generated  Thu May 07 10:24:01 CEST 2020
	 */
	List<SirtplaDNaturaGiuridicaDTO> selectByExample(SirtplaDNaturaGiuridicaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_natura_giuridica
	 * @mbg.generated  Thu May 07 10:24:01 CEST 2020
	 */
	SirtplaDNaturaGiuridicaDTO selectByPrimaryKey(Long idNaturaGiuridica);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_natura_giuridica
	 * @mbg.generated  Thu May 07 10:24:01 CEST 2020
	 */
	int updateByExampleSelective(@Param("record") SirtplaDNaturaGiuridicaDTO record, @Param("example") SirtplaDNaturaGiuridicaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_natura_giuridica
	 * @mbg.generated  Thu May 07 10:24:01 CEST 2020
	 */
	int updateByExample(@Param("record") SirtplaDNaturaGiuridicaDTO record, @Param("example") SirtplaDNaturaGiuridicaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_natura_giuridica
	 * @mbg.generated  Thu May 07 10:24:01 CEST 2020
	 */
	int updateByPrimaryKeySelective(SirtplaDNaturaGiuridicaDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_natura_giuridica
	 * @mbg.generated  Thu May 07 10:24:01 CEST 2020
	 */
	int updateByPrimaryKey(SirtplaDNaturaGiuridicaDTO record);
}