/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dao;

import it.csi.rebus.anagraficasrv.integration.dto.SirtplaTDatoBancarioDTO;
import it.csi.rebus.anagraficasrv.integration.dto.SirtplaTDatoBancarioSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirtplaTDatoBancarioDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	long countByExample(SirtplaTDatoBancarioSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	int deleteByExample(SirtplaTDatoBancarioSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	int deleteByPrimaryKey(Long idDatoBancario);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	int insert(SirtplaTDatoBancarioDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	int insertSelective(SirtplaTDatoBancarioDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	List<SirtplaTDatoBancarioDTO> selectByExample(SirtplaTDatoBancarioSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	SirtplaTDatoBancarioDTO selectByPrimaryKey(Long idDatoBancario);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	int updateByExampleSelective(@Param("record") SirtplaTDatoBancarioDTO record, @Param("example") SirtplaTDatoBancarioSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	int updateByExample(@Param("record") SirtplaTDatoBancarioDTO record, @Param("example") SirtplaTDatoBancarioSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	int updateByPrimaryKeySelective(SirtplaTDatoBancarioDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	int updateByPrimaryKey(SirtplaTDatoBancarioDTO record);
}