/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dao;

import it.csi.rebus.anagraficasrv.integration.dto.SirtplcRContrattoRaggruppDTO;
import it.csi.rebus.anagraficasrv.integration.dto.SirtplcRContrattoRaggruppSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirtplcRContrattoRaggruppDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_raggrupp
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    long countByExample(SirtplcRContrattoRaggruppSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_raggrupp
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int deleteByExample(SirtplcRContrattoRaggruppSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_raggrupp
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int deleteByPrimaryKey(Long idContrattoRaggrupp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_raggrupp
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int insert(SirtplcRContrattoRaggruppDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_raggrupp
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int insertSelective(SirtplcRContrattoRaggruppDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_raggrupp
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    List<SirtplcRContrattoRaggruppDTO> selectByExample(SirtplcRContrattoRaggruppSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_raggrupp
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    SirtplcRContrattoRaggruppDTO selectByPrimaryKey(Long idContrattoRaggrupp);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_raggrupp
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int updateByExampleSelective(@Param("record") SirtplcRContrattoRaggruppDTO record, @Param("example") SirtplcRContrattoRaggruppSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_raggrupp
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int updateByExample(@Param("record") SirtplcRContrattoRaggruppDTO record, @Param("example") SirtplcRContrattoRaggruppSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_raggrupp
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int updateByPrimaryKeySelective(SirtplcRContrattoRaggruppDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_raggrupp
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int updateByPrimaryKey(SirtplcRContrattoRaggruppDTO record);
}