/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dao;

import it.csi.rebus.anagraficasrv.integration.dto.SirtplcTPercorrenzaDTO;
import it.csi.rebus.anagraficasrv.integration.dto.SirtplcTPercorrenzaSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirtplcTPercorrenzaDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    long countByExample(SirtplcTPercorrenzaSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int deleteByExample(SirtplcTPercorrenzaSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int deleteByPrimaryKey(Long idPercorrenza);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int insert(SirtplcTPercorrenzaDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int insertSelective(SirtplcTPercorrenzaDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    List<SirtplcTPercorrenzaDTO> selectByExample(SirtplcTPercorrenzaSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    SirtplcTPercorrenzaDTO selectByPrimaryKey(Long idPercorrenza);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int updateByExampleSelective(@Param("record") SirtplcTPercorrenzaDTO record, @Param("example") SirtplcTPercorrenzaSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int updateByExample(@Param("record") SirtplcTPercorrenzaDTO record, @Param("example") SirtplcTPercorrenzaSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int updateByPrimaryKeySelective(SirtplcTPercorrenzaDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    int updateByPrimaryKey(SirtplcTPercorrenzaDTO record);
}