/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dao;

import it.csi.rebus.anagraficasrv.integration.dto.SirtplcRAmbTipServizioDTO;
import it.csi.rebus.anagraficasrv.integration.dto.SirtplcRAmbTipServizioSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirtplcRAmbTipServizioDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_amb_tip_servizio
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	long countByExample(SirtplcRAmbTipServizioSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_amb_tip_servizio
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int deleteByExample(SirtplcRAmbTipServizioSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_amb_tip_servizio
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int deleteByPrimaryKey(Long idAmbTipServizio);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_amb_tip_servizio
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int insert(SirtplcRAmbTipServizioDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_amb_tip_servizio
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int insertSelective(SirtplcRAmbTipServizioDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_amb_tip_servizio
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	List<SirtplcRAmbTipServizioDTO> selectByExample(SirtplcRAmbTipServizioSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_amb_tip_servizio
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	SirtplcRAmbTipServizioDTO selectByPrimaryKey(Long idAmbTipServizio);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_amb_tip_servizio
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int updateByExampleSelective(@Param("record") SirtplcRAmbTipServizioDTO record,
			@Param("example") SirtplcRAmbTipServizioSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_amb_tip_servizio
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int updateByExample(@Param("record") SirtplcRAmbTipServizioDTO record,
			@Param("example") SirtplcRAmbTipServizioSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_amb_tip_servizio
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int updateByPrimaryKeySelective(SirtplcRAmbTipServizioDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_amb_tip_servizio
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int updateByPrimaryKey(SirtplcRAmbTipServizioDTO record);
}