/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dao;

import it.csi.rebus.anagraficasrv.integration.dto.SirtplaDTipoSogGiuridicoDTO;
import it.csi.rebus.anagraficasrv.integration.dto.SirtplaDTipoSogGiuridicoSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirtplaDTipoSogGiuridicoDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_tipo_sog_giuridico
	 * @mbg.generated  Fri Jan 15 10:23:15 CET 2021
	 */
	long countByExample(SirtplaDTipoSogGiuridicoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_tipo_sog_giuridico
	 * @mbg.generated  Fri Jan 15 10:23:15 CET 2021
	 */
	int deleteByExample(SirtplaDTipoSogGiuridicoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_tipo_sog_giuridico
	 * @mbg.generated  Fri Jan 15 10:23:15 CET 2021
	 */
	int deleteByPrimaryKey(Long idTipoSogGiuridico);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_tipo_sog_giuridico
	 * @mbg.generated  Fri Jan 15 10:23:15 CET 2021
	 */
	int insert(SirtplaDTipoSogGiuridicoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_tipo_sog_giuridico
	 * @mbg.generated  Fri Jan 15 10:23:15 CET 2021
	 */
	int insertSelective(SirtplaDTipoSogGiuridicoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_tipo_sog_giuridico
	 * @mbg.generated  Fri Jan 15 10:23:15 CET 2021
	 */
	List<SirtplaDTipoSogGiuridicoDTO> selectByExample(SirtplaDTipoSogGiuridicoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_tipo_sog_giuridico
	 * @mbg.generated  Fri Jan 15 10:23:15 CET 2021
	 */
	SirtplaDTipoSogGiuridicoDTO selectByPrimaryKey(Long idTipoSogGiuridico);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_tipo_sog_giuridico
	 * @mbg.generated  Fri Jan 15 10:23:15 CET 2021
	 */
	int updateByExampleSelective(@Param("record") SirtplaDTipoSogGiuridicoDTO record,
			@Param("example") SirtplaDTipoSogGiuridicoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_tipo_sog_giuridico
	 * @mbg.generated  Fri Jan 15 10:23:15 CET 2021
	 */
	int updateByExample(@Param("record") SirtplaDTipoSogGiuridicoDTO record,
			@Param("example") SirtplaDTipoSogGiuridicoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_tipo_sog_giuridico
	 * @mbg.generated  Fri Jan 15 10:23:15 CET 2021
	 */
	int updateByPrimaryKeySelective(SirtplaDTipoSogGiuridicoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_d_tipo_sog_giuridico
	 * @mbg.generated  Fri Jan 15 10:23:15 CET 2021
	 */
	int updateByPrimaryKey(SirtplaDTipoSogGiuridicoDTO record);
}