/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dao;

import it.csi.rebus.anagraficasrv.integration.dto.SirtplcDTipoRaggruppamentoDTO;
import it.csi.rebus.anagraficasrv.integration.dto.SirtplcDTipoRaggruppamentoSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirtplcDTipoRaggruppamentoDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_tipo_raggruppamento
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	long countByExample(SirtplcDTipoRaggruppamentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_tipo_raggruppamento
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int deleteByExample(SirtplcDTipoRaggruppamentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_tipo_raggruppamento
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int deleteByPrimaryKey(Long idTipoRaggruppamento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_tipo_raggruppamento
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int insert(SirtplcDTipoRaggruppamentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_tipo_raggruppamento
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int insertSelective(SirtplcDTipoRaggruppamentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_tipo_raggruppamento
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	List<SirtplcDTipoRaggruppamentoDTO> selectByExample(SirtplcDTipoRaggruppamentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_tipo_raggruppamento
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	SirtplcDTipoRaggruppamentoDTO selectByPrimaryKey(Long idTipoRaggruppamento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_tipo_raggruppamento
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int updateByExampleSelective(@Param("record") SirtplcDTipoRaggruppamentoDTO record,
			@Param("example") SirtplcDTipoRaggruppamentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_tipo_raggruppamento
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int updateByExample(@Param("record") SirtplcDTipoRaggruppamentoDTO record,
			@Param("example") SirtplcDTipoRaggruppamentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_tipo_raggruppamento
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int updateByPrimaryKeySelective(SirtplcDTipoRaggruppamentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_tipo_raggruppamento
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	int updateByPrimaryKey(SirtplcDTipoRaggruppamentoDTO record);
}