/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SirtplcDBacinoSelector {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	public SirtplcDBacinoSelector() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdBacinoIsNull() {
			addCriterion("id_bacino is null");
			return (Criteria) this;
		}

		public Criteria andIdBacinoIsNotNull() {
			addCriterion("id_bacino is not null");
			return (Criteria) this;
		}

		public Criteria andIdBacinoEqualTo(Long value) {
			addCriterion("id_bacino =", value, "idBacino");
			return (Criteria) this;
		}

		public Criteria andIdBacinoNotEqualTo(Long value) {
			addCriterion("id_bacino <>", value, "idBacino");
			return (Criteria) this;
		}

		public Criteria andIdBacinoGreaterThan(Long value) {
			addCriterion("id_bacino >", value, "idBacino");
			return (Criteria) this;
		}

		public Criteria andIdBacinoGreaterThanOrEqualTo(Long value) {
			addCriterion("id_bacino >=", value, "idBacino");
			return (Criteria) this;
		}

		public Criteria andIdBacinoLessThan(Long value) {
			addCriterion("id_bacino <", value, "idBacino");
			return (Criteria) this;
		}

		public Criteria andIdBacinoLessThanOrEqualTo(Long value) {
			addCriterion("id_bacino <=", value, "idBacino");
			return (Criteria) this;
		}

		public Criteria andIdBacinoIn(List<Long> values) {
			addCriterion("id_bacino in", values, "idBacino");
			return (Criteria) this;
		}

		public Criteria andIdBacinoNotIn(List<Long> values) {
			addCriterion("id_bacino not in", values, "idBacino");
			return (Criteria) this;
		}

		public Criteria andIdBacinoBetween(Long value1, Long value2) {
			addCriterion("id_bacino between", value1, value2, "idBacino");
			return (Criteria) this;
		}

		public Criteria andIdBacinoNotBetween(Long value1, Long value2) {
			addCriterion("id_bacino not between", value1, value2, "idBacino");
			return (Criteria) this;
		}

		public Criteria andDenomBacinoIsNull() {
			addCriterion("denom_bacino is null");
			return (Criteria) this;
		}

		public Criteria andDenomBacinoIsNotNull() {
			addCriterion("denom_bacino is not null");
			return (Criteria) this;
		}

		public Criteria andDenomBacinoEqualTo(String value) {
			addCriterion("denom_bacino =", value, "denomBacino");
			return (Criteria) this;
		}

		public Criteria andDenomBacinoNotEqualTo(String value) {
			addCriterion("denom_bacino <>", value, "denomBacino");
			return (Criteria) this;
		}

		public Criteria andDenomBacinoGreaterThan(String value) {
			addCriterion("denom_bacino >", value, "denomBacino");
			return (Criteria) this;
		}

		public Criteria andDenomBacinoGreaterThanOrEqualTo(String value) {
			addCriterion("denom_bacino >=", value, "denomBacino");
			return (Criteria) this;
		}

		public Criteria andDenomBacinoLessThan(String value) {
			addCriterion("denom_bacino <", value, "denomBacino");
			return (Criteria) this;
		}

		public Criteria andDenomBacinoLessThanOrEqualTo(String value) {
			addCriterion("denom_bacino <=", value, "denomBacino");
			return (Criteria) this;
		}

		public Criteria andDenomBacinoLike(String value) {
			addCriterion("denom_bacino like", value, "denomBacino");
			return (Criteria) this;
		}

		public Criteria andDenomBacinoNotLike(String value) {
			addCriterion("denom_bacino not like", value, "denomBacino");
			return (Criteria) this;
		}

		public Criteria andDenomBacinoIn(List<String> values) {
			addCriterion("denom_bacino in", values, "denomBacino");
			return (Criteria) this;
		}

		public Criteria andDenomBacinoNotIn(List<String> values) {
			addCriterion("denom_bacino not in", values, "denomBacino");
			return (Criteria) this;
		}

		public Criteria andDenomBacinoBetween(String value1, String value2) {
			addCriterion("denom_bacino between", value1, value2, "denomBacino");
			return (Criteria) this;
		}

		public Criteria andDenomBacinoNotBetween(String value1, String value2) {
			addCriterion("denom_bacino not between", value1, value2, "denomBacino");
			return (Criteria) this;
		}

		public Criteria andDescBacinoIsNull() {
			addCriterion("desc_bacino is null");
			return (Criteria) this;
		}

		public Criteria andDescBacinoIsNotNull() {
			addCriterion("desc_bacino is not null");
			return (Criteria) this;
		}

		public Criteria andDescBacinoEqualTo(String value) {
			addCriterion("desc_bacino =", value, "descBacino");
			return (Criteria) this;
		}

		public Criteria andDescBacinoNotEqualTo(String value) {
			addCriterion("desc_bacino <>", value, "descBacino");
			return (Criteria) this;
		}

		public Criteria andDescBacinoGreaterThan(String value) {
			addCriterion("desc_bacino >", value, "descBacino");
			return (Criteria) this;
		}

		public Criteria andDescBacinoGreaterThanOrEqualTo(String value) {
			addCriterion("desc_bacino >=", value, "descBacino");
			return (Criteria) this;
		}

		public Criteria andDescBacinoLessThan(String value) {
			addCriterion("desc_bacino <", value, "descBacino");
			return (Criteria) this;
		}

		public Criteria andDescBacinoLessThanOrEqualTo(String value) {
			addCriterion("desc_bacino <=", value, "descBacino");
			return (Criteria) this;
		}

		public Criteria andDescBacinoLike(String value) {
			addCriterion("desc_bacino like", value, "descBacino");
			return (Criteria) this;
		}

		public Criteria andDescBacinoNotLike(String value) {
			addCriterion("desc_bacino not like", value, "descBacino");
			return (Criteria) this;
		}

		public Criteria andDescBacinoIn(List<String> values) {
			addCriterion("desc_bacino in", values, "descBacino");
			return (Criteria) this;
		}

		public Criteria andDescBacinoNotIn(List<String> values) {
			addCriterion("desc_bacino not in", values, "descBacino");
			return (Criteria) this;
		}

		public Criteria andDescBacinoBetween(String value1, String value2) {
			addCriterion("desc_bacino between", value1, value2, "descBacino");
			return (Criteria) this;
		}

		public Criteria andDescBacinoNotBetween(String value1, String value2) {
			addCriterion("desc_bacino not between", value1, value2, "descBacino");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaIsNull() {
			addCriterion("data_inizio_validita is null");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaIsNotNull() {
			addCriterion("data_inizio_validita is not null");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaEqualTo(Date value) {
			addCriterionForJDBCDate("data_inizio_validita =", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaNotEqualTo(Date value) {
			addCriterionForJDBCDate("data_inizio_validita <>", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaGreaterThan(Date value) {
			addCriterionForJDBCDate("data_inizio_validita >", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_inizio_validita >=", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaLessThan(Date value) {
			addCriterionForJDBCDate("data_inizio_validita <", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_inizio_validita <=", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaIn(List<Date> values) {
			addCriterionForJDBCDate("data_inizio_validita in", values, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaNotIn(List<Date> values) {
			addCriterionForJDBCDate("data_inizio_validita not in", values, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_inizio_validita between", value1, value2, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_inizio_validita not between", value1, value2, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaIsNull() {
			addCriterion("data_fine_validita is null");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaIsNotNull() {
			addCriterion("data_fine_validita is not null");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaEqualTo(Date value) {
			addCriterionForJDBCDate("data_fine_validita =", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaNotEqualTo(Date value) {
			addCriterionForJDBCDate("data_fine_validita <>", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaGreaterThan(Date value) {
			addCriterionForJDBCDate("data_fine_validita >", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_fine_validita >=", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaLessThan(Date value) {
			addCriterionForJDBCDate("data_fine_validita <", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_fine_validita <=", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaIn(List<Date> values) {
			addCriterionForJDBCDate("data_fine_validita in", values, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaNotIn(List<Date> values) {
			addCriterionForJDBCDate("data_fine_validita not in", values, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_fine_validita between", value1, value2, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_fine_validita not between", value1, value2, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDenomBacinoLikeInsensitive(String value) {
			addCriterion("upper(denom_bacino) like", value.toUpperCase(), "denomBacino");
			return (Criteria) this;
		}

		public Criteria andDescBacinoLikeInsensitive(String value) {
			addCriterion("upper(desc_bacino) like", value.toUpperCase(), "descBacino");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sirtplc_d_bacino
	 * @mbg.generated  Mon Nov 04 11:33:48 CET 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sirtplc_d_bacino
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 21 14:07:51 CEST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}