/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dto;

import java.io.Serializable;

public class SirtplcDTipoPercorenzaDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_d_tipo_percorenza.id_tipo_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    private Long idTipoPercorrenza;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_d_tipo_percorenza.desc_tipo_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    private String descTipoPercorrenza;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirtplc_d_tipo_percorenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_d_tipo_percorenza.id_tipo_percorrenza
     *
     * @return the value of sirtplc_d_tipo_percorenza.id_tipo_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public Long getIdTipoPercorrenza() {
        return idTipoPercorrenza;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_d_tipo_percorenza.id_tipo_percorrenza
     *
     * @param idTipoPercorrenza the value for sirtplc_d_tipo_percorenza.id_tipo_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public void setIdTipoPercorrenza(Long idTipoPercorrenza) {
        this.idTipoPercorrenza = idTipoPercorrenza;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_d_tipo_percorenza.desc_tipo_percorrenza
     *
     * @return the value of sirtplc_d_tipo_percorenza.desc_tipo_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public String getDescTipoPercorrenza() {
        return descTipoPercorrenza;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_d_tipo_percorenza.desc_tipo_percorrenza
     *
     * @param descTipoPercorrenza the value for sirtplc_d_tipo_percorenza.desc_tipo_percorrenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public void setDescTipoPercorrenza(String descTipoPercorrenza) {
        this.descTipoPercorrenza = descTipoPercorrenza == null ? null : descTipoPercorrenza.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_d_tipo_percorenza
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idTipoPercorrenza=").append(idTipoPercorrenza);
        sb.append(", descTipoPercorrenza=").append(descTipoPercorrenza);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}