/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dto;

import java.io.Serializable;

public class SirtplcRContrAmbTipServKey extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_r_contr_amb_tip_serv.id_contratto
     *
     * @mbg.generated Tue Nov 12 14:18:40 CET 2019
     */
    private Long idContratto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_r_contr_amb_tip_serv.id_amb_tip_servizio
     *
     * @mbg.generated Tue Nov 12 14:18:40 CET 2019
     */
    private Long idAmbTipServizio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirtplc_r_contr_amb_tip_serv
     *
     * @mbg.generated Tue Nov 12 14:18:40 CET 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_r_contr_amb_tip_serv.id_contratto
     *
     * @return the value of sirtplc_r_contr_amb_tip_serv.id_contratto
     *
     * @mbg.generated Tue Nov 12 14:18:40 CET 2019
     */
    public Long getIdContratto() {
        return idContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_r_contr_amb_tip_serv.id_contratto
     *
     * @param idContratto the value for sirtplc_r_contr_amb_tip_serv.id_contratto
     *
     * @mbg.generated Tue Nov 12 14:18:40 CET 2019
     */
    public void setIdContratto(Long idContratto) {
        this.idContratto = idContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_r_contr_amb_tip_serv.id_amb_tip_servizio
     *
     * @return the value of sirtplc_r_contr_amb_tip_serv.id_amb_tip_servizio
     *
     * @mbg.generated Tue Nov 12 14:18:40 CET 2019
     */
    public Long getIdAmbTipServizio() {
        return idAmbTipServizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_r_contr_amb_tip_serv.id_amb_tip_servizio
     *
     * @param idAmbTipServizio the value for sirtplc_r_contr_amb_tip_serv.id_amb_tip_servizio
     *
     * @mbg.generated Tue Nov 12 14:18:40 CET 2019
     */
    public void setIdAmbTipServizio(Long idAmbTipServizio) {
        this.idAmbTipServizio = idAmbTipServizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contr_amb_tip_serv
     *
     * @mbg.generated Tue Nov 12 14:18:40 CET 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idContratto=").append(idContratto);
        sb.append(", idAmbTipServizio=").append(idAmbTipServizio);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}