/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dto;

import java.io.Serializable;

public class SirtplaDRuoloSogGiuridicoDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtpla_d_ruolo_sog_giuridico.id_ruolo_sog_giuridico
     *
     * @mbg.generated Fri Jan 15 10:23:15 CET 2021
     */
    private Long idRuoloSogGiuridico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtpla_d_ruolo_sog_giuridico.cod_ruolo_sog_giuridico
     *
     * @mbg.generated Fri Jan 15 10:23:15 CET 2021
     */
    private String codRuoloSogGiuridico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtpla_d_ruolo_sog_giuridico.desc_ruolo_sog_giuridico
     *
     * @mbg.generated Fri Jan 15 10:23:15 CET 2021
     */
    private String descRuoloSogGiuridico;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirtpla_d_ruolo_sog_giuridico
     *
     * @mbg.generated Fri Jan 15 10:23:15 CET 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtpla_d_ruolo_sog_giuridico.id_ruolo_sog_giuridico
     *
     * @return the value of sirtpla_d_ruolo_sog_giuridico.id_ruolo_sog_giuridico
     *
     * @mbg.generated Fri Jan 15 10:23:15 CET 2021
     */
    public Long getIdRuoloSogGiuridico() {
        return idRuoloSogGiuridico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtpla_d_ruolo_sog_giuridico.id_ruolo_sog_giuridico
     *
     * @param idRuoloSogGiuridico the value for sirtpla_d_ruolo_sog_giuridico.id_ruolo_sog_giuridico
     *
     * @mbg.generated Fri Jan 15 10:23:15 CET 2021
     */
    public void setIdRuoloSogGiuridico(Long idRuoloSogGiuridico) {
        this.idRuoloSogGiuridico = idRuoloSogGiuridico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtpla_d_ruolo_sog_giuridico.cod_ruolo_sog_giuridico
     *
     * @return the value of sirtpla_d_ruolo_sog_giuridico.cod_ruolo_sog_giuridico
     *
     * @mbg.generated Fri Jan 15 10:23:15 CET 2021
     */
    public String getCodRuoloSogGiuridico() {
        return codRuoloSogGiuridico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtpla_d_ruolo_sog_giuridico.cod_ruolo_sog_giuridico
     *
     * @param codRuoloSogGiuridico the value for sirtpla_d_ruolo_sog_giuridico.cod_ruolo_sog_giuridico
     *
     * @mbg.generated Fri Jan 15 10:23:15 CET 2021
     */
    public void setCodRuoloSogGiuridico(String codRuoloSogGiuridico) {
        this.codRuoloSogGiuridico = codRuoloSogGiuridico == null ? null : codRuoloSogGiuridico.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtpla_d_ruolo_sog_giuridico.desc_ruolo_sog_giuridico
     *
     * @return the value of sirtpla_d_ruolo_sog_giuridico.desc_ruolo_sog_giuridico
     *
     * @mbg.generated Fri Jan 15 10:23:15 CET 2021
     */
    public String getDescRuoloSogGiuridico() {
        return descRuoloSogGiuridico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtpla_d_ruolo_sog_giuridico.desc_ruolo_sog_giuridico
     *
     * @param descRuoloSogGiuridico the value for sirtpla_d_ruolo_sog_giuridico.desc_ruolo_sog_giuridico
     *
     * @mbg.generated Fri Jan 15 10:23:15 CET 2021
     */
    public void setDescRuoloSogGiuridico(String descRuoloSogGiuridico) {
        this.descRuoloSogGiuridico = descRuoloSogGiuridico == null ? null : descRuoloSogGiuridico.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_d_ruolo_sog_giuridico
     *
     * @mbg.generated Fri Jan 15 10:23:15 CET 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idRuoloSogGiuridico=").append(idRuoloSogGiuridico);
        sb.append(", codRuoloSogGiuridico=").append(codRuoloSogGiuridico);
        sb.append(", descRuoloSogGiuridico=").append(descRuoloSogGiuridico);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}