/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class SirtplcDVincoloDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_d_vincolo.id_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    private Long idVincolo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_d_vincolo.desc_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    private String descVincolo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_d_vincolo.data_inizio_validita
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    private Date dataInizioValidita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_d_vincolo.data_fine_validita
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    private Date dataFineValidita;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirtplc_d_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_d_vincolo.id_vincolo
     *
     * @return the value of sirtplc_d_vincolo.id_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public Long getIdVincolo() {
        return idVincolo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_d_vincolo.id_vincolo
     *
     * @param idVincolo the value for sirtplc_d_vincolo.id_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public void setIdVincolo(Long idVincolo) {
        this.idVincolo = idVincolo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_d_vincolo.desc_vincolo
     *
     * @return the value of sirtplc_d_vincolo.desc_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public String getDescVincolo() {
        return descVincolo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_d_vincolo.desc_vincolo
     *
     * @param descVincolo the value for sirtplc_d_vincolo.desc_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public void setDescVincolo(String descVincolo) {
        this.descVincolo = descVincolo == null ? null : descVincolo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_d_vincolo.data_inizio_validita
     *
     * @return the value of sirtplc_d_vincolo.data_inizio_validita
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public Date getDataInizioValidita() {
        return dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_d_vincolo.data_inizio_validita
     *
     * @param dataInizioValidita the value for sirtplc_d_vincolo.data_inizio_validita
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public void setDataInizioValidita(Date dataInizioValidita) {
        this.dataInizioValidita = dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_d_vincolo.data_fine_validita
     *
     * @return the value of sirtplc_d_vincolo.data_fine_validita
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public Date getDataFineValidita() {
        return dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_d_vincolo.data_fine_validita
     *
     * @param dataFineValidita the value for sirtplc_d_vincolo.data_fine_validita
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public void setDataFineValidita(Date dataFineValidita) {
        this.dataFineValidita = dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_d_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idVincolo=").append(idVincolo);
        sb.append(", descVincolo=").append(descVincolo);
        sb.append(", dataInizioValidita=").append(dataInizioValidita);
        sb.append(", dataFineValidita=").append(dataFineValidita);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}