/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class SirtplaTDatoBancarioDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpla_t_dato_bancario.id_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	private Long idDatoBancario;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpla_t_dato_bancario.id_soggetto_giuridico
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	private Long idSoggettoGiuridico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpla_t_dato_bancario.iban
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	private String iban;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpla_t_dato_bancario.note
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpla_t_dato_bancario.id_utente_aggiornamento
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	private Long idUtenteAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpla_t_dato_bancario.data_aggiornamento
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	private Date dataAggiornamento;
	
	private Boolean doatpl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sirtpla_t_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpla_t_dato_bancario.id_dato_bancario
	 * @return  the value of sirtpla_t_dato_bancario.id_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	public Long getIdDatoBancario() {
		return idDatoBancario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpla_t_dato_bancario.id_dato_bancario
	 * @param idDatoBancario  the value for sirtpla_t_dato_bancario.id_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	public void setIdDatoBancario(Long idDatoBancario) {
		this.idDatoBancario = idDatoBancario;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpla_t_dato_bancario.id_soggetto_giuridico
	 * @return  the value of sirtpla_t_dato_bancario.id_soggetto_giuridico
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	public Long getIdSoggettoGiuridico() {
		return idSoggettoGiuridico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpla_t_dato_bancario.id_soggetto_giuridico
	 * @param idSoggettoGiuridico  the value for sirtpla_t_dato_bancario.id_soggetto_giuridico
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	public void setIdSoggettoGiuridico(Long idSoggettoGiuridico) {
		this.idSoggettoGiuridico = idSoggettoGiuridico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpla_t_dato_bancario.iban
	 * @return  the value of sirtpla_t_dato_bancario.iban
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	public String getIban() {
		return iban;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpla_t_dato_bancario.iban
	 * @param iban  the value for sirtpla_t_dato_bancario.iban
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	public void setIban(String iban) {
		this.iban = iban == null ? null : iban.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpla_t_dato_bancario.note
	 * @return  the value of sirtpla_t_dato_bancario.note
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpla_t_dato_bancario.note
	 * @param note  the value for sirtpla_t_dato_bancario.note
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpla_t_dato_bancario.id_utente_aggiornamento
	 * @return  the value of sirtpla_t_dato_bancario.id_utente_aggiornamento
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	public Long getIdUtenteAggiornamento() {
		return idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpla_t_dato_bancario.id_utente_aggiornamento
	 * @param idUtenteAggiornamento  the value for sirtpla_t_dato_bancario.id_utente_aggiornamento
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	public void setIdUtenteAggiornamento(Long idUtenteAggiornamento) {
		this.idUtenteAggiornamento = idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpla_t_dato_bancario.data_aggiornamento
	 * @return  the value of sirtpla_t_dato_bancario.data_aggiornamento
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpla_t_dato_bancario.data_aggiornamento
	 * @param dataAggiornamento  the value for sirtpla_t_dato_bancario.data_aggiornamento
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	public Boolean getDoatpl() {
		return doatpl;
	}

	public void setDoatpl(Boolean doatpl) {
		this.doatpl = doatpl;
	}
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_dato_bancario
	 * @mbg.generated  Mon Oct 21 14:09:21 CEST 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idDatoBancario=").append(idDatoBancario);
		sb.append(", idSoggettoGiuridico=").append(idSoggettoGiuridico);
		sb.append(", iban=").append(iban);
		sb.append(", note=").append(note);
		sb.append(", idUtenteAggiornamento=").append(idUtenteAggiornamento);
		sb.append(", dataAggiornamento=").append(dataAggiornamento);
		sb.append(", doatpl=").append(doatpl);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	
}