/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SirtplcRContrattoVincoloSelector {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public SirtplcRContrattoVincoloSelector() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdContrattoVincoloIsNull() {
            addCriterion("id_contratto_vincolo is null");
            return (Criteria) this;
        }

        public Criteria andIdContrattoVincoloIsNotNull() {
            addCriterion("id_contratto_vincolo is not null");
            return (Criteria) this;
        }

        public Criteria andIdContrattoVincoloEqualTo(Long value) {
            addCriterion("id_contratto_vincolo =", value, "idContrattoVincolo");
            return (Criteria) this;
        }

        public Criteria andIdContrattoVincoloNotEqualTo(Long value) {
            addCriterion("id_contratto_vincolo <>", value, "idContrattoVincolo");
            return (Criteria) this;
        }

        public Criteria andIdContrattoVincoloGreaterThan(Long value) {
            addCriterion("id_contratto_vincolo >", value, "idContrattoVincolo");
            return (Criteria) this;
        }

        public Criteria andIdContrattoVincoloGreaterThanOrEqualTo(Long value) {
            addCriterion("id_contratto_vincolo >=", value, "idContrattoVincolo");
            return (Criteria) this;
        }

        public Criteria andIdContrattoVincoloLessThan(Long value) {
            addCriterion("id_contratto_vincolo <", value, "idContrattoVincolo");
            return (Criteria) this;
        }

        public Criteria andIdContrattoVincoloLessThanOrEqualTo(Long value) {
            addCriterion("id_contratto_vincolo <=", value, "idContrattoVincolo");
            return (Criteria) this;
        }

        public Criteria andIdContrattoVincoloIn(List<Long> values) {
            addCriterion("id_contratto_vincolo in", values, "idContrattoVincolo");
            return (Criteria) this;
        }

        public Criteria andIdContrattoVincoloNotIn(List<Long> values) {
            addCriterion("id_contratto_vincolo not in", values, "idContrattoVincolo");
            return (Criteria) this;
        }

        public Criteria andIdContrattoVincoloBetween(Long value1, Long value2) {
            addCriterion("id_contratto_vincolo between", value1, value2, "idContrattoVincolo");
            return (Criteria) this;
        }

        public Criteria andIdContrattoVincoloNotBetween(Long value1, Long value2) {
            addCriterion("id_contratto_vincolo not between", value1, value2, "idContrattoVincolo");
            return (Criteria) this;
        }

        public Criteria andIdContrattoIsNull() {
            addCriterion("id_contratto is null");
            return (Criteria) this;
        }

        public Criteria andIdContrattoIsNotNull() {
            addCriterion("id_contratto is not null");
            return (Criteria) this;
        }

        public Criteria andIdContrattoEqualTo(Long value) {
            addCriterion("id_contratto =", value, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoNotEqualTo(Long value) {
            addCriterion("id_contratto <>", value, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoGreaterThan(Long value) {
            addCriterion("id_contratto >", value, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoGreaterThanOrEqualTo(Long value) {
            addCriterion("id_contratto >=", value, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoLessThan(Long value) {
            addCriterion("id_contratto <", value, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoLessThanOrEqualTo(Long value) {
            addCriterion("id_contratto <=", value, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoIn(List<Long> values) {
            addCriterion("id_contratto in", values, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoNotIn(List<Long> values) {
            addCriterion("id_contratto not in", values, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoBetween(Long value1, Long value2) {
            addCriterion("id_contratto between", value1, value2, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoNotBetween(Long value1, Long value2) {
            addCriterion("id_contratto not between", value1, value2, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdVincoloIsNull() {
            addCriterion("id_vincolo is null");
            return (Criteria) this;
        }

        public Criteria andIdVincoloIsNotNull() {
            addCriterion("id_vincolo is not null");
            return (Criteria) this;
        }

        public Criteria andIdVincoloEqualTo(Long value) {
            addCriterion("id_vincolo =", value, "idVincolo");
            return (Criteria) this;
        }

        public Criteria andIdVincoloNotEqualTo(Long value) {
            addCriterion("id_vincolo <>", value, "idVincolo");
            return (Criteria) this;
        }

        public Criteria andIdVincoloGreaterThan(Long value) {
            addCriterion("id_vincolo >", value, "idVincolo");
            return (Criteria) this;
        }

        public Criteria andIdVincoloGreaterThanOrEqualTo(Long value) {
            addCriterion("id_vincolo >=", value, "idVincolo");
            return (Criteria) this;
        }

        public Criteria andIdVincoloLessThan(Long value) {
            addCriterion("id_vincolo <", value, "idVincolo");
            return (Criteria) this;
        }

        public Criteria andIdVincoloLessThanOrEqualTo(Long value) {
            addCriterion("id_vincolo <=", value, "idVincolo");
            return (Criteria) this;
        }

        public Criteria andIdVincoloIn(List<Long> values) {
            addCriterion("id_vincolo in", values, "idVincolo");
            return (Criteria) this;
        }

        public Criteria andIdVincoloNotIn(List<Long> values) {
            addCriterion("id_vincolo not in", values, "idVincolo");
            return (Criteria) this;
        }

        public Criteria andIdVincoloBetween(Long value1, Long value2) {
            addCriterion("id_vincolo between", value1, value2, "idVincolo");
            return (Criteria) this;
        }

        public Criteria andIdVincoloNotBetween(Long value1, Long value2) {
            addCriterion("id_vincolo not between", value1, value2, "idVincolo");
            return (Criteria) this;
        }

        public Criteria andValoreIsNull() {
            addCriterion("valore is null");
            return (Criteria) this;
        }

        public Criteria andValoreIsNotNull() {
            addCriterion("valore is not null");
            return (Criteria) this;
        }

        public Criteria andValoreEqualTo(Long value) {
            addCriterion("valore =", value, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreNotEqualTo(Long value) {
            addCriterion("valore <>", value, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreGreaterThan(Long value) {
            addCriterion("valore >", value, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreGreaterThanOrEqualTo(Long value) {
            addCriterion("valore >=", value, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreLessThan(Long value) {
            addCriterion("valore <", value, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreLessThanOrEqualTo(Long value) {
            addCriterion("valore <=", value, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreIn(List<Long> values) {
            addCriterion("valore in", values, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreNotIn(List<Long> values) {
            addCriterion("valore not in", values, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreBetween(Long value1, Long value2) {
            addCriterion("valore between", value1, value2, "valore");
            return (Criteria) this;
        }

        public Criteria andValoreNotBetween(Long value1, Long value2) {
            addCriterion("valore not between", value1, value2, "valore");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaIsNull() {
            addCriterion("data_inizio_validita is null");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaIsNotNull() {
            addCriterion("data_inizio_validita is not null");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_validita =", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaNotEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_validita <>", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaGreaterThan(Date value) {
            addCriterionForJDBCDate("data_inizio_validita >", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_validita >=", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaLessThan(Date value) {
            addCriterionForJDBCDate("data_inizio_validita <", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_validita <=", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaIn(List<Date> values) {
            addCriterionForJDBCDate("data_inizio_validita in", values, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaNotIn(List<Date> values) {
            addCriterionForJDBCDate("data_inizio_validita not in", values, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_inizio_validita between", value1, value2, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_inizio_validita not between", value1, value2, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaIsNull() {
            addCriterion("data_fine_validita is null");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaIsNotNull() {
            addCriterion("data_fine_validita is not null");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_validita =", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaNotEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_validita <>", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaGreaterThan(Date value) {
            addCriterionForJDBCDate("data_fine_validita >", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_validita >=", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaLessThan(Date value) {
            addCriterionForJDBCDate("data_fine_validita <", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_validita <=", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaIn(List<Date> values) {
            addCriterionForJDBCDate("data_fine_validita in", values, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaNotIn(List<Date> values) {
            addCriterionForJDBCDate("data_fine_validita not in", values, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_fine_validita between", value1, value2, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_fine_validita not between", value1, value2, "dataFineValidita");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 04 11:33:48 CET 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sirtplc_r_contratto_vincolo
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}