/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dto;

import java.io.Serializable;

public class SirtplcDTipoSostituzioneDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_d_tipo_sostituzione.id_tipo_sostituzione
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    private Long idTipoSostituzione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_d_tipo_sostituzione.desc_tipo_sostituzione
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    private String descTipoSostituzione;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirtplc_d_tipo_sostituzione
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_d_tipo_sostituzione.id_tipo_sostituzione
     *
     * @return the value of sirtplc_d_tipo_sostituzione.id_tipo_sostituzione
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public Long getIdTipoSostituzione() {
        return idTipoSostituzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_d_tipo_sostituzione.id_tipo_sostituzione
     *
     * @param idTipoSostituzione the value for sirtplc_d_tipo_sostituzione.id_tipo_sostituzione
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public void setIdTipoSostituzione(Long idTipoSostituzione) {
        this.idTipoSostituzione = idTipoSostituzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_d_tipo_sostituzione.desc_tipo_sostituzione
     *
     * @return the value of sirtplc_d_tipo_sostituzione.desc_tipo_sostituzione
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public String getDescTipoSostituzione() {
        return descTipoSostituzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_d_tipo_sostituzione.desc_tipo_sostituzione
     *
     * @param descTipoSostituzione the value for sirtplc_d_tipo_sostituzione.desc_tipo_sostituzione
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    public void setDescTipoSostituzione(String descTipoSostituzione) {
        this.descTipoSostituzione = descTipoSostituzione == null ? null : descTipoSostituzione.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_d_tipo_sostituzione
     *
     * @mbg.generated Mon Nov 04 11:33:48 CET 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idTipoSostituzione=").append(idTipoSostituzione);
        sb.append(", descTipoSostituzione=").append(descTipoSostituzione);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}