/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class VExportRicercaContrattiDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.cod_id_nazionale
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String codIdNazionale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.cod_id_regionale
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String codIdRegionale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.num_repertorio
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String numRepertorio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.bacino
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String bacino;

	// denomBacino
	//private String denomBacino;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.tipo_affidamento
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String tipoAffidamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.modalita_affidamento
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String modalitaAffidamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column
	 * sirtpl_trasv.v_export_ricerca_contratti.tipologia_ambito_servizio
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String tipologiaAmbitoServizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.accordo_programma
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String accordoProgramma;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.gross_cost
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private Boolean grossCost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.cig
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String cig;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.data_stipula
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private Date dataStipula;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.data_inizio_validita
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private Date dataInizioValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.data_fine_validita
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private Date dataFineValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_committente
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String sogGiuridCommittente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_committente_breve
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String sogGiuridCommittenteBreve;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_committente_aaep
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String sogGiuridCommittenteAaep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_esecutore
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String sogGiuridEsecutore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_esecutore_breve
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String sogGiuridEsecutoreBreve;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_esecutore_aaep
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String sogGiuridEsecutoreAaep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.tipo_sog_giurid_esec
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String tipoSogGiuridEsec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column
	 * sirtpl_trasv.v_export_ricerca_contratti.tipo_raggr_sog_giurid_esec
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String tipoRaggrSogGiuridEsec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.azienda_mandataria
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String aziendaMandataria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column
	 * sirtpl_trasv.v_export_ricerca_contratti.azienda_mandataria_breve
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String aziendaMandatariaBreve;
	
	private String aziendaMandatariaAaep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column
	 * sirtpl_trasv.v_export_ricerca_contratti.composizione_raggruppamento
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String composizioneRaggruppamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column
	 * sirtpl_trasv.v_export_ricerca_contratti.composizione_raggruppamento_breve
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String composizioneRaggruppamentoBreve;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column
	 * sirtpl_trasv.v_export_ricerca_contratti.cod_oss_azienda_mandataria
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String codOssAziendaMandataria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.desc_contratto
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String descContratto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.utente_aggiornamento
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private Long utenteAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.data_aggiornamento
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.atto_proroga
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String attoProroga;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.data_fine_proroga
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private Date dataFineProroga;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column
	 * sirtpl_trasv.v_export_ricerca_contratti.id_utente_aggiornamento
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private Long idUtenteAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column
	 * sirtpl_trasv.v_export_ricerca_contratti.cod_oss_sog_giurid_committente
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String codOssSogGiuridCommittente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column
	 * sirtpl_trasv.v_export_ricerca_contratti.cod_oss_sog_giurid_esecutore
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String codOssSogGiuridEsecutore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column sirtpl_trasv.v_export_ricerca_contratti.codregionale
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private String codregionale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database table sirtpl_trasv.v_export_ricerca_contratti
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.cod_id_nazionale
	 * 
	 * @return the value of sirtpl_trasv.v_export_ricerca_contratti.cod_id_nazionale
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getCodIdNazionale() {
		return codIdNazionale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sirtpl_trasv.v_export_ricerca_contratti.cod_id_nazionale
	 * 
	 * @param codIdNazionale the value for
	 *                       sirtpl_trasv.v_export_ricerca_contratti.cod_id_nazionale
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setCodIdNazionale(String codIdNazionale) {
		this.codIdNazionale = codIdNazionale == null ? null : codIdNazionale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.cod_id_regionale
	 * 
	 * @return the value of sirtpl_trasv.v_export_ricerca_contratti.cod_id_regionale
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getCodIdRegionale() {
		return codIdRegionale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sirtpl_trasv.v_export_ricerca_contratti.cod_id_regionale
	 * 
	 * @param codIdRegionale the value for
	 *                       sirtpl_trasv.v_export_ricerca_contratti.cod_id_regionale
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setCodIdRegionale(String codIdRegionale) {
		this.codIdRegionale = codIdRegionale == null ? null : codIdRegionale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sirtpl_trasv.v_export_ricerca_contratti.num_repertorio
	 * 
	 * @return the value of sirtpl_trasv.v_export_ricerca_contratti.num_repertorio
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getNumRepertorio() {
		return numRepertorio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sirtpl_trasv.v_export_ricerca_contratti.num_repertorio
	 * 
	 * @param numRepertorio the value for
	 *                      sirtpl_trasv.v_export_ricerca_contratti.num_repertorio
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setNumRepertorio(String numRepertorio) {
		this.numRepertorio = numRepertorio == null ? null : numRepertorio.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sirtpl_trasv.v_export_ricerca_contratti.bacino
	 * 
	 * @return the value of sirtpl_trasv.v_export_ricerca_contratti.bacino
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getBacino() {
		return bacino;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sirtpl_trasv.v_export_ricerca_contratti.bacino
	 * 
	 * @param bacino the value for sirtpl_trasv.v_export_ricerca_contratti.bacino
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setBacino(String bacino) {
		this.bacino = bacino == null ? null : bacino.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sirtplc_d_bacino.denom_bacino
	 * 
	 * @return the value of column sirtplc_d_bacino.denom_bacino for excel
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	
	/*
	 * public String getDenomBacino() { return denomBacino; }
	 */

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sirtplc_d_bacino.denom_bacino
	 * 
	 * @param bacino the value for column sirtplc_d_bacino.denom_bacino for excel
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	
	/*
	 * public void setDenomBacino(String denomBacino) { this.denomBacino =
	 * denomBacino == null ? null : denomBacino.trim(); }
	 */

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.tipo_affidamento
	 * 
	 * @return the value of sirtpl_trasv.v_export_ricerca_contratti.tipo_affidamento
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getTipoAffidamento() {
		return tipoAffidamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sirtpl_trasv.v_export_ricerca_contratti.tipo_affidamento
	 * 
	 * @param tipoAffidamento the value for
	 *                        sirtpl_trasv.v_export_ricerca_contratti.tipo_affidamento
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setTipoAffidamento(String tipoAffidamento) {
		this.tipoAffidamento = tipoAffidamento == null ? null : tipoAffidamento.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.modalita_affidamento
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.modalita_affidamento
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getModalitaAffidamento() {
		return modalitaAffidamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.modalita_affidamento
	 * 
	 * @param modalitaAffidamento the value for
	 *                            sirtpl_trasv.v_export_ricerca_contratti.modalita_affidamento
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setModalitaAffidamento(String modalitaAffidamento) {
		this.modalitaAffidamento = modalitaAffidamento == null ? null : modalitaAffidamento.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.tipologia_ambito_servizio
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.tipologia_ambito_servizio
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getTipologiaAmbitoServizio() {
		return tipologiaAmbitoServizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.tipologia_ambito_servizio
	 * 
	 * @param tipologiaAmbitoServizio the value for
	 *                                sirtpl_trasv.v_export_ricerca_contratti.tipologia_ambito_servizio
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setTipologiaAmbitoServizio(String tipologiaAmbitoServizio) {
		this.tipologiaAmbitoServizio = tipologiaAmbitoServizio == null ? null : tipologiaAmbitoServizio.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.accordo_programma
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.accordo_programma
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getAccordoProgramma() {
		return accordoProgramma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sirtpl_trasv.v_export_ricerca_contratti.accordo_programma
	 * 
	 * @param accordoProgramma the value for
	 *                         sirtpl_trasv.v_export_ricerca_contratti.accordo_programma
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setAccordoProgramma(String accordoProgramma) {
		this.accordoProgramma = accordoProgramma == null ? null : accordoProgramma.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sirtpl_trasv.v_export_ricerca_contratti.gross_cost
	 * 
	 * @return the value of sirtpl_trasv.v_export_ricerca_contratti.gross_cost
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public Boolean getGrossCost() {
		return grossCost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sirtpl_trasv.v_export_ricerca_contratti.gross_cost
	 * 
	 * @param grossCost the value for
	 *                  sirtpl_trasv.v_export_ricerca_contratti.gross_cost
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setGrossCost(Boolean grossCost) {
		this.grossCost = grossCost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sirtpl_trasv.v_export_ricerca_contratti.cig
	 * 
	 * @return the value of sirtpl_trasv.v_export_ricerca_contratti.cig
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getCig() {
		return cig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sirtpl_trasv.v_export_ricerca_contratti.cig
	 * 
	 * @param cig the value for sirtpl_trasv.v_export_ricerca_contratti.cig
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setCig(String cig) {
		this.cig = cig == null ? null : cig.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sirtpl_trasv.v_export_ricerca_contratti.data_stipula
	 * 
	 * @return the value of sirtpl_trasv.v_export_ricerca_contratti.data_stipula
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public Date getDataStipula() {
		return dataStipula;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sirtpl_trasv.v_export_ricerca_contratti.data_stipula
	 * 
	 * @param dataStipula the value for
	 *                    sirtpl_trasv.v_export_ricerca_contratti.data_stipula
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setDataStipula(Date dataStipula) {
		this.dataStipula = dataStipula;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.data_inizio_validita
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.data_inizio_validita
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public Date getDataInizioValidita() {
		return dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.data_inizio_validita
	 * 
	 * @param dataInizioValidita the value for
	 *                           sirtpl_trasv.v_export_ricerca_contratti.data_inizio_validita
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setDataInizioValidita(Date dataInizioValidita) {
		this.dataInizioValidita = dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.data_fine_validita
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.data_fine_validita
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public Date getDataFineValidita() {
		return dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.data_fine_validita
	 * 
	 * @param dataFineValidita the value for
	 *                         sirtpl_trasv.v_export_ricerca_contratti.data_fine_validita
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setDataFineValidita(Date dataFineValidita) {
		this.dataFineValidita = dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_committente
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_committente
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getSogGiuridCommittente() {
		return sogGiuridCommittente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_committente
	 * 
	 * @param sogGiuridCommittente the value for
	 *                             sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_committente
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setSogGiuridCommittente(String sogGiuridCommittente) {
		this.sogGiuridCommittente = sogGiuridCommittente == null ? null : sogGiuridCommittente.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_committente_breve
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_committente_breve
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getSogGiuridCommittenteBreve() {
		return sogGiuridCommittenteBreve;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_committente_breve
	 * 
	 * @param sogGiuridCommittenteBreve the value for
	 *                                  sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_committente_breve
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setSogGiuridCommittenteBreve(String sogGiuridCommittenteBreve) {
		this.sogGiuridCommittenteBreve = sogGiuridCommittenteBreve == null ? null : sogGiuridCommittenteBreve.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_committente_aaep
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_committente_aaep
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getSogGiuridCommittenteAaep() {
		return sogGiuridCommittenteAaep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_committente_aaep
	 * 
	 * @param sogGiuridCommittenteAaep the value for
	 *                                 sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_committente_aaep
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setSogGiuridCommittenteAaep(String sogGiuridCommittenteAaep) {
		this.sogGiuridCommittenteAaep = sogGiuridCommittenteAaep == null ? null : sogGiuridCommittenteAaep.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_esecutore
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_esecutore
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getSogGiuridEsecutore() {
		return sogGiuridEsecutore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_esecutore
	 * 
	 * @param sogGiuridEsecutore the value for
	 *                           sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_esecutore
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setSogGiuridEsecutore(String sogGiuridEsecutore) {
		this.sogGiuridEsecutore = sogGiuridEsecutore == null ? null : sogGiuridEsecutore.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_esecutore_breve
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_esecutore_breve
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getSogGiuridEsecutoreBreve() {
		return sogGiuridEsecutoreBreve;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_esecutore_breve
	 * 
	 * @param sogGiuridEsecutoreBreve the value for
	 *                                sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_esecutore_breve
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setSogGiuridEsecutoreBreve(String sogGiuridEsecutoreBreve) {
		this.sogGiuridEsecutoreBreve = sogGiuridEsecutoreBreve == null ? null : sogGiuridEsecutoreBreve.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_esecutore_aaep
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_esecutore_aaep
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getSogGiuridEsecutoreAaep() {
		return sogGiuridEsecutoreAaep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_esecutore_aaep
	 * 
	 * @param sogGiuridEsecutoreAaep the value for
	 *                               sirtpl_trasv.v_export_ricerca_contratti.sog_giurid_esecutore_aaep
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setSogGiuridEsecutoreAaep(String sogGiuridEsecutoreAaep) {
		this.sogGiuridEsecutoreAaep = sogGiuridEsecutoreAaep == null ? null : sogGiuridEsecutoreAaep.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.tipo_sog_giurid_esec
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.tipo_sog_giurid_esec
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getTipoSogGiuridEsec() {
		return tipoSogGiuridEsec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.tipo_sog_giurid_esec
	 * 
	 * @param tipoSogGiuridEsec the value for
	 *                          sirtpl_trasv.v_export_ricerca_contratti.tipo_sog_giurid_esec
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setTipoSogGiuridEsec(String tipoSogGiuridEsec) {
		this.tipoSogGiuridEsec = tipoSogGiuridEsec == null ? null : tipoSogGiuridEsec.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.tipo_raggr_sog_giurid_esec
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.tipo_raggr_sog_giurid_esec
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getTipoRaggrSogGiuridEsec() {
		return tipoRaggrSogGiuridEsec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.tipo_raggr_sog_giurid_esec
	 * 
	 * @param tipoRaggrSogGiuridEsec the value for
	 *                               sirtpl_trasv.v_export_ricerca_contratti.tipo_raggr_sog_giurid_esec
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setTipoRaggrSogGiuridEsec(String tipoRaggrSogGiuridEsec) {
		this.tipoRaggrSogGiuridEsec = tipoRaggrSogGiuridEsec == null ? null : tipoRaggrSogGiuridEsec.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.azienda_mandataria
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.azienda_mandataria
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getAziendaMandataria() {
		return aziendaMandataria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.azienda_mandataria
	 * 
	 * @param aziendaMandataria the value for
	 *                          sirtpl_trasv.v_export_ricerca_contratti.azienda_mandataria
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setAziendaMandataria(String aziendaMandataria) {
		this.aziendaMandataria = aziendaMandataria == null ? null : aziendaMandataria.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.azienda_mandataria_breve
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.azienda_mandataria_breve
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getAziendaMandatariaBreve() {
		return aziendaMandatariaBreve;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.azienda_mandataria_breve
	 * 
	 * @param aziendaMandatariaBreve the value for
	 *                               sirtpl_trasv.v_export_ricerca_contratti.azienda_mandataria_breve
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setAziendaMandatariaBreve(String aziendaMandatariaBreve) {
		this.aziendaMandatariaBreve = aziendaMandatariaBreve == null ? null : aziendaMandatariaBreve.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.composizione_raggruppamento
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.composizione_raggruppamento
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getComposizioneRaggruppamento() {
		return composizioneRaggruppamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.composizione_raggruppamento
	 * 
	 * @param composizioneRaggruppamento the value for
	 *                                   sirtpl_trasv.v_export_ricerca_contratti.composizione_raggruppamento
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setComposizioneRaggruppamento(String composizioneRaggruppamento) {
		this.composizioneRaggruppamento = composizioneRaggruppamento == null ? null : composizioneRaggruppamento.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.composizione_raggruppamento_breve
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.composizione_raggruppamento_breve
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getComposizioneRaggruppamentoBreve() {
		return composizioneRaggruppamentoBreve;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.composizione_raggruppamento_breve
	 * 
	 * @param composizioneRaggruppamentoBreve the value for
	 *                                        sirtpl_trasv.v_export_ricerca_contratti.composizione_raggruppamento_breve
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setComposizioneRaggruppamentoBreve(String composizioneRaggruppamentoBreve) {
		this.composizioneRaggruppamentoBreve = composizioneRaggruppamentoBreve == null ? null
				: composizioneRaggruppamentoBreve.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.cod_oss_azienda_mandataria
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.cod_oss_azienda_mandataria
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getCodOssAziendaMandataria() {
		return codOssAziendaMandataria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.cod_oss_azienda_mandataria
	 * 
	 * @param codOssAziendaMandataria the value for
	 *                                sirtpl_trasv.v_export_ricerca_contratti.cod_oss_azienda_mandataria
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setCodOssAziendaMandataria(String codOssAziendaMandataria) {
		this.codOssAziendaMandataria = codOssAziendaMandataria == null ? null : codOssAziendaMandataria.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sirtpl_trasv.v_export_ricerca_contratti.desc_contratto
	 * 
	 * @return the value of sirtpl_trasv.v_export_ricerca_contratti.desc_contratto
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getDescContratto() {
		return descContratto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sirtpl_trasv.v_export_ricerca_contratti.desc_contratto
	 * 
	 * @param descContratto the value for
	 *                      sirtpl_trasv.v_export_ricerca_contratti.desc_contratto
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setDescContratto(String descContratto) {
		this.descContratto = descContratto == null ? null : descContratto.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.utente_aggiornamento
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.utente_aggiornamento
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public Long getUtenteAggiornamento() {
		return utenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.utente_aggiornamento
	 * 
	 * @param utenteAggiornamento the value for
	 *                            sirtpl_trasv.v_export_ricerca_contratti.utente_aggiornamento
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setUtenteAggiornamento(Long utenteAggiornamento) {
		this.utenteAggiornamento = utenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.data_aggiornamento
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.data_aggiornamento
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.data_aggiornamento
	 * 
	 * @param dataAggiornamento the value for
	 *                          sirtpl_trasv.v_export_ricerca_contratti.data_aggiornamento
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sirtpl_trasv.v_export_ricerca_contratti.atto_proroga
	 * 
	 * @return the value of sirtpl_trasv.v_export_ricerca_contratti.atto_proroga
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getAttoProroga() {
		return attoProroga;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sirtpl_trasv.v_export_ricerca_contratti.atto_proroga
	 * 
	 * @param attoProroga the value for
	 *                    sirtpl_trasv.v_export_ricerca_contratti.atto_proroga
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setAttoProroga(String attoProroga) {
		this.attoProroga = attoProroga == null ? null : attoProroga.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.data_fine_proroga
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.data_fine_proroga
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public Date getDataFineProroga() {
		return dataFineProroga;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sirtpl_trasv.v_export_ricerca_contratti.data_fine_proroga
	 * 
	 * @param dataFineProroga the value for
	 *                        sirtpl_trasv.v_export_ricerca_contratti.data_fine_proroga
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setDataFineProroga(Date dataFineProroga) {
		this.dataFineProroga = dataFineProroga;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.id_utente_aggiornamento
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.id_utente_aggiornamento
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public Long getIdUtenteAggiornamento() {
		return idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.id_utente_aggiornamento
	 * 
	 * @param idUtenteAggiornamento the value for
	 *                              sirtpl_trasv.v_export_ricerca_contratti.id_utente_aggiornamento
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setIdUtenteAggiornamento(Long idUtenteAggiornamento) {
		this.idUtenteAggiornamento = idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.cod_oss_sog_giurid_committente
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.cod_oss_sog_giurid_committente
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getCodOssSogGiuridCommittente() {
		return codOssSogGiuridCommittente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.cod_oss_sog_giurid_committente
	 * 
	 * @param codOssSogGiuridCommittente the value for
	 *                                   sirtpl_trasv.v_export_ricerca_contratti.cod_oss_sog_giurid_committente
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setCodOssSogGiuridCommittente(String codOssSogGiuridCommittente) {
		this.codOssSogGiuridCommittente = codOssSogGiuridCommittente == null ? null : codOssSogGiuridCommittente.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.cod_oss_sog_giurid_esecutore
	 * 
	 * @return the value of
	 *         sirtpl_trasv.v_export_ricerca_contratti.cod_oss_sog_giurid_esecutore
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getCodOssSogGiuridEsecutore() {
		return codOssSogGiuridEsecutore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column
	 * sirtpl_trasv.v_export_ricerca_contratti.cod_oss_sog_giurid_esecutore
	 * 
	 * @param codOssSogGiuridEsecutore the value for
	 *                                 sirtpl_trasv.v_export_ricerca_contratti.cod_oss_sog_giurid_esecutore
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setCodOssSogGiuridEsecutore(String codOssSogGiuridEsecutore) {
		this.codOssSogGiuridEsecutore = codOssSogGiuridEsecutore == null ? null : codOssSogGiuridEsecutore.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column sirtpl_trasv.v_export_ricerca_contratti.codregionale
	 * 
	 * @return the value of sirtpl_trasv.v_export_ricerca_contratti.codregionale
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getCodregionale() {
		return codregionale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column sirtpl_trasv.v_export_ricerca_contratti.codregionale
	 * 
	 * @param codregionale the value for
	 *                     sirtpl_trasv.v_export_ricerca_contratti.codregionale
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setCodregionale(String codregionale) {
		this.codregionale = codregionale == null ? null : codregionale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table sirtpl_trasv.v_export_ricerca_contratti
	 * 
	 * @mbg.generated Tue Aug 04 17:47:30 CEST 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", codIdNazionale=").append(codIdNazionale);
		sb.append(", codIdRegionale=").append(codIdRegionale);
		sb.append(", numRepertorio=").append(numRepertorio);
		sb.append(", bacino=").append(bacino);
		sb.append(", tipoAffidamento=").append(tipoAffidamento);
		sb.append(", modalitaAffidamento=").append(modalitaAffidamento);
		sb.append(", tipologiaAmbitoServizio=").append(tipologiaAmbitoServizio);
		sb.append(", accordoProgramma=").append(accordoProgramma);
		sb.append(", grossCost=").append(grossCost);
		sb.append(", cig=").append(cig);
		sb.append(", dataStipula=").append(dataStipula);
		sb.append(", dataInizioValidita=").append(dataInizioValidita);
		sb.append(", dataFineValidita=").append(dataFineValidita);
		sb.append(", sogGiuridCommittente=").append(sogGiuridCommittente);
		sb.append(", sogGiuridCommittenteBreve=").append(sogGiuridCommittenteBreve);
		sb.append(", sogGiuridCommittenteAaep=").append(sogGiuridCommittenteAaep);
		sb.append(", sogGiuridEsecutore=").append(sogGiuridEsecutore);
		sb.append(", sogGiuridEsecutoreBreve=").append(sogGiuridEsecutoreBreve);
		sb.append(", sogGiuridEsecutoreAaep=").append(sogGiuridEsecutoreAaep);
		sb.append(", tipoSogGiuridEsec=").append(tipoSogGiuridEsec);
		sb.append(", tipoRaggrSogGiuridEsec=").append(tipoRaggrSogGiuridEsec);
		sb.append(", aziendaMandataria=").append(aziendaMandataria);
		sb.append(", aziendaMandatariaBreve=").append(aziendaMandatariaBreve);
		sb.append(", composizioneRaggruppamento=").append(composizioneRaggruppamento);
		sb.append(", composizioneRaggruppamentoBreve=").append(composizioneRaggruppamentoBreve);
		sb.append(", codOssAziendaMandataria=").append(codOssAziendaMandataria);
		sb.append(", descContratto=").append(descContratto);
		sb.append(", utenteAggiornamento=").append(utenteAggiornamento);
		sb.append(", dataAggiornamento=").append(dataAggiornamento);
		sb.append(", attoProroga=").append(attoProroga);
		sb.append(", dataFineProroga=").append(dataFineProroga);
		sb.append(", idUtenteAggiornamento=").append(idUtenteAggiornamento);
		sb.append(", codOssSogGiuridCommittente=").append(codOssSogGiuridCommittente);
		sb.append(", codOssSogGiuridEsecutore=").append(codOssSogGiuridEsecutore);
		sb.append(", codregionale=").append(codregionale);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	public String getAziendaMandatariaAaep() {
		return aziendaMandatariaAaep;
	}

	public void setAziendaMandatariaAaep(String aziendaMandatariaAaep) {
		this.aziendaMandatariaAaep = aziendaMandatariaAaep;
	}
}