/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class VExportRicercaSoggGiurDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.id_soggetto_giuridico
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private Long idSoggettoGiuridico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.tipo_soggetto_giuridico
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String tipoSoggettoGiuridico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.natura_giuridica
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String naturaGiuridica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.denominazione_breve
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String denominazioneBreve;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.denominazione_aaep
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String denominazioneAaep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.denom_soggetto_giuridico
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String denomSoggettoGiuridico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.partita_iva
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String partitaIva;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.codice_fiscale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String codiceFiscale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.cod_osservatorio_naz
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String codOsservatorioNaz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.rappresentante_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String rappresentanteLegale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.indirizzo_sede_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String indirizzoSedeLegale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.telefono_sede_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String telefonoSedeLegale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.fax_sede_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String faxSedeLegale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.email_sede_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String emailSedeLegale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.pec_sede_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String pecSedeLegale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.indirizzo_web
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String indirizzoWeb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.numero_verde
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String numeroVerde;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.note
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.tipo_ente
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String tipoEnte;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.descrizione
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String descrizione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.data_inizio_attivita
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private Date dataInizioAttivita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.data_cessazione
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private Date dataCessazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.id_omnibus
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private Long idOmnibus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.id_utente_aggiornamento
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private Long idUtenteAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.data_aggiornamento
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.denominazione_oss
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String denominazioneOss;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.bacino_appart_ente
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private Object bacinoAppartEnte;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_export_ricerca_sogg_giur.codregionale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private String codregionale;
	
	private Long codCsrBip;
	
	private Boolean attivoTpl;
	
	private Boolean cessato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sirtpl_trasv.v_export_ricerca_sogg_giur
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.id_soggetto_giuridico
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.id_soggetto_giuridico
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public Long getIdSoggettoGiuridico() {
		return idSoggettoGiuridico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.id_soggetto_giuridico
	 * @param idSoggettoGiuridico  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.id_soggetto_giuridico
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setIdSoggettoGiuridico(Long idSoggettoGiuridico) {
		this.idSoggettoGiuridico = idSoggettoGiuridico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.tipo_soggetto_giuridico
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.tipo_soggetto_giuridico
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getTipoSoggettoGiuridico() {
		return tipoSoggettoGiuridico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.tipo_soggetto_giuridico
	 * @param tipoSoggettoGiuridico  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.tipo_soggetto_giuridico
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setTipoSoggettoGiuridico(String tipoSoggettoGiuridico) {
		this.tipoSoggettoGiuridico = tipoSoggettoGiuridico == null ? null : tipoSoggettoGiuridico.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.natura_giuridica
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.natura_giuridica
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getNaturaGiuridica() {
		return naturaGiuridica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.natura_giuridica
	 * @param naturaGiuridica  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.natura_giuridica
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setNaturaGiuridica(String naturaGiuridica) {
		this.naturaGiuridica = naturaGiuridica == null ? null : naturaGiuridica.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.denominazione_breve
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.denominazione_breve
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getDenominazioneBreve() {
		return denominazioneBreve;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.denominazione_breve
	 * @param denominazioneBreve  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.denominazione_breve
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setDenominazioneBreve(String denominazioneBreve) {
		this.denominazioneBreve = denominazioneBreve == null ? null : denominazioneBreve.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.denominazione_aaep
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.denominazione_aaep
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getDenominazioneAaep() {
		return denominazioneAaep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.denominazione_aaep
	 * @param denominazioneAaep  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.denominazione_aaep
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setDenominazioneAaep(String denominazioneAaep) {
		this.denominazioneAaep = denominazioneAaep == null ? null : denominazioneAaep.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.denom_soggetto_giuridico
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.denom_soggetto_giuridico
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getDenomSoggettoGiuridico() {
		return denomSoggettoGiuridico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.denom_soggetto_giuridico
	 * @param denomSoggettoGiuridico  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.denom_soggetto_giuridico
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setDenomSoggettoGiuridico(String denomSoggettoGiuridico) {
		this.denomSoggettoGiuridico = denomSoggettoGiuridico == null ? null : denomSoggettoGiuridico.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.partita_iva
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.partita_iva
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getPartitaIva() {
		return partitaIva;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.partita_iva
	 * @param partitaIva  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.partita_iva
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setPartitaIva(String partitaIva) {
		this.partitaIva = partitaIva == null ? null : partitaIva.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.codice_fiscale
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.codice_fiscale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getCodiceFiscale() {
		return codiceFiscale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.codice_fiscale
	 * @param codiceFiscale  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.codice_fiscale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setCodiceFiscale(String codiceFiscale) {
		this.codiceFiscale = codiceFiscale == null ? null : codiceFiscale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.cod_osservatorio_naz
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.cod_osservatorio_naz
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getCodOsservatorioNaz() {
		return codOsservatorioNaz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.cod_osservatorio_naz
	 * @param codOsservatorioNaz  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.cod_osservatorio_naz
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setCodOsservatorioNaz(String codOsservatorioNaz) {
		this.codOsservatorioNaz = codOsservatorioNaz == null ? null : codOsservatorioNaz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.rappresentante_legale
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.rappresentante_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getRappresentanteLegale() {
		return rappresentanteLegale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.rappresentante_legale
	 * @param rappresentanteLegale  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.rappresentante_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setRappresentanteLegale(String rappresentanteLegale) {
		this.rappresentanteLegale = rappresentanteLegale == null ? null : rappresentanteLegale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.indirizzo_sede_legale
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.indirizzo_sede_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getIndirizzoSedeLegale() {
		return indirizzoSedeLegale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.indirizzo_sede_legale
	 * @param indirizzoSedeLegale  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.indirizzo_sede_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setIndirizzoSedeLegale(String indirizzoSedeLegale) {
		this.indirizzoSedeLegale = indirizzoSedeLegale == null ? null : indirizzoSedeLegale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.telefono_sede_legale
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.telefono_sede_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getTelefonoSedeLegale() {
		return telefonoSedeLegale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.telefono_sede_legale
	 * @param telefonoSedeLegale  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.telefono_sede_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setTelefonoSedeLegale(String telefonoSedeLegale) {
		this.telefonoSedeLegale = telefonoSedeLegale == null ? null : telefonoSedeLegale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.fax_sede_legale
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.fax_sede_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getFaxSedeLegale() {
		return faxSedeLegale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.fax_sede_legale
	 * @param faxSedeLegale  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.fax_sede_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setFaxSedeLegale(String faxSedeLegale) {
		this.faxSedeLegale = faxSedeLegale == null ? null : faxSedeLegale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.email_sede_legale
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.email_sede_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getEmailSedeLegale() {
		return emailSedeLegale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.email_sede_legale
	 * @param emailSedeLegale  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.email_sede_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setEmailSedeLegale(String emailSedeLegale) {
		this.emailSedeLegale = emailSedeLegale == null ? null : emailSedeLegale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.pec_sede_legale
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.pec_sede_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getPecSedeLegale() {
		return pecSedeLegale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.pec_sede_legale
	 * @param pecSedeLegale  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.pec_sede_legale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setPecSedeLegale(String pecSedeLegale) {
		this.pecSedeLegale = pecSedeLegale == null ? null : pecSedeLegale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.indirizzo_web
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.indirizzo_web
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getIndirizzoWeb() {
		return indirizzoWeb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.indirizzo_web
	 * @param indirizzoWeb  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.indirizzo_web
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setIndirizzoWeb(String indirizzoWeb) {
		this.indirizzoWeb = indirizzoWeb == null ? null : indirizzoWeb.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.numero_verde
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.numero_verde
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getNumeroVerde() {
		return numeroVerde;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.numero_verde
	 * @param numeroVerde  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.numero_verde
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setNumeroVerde(String numeroVerde) {
		this.numeroVerde = numeroVerde == null ? null : numeroVerde.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.note
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.note
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.note
	 * @param note  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.note
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.tipo_ente
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.tipo_ente
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getTipoEnte() {
		return tipoEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.tipo_ente
	 * @param tipoEnte  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.tipo_ente
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setTipoEnte(String tipoEnte) {
		this.tipoEnte = tipoEnte == null ? null : tipoEnte.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.descrizione
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.descrizione
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getDescrizione() {
		return descrizione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.descrizione
	 * @param descrizione  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.descrizione
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione == null ? null : descrizione.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.data_inizio_attivita
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.data_inizio_attivita
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public Date getDataInizioAttivita() {
		return dataInizioAttivita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.data_inizio_attivita
	 * @param dataInizioAttivita  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.data_inizio_attivita
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setDataInizioAttivita(Date dataInizioAttivita) {
		this.dataInizioAttivita = dataInizioAttivita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.data_cessazione
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.data_cessazione
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public Date getDataCessazione() {
		return dataCessazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.data_cessazione
	 * @param dataCessazione  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.data_cessazione
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setDataCessazione(Date dataCessazione) {
		this.dataCessazione = dataCessazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.id_omnibus
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.id_omnibus
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public Long getIdOmnibus() {
		return idOmnibus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.id_omnibus
	 * @param idOmnibus  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.id_omnibus
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setIdOmnibus(Long idOmnibus) {
		this.idOmnibus = idOmnibus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.id_utente_aggiornamento
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.id_utente_aggiornamento
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public Long getIdUtenteAggiornamento() {
		return idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.id_utente_aggiornamento
	 * @param idUtenteAggiornamento  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.id_utente_aggiornamento
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setIdUtenteAggiornamento(Long idUtenteAggiornamento) {
		this.idUtenteAggiornamento = idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.data_aggiornamento
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.data_aggiornamento
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.data_aggiornamento
	 * @param dataAggiornamento  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.data_aggiornamento
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.denominazione_oss
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.denominazione_oss
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getDenominazioneOss() {
		return denominazioneOss;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.denominazione_oss
	 * @param denominazioneOss  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.denominazione_oss
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setDenominazioneOss(String denominazioneOss) {
		this.denominazioneOss = denominazioneOss == null ? null : denominazioneOss.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.bacino_appart_ente
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.bacino_appart_ente
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public Object getBacinoAppartEnte() {
		return bacinoAppartEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.bacino_appart_ente
	 * @param bacinoAppartEnte  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.bacino_appart_ente
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setBacinoAppartEnte(Object bacinoAppartEnte) {
		this.bacinoAppartEnte = bacinoAppartEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.codregionale
	 * @return  the value of sirtpl_trasv.v_export_ricerca_sogg_giur.codregionale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public String getCodregionale() {
		return codregionale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.codregionale
	 * @param codregionale  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.codregionale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setCodregionale(String codregionale) {
		this.codregionale = codregionale == null ? null : codregionale.trim();
	}

	public Long getCodCsrBip() {
		return codCsrBip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_export_ricerca_sogg_giur.codregionale
	 * @param codregionale  the value for sirtpl_trasv.v_export_ricerca_sogg_giur.codregionale
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	public void setCodCsrBip(Long codCsrBip) {
		this.codCsrBip = codCsrBip;
	}
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_export_ricerca_sogg_giur
	 * @mbg.generated  Tue Aug 04 17:47:30 CEST 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idSoggettoGiuridico=").append(idSoggettoGiuridico);
		sb.append(", tipoSoggettoGiuridico=").append(tipoSoggettoGiuridico);
		sb.append(", naturaGiuridica=").append(naturaGiuridica);
		sb.append(", denominazioneBreve=").append(denominazioneBreve);
		sb.append(", denominazioneAaep=").append(denominazioneAaep);
		sb.append(", denomSoggettoGiuridico=").append(denomSoggettoGiuridico);
		sb.append(", partitaIva=").append(partitaIva);
		sb.append(", codiceFiscale=").append(codiceFiscale);
		sb.append(", codOsservatorioNaz=").append(codOsservatorioNaz);
		sb.append(", codCsrBip=").append(codCsrBip);
		sb.append(", rappresentanteLegale=").append(rappresentanteLegale);
		sb.append(", indirizzoSedeLegale=").append(indirizzoSedeLegale);
		sb.append(", telefonoSedeLegale=").append(telefonoSedeLegale);
		sb.append(", faxSedeLegale=").append(faxSedeLegale);
		sb.append(", emailSedeLegale=").append(emailSedeLegale);
		sb.append(", pecSedeLegale=").append(pecSedeLegale);
		sb.append(", indirizzoWeb=").append(indirizzoWeb);
		sb.append(", numeroVerde=").append(numeroVerde);
		sb.append(", note=").append(note);
		sb.append(", tipoEnte=").append(tipoEnte);
		sb.append(", descrizione=").append(descrizione);
		sb.append(", dataInizioAttivita=").append(dataInizioAttivita);
		sb.append(", dataCessazione=").append(dataCessazione);
		sb.append(", idOmnibus=").append(idOmnibus);
		sb.append(", idUtenteAggiornamento=").append(idUtenteAggiornamento);
		sb.append(", dataAggiornamento=").append(dataAggiornamento);
		sb.append(", denominazioneOss=").append(denominazioneOss);
		sb.append(", bacinoAppartEnte=").append(bacinoAppartEnte);
		sb.append(", codregionale=").append(codregionale);
		sb.append(", cessato=").append(cessato);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	public Boolean getAttivoTpl() {
		return attivoTpl;
	}

	public void setAttivoTpl(Boolean attivoTpl) {
		this.attivoTpl = attivoTpl;
	}

	public Boolean getCessato() {
		return cessato;
	}

	public void setCessato(Boolean cessato) {
		this.cessato = cessato;
	}
}