/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class VSoggettiCoinvoltiPeriodiSelector {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	public VSoggettiCoinvoltiPeriodiSelector() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdcIsNull() {
			addCriterion("idc is null");
			return (Criteria) this;
		}

		public Criteria andIdcIsNotNull() {
			addCriterion("idc is not null");
			return (Criteria) this;
		}

		public Criteria andIdcEqualTo(Long value) {
			addCriterion("idc =", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcNotEqualTo(Long value) {
			addCriterion("idc <>", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcGreaterThan(Long value) {
			addCriterion("idc >", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcGreaterThanOrEqualTo(Long value) {
			addCriterion("idc >=", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcLessThan(Long value) {
			addCriterion("idc <", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcLessThanOrEqualTo(Long value) {
			addCriterion("idc <=", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcIn(List<Long> values) {
			addCriterion("idc in", values, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcNotIn(List<Long> values) {
			addCriterion("idc not in", values, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcBetween(Long value1, Long value2) {
			addCriterion("idc between", value1, value2, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcNotBetween(Long value1, Long value2) {
			addCriterion("idc not between", value1, value2, "idc");
			return (Criteria) this;
		}

		public Criteria andAliasIsNull() {
			addCriterion("alias is null");
			return (Criteria) this;
		}

		public Criteria andAliasIsNotNull() {
			addCriterion("alias is not null");
			return (Criteria) this;
		}

		public Criteria andAliasEqualTo(String value) {
			addCriterion("alias =", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotEqualTo(String value) {
			addCriterion("alias <>", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasGreaterThan(String value) {
			addCriterion("alias >", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasGreaterThanOrEqualTo(String value) {
			addCriterion("alias >=", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasLessThan(String value) {
			addCriterion("alias <", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasLessThanOrEqualTo(String value) {
			addCriterion("alias <=", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasLike(String value) {
			addCriterion("alias like", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotLike(String value) {
			addCriterion("alias not like", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasIn(List<String> values) {
			addCriterion("alias in", values, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotIn(List<String> values) {
			addCriterion("alias not in", values, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasBetween(String value1, String value2) {
			addCriterion("alias between", value1, value2, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotBetween(String value1, String value2) {
			addCriterion("alias not between", value1, value2, "alias");
			return (Criteria) this;
		}

		public Criteria andRuoloIsNull() {
			addCriterion("ruolo is null");
			return (Criteria) this;
		}

		public Criteria andRuoloIsNotNull() {
			addCriterion("ruolo is not null");
			return (Criteria) this;
		}

		public Criteria andRuoloEqualTo(String value) {
			addCriterion("ruolo =", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloNotEqualTo(String value) {
			addCriterion("ruolo <>", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloGreaterThan(String value) {
			addCriterion("ruolo >", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloGreaterThanOrEqualTo(String value) {
			addCriterion("ruolo >=", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloLessThan(String value) {
			addCriterion("ruolo <", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloLessThanOrEqualTo(String value) {
			addCriterion("ruolo <=", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloLike(String value) {
			addCriterion("ruolo like", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloNotLike(String value) {
			addCriterion("ruolo not like", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloIn(List<String> values) {
			addCriterion("ruolo in", values, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloNotIn(List<String> values) {
			addCriterion("ruolo not in", values, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloBetween(String value1, String value2) {
			addCriterion("ruolo between", value1, value2, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloNotBetween(String value1, String value2) {
			addCriterion("ruolo not between", value1, value2, "ruolo");
			return (Criteria) this;
		}

		public Criteria andDIniIsNull() {
			addCriterion("d_ini is null");
			return (Criteria) this;
		}

		public Criteria andDIniIsNotNull() {
			addCriterion("d_ini is not null");
			return (Criteria) this;
		}

		public Criteria andDIniEqualTo(String value) {
			addCriterion("d_ini =", value, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniNotEqualTo(String value) {
			addCriterion("d_ini <>", value, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniGreaterThan(String value) {
			addCriterion("d_ini >", value, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniGreaterThanOrEqualTo(String value) {
			addCriterion("d_ini >=", value, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniLessThan(String value) {
			addCriterion("d_ini <", value, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniLessThanOrEqualTo(String value) {
			addCriterion("d_ini <=", value, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniLike(String value) {
			addCriterion("d_ini like", value, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniNotLike(String value) {
			addCriterion("d_ini not like", value, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniIn(List<String> values) {
			addCriterion("d_ini in", values, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniNotIn(List<String> values) {
			addCriterion("d_ini not in", values, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniBetween(String value1, String value2) {
			addCriterion("d_ini between", value1, value2, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniNotBetween(String value1, String value2) {
			addCriterion("d_ini not between", value1, value2, "dIni");
			return (Criteria) this;
		}

		public Criteria andDFinIsNull() {
			addCriterion("d_fin is null");
			return (Criteria) this;
		}

		public Criteria andDFinIsNotNull() {
			addCriterion("d_fin is not null");
			return (Criteria) this;
		}

		public Criteria andDFinEqualTo(String value) {
			addCriterion("d_fin =", value, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinNotEqualTo(String value) {
			addCriterion("d_fin <>", value, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinGreaterThan(String value) {
			addCriterion("d_fin >", value, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinGreaterThanOrEqualTo(String value) {
			addCriterion("d_fin >=", value, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinLessThan(String value) {
			addCriterion("d_fin <", value, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinLessThanOrEqualTo(String value) {
			addCriterion("d_fin <=", value, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinLike(String value) {
			addCriterion("d_fin like", value, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinNotLike(String value) {
			addCriterion("d_fin not like", value, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinIn(List<String> values) {
			addCriterion("d_fin in", values, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinNotIn(List<String> values) {
			addCriterion("d_fin not in", values, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinBetween(String value1, String value2) {
			addCriterion("d_fin between", value1, value2, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinNotBetween(String value1, String value2) {
			addCriterion("d_fin not between", value1, value2, "dFin");
			return (Criteria) this;
		}

		public Criteria andIdSgAffIsNull() {
			addCriterion("id_sg_aff is null");
			return (Criteria) this;
		}

		public Criteria andIdSgAffIsNotNull() {
			addCriterion("id_sg_aff is not null");
			return (Criteria) this;
		}

		public Criteria andIdSgAffEqualTo(Double value) {
			addCriterion("id_sg_aff =", value, "idSgAff");
			return (Criteria) this;
		}

		public Criteria andIdSgAffNotEqualTo(Double value) {
			addCriterion("id_sg_aff <>", value, "idSgAff");
			return (Criteria) this;
		}

		public Criteria andIdSgAffGreaterThan(Double value) {
			addCriterion("id_sg_aff >", value, "idSgAff");
			return (Criteria) this;
		}

		public Criteria andIdSgAffGreaterThanOrEqualTo(Double value) {
			addCriterion("id_sg_aff >=", value, "idSgAff");
			return (Criteria) this;
		}

		public Criteria andIdSgAffLessThan(Double value) {
			addCriterion("id_sg_aff <", value, "idSgAff");
			return (Criteria) this;
		}

		public Criteria andIdSgAffLessThanOrEqualTo(Double value) {
			addCriterion("id_sg_aff <=", value, "idSgAff");
			return (Criteria) this;
		}

		public Criteria andIdSgAffIn(List<Double> values) {
			addCriterion("id_sg_aff in", values, "idSgAff");
			return (Criteria) this;
		}

		public Criteria andIdSgAffNotIn(List<Double> values) {
			addCriterion("id_sg_aff not in", values, "idSgAff");
			return (Criteria) this;
		}

		public Criteria andIdSgAffBetween(Double value1, Double value2) {
			addCriterion("id_sg_aff between", value1, value2, "idSgAff");
			return (Criteria) this;
		}

		public Criteria andIdSgAffNotBetween(Double value1, Double value2) {
			addCriterion("id_sg_aff not between", value1, value2, "idSgAff");
			return (Criteria) this;
		}

		public Criteria andSgAffIsNull() {
			addCriterion("sg_aff is null");
			return (Criteria) this;
		}

		public Criteria andSgAffIsNotNull() {
			addCriterion("sg_aff is not null");
			return (Criteria) this;
		}

		public Criteria andSgAffEqualTo(String value) {
			addCriterion("sg_aff =", value, "sgAff");
			return (Criteria) this;
		}

		public Criteria andSgAffNotEqualTo(String value) {
			addCriterion("sg_aff <>", value, "sgAff");
			return (Criteria) this;
		}

		public Criteria andSgAffGreaterThan(String value) {
			addCriterion("sg_aff >", value, "sgAff");
			return (Criteria) this;
		}

		public Criteria andSgAffGreaterThanOrEqualTo(String value) {
			addCriterion("sg_aff >=", value, "sgAff");
			return (Criteria) this;
		}

		public Criteria andSgAffLessThan(String value) {
			addCriterion("sg_aff <", value, "sgAff");
			return (Criteria) this;
		}

		public Criteria andSgAffLessThanOrEqualTo(String value) {
			addCriterion("sg_aff <=", value, "sgAff");
			return (Criteria) this;
		}

		public Criteria andSgAffLike(String value) {
			addCriterion("sg_aff like", value, "sgAff");
			return (Criteria) this;
		}

		public Criteria andSgAffNotLike(String value) {
			addCriterion("sg_aff not like", value, "sgAff");
			return (Criteria) this;
		}

		public Criteria andSgAffIn(List<String> values) {
			addCriterion("sg_aff in", values, "sgAff");
			return (Criteria) this;
		}

		public Criteria andSgAffNotIn(List<String> values) {
			addCriterion("sg_aff not in", values, "sgAff");
			return (Criteria) this;
		}

		public Criteria andSgAffBetween(String value1, String value2) {
			addCriterion("sg_aff between", value1, value2, "sgAff");
			return (Criteria) this;
		}

		public Criteria andSgAffNotBetween(String value1, String value2) {
			addCriterion("sg_aff not between", value1, value2, "sgAff");
			return (Criteria) this;
		}

		public Criteria andIdSgSostIsNull() {
			addCriterion("id_sg_sost is null");
			return (Criteria) this;
		}

		public Criteria andIdSgSostIsNotNull() {
			addCriterion("id_sg_sost is not null");
			return (Criteria) this;
		}

		public Criteria andIdSgSostEqualTo(Double value) {
			addCriterion("id_sg_sost =", value, "idSgSost");
			return (Criteria) this;
		}

		public Criteria andIdSgSostNotEqualTo(Double value) {
			addCriterion("id_sg_sost <>", value, "idSgSost");
			return (Criteria) this;
		}

		public Criteria andIdSgSostGreaterThan(Double value) {
			addCriterion("id_sg_sost >", value, "idSgSost");
			return (Criteria) this;
		}

		public Criteria andIdSgSostGreaterThanOrEqualTo(Double value) {
			addCriterion("id_sg_sost >=", value, "idSgSost");
			return (Criteria) this;
		}

		public Criteria andIdSgSostLessThan(Double value) {
			addCriterion("id_sg_sost <", value, "idSgSost");
			return (Criteria) this;
		}

		public Criteria andIdSgSostLessThanOrEqualTo(Double value) {
			addCriterion("id_sg_sost <=", value, "idSgSost");
			return (Criteria) this;
		}

		public Criteria andIdSgSostIn(List<Double> values) {
			addCriterion("id_sg_sost in", values, "idSgSost");
			return (Criteria) this;
		}

		public Criteria andIdSgSostNotIn(List<Double> values) {
			addCriterion("id_sg_sost not in", values, "idSgSost");
			return (Criteria) this;
		}

		public Criteria andIdSgSostBetween(Double value1, Double value2) {
			addCriterion("id_sg_sost between", value1, value2, "idSgSost");
			return (Criteria) this;
		}

		public Criteria andIdSgSostNotBetween(Double value1, Double value2) {
			addCriterion("id_sg_sost not between", value1, value2, "idSgSost");
			return (Criteria) this;
		}

		public Criteria andSgSostIsNull() {
			addCriterion("sg_sost is null");
			return (Criteria) this;
		}

		public Criteria andSgSostIsNotNull() {
			addCriterion("sg_sost is not null");
			return (Criteria) this;
		}

		public Criteria andSgSostEqualTo(String value) {
			addCriterion("sg_sost =", value, "sgSost");
			return (Criteria) this;
		}

		public Criteria andSgSostNotEqualTo(String value) {
			addCriterion("sg_sost <>", value, "sgSost");
			return (Criteria) this;
		}

		public Criteria andSgSostGreaterThan(String value) {
			addCriterion("sg_sost >", value, "sgSost");
			return (Criteria) this;
		}

		public Criteria andSgSostGreaterThanOrEqualTo(String value) {
			addCriterion("sg_sost >=", value, "sgSost");
			return (Criteria) this;
		}

		public Criteria andSgSostLessThan(String value) {
			addCriterion("sg_sost <", value, "sgSost");
			return (Criteria) this;
		}

		public Criteria andSgSostLessThanOrEqualTo(String value) {
			addCriterion("sg_sost <=", value, "sgSost");
			return (Criteria) this;
		}

		public Criteria andSgSostLike(String value) {
			addCriterion("sg_sost like", value, "sgSost");
			return (Criteria) this;
		}

		public Criteria andSgSostNotLike(String value) {
			addCriterion("sg_sost not like", value, "sgSost");
			return (Criteria) this;
		}

		public Criteria andSgSostIn(List<String> values) {
			addCriterion("sg_sost in", values, "sgSost");
			return (Criteria) this;
		}

		public Criteria andSgSostNotIn(List<String> values) {
			addCriterion("sg_sost not in", values, "sgSost");
			return (Criteria) this;
		}

		public Criteria andSgSostBetween(String value1, String value2) {
			addCriterion("sg_sost between", value1, value2, "sgSost");
			return (Criteria) this;
		}

		public Criteria andSgSostNotBetween(String value1, String value2) {
			addCriterion("sg_sost not between", value1, value2, "sgSost");
			return (Criteria) this;
		}

		public Criteria andAttoIsNull() {
			addCriterion("atto is null");
			return (Criteria) this;
		}

		public Criteria andAttoIsNotNull() {
			addCriterion("atto is not null");
			return (Criteria) this;
		}

		public Criteria andAttoEqualTo(String value) {
			addCriterion("atto =", value, "atto");
			return (Criteria) this;
		}

		public Criteria andAttoNotEqualTo(String value) {
			addCriterion("atto <>", value, "atto");
			return (Criteria) this;
		}

		public Criteria andAttoGreaterThan(String value) {
			addCriterion("atto >", value, "atto");
			return (Criteria) this;
		}

		public Criteria andAttoGreaterThanOrEqualTo(String value) {
			addCriterion("atto >=", value, "atto");
			return (Criteria) this;
		}

		public Criteria andAttoLessThan(String value) {
			addCriterion("atto <", value, "atto");
			return (Criteria) this;
		}

		public Criteria andAttoLessThanOrEqualTo(String value) {
			addCriterion("atto <=", value, "atto");
			return (Criteria) this;
		}

		public Criteria andAttoLike(String value) {
			addCriterion("atto like", value, "atto");
			return (Criteria) this;
		}

		public Criteria andAttoNotLike(String value) {
			addCriterion("atto not like", value, "atto");
			return (Criteria) this;
		}

		public Criteria andAttoIn(List<String> values) {
			addCriterion("atto in", values, "atto");
			return (Criteria) this;
		}

		public Criteria andAttoNotIn(List<String> values) {
			addCriterion("atto not in", values, "atto");
			return (Criteria) this;
		}

		public Criteria andAttoBetween(String value1, String value2) {
			addCriterion("atto between", value1, value2, "atto");
			return (Criteria) this;
		}

		public Criteria andAttoNotBetween(String value1, String value2) {
			addCriterion("atto not between", value1, value2, "atto");
			return (Criteria) this;
		}

		public Criteria andIdSgIsNull() {
			addCriterion("id_sg is null");
			return (Criteria) this;
		}

		public Criteria andIdSgIsNotNull() {
			addCriterion("id_sg is not null");
			return (Criteria) this;
		}

		public Criteria andIdSgEqualTo(Long value) {
			addCriterion("id_sg =", value, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgNotEqualTo(Long value) {
			addCriterion("id_sg <>", value, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgGreaterThan(Long value) {
			addCriterion("id_sg >", value, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgGreaterThanOrEqualTo(Long value) {
			addCriterion("id_sg >=", value, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgLessThan(Long value) {
			addCriterion("id_sg <", value, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgLessThanOrEqualTo(Long value) {
			addCriterion("id_sg <=", value, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgIn(List<Long> values) {
			addCriterion("id_sg in", values, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgNotIn(List<Long> values) {
			addCriterion("id_sg not in", values, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgBetween(Long value1, Long value2) {
			addCriterion("id_sg between", value1, value2, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgNotBetween(Long value1, Long value2) {
			addCriterion("id_sg not between", value1, value2, "idSg");
			return (Criteria) this;
		}

		public Criteria andScadutoIsNull() {
			addCriterion("scaduto is null");
			return (Criteria) this;
		}

		public Criteria andScadutoIsNotNull() {
			addCriterion("scaduto is not null");
			return (Criteria) this;
		}

		public Criteria andScadutoEqualTo(Boolean value) {
			addCriterion("scaduto =", value, "scaduto");
			return (Criteria) this;
		}

		public Criteria andScadutoNotEqualTo(Boolean value) {
			addCriterion("scaduto <>", value, "scaduto");
			return (Criteria) this;
		}

		public Criteria andScadutoGreaterThan(Boolean value) {
			addCriterion("scaduto >", value, "scaduto");
			return (Criteria) this;
		}

		public Criteria andScadutoGreaterThanOrEqualTo(Boolean value) {
			addCriterion("scaduto >=", value, "scaduto");
			return (Criteria) this;
		}

		public Criteria andScadutoLessThan(Boolean value) {
			addCriterion("scaduto <", value, "scaduto");
			return (Criteria) this;
		}

		public Criteria andScadutoLessThanOrEqualTo(Boolean value) {
			addCriterion("scaduto <=", value, "scaduto");
			return (Criteria) this;
		}

		public Criteria andScadutoIn(List<Boolean> values) {
			addCriterion("scaduto in", values, "scaduto");
			return (Criteria) this;
		}

		public Criteria andScadutoNotIn(List<Boolean> values) {
			addCriterion("scaduto not in", values, "scaduto");
			return (Criteria) this;
		}

		public Criteria andScadutoBetween(Boolean value1, Boolean value2) {
			addCriterion("scaduto between", value1, value2, "scaduto");
			return (Criteria) this;
		}

		public Criteria andScadutoNotBetween(Boolean value1, Boolean value2) {
			addCriterion("scaduto not between", value1, value2, "scaduto");
			return (Criteria) this;
		}

		public Criteria andAliasLikeInsensitive(String value) {
			addCriterion("upper(alias) like", value.toUpperCase(), "alias");
			return (Criteria) this;
		}

		public Criteria andRuoloLikeInsensitive(String value) {
			addCriterion("upper(ruolo) like", value.toUpperCase(), "ruolo");
			return (Criteria) this;
		}

		public Criteria andDIniLikeInsensitive(String value) {
			addCriterion("upper(d_ini) like", value.toUpperCase(), "dIni");
			return (Criteria) this;
		}

		public Criteria andDFinLikeInsensitive(String value) {
			addCriterion("upper(d_fin) like", value.toUpperCase(), "dFin");
			return (Criteria) this;
		}

		public Criteria andSgAffLikeInsensitive(String value) {
			addCriterion("upper(sg_aff) like", value.toUpperCase(), "sgAff");
			return (Criteria) this;
		}

		public Criteria andSgSostLikeInsensitive(String value) {
			addCriterion("upper(sg_sost) like", value.toUpperCase(), "sgSost");
			return (Criteria) this;
		}

		public Criteria andAttoLikeInsensitive(String value) {
			addCriterion("upper(atto) like", value.toUpperCase(), "atto");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
	 * @mbg.generated  Wed Mar 17 15:31:39 CET 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti_periodi
     *
     * @mbg.generated do_not_delete_during_merge Fri Feb 26 12:03:00 CET 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}