/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class VSoggettiCoinvoltiSelector {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public VSoggettiCoinvoltiSelector() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdcIsNull() {
			addCriterion("idc is null");
			return (Criteria) this;
		}

		public Criteria andIdcIsNotNull() {
			addCriterion("idc is not null");
			return (Criteria) this;
		}

		public Criteria andIdcEqualTo(Long value) {
			addCriterion("idc =", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcNotEqualTo(Long value) {
			addCriterion("idc <>", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcGreaterThan(Long value) {
			addCriterion("idc >", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcGreaterThanOrEqualTo(Long value) {
			addCriterion("idc >=", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcLessThan(Long value) {
			addCriterion("idc <", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcLessThanOrEqualTo(Long value) {
			addCriterion("idc <=", value, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcIn(List<Long> values) {
			addCriterion("idc in", values, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcNotIn(List<Long> values) {
			addCriterion("idc not in", values, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcBetween(Long value1, Long value2) {
			addCriterion("idc between", value1, value2, "idc");
			return (Criteria) this;
		}

		public Criteria andIdcNotBetween(Long value1, Long value2) {
			addCriterion("idc not between", value1, value2, "idc");
			return (Criteria) this;
		}

		public Criteria andAliasIsNull() {
			addCriterion("alias is null");
			return (Criteria) this;
		}

		public Criteria andAliasIsNotNull() {
			addCriterion("alias is not null");
			return (Criteria) this;
		}

		public Criteria andAliasEqualTo(String value) {
			addCriterion("alias =", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotEqualTo(String value) {
			addCriterion("alias <>", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasGreaterThan(String value) {
			addCriterion("alias >", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasGreaterThanOrEqualTo(String value) {
			addCriterion("alias >=", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasLessThan(String value) {
			addCriterion("alias <", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasLessThanOrEqualTo(String value) {
			addCriterion("alias <=", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasLike(String value) {
			addCriterion("alias like", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotLike(String value) {
			addCriterion("alias not like", value, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasIn(List<String> values) {
			addCriterion("alias in", values, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotIn(List<String> values) {
			addCriterion("alias not in", values, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasBetween(String value1, String value2) {
			addCriterion("alias between", value1, value2, "alias");
			return (Criteria) this;
		}

		public Criteria andAliasNotBetween(String value1, String value2) {
			addCriterion("alias not between", value1, value2, "alias");
			return (Criteria) this;
		}

		public Criteria andRuoloIsNull() {
			addCriterion("ruolo is null");
			return (Criteria) this;
		}

		public Criteria andRuoloIsNotNull() {
			addCriterion("ruolo is not null");
			return (Criteria) this;
		}

		public Criteria andRuoloEqualTo(String value) {
			addCriterion("ruolo =", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloNotEqualTo(String value) {
			addCriterion("ruolo <>", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloGreaterThan(String value) {
			addCriterion("ruolo >", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloGreaterThanOrEqualTo(String value) {
			addCriterion("ruolo >=", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloLessThan(String value) {
			addCriterion("ruolo <", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloLessThanOrEqualTo(String value) {
			addCriterion("ruolo <=", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloLike(String value) {
			addCriterion("ruolo like", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloNotLike(String value) {
			addCriterion("ruolo not like", value, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloIn(List<String> values) {
			addCriterion("ruolo in", values, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloNotIn(List<String> values) {
			addCriterion("ruolo not in", values, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloBetween(String value1, String value2) {
			addCriterion("ruolo between", value1, value2, "ruolo");
			return (Criteria) this;
		}

		public Criteria andRuoloNotBetween(String value1, String value2) {
			addCriterion("ruolo not between", value1, value2, "ruolo");
			return (Criteria) this;
		}

		public Criteria andPerContoDiIsNull() {
			addCriterion("per_conto_di is null");
			return (Criteria) this;
		}

		public Criteria andPerContoDiIsNotNull() {
			addCriterion("per_conto_di is not null");
			return (Criteria) this;
		}

		public Criteria andPerContoDiEqualTo(String value) {
			addCriterion("per_conto_di =", value, "perContoDi");
			return (Criteria) this;
		}

		public Criteria andPerContoDiNotEqualTo(String value) {
			addCriterion("per_conto_di <>", value, "perContoDi");
			return (Criteria) this;
		}

		public Criteria andPerContoDiGreaterThan(String value) {
			addCriterion("per_conto_di >", value, "perContoDi");
			return (Criteria) this;
		}

		public Criteria andPerContoDiGreaterThanOrEqualTo(String value) {
			addCriterion("per_conto_di >=", value, "perContoDi");
			return (Criteria) this;
		}

		public Criteria andPerContoDiLessThan(String value) {
			addCriterion("per_conto_di <", value, "perContoDi");
			return (Criteria) this;
		}

		public Criteria andPerContoDiLessThanOrEqualTo(String value) {
			addCriterion("per_conto_di <=", value, "perContoDi");
			return (Criteria) this;
		}

		public Criteria andPerContoDiLike(String value) {
			addCriterion("per_conto_di like", value, "perContoDi");
			return (Criteria) this;
		}

		public Criteria andPerContoDiNotLike(String value) {
			addCriterion("per_conto_di not like", value, "perContoDi");
			return (Criteria) this;
		}

		public Criteria andPerContoDiIn(List<String> values) {
			addCriterion("per_conto_di in", values, "perContoDi");
			return (Criteria) this;
		}

		public Criteria andPerContoDiNotIn(List<String> values) {
			addCriterion("per_conto_di not in", values, "perContoDi");
			return (Criteria) this;
		}

		public Criteria andPerContoDiBetween(String value1, String value2) {
			addCriterion("per_conto_di between", value1, value2, "perContoDi");
			return (Criteria) this;
		}

		public Criteria andPerContoDiNotBetween(String value1, String value2) {
			addCriterion("per_conto_di not between", value1, value2, "perContoDi");
			return (Criteria) this;
		}

		public Criteria andIdSgIsNull() {
			addCriterion("id_sg is null");
			return (Criteria) this;
		}

		public Criteria andIdSgIsNotNull() {
			addCriterion("id_sg is not null");
			return (Criteria) this;
		}

		public Criteria andIdSgEqualTo(Long value) {
			addCriterion("id_sg =", value, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgNotEqualTo(Long value) {
			addCriterion("id_sg <>", value, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgGreaterThan(Long value) {
			addCriterion("id_sg >", value, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgGreaterThanOrEqualTo(Long value) {
			addCriterion("id_sg >=", value, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgLessThan(Long value) {
			addCriterion("id_sg <", value, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgLessThanOrEqualTo(Long value) {
			addCriterion("id_sg <=", value, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgIn(List<Long> values) {
			addCriterion("id_sg in", values, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgNotIn(List<Long> values) {
			addCriterion("id_sg not in", values, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgBetween(Long value1, Long value2) {
			addCriterion("id_sg between", value1, value2, "idSg");
			return (Criteria) this;
		}

		public Criteria andIdSgNotBetween(Long value1, Long value2) {
			addCriterion("id_sg not between", value1, value2, "idSg");
			return (Criteria) this;
		}

		public Criteria andDIniIsNull() {
			addCriterion("d_ini is null");
			return (Criteria) this;
		}

		public Criteria andDIniIsNotNull() {
			addCriterion("d_ini is not null");
			return (Criteria) this;
		}

		public Criteria andDIniEqualTo(Date value) {
			addCriterionForJDBCDate("d_ini =", value, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniNotEqualTo(Date value) {
			addCriterionForJDBCDate("d_ini <>", value, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniGreaterThan(Date value) {
			addCriterionForJDBCDate("d_ini >", value, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("d_ini >=", value, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniLessThan(Date value) {
			addCriterionForJDBCDate("d_ini <", value, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("d_ini <=", value, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniIn(List<Date> values) {
			addCriterionForJDBCDate("d_ini in", values, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniNotIn(List<Date> values) {
			addCriterionForJDBCDate("d_ini not in", values, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("d_ini between", value1, value2, "dIni");
			return (Criteria) this;
		}

		public Criteria andDIniNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("d_ini not between", value1, value2, "dIni");
			return (Criteria) this;
		}

		public Criteria andDFinIsNull() {
			addCriterion("d_fin is null");
			return (Criteria) this;
		}

		public Criteria andDFinIsNotNull() {
			addCriterion("d_fin is not null");
			return (Criteria) this;
		}

		public Criteria andDFinEqualTo(Date value) {
			addCriterionForJDBCDate("d_fin =", value, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinNotEqualTo(Date value) {
			addCriterionForJDBCDate("d_fin <>", value, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinGreaterThan(Date value) {
			addCriterionForJDBCDate("d_fin >", value, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("d_fin >=", value, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinLessThan(Date value) {
			addCriterionForJDBCDate("d_fin <", value, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("d_fin <=", value, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinIn(List<Date> values) {
			addCriterionForJDBCDate("d_fin in", values, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinNotIn(List<Date> values) {
			addCriterionForJDBCDate("d_fin not in", values, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("d_fin between", value1, value2, "dFin");
			return (Criteria) this;
		}

		public Criteria andDFinNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("d_fin not between", value1, value2, "dFin");
			return (Criteria) this;
		}

		public Criteria andAliasLikeInsensitive(String value) {
			addCriterion("upper(alias) like", value.toUpperCase(), "alias");
			return (Criteria) this;
		}

		public Criteria andRuoloLikeInsensitive(String value) {
			addCriterion("upper(ruolo) like", value.toUpperCase(), "ruolo");
			return (Criteria) this;
		}

		public Criteria andPerContoDiLikeInsensitive(String value) {
			addCriterion("upper(per_conto_di) like", value.toUpperCase(), "perContoDi");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
     *
     * @mbg.generated do_not_delete_during_merge Wed Dec 16 10:32:01 CET 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}