/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class VSoggettiCoinvoltiDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_soggetti_coinvolti.idc
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	private Long idc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_soggetti_coinvolti.alias
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	private String alias;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_soggetti_coinvolti.ruolo
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	private String ruolo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_soggetti_coinvolti.per_conto_di
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	private String perContoDi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_soggetti_coinvolti.id_sg
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	private Long idSg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_soggetti_coinvolti.d_ini
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	private Date dIni;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtpl_trasv.v_soggetti_coinvolti.d_fin
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	private Date dFin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_soggetti_coinvolti.idc
	 * @return  the value of sirtpl_trasv.v_soggetti_coinvolti.idc
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public Long getIdc() {
		return idc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_soggetti_coinvolti.idc
	 * @param idc  the value for sirtpl_trasv.v_soggetti_coinvolti.idc
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public void setIdc(Long idc) {
		this.idc = idc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_soggetti_coinvolti.alias
	 * @return  the value of sirtpl_trasv.v_soggetti_coinvolti.alias
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public String getAlias() {
		return alias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_soggetti_coinvolti.alias
	 * @param alias  the value for sirtpl_trasv.v_soggetti_coinvolti.alias
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public void setAlias(String alias) {
		this.alias = alias == null ? null : alias.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_soggetti_coinvolti.ruolo
	 * @return  the value of sirtpl_trasv.v_soggetti_coinvolti.ruolo
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public String getRuolo() {
		return ruolo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_soggetti_coinvolti.ruolo
	 * @param ruolo  the value for sirtpl_trasv.v_soggetti_coinvolti.ruolo
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public void setRuolo(String ruolo) {
		this.ruolo = ruolo == null ? null : ruolo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_soggetti_coinvolti.per_conto_di
	 * @return  the value of sirtpl_trasv.v_soggetti_coinvolti.per_conto_di
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public String getPerContoDi() {
		return perContoDi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_soggetti_coinvolti.per_conto_di
	 * @param perContoDi  the value for sirtpl_trasv.v_soggetti_coinvolti.per_conto_di
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public void setPerContoDi(String perContoDi) {
		this.perContoDi = perContoDi == null ? null : perContoDi.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_soggetti_coinvolti.id_sg
	 * @return  the value of sirtpl_trasv.v_soggetti_coinvolti.id_sg
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public Long getIdSg() {
		return idSg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_soggetti_coinvolti.id_sg
	 * @param idSg  the value for sirtpl_trasv.v_soggetti_coinvolti.id_sg
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public void setIdSg(Long idSg) {
		this.idSg = idSg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_soggetti_coinvolti.d_ini
	 * @return  the value of sirtpl_trasv.v_soggetti_coinvolti.d_ini
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public Date getdIni() {
		return dIni;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_soggetti_coinvolti.d_ini
	 * @param dIni  the value for sirtpl_trasv.v_soggetti_coinvolti.d_ini
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public void setdIni(Date dIni) {
		this.dIni = dIni;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtpl_trasv.v_soggetti_coinvolti.d_fin
	 * @return  the value of sirtpl_trasv.v_soggetti_coinvolti.d_fin
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public Date getdFin() {
		return dFin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtpl_trasv.v_soggetti_coinvolti.d_fin
	 * @param dFin  the value for sirtpl_trasv.v_soggetti_coinvolti.d_fin
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	public void setdFin(Date dFin) {
		this.dFin = dFin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpl_trasv.v_soggetti_coinvolti
	 * @mbg.generated  Mon Mar 08 11:33:08 CET 2021
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idc=").append(idc);
		sb.append(", alias=").append(alias);
		sb.append(", ruolo=").append(ruolo);
		sb.append(", perContoDi=").append(perContoDi);
		sb.append(", idSg=").append(idSg);
		sb.append(", dIni=").append(dIni);
		sb.append(", dFin=").append(dFin);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}