-- Views
DROP VIEW IF EXISTS rebus_r_utente_az_ente;
DROP VIEW IF EXISTS rebus_t_aziende;
DROP VIEW IF EXISTS rebus_t_enti;
DROP VIEW IF EXISTS rebus_t_utenti;
DROP VIEW IF EXISTS v_autobus;
DROP VIEW IF EXISTS v_autobus_small;
DROP VIEW IF EXISTS v_autobus_small2;
DROP VIEW IF EXISTS v_export_ricerca_autobus;
DROP VIEW IF EXISTS v_export_ricerca_contribuzione;
DROP VIEW IF EXISTS v_export_ricerca_storia_autobus;
DROP VIEW IF EXISTS v_procedimenti_veicoli;
DROP VIEW IF EXISTS v_sirtpl_utente;
DROP VIEW IF EXISTS v_sirtpl_utente_ente;
DROP VIEW IF EXISTS v_sirtpla_aziende;
DROP VIEW IF EXISTS v_sirtpla_enti;
DROP VIEW IF EXISTS v_storia_autobus;
DROP VIEW IF EXISTS v_varautobus_no_dispositivi;
DROP VIEW IF EXISTS v_veicoli_procedimenti;



-- Functions
DROP FUNCTION IF EXISTS fnc_trg_t_variaz_autobus_bu()         CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_variaz_autobus_bi()         CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_storia_variaz_autobus_bu()  CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_storia_variaz_autobus_bi()  CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_procedimento_bu()           CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_procedimento_bi()           CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_ordine_acquisto_bu()        CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_ordine_acquisto_bi()        CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_messaggi_bu()               CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_messaggi_bi()               CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_iter_procedimento_bu()      CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_iter_procedimento_bi()      CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_documento_bu()              CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_documento_bi()              CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_dato_messa_servizio_bu()    CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_dato_messa_servizio_bi()    CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_costo_fornitura_bu()        CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_costo_fornitura_bi()        CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_contribuzione_bu()          CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_contribuzione_bi()          CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_assegnazione_risorse_bu()   CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_t_assegnazione_risorse_bi()   CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_r_proc_veicolo_bu()           CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_r_proc_veicolo_bi()           CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_r_proc_documento_bu()         CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_r_proc_documento_bi()         CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_r_proc_contratto_bu()         CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_r_proc_contratto_bi()         CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_r_doc_variaz_autobus_bu()     CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_r_doc_variaz_autobus_bi()     CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_r_doc_contribuzione_bu()      CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_r_doc_contribuzione_bi()      CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_dato_spesa_bu()               CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_dato_spesa_bi()               CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_d_tipo_messaggio_bu()         CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_d_tipo_messaggio_bi()         CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_d_tipo_documento_bu()         CASCADE;
DROP FUNCTION IF EXISTS fnc_trg_d_tipo_documento_bi()         CASCADE;
DROP FUNCTION IF EXISTS BonificaDispositivi()                 CASCADE;



-- Tables
DROP TABLE IF EXISTS rebus_d_categoria_veicolo                  CASCADE;
DROP TABLE IF EXISTS rebus_d_classe_amb_euro                    CASCADE;
DROP TABLE IF EXISTS rebus_d_classe_veicolo                     CASCADE;
DROP TABLE IF EXISTS rebus_d_dispositivi_prevenz                CASCADE;
DROP TABLE IF EXISTS rebus_d_dotazione_disabili                 CASCADE;
DROP TABLE IF EXISTS rebus_d_impianti_audio                     CASCADE;
DROP TABLE IF EXISTS rebus_d_impianti_visivi                    CASCADE;
DROP TABLE IF EXISTS rebus_d_proprieta                          CASCADE;
DROP TABLE IF EXISTS rebus_d_ruolo_azienda                      CASCADE;
DROP TABLE IF EXISTS rebus_d_tipo_alimentazione                 CASCADE;
DROP TABLE IF EXISTS rebus_d_tipo_allestimento                  CASCADE;
DROP TABLE IF EXISTS rebus_d_tipo_documento                     CASCADE;
DROP TABLE IF EXISTS rebus_d_tipo_immatricol                    CASCADE;
DROP TABLE IF EXISTS rebus_d_tipo_messaggio                     CASCADE;
DROP TABLE IF EXISTS rebus_d_tipo_messaggio_sistema             CASCADE;
DROP TABLE IF EXISTS rebus_r_azienda_azienda                    CASCADE;
DROP TABLE IF EXISTS rebus_t_bacini                             CASCADE;
DROP TABLE IF EXISTS rebus_t_bandi                              CASCADE;
DROP TABLE IF EXISTS rebus_t_consorzi                           CASCADE;
DROP TABLE IF EXISTS rebus_t_gestori_trasporti                  CASCADE;
DROP TABLE IF EXISTS rebus_t_stati                              CASCADE;
DROP TABLE IF EXISTS rebusc_d_portabici                         CASCADE;
DROP TABLE IF EXISTS rebusc_d_sistema_bigliettazione            CASCADE;
DROP TABLE IF EXISTS rebusc_d_sistema_localizzazione            CASCADE;
DROP TABLE IF EXISTS rebusc_d_sistema_videosorveglianza         CASCADE;
DROP TABLE IF EXISTS rebusc_d_tipo_doc_quietanza                CASCADE;
DROP TABLE IF EXISTS rebusc_d_tipo_garanzia                     CASCADE;
DROP TABLE IF EXISTS rebusc_d_tipo_sostituzione                 CASCADE;
DROP TABLE IF EXISTS rebusc_d_voce_costo                        CASCADE;
DROP TABLE IF EXISTS rebusc_t_atto_assegnazione                 CASCADE;
DROP TABLE IF EXISTS rebusc_t_dato_bonifico                     CASCADE;
DROP TABLE IF EXISTS rebusc_t_dato_spesa                        CASCADE;
DROP TABLE IF EXISTS rebusc_t_ordine_acquisto                   CASCADE;
DROP TABLE IF EXISTS rebusm_d_tipo_monitoraggio                 CASCADE;
DROP TABLE IF EXISTS rebusp_d_motorizzazione                    CASCADE;
DROP TABLE IF EXISTS rebusp_d_stato_iter                        CASCADE;
DROP TABLE IF EXISTS rebusp_d_tipo_procedimento                 CASCADE;
DROP TABLE IF EXISTS rebusp_d_tipo_ruolo                        CASCADE;
DROP TABLE IF EXISTS rebusp_d_tipo_stampa                       CASCADE;
DROP TABLE IF EXISTS rebusp_r_proc_contratto_linea              CASCADE;
DROP TABLE IF EXISTS rebusp_t_documento                         CASCADE;
DROP TABLE IF EXISTS rebus_d_tipologia_dimens                   CASCADE;
DROP TABLE IF EXISTS rebus_r_consorzi_aziende                   CASCADE;
DROP TABLE IF EXISTS rebus_r_contratti_servizio                 CASCADE;
DROP TABLE IF EXISTS rebus_r_doc_variaz_autobus                 CASCADE;
DROP TABLE IF EXISTS rebus_t_autobus                            CASCADE;
DROP TABLE IF EXISTS rebus_t_regioni                            CASCADE;
DROP TABLE IF EXISTS rebus_t_storia_variaz_autobus              CASCADE;
DROP TABLE IF EXISTS rebus_t_variaz_autobus                     CASCADE;
DROP TABLE IF EXISTS rebusc_r_doc_contribuzione                 CASCADE;
DROP TABLE IF EXISTS rebusc_t_costo_fornitura                   CASCADE;
DROP TABLE IF EXISTS rebusc_t_dato_fattura                      CASCADE;
DROP TABLE IF EXISTS rebusc_t_dato_messa_servizio               CASCADE;
DROP TABLE IF EXISTS rebusc_t_fonte_finanziamento               CASCADE;
DROP TABLE IF EXISTS rebusm_d_campagna                          CASCADE;
DROP TABLE IF EXISTS rebusm_r_doc_misurazione                   CASCADE;
DROP TABLE IF EXISTS rebusm_t_misurazione                       CASCADE;
DROP TABLE IF EXISTS rebusp_c_tipo_proc_tipo_doc                CASCADE;
DROP TABLE IF EXISTS rebusp_d_motivazione                       CASCADE;
DROP TABLE IF EXISTS rebusp_d_transizione_automa                CASCADE;
DROP TABLE IF EXISTS rebusp_t_procedimento                      CASCADE;
DROP TABLE IF EXISTS rebusp_t_sub_procedimento                  CASCADE;
DROP TABLE IF EXISTS rebus_r_azienda_autobus                    CASCADE;
DROP TABLE IF EXISTS rebus_r_storia_varautobus_dp               CASCADE;
DROP TABLE IF EXISTS rebus_r_varautobus_dp                      CASCADE;
DROP TABLE IF EXISTS rebus_t_messaggi                           CASCADE;
DROP TABLE IF EXISTS rebus_t_province                           CASCADE;
DROP TABLE IF EXISTS rebusc_r_doc_dato_messa_servizio           CASCADE;
DROP TABLE IF EXISTS rebusc_r_fattura_bonifico                  CASCADE;
DROP TABLE IF EXISTS rebusc_r_voce_costo_fornitura              CASCADE;
DROP TABLE IF EXISTS rebusc_t_assegnazione_risorse              CASCADE;
DROP TABLE IF EXISTS rebusc_t_contribuzione                     CASCADE;
DROP TABLE IF EXISTS rebusm_r_campagna_misurazione              CASCADE;
DROP TABLE IF EXISTS rebusm_t_mis_emissioni                     CASCADE;
DROP TABLE IF EXISTS rebusm_t_mis_portabici                     CASCADE;
DROP TABLE IF EXISTS rebusp_r_proc_contratto                    CASCADE;
DROP TABLE IF EXISTS rebusp_r_proc_documento                    CASCADE;
DROP TABLE IF EXISTS rebusp_r_proc_veicolo                      CASCADE;
DROP TABLE IF EXISTS rebusp_t_iter_procedimento                 CASCADE;
DROP TABLE IF EXISTS rebus_t_comuni                             CASCADE;
DROP TABLE IF EXISTS rebus_t_depositi                           CASCADE;
DROP TABLE IF EXISTS rebusc_r_oggetto_fattura                   CASCADE;
DROP TABLE IF EXISTS rebus_r_depositi_azienda                   CASCADE;



-- Sequuences
DROP SEQUENCE IF EXISTS seq_r_doc_contribuzione;
DROP SEQUENCE IF EXISTS seq_r_proc_contratto;
DROP SEQUENCE IF EXISTS seq_r_voce_costo_veicolo;
DROP SEQUENCE IF EXISTS seq_rebus_t_aziende;
DROP SEQUENCE IF EXISTS seq_rebus_t_bacini;
DROP SEQUENCE IF EXISTS seq_rebus_t_bandi;
DROP SEQUENCE IF EXISTS seq_rebus_t_consorzi;
DROP SEQUENCE IF EXISTS seq_rebus_t_depositi;
DROP SEQUENCE IF EXISTS seq_rebus_t_gestori_trasporti;
DROP SEQUENCE IF EXISTS seq_rebus_t_messaggi;
DROP SEQUENCE IF EXISTS seq_rebus_t_storia_variaz_autobus;
DROP SEQUENCE IF EXISTS seq_rebus_t_utenti;
DROP SEQUENCE IF EXISTS seq_rebus_t_variaz_autobus;
DROP SEQUENCE IF EXISTS seq_rebus_t_variaz_aziende;
DROP SEQUENCE IF EXISTS seq_t_assegnazione_risorse;
DROP SEQUENCE IF EXISTS seq_t_contribuzione;
DROP SEQUENCE IF EXISTS seq_t_costo_fornitura;
DROP SEQUENCE IF EXISTS seq_t_dato_bonifico;
DROP SEQUENCE IF EXISTS seq_t_dato_fattura;
DROP SEQUENCE IF EXISTS seq_t_dato_messa_servizio;
DROP SEQUENCE IF EXISTS seq_t_dato_spesa;
DROP SEQUENCE IF EXISTS seq_t_documento;
DROP SEQUENCE IF EXISTS seq_t_iter_procedimento;
DROP SEQUENCE IF EXISTS seq_t_ordine_acquisto;
DROP SEQUENCE IF EXISTS seq_t_procedimento;
