/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.anagraficasrv.security;

public enum AuthorizationRoles {
	ACCESSO_AL_SISTEMA_REBUS("REBUS-1"), //
	ACCESSO_SEZIONE_ANAGRAFICA_AUTOBUS("REBUS-2"), //
	DOWNLOAD_FILE_XLS("REBUS-3"), //
	UPLOAD_FILE_XLS("REBUS-4"), //
	UPLOAD_FILE_XLS_PRIMO_IMPIANTO("REBUS-16"), //
	RICERCA_ANAGRAFICA_BUS("REBUS-5"), //
	INSERIMENTO_ANAGRAFICA_BUS("REBUS-6"), //
	CONSULTAZIONE_DETTAGLIO_ANAGRAFICA_BUS("REBUS-7"), //
	MODIFICA_BUS("REBUS-8"), //
	MODIFICA_BUS_AMP("REBUS-17"), //
	CANCELLAZIONE_AUTOBUS_NON_VERIFICATO_AZIENDA("REBUS-9"), //
	ESPORTA_ELENCO_ANAGRAFICA_BUS("REBUS-10"), //
	ACCESSO_SEZIONE_ANAGRAFICA_AZIENDE("REBUS-11"), //
	RICERCA_ANAGRAFICA_AZIENDA("REBUS-12"), //
	VISUALIZZA_DETTAGLI_ANAGRAFICA_AZIENDA("REBUS-13"), //
	ESPORTA_ELENCO_ANAGRAFICA_AZIENDA("REBUS-14"), //
	MESSAGGISTICA("REBUS-15"), //
	UTENTE("UTENTE"), //
	ACCESSO_AL_SISTEMA_ANAGRAFICHE("ANAG-1"), //
	ACCESSO_SEZIONE_ANAGRAFICA_SOGGETTI("ANAGA-1"), //
	RICERCA_ANAGRAFICA_SOGGETTI("ANAGA-2"), //
	VISUALIZZA_DETTAGLI_ANAGRAFICA_SOGGETTO("ANAGA-3"), //
	ESPORTA_ELENCO_ANAGRAFICA_SOGGETTI("ANAGA-4"), //
	INSERIMENTO_ANAGRAFICA_SOGGETTO("ANAGA-5"), //
	MODIFICA_ANAGRAFICA_SOGGETTO("ANAGA-6"), //
	ACCESSO_SEZIONE_ANAGRAFICA_CONTRATTI("ANAGC-1"), //
	RICERCA_ANAGRAFICA_CONTRATTI("ANAGC-2"), //
	VISUALIZZA_DETTAGLI_ANAGRAFICA_CONTRATTO("ANAGC-3"), //
	ESPORTA_ELENCO_ANAGRAFICA_CONTRATTI("ANAGC-4"), //
	INSERIMENTO_ANAGRAFICA_CONTRATTO("ANAGC-5"), //
	MODIFICA_ANAGRAFICA_CONTRATTO("ANAGC-6"); //

	private String id;

	private AuthorizationRoles(String id) {
		this.id = id;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

}
