/*************************************************
Copyright Regione Piemonte - 2022
SPDX-License-Identifier: EUPL-1.2-or-later
***************************************************/


export enum AuthorizationRoles {
    ACCESSO_AL_SISTEMA = "REBUS-1", //
    ACCESSO_SEZIONE_ANAGRAFICA_AUTOBUS = "REBUS-2", //non utilizzato
    DOWNLOAD_FILE_XLS = "REBUS-3", //
    UPLOAD_FILE_XLS = "REBUS-4", //
    UPLOAD_FILE_XLS_PRIMO_IMPIANTO = "REBUS-16", //
    RICERCA_ANAGRAFICA_BUS = "REBUS-5", //
    INSERIMENTO_ANAGRAFICA_BUS = "REBUS-6", //
    CONSULTAZIONE_DETTAGLIO_ANAGRAFICA_BUS = "REBUS-7", //
    MODIFICA_BUS = "REBUS-8", //
    MODIFICA_BUS_AMP = "REBUS-17", //
    CANCELLAZIONE_AUTOBUS_NON_VERIFICATO_AZIENDA = "REBUS-9", //
    ESPORTA_ELENCO_ANAGRAFICA_BUS = "REBUS-10", //
    ACCESSO_SEZIONE_ANAGRAFICA_AZIENDE = "REBUS-11", //
    RICERCA_ANAGRAFICA_AZIENDA = "REBUS-12", //
    VISUALIZZA_DETTAGLI_ANAGRAFICA_AZIENDA = "REBUS-13", //
    ESPORTA_ELENCO_ANAGRAFICA_AZIENDA = "REBUS-14", //
    MESSAGGISTICA = "REBUS-15", //
    RICERCA_PROCEDIMENTI = "REBUSP-2",
    DETTAGLIO_PROCEDIMENTO = "REBUSP-3",
    INSERIMENTO_PROCEDIMENTO = "REBUSP-4",
    MODIFICA_PROCEDIMENTO = "REBUSP-5",
    ELIMINA_PROCEDIMENTO = "REBUSP-6",
    SCARICA_EXCEL_PROCEDIMENTO = "REBUSP-7",
    SCARICA_PDF = "REBUSP-8",
    SCARICA_RIFERIMENTI  = "REBUSP-9",
    MODIFICA_RIFERIMENTI = "REBUSP-10",
    UTENTE = "UTENTE",//
    ACCESSO_AL_SISTEMA_ANAGRAFICHE = "ANAG-1", //
    ACCESSO_SEZIONE_ANAGRAFICA_SOGGETTI = "ANAGA-1", //
    RICERCA_ANAGRAFICA_SOGGETTI = "ANAGA-2", //
    VISUALIZZA_DETTAGLI_ANAGRAFICA_SOGGETTO = "ANAGA-3", //
    ESPORTA_ELENCO_ANAGRAFICA_SOGGETTI = "ANAGA-4", //
    INSERIMENTO_ANAGRAFICA_SOGGETTO = "ANAGA-5", //
    MODIFICA_ANAGRAFICA_SOGGETTO = "ANAGA-6", //
    ACCESSO_SEZIONE_ANAGRAFICA_CONTRATTI = "ANAGC-1", //
    RICERCA_ANAGRAFICA_CONTRATTI = "ANAGC-2", //
    VISUALIZZA_DETTAGLI_ANAGRAFICA_CONTRATTO = "ANAGC-3", //
    ESPORTA_ELENCO_ANAGRAFICA_CONTRATTI = "ANAGC-4", //
    INSERIMENTO_ANAGRAFICA_CONTRATTO = "ANAGC-5", //
    MODIFICA_ANAGRAFICA_CONTRATTO = "ANAGC-6", //
    // CONTRIBUZIONE
    ACCESSO_SEZIONE_CONTRIBUZIONE = "REBUSC-1",
	RICERCA_CONTRIBUZIONE = "REBUSC-2",
	VISUALIZZA_DETTAGLI_CONTRIBUZIONE = "REBUSC-3",
	INSERIMENTO_CONTRIBUZIONE = "REBUSC-4",
	MODIFICA_DETTAGLI_CONTRIBUZIONE = "REBUSC-5",
	ELIMINA_CONTRIBUZIONE = "REBUSC-6",
	ESPORTA_RICERCA_CONTRIBUZIONE = "REBUSC-7",
	GENERA_ZIP = "REBUSC-8",
    // messaggi
    MESSAGGI = "REBUS-18", 
    MESSAGGI_RICHIESTE = "REBUSP-11", 
    MESSAGGI_RENDICONTRAZIONE =  "REBUSC-9"

}