/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;

public class RebuscRDocDatoMessaServizioKey extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusc_r_doc_dato_messa_servizio.id_dato_messa_servizio
     *
     * @mbg.generated Wed Nov 24 17:39:06 CET 2021
     */
    private Long idDatoMessaServizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusc_r_doc_dato_messa_servizio.id_doc_contribuzione
     *
     * @mbg.generated Wed Nov 24 17:39:06 CET 2021
     */
    private Long idDocContribuzione;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusc_r_doc_dato_messa_servizio
     *
     * @mbg.generated Wed Nov 24 17:39:06 CET 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusc_r_doc_dato_messa_servizio.id_dato_messa_servizio
     *
     * @return the value of rebusc_r_doc_dato_messa_servizio.id_dato_messa_servizio
     *
     * @mbg.generated Wed Nov 24 17:39:06 CET 2021
     */
    public Long getIdDatoMessaServizio() {
        return idDatoMessaServizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusc_r_doc_dato_messa_servizio.id_dato_messa_servizio
     *
     * @param idDatoMessaServizio the value for rebusc_r_doc_dato_messa_servizio.id_dato_messa_servizio
     *
     * @mbg.generated Wed Nov 24 17:39:06 CET 2021
     */
    public void setIdDatoMessaServizio(Long idDatoMessaServizio) {
        this.idDatoMessaServizio = idDatoMessaServizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusc_r_doc_dato_messa_servizio.id_doc_contribuzione
     *
     * @return the value of rebusc_r_doc_dato_messa_servizio.id_doc_contribuzione
     *
     * @mbg.generated Wed Nov 24 17:39:06 CET 2021
     */
    public Long getIdDocContribuzione() {
        return idDocContribuzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusc_r_doc_dato_messa_servizio.id_doc_contribuzione
     *
     * @param idDocContribuzione the value for rebusc_r_doc_dato_messa_servizio.id_doc_contribuzione
     *
     * @mbg.generated Wed Nov 24 17:39:06 CET 2021
     */
    public void setIdDocContribuzione(Long idDocContribuzione) {
        this.idDocContribuzione = idDocContribuzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_r_doc_dato_messa_servizio
     *
     * @mbg.generated Wed Nov 24 17:39:06 CET 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idDatoMessaServizio=").append(idDatoMessaServizio);
        sb.append(", idDocContribuzione=").append(idDocContribuzione);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}