/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;

public class RebusDTipologiaDimensDTO extends RebusDTipologiaDimensKey implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_d_tipologia_dimens.lunghezza_min
	 * @mbg.generated  Mon Feb 10 18:12:36 CET 2020
	 */
	private Double lunghezzaMin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_d_tipologia_dimens.lunghezza_max
	 * @mbg.generated  Mon Feb 10 18:12:36 CET 2020
	 */
	private Double lunghezzaMax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_d_tipologia_dimens.tipologia_dimens
	 * @mbg.generated  Mon Feb 10 18:12:36 CET 2020
	 */
	private String tipologiaDimens;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebus_d_tipologia_dimens
	 * @mbg.generated  Mon Feb 10 18:12:36 CET 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_d_tipologia_dimens.lunghezza_min
	 * @return  the value of rebus_d_tipologia_dimens.lunghezza_min
	 * @mbg.generated  Mon Feb 10 18:12:36 CET 2020
	 */
	public Double getLunghezzaMin() {
		return lunghezzaMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_d_tipologia_dimens.lunghezza_min
	 * @param lunghezzaMin  the value for rebus_d_tipologia_dimens.lunghezza_min
	 * @mbg.generated  Mon Feb 10 18:12:36 CET 2020
	 */
	public void setLunghezzaMin(Double lunghezzaMin) {
		this.lunghezzaMin = lunghezzaMin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_d_tipologia_dimens.lunghezza_max
	 * @return  the value of rebus_d_tipologia_dimens.lunghezza_max
	 * @mbg.generated  Mon Feb 10 18:12:36 CET 2020
	 */
	public Double getLunghezzaMax() {
		return lunghezzaMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_d_tipologia_dimens.lunghezza_max
	 * @param lunghezzaMax  the value for rebus_d_tipologia_dimens.lunghezza_max
	 * @mbg.generated  Mon Feb 10 18:12:36 CET 2020
	 */
	public void setLunghezzaMax(Double lunghezzaMax) {
		this.lunghezzaMax = lunghezzaMax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_d_tipologia_dimens.tipologia_dimens
	 * @return  the value of rebus_d_tipologia_dimens.tipologia_dimens
	 * @mbg.generated  Mon Feb 10 18:12:36 CET 2020
	 */
	public String getTipologiaDimens() {
		return tipologiaDimens;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_d_tipologia_dimens.tipologia_dimens
	 * @param tipologiaDimens  the value for rebus_d_tipologia_dimens.tipologia_dimens
	 * @mbg.generated  Mon Feb 10 18:12:36 CET 2020
	 */
	public void setTipologiaDimens(String tipologiaDimens) {
		this.tipologiaDimens = tipologiaDimens == null ? null : tipologiaDimens.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipologia_dimens
	 * @mbg.generated  Mon Feb 10 18:12:36 CET 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", lunghezzaMin=").append(lunghezzaMin);
		sb.append(", lunghezzaMax=").append(lunghezzaMax);
		sb.append(", tipologiaDimens=").append(tipologiaDimens);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}