/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebuspDTransizioneAutomaDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_transizione_automa.id_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	private Long idTransizioneAutoma;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_transizione_automa.id_stato_iter_da
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	private Long idStatoIterDa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_transizione_automa.id_stato_iter_a
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	private Long idStatoIterA;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_transizione_automa.titolo
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	private String titolo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_transizione_automa.label
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	private String label;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_transizione_automa.testo
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	private String testo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_transizione_automa.condizioni
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	private String condizioni;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_transizione_automa.flg_note_obbligatorie
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	private Boolean flgNoteObbligatorie;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_transizione_automa.id_tipo_messaggio
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	private Long idTipoMessaggio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_transizione_automa.data_inizio_validita
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	private Date dataInizioValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_transizione_automa.data_fine_validita
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	private Date dataFineValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_transizione_automa.flag_default
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	private Boolean flagDefault;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_transizione_automa.id_transizione_automa
	 * @return  the value of rebusp_d_transizione_automa.id_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public Long getIdTransizioneAutoma() {
		return idTransizioneAutoma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_transizione_automa.id_transizione_automa
	 * @param idTransizioneAutoma  the value for rebusp_d_transizione_automa.id_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void setIdTransizioneAutoma(Long idTransizioneAutoma) {
		this.idTransizioneAutoma = idTransizioneAutoma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_transizione_automa.id_stato_iter_da
	 * @return  the value of rebusp_d_transizione_automa.id_stato_iter_da
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public Long getIdStatoIterDa() {
		return idStatoIterDa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_transizione_automa.id_stato_iter_da
	 * @param idStatoIterDa  the value for rebusp_d_transizione_automa.id_stato_iter_da
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void setIdStatoIterDa(Long idStatoIterDa) {
		this.idStatoIterDa = idStatoIterDa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_transizione_automa.id_stato_iter_a
	 * @return  the value of rebusp_d_transizione_automa.id_stato_iter_a
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public Long getIdStatoIterA() {
		return idStatoIterA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_transizione_automa.id_stato_iter_a
	 * @param idStatoIterA  the value for rebusp_d_transizione_automa.id_stato_iter_a
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void setIdStatoIterA(Long idStatoIterA) {
		this.idStatoIterA = idStatoIterA;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_transizione_automa.titolo
	 * @return  the value of rebusp_d_transizione_automa.titolo
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public String getTitolo() {
		return titolo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_transizione_automa.titolo
	 * @param titolo  the value for rebusp_d_transizione_automa.titolo
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void setTitolo(String titolo) {
		this.titolo = titolo == null ? null : titolo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_transizione_automa.label
	 * @return  the value of rebusp_d_transizione_automa.label
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_transizione_automa.label
	 * @param label  the value for rebusp_d_transizione_automa.label
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void setLabel(String label) {
		this.label = label == null ? null : label.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_transizione_automa.testo
	 * @return  the value of rebusp_d_transizione_automa.testo
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public String getTesto() {
		return testo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_transizione_automa.testo
	 * @param testo  the value for rebusp_d_transizione_automa.testo
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void setTesto(String testo) {
		this.testo = testo == null ? null : testo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_transizione_automa.condizioni
	 * @return  the value of rebusp_d_transizione_automa.condizioni
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public String getCondizioni() {
		return condizioni;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_transizione_automa.condizioni
	 * @param condizioni  the value for rebusp_d_transizione_automa.condizioni
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void setCondizioni(String condizioni) {
		this.condizioni = condizioni == null ? null : condizioni.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_transizione_automa.flg_note_obbligatorie
	 * @return  the value of rebusp_d_transizione_automa.flg_note_obbligatorie
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public Boolean getFlgNoteObbligatorie() {
		return flgNoteObbligatorie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_transizione_automa.flg_note_obbligatorie
	 * @param flgNoteObbligatorie  the value for rebusp_d_transizione_automa.flg_note_obbligatorie
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void setFlgNoteObbligatorie(Boolean flgNoteObbligatorie) {
		this.flgNoteObbligatorie = flgNoteObbligatorie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_transizione_automa.id_tipo_messaggio
	 * @return  the value of rebusp_d_transizione_automa.id_tipo_messaggio
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public Long getIdTipoMessaggio() {
		return idTipoMessaggio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_transizione_automa.id_tipo_messaggio
	 * @param idTipoMessaggio  the value for rebusp_d_transizione_automa.id_tipo_messaggio
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void setIdTipoMessaggio(Long idTipoMessaggio) {
		this.idTipoMessaggio = idTipoMessaggio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_transizione_automa.data_inizio_validita
	 * @return  the value of rebusp_d_transizione_automa.data_inizio_validita
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public Date getDataInizioValidita() {
		return dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_transizione_automa.data_inizio_validita
	 * @param dataInizioValidita  the value for rebusp_d_transizione_automa.data_inizio_validita
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void setDataInizioValidita(Date dataInizioValidita) {
		this.dataInizioValidita = dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_transizione_automa.data_fine_validita
	 * @return  the value of rebusp_d_transizione_automa.data_fine_validita
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public Date getDataFineValidita() {
		return dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_transizione_automa.data_fine_validita
	 * @param dataFineValidita  the value for rebusp_d_transizione_automa.data_fine_validita
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void setDataFineValidita(Date dataFineValidita) {
		this.dataFineValidita = dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_transizione_automa.flag_default
	 * @return  the value of rebusp_d_transizione_automa.flag_default
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public Boolean getFlagDefault() {
		return flagDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_transizione_automa.flag_default
	 * @param flagDefault  the value for rebusp_d_transizione_automa.flag_default
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void setFlagDefault(Boolean flagDefault) {
		this.flagDefault = flagDefault;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idTransizioneAutoma=").append(idTransizioneAutoma);
		sb.append(", idStatoIterDa=").append(idStatoIterDa);
		sb.append(", idStatoIterA=").append(idStatoIterA);
		sb.append(", titolo=").append(titolo);
		sb.append(", label=").append(label);
		sb.append(", testo=").append(testo);
		sb.append(", condizioni=").append(condizioni);
		sb.append(", flgNoteObbligatorie=").append(flgNoteObbligatorie);
		sb.append(", idTipoMessaggio=").append(idTipoMessaggio);
		sb.append(", dataInizioValidita=").append(dataInizioValidita);
		sb.append(", dataFineValidita=").append(dataFineValidita);
		sb.append(", flagDefault=").append(flagDefault);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}