/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;

public class RebuspCTipoProcTipoDocKey extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_c_tipo_proc_tipo_doc.id_tipo_procedimento
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    private Long idTipoProcedimento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_c_tipo_proc_tipo_doc.id_tipo_documento
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    private Long idTipoDocumento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusp_c_tipo_proc_tipo_doc
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_c_tipo_proc_tipo_doc.id_tipo_procedimento
     *
     * @return the value of rebusp_c_tipo_proc_tipo_doc.id_tipo_procedimento
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    public Long getIdTipoProcedimento() {
        return idTipoProcedimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_c_tipo_proc_tipo_doc.id_tipo_procedimento
     *
     * @param idTipoProcedimento the value for rebusp_c_tipo_proc_tipo_doc.id_tipo_procedimento
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    public void setIdTipoProcedimento(Long idTipoProcedimento) {
        this.idTipoProcedimento = idTipoProcedimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_c_tipo_proc_tipo_doc.id_tipo_documento
     *
     * @return the value of rebusp_c_tipo_proc_tipo_doc.id_tipo_documento
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    public Long getIdTipoDocumento() {
        return idTipoDocumento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_c_tipo_proc_tipo_doc.id_tipo_documento
     *
     * @param idTipoDocumento the value for rebusp_c_tipo_proc_tipo_doc.id_tipo_documento
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    public void setIdTipoDocumento(Long idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_c_tipo_proc_tipo_doc
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idTipoProcedimento=").append(idTipoProcedimento);
        sb.append(", idTipoDocumento=").append(idTipoDocumento);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}