/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;

public class RebuspTSubProcedimentoKey extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_t_sub_procedimento.id_procedimento
     *
     * @mbg.generated Tue Mar 17 14:34:44 CET 2020
     */
    private Long idProcedimento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_t_sub_procedimento.id_sub_procedimento_1
     *
     * @mbg.generated Tue Mar 17 14:34:44 CET 2020
     */
    private Long idSubProcedimento1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_t_sub_procedimento.id_sub_procedimento_2
     *
     * @mbg.generated Tue Mar 17 14:34:44 CET 2020
     */
    private Long idSubProcedimento2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusp_t_sub_procedimento
     *
     * @mbg.generated Tue Mar 17 14:34:44 CET 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_t_sub_procedimento.id_procedimento
     *
     * @return the value of rebusp_t_sub_procedimento.id_procedimento
     *
     * @mbg.generated Tue Mar 17 14:34:44 CET 2020
     */
    public Long getIdProcedimento() {
        return idProcedimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_t_sub_procedimento.id_procedimento
     *
     * @param idProcedimento the value for rebusp_t_sub_procedimento.id_procedimento
     *
     * @mbg.generated Tue Mar 17 14:34:44 CET 2020
     */
    public void setIdProcedimento(Long idProcedimento) {
        this.idProcedimento = idProcedimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_t_sub_procedimento.id_sub_procedimento_1
     *
     * @return the value of rebusp_t_sub_procedimento.id_sub_procedimento_1
     *
     * @mbg.generated Tue Mar 17 14:34:44 CET 2020
     */
    public Long getIdSubProcedimento1() {
        return idSubProcedimento1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_t_sub_procedimento.id_sub_procedimento_1
     *
     * @param idSubProcedimento1 the value for rebusp_t_sub_procedimento.id_sub_procedimento_1
     *
     * @mbg.generated Tue Mar 17 14:34:44 CET 2020
     */
    public void setIdSubProcedimento1(Long idSubProcedimento1) {
        this.idSubProcedimento1 = idSubProcedimento1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_t_sub_procedimento.id_sub_procedimento_2
     *
     * @return the value of rebusp_t_sub_procedimento.id_sub_procedimento_2
     *
     * @mbg.generated Tue Mar 17 14:34:44 CET 2020
     */
    public Long getIdSubProcedimento2() {
        return idSubProcedimento2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_t_sub_procedimento.id_sub_procedimento_2
     *
     * @param idSubProcedimento2 the value for rebusp_t_sub_procedimento.id_sub_procedimento_2
     *
     * @mbg.generated Tue Mar 17 14:34:44 CET 2020
     */
    public void setIdSubProcedimento2(Long idSubProcedimento2) {
        this.idSubProcedimento2 = idSubProcedimento2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_t_sub_procedimento
     *
     * @mbg.generated Tue Mar 17 14:34:44 CET 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idProcedimento=").append(idProcedimento);
        sb.append(", idSubProcedimento1=").append(idSubProcedimento1);
        sb.append(", idSubProcedimento2=").append(idSubProcedimento2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}