/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebuspTProcedimentoDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.id_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private Long idProcedimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.id_motorizzazione
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private Long idMotorizzazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.id_tipo_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private Long idTipoProcedimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.id_motivazione
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private Long idMotivazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.testo_motiv_altro
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private String testoMotivAltro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.ruolo_firma
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private String ruoloFirma;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.ruolo_firma_ente
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private String ruoloFirmaEnte;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.nominativo_firma
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private String nominativoFirma;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.nominativo_firma_ente
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private String nominativoFirmaEnte;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.premesse
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private String premesse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.prescrizioni
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private String prescrizioni;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.num_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private Long numProcedimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.note
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.flg_firma_digitale_ente
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private Boolean flgFirmaDigitaleEnte;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.flg_firma_digitale
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private Boolean flgFirmaDigitale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.flg_allega_linee
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private Boolean flgAllegaLinee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.id_utente_aggiornamento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private Long idUtenteAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_t_procedimento.data_aggiornamento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusp_t_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.id_procedimento
	 * @return  the value of rebusp_t_procedimento.id_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public Long getIdProcedimento() {
		return idProcedimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.id_procedimento
	 * @param idProcedimento  the value for rebusp_t_procedimento.id_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setIdProcedimento(Long idProcedimento) {
		this.idProcedimento = idProcedimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.id_motorizzazione
	 * @return  the value of rebusp_t_procedimento.id_motorizzazione
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public Long getIdMotorizzazione() {
		return idMotorizzazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.id_motorizzazione
	 * @param idMotorizzazione  the value for rebusp_t_procedimento.id_motorizzazione
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setIdMotorizzazione(Long idMotorizzazione) {
		this.idMotorizzazione = idMotorizzazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.id_tipo_procedimento
	 * @return  the value of rebusp_t_procedimento.id_tipo_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public Long getIdTipoProcedimento() {
		return idTipoProcedimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.id_tipo_procedimento
	 * @param idTipoProcedimento  the value for rebusp_t_procedimento.id_tipo_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setIdTipoProcedimento(Long idTipoProcedimento) {
		this.idTipoProcedimento = idTipoProcedimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.id_motivazione
	 * @return  the value of rebusp_t_procedimento.id_motivazione
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public Long getIdMotivazione() {
		return idMotivazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.id_motivazione
	 * @param idMotivazione  the value for rebusp_t_procedimento.id_motivazione
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setIdMotivazione(Long idMotivazione) {
		this.idMotivazione = idMotivazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.testo_motiv_altro
	 * @return  the value of rebusp_t_procedimento.testo_motiv_altro
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public String getTestoMotivAltro() {
		return testoMotivAltro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.testo_motiv_altro
	 * @param testoMotivAltro  the value for rebusp_t_procedimento.testo_motiv_altro
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setTestoMotivAltro(String testoMotivAltro) {
		this.testoMotivAltro = testoMotivAltro == null ? null : testoMotivAltro.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.ruolo_firma
	 * @return  the value of rebusp_t_procedimento.ruolo_firma
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public String getRuoloFirma() {
		return ruoloFirma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.ruolo_firma
	 * @param ruoloFirma  the value for rebusp_t_procedimento.ruolo_firma
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setRuoloFirma(String ruoloFirma) {
		this.ruoloFirma = ruoloFirma == null ? null : ruoloFirma.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.ruolo_firma_ente
	 * @return  the value of rebusp_t_procedimento.ruolo_firma_ente
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public String getRuoloFirmaEnte() {
		return ruoloFirmaEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.ruolo_firma_ente
	 * @param ruoloFirmaEnte  the value for rebusp_t_procedimento.ruolo_firma_ente
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setRuoloFirmaEnte(String ruoloFirmaEnte) {
		this.ruoloFirmaEnte = ruoloFirmaEnte == null ? null : ruoloFirmaEnte.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.nominativo_firma
	 * @return  the value of rebusp_t_procedimento.nominativo_firma
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public String getNominativoFirma() {
		return nominativoFirma;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.nominativo_firma
	 * @param nominativoFirma  the value for rebusp_t_procedimento.nominativo_firma
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setNominativoFirma(String nominativoFirma) {
		this.nominativoFirma = nominativoFirma == null ? null : nominativoFirma.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.nominativo_firma_ente
	 * @return  the value of rebusp_t_procedimento.nominativo_firma_ente
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public String getNominativoFirmaEnte() {
		return nominativoFirmaEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.nominativo_firma_ente
	 * @param nominativoFirmaEnte  the value for rebusp_t_procedimento.nominativo_firma_ente
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setNominativoFirmaEnte(String nominativoFirmaEnte) {
		this.nominativoFirmaEnte = nominativoFirmaEnte == null ? null : nominativoFirmaEnte.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.premesse
	 * @return  the value of rebusp_t_procedimento.premesse
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public String getPremesse() {
		return premesse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.premesse
	 * @param premesse  the value for rebusp_t_procedimento.premesse
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setPremesse(String premesse) {
		this.premesse = premesse == null ? null : premesse.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.prescrizioni
	 * @return  the value of rebusp_t_procedimento.prescrizioni
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public String getPrescrizioni() {
		return prescrizioni;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.prescrizioni
	 * @param prescrizioni  the value for rebusp_t_procedimento.prescrizioni
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setPrescrizioni(String prescrizioni) {
		this.prescrizioni = prescrizioni == null ? null : prescrizioni.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.num_procedimento
	 * @return  the value of rebusp_t_procedimento.num_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public Long getNumProcedimento() {
		return numProcedimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.num_procedimento
	 * @param numProcedimento  the value for rebusp_t_procedimento.num_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setNumProcedimento(Long numProcedimento) {
		this.numProcedimento = numProcedimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.note
	 * @return  the value of rebusp_t_procedimento.note
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.note
	 * @param note  the value for rebusp_t_procedimento.note
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.flg_firma_digitale_ente
	 * @return  the value of rebusp_t_procedimento.flg_firma_digitale_ente
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public Boolean getFlgFirmaDigitaleEnte() {
		return flgFirmaDigitaleEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.flg_firma_digitale_ente
	 * @param flgFirmaDigitaleEnte  the value for rebusp_t_procedimento.flg_firma_digitale_ente
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setFlgFirmaDigitaleEnte(Boolean flgFirmaDigitaleEnte) {
		this.flgFirmaDigitaleEnte = flgFirmaDigitaleEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.flg_firma_digitale
	 * @return  the value of rebusp_t_procedimento.flg_firma_digitale
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public Boolean getFlgFirmaDigitale() {
		return flgFirmaDigitale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.flg_firma_digitale
	 * @param flgFirmaDigitale  the value for rebusp_t_procedimento.flg_firma_digitale
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setFlgFirmaDigitale(Boolean flgFirmaDigitale) {
		this.flgFirmaDigitale = flgFirmaDigitale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.flg_allega_linee
	 * @return  the value of rebusp_t_procedimento.flg_allega_linee
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public Boolean getFlgAllegaLinee() {
		return flgAllegaLinee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.flg_allega_linee
	 * @param flgAllegaLinee  the value for rebusp_t_procedimento.flg_allega_linee
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setFlgAllegaLinee(Boolean flgAllegaLinee) {
		this.flgAllegaLinee = flgAllegaLinee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.id_utente_aggiornamento
	 * @return  the value of rebusp_t_procedimento.id_utente_aggiornamento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public Long getIdUtenteAggiornamento() {
		return idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.id_utente_aggiornamento
	 * @param idUtenteAggiornamento  the value for rebusp_t_procedimento.id_utente_aggiornamento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setIdUtenteAggiornamento(Long idUtenteAggiornamento) {
		this.idUtenteAggiornamento = idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_t_procedimento.data_aggiornamento
	 * @return  the value of rebusp_t_procedimento.data_aggiornamento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_t_procedimento.data_aggiornamento
	 * @param dataAggiornamento  the value for rebusp_t_procedimento.data_aggiornamento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idProcedimento=").append(idProcedimento);
		sb.append(", idMotorizzazione=").append(idMotorizzazione);
		sb.append(", idTipoProcedimento=").append(idTipoProcedimento);
		sb.append(", idMotivazione=").append(idMotivazione);
		sb.append(", testoMotivAltro=").append(testoMotivAltro);
		sb.append(", ruoloFirma=").append(ruoloFirma);
		sb.append(", ruoloFirmaEnte=").append(ruoloFirmaEnte);
		sb.append(", nominativoFirma=").append(nominativoFirma);
		sb.append(", nominativoFirmaEnte=").append(nominativoFirmaEnte);
		sb.append(", premesse=").append(premesse);
		sb.append(", prescrizioni=").append(prescrizioni);
		sb.append(", numProcedimento=").append(numProcedimento);
		sb.append(", note=").append(note);
		sb.append(", flgFirmaDigitaleEnte=").append(flgFirmaDigitaleEnte);
		sb.append(", flgFirmaDigitale=").append(flgFirmaDigitale);
		sb.append(", flgAllegaLinee=").append(flgAllegaLinee);
		sb.append(", idUtenteAggiornamento=").append(idUtenteAggiornamento);
		sb.append(", dataAggiornamento=").append(dataAggiornamento);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}

	
}