/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RebusTMessaggiSelector {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	public RebusTMessaggiSelector() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdMessaggioIsNull() {
			addCriterion("id_messaggio is null");
			return (Criteria) this;
		}

		public Criteria andIdMessaggioIsNotNull() {
			addCriterion("id_messaggio is not null");
			return (Criteria) this;
		}

		public Criteria andIdMessaggioEqualTo(Long value) {
			addCriterion("id_messaggio =", value, "idMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdMessaggioNotEqualTo(Long value) {
			addCriterion("id_messaggio <>", value, "idMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdMessaggioGreaterThan(Long value) {
			addCriterion("id_messaggio >", value, "idMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdMessaggioGreaterThanOrEqualTo(Long value) {
			addCriterion("id_messaggio >=", value, "idMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdMessaggioLessThan(Long value) {
			addCriterion("id_messaggio <", value, "idMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdMessaggioLessThanOrEqualTo(Long value) {
			addCriterion("id_messaggio <=", value, "idMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdMessaggioIn(List<Long> values) {
			addCriterion("id_messaggio in", values, "idMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdMessaggioNotIn(List<Long> values) {
			addCriterion("id_messaggio not in", values, "idMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdMessaggioBetween(Long value1, Long value2) {
			addCriterion("id_messaggio between", value1, value2, "idMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdMessaggioNotBetween(Long value1, Long value2) {
			addCriterion("id_messaggio not between", value1, value2, "idMessaggio");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioIsNull() {
			addCriterion("fk_tipo_messaggio is null");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioIsNotNull() {
			addCriterion("fk_tipo_messaggio is not null");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioEqualTo(Long value) {
			addCriterion("fk_tipo_messaggio =", value, "fkTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioNotEqualTo(Long value) {
			addCriterion("fk_tipo_messaggio <>", value, "fkTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioGreaterThan(Long value) {
			addCriterion("fk_tipo_messaggio >", value, "fkTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioGreaterThanOrEqualTo(Long value) {
			addCriterion("fk_tipo_messaggio >=", value, "fkTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioLessThan(Long value) {
			addCriterion("fk_tipo_messaggio <", value, "fkTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioLessThanOrEqualTo(Long value) {
			addCriterion("fk_tipo_messaggio <=", value, "fkTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioIn(List<Long> values) {
			addCriterion("fk_tipo_messaggio in", values, "fkTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioNotIn(List<Long> values) {
			addCriterion("fk_tipo_messaggio not in", values, "fkTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioBetween(Long value1, Long value2) {
			addCriterion("fk_tipo_messaggio between", value1, value2, "fkTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioNotBetween(Long value1, Long value2) {
			addCriterion("fk_tipo_messaggio not between", value1, value2, "fkTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andFkUtenteMittenteIsNull() {
			addCriterion("fk_utente_mittente is null");
			return (Criteria) this;
		}

		public Criteria andFkUtenteMittenteIsNotNull() {
			addCriterion("fk_utente_mittente is not null");
			return (Criteria) this;
		}

		public Criteria andFkUtenteMittenteEqualTo(Long value) {
			addCriterion("fk_utente_mittente =", value, "fkUtenteMittente");
			return (Criteria) this;
		}

		public Criteria andFkUtenteMittenteNotEqualTo(Long value) {
			addCriterion("fk_utente_mittente <>", value, "fkUtenteMittente");
			return (Criteria) this;
		}

		public Criteria andFkUtenteMittenteGreaterThan(Long value) {
			addCriterion("fk_utente_mittente >", value, "fkUtenteMittente");
			return (Criteria) this;
		}

		public Criteria andFkUtenteMittenteGreaterThanOrEqualTo(Long value) {
			addCriterion("fk_utente_mittente >=", value, "fkUtenteMittente");
			return (Criteria) this;
		}

		public Criteria andFkUtenteMittenteLessThan(Long value) {
			addCriterion("fk_utente_mittente <", value, "fkUtenteMittente");
			return (Criteria) this;
		}

		public Criteria andFkUtenteMittenteLessThanOrEqualTo(Long value) {
			addCriterion("fk_utente_mittente <=", value, "fkUtenteMittente");
			return (Criteria) this;
		}

		public Criteria andFkUtenteMittenteIn(List<Long> values) {
			addCriterion("fk_utente_mittente in", values, "fkUtenteMittente");
			return (Criteria) this;
		}

		public Criteria andFkUtenteMittenteNotIn(List<Long> values) {
			addCriterion("fk_utente_mittente not in", values, "fkUtenteMittente");
			return (Criteria) this;
		}

		public Criteria andFkUtenteMittenteBetween(Long value1, Long value2) {
			addCriterion("fk_utente_mittente between", value1, value2, "fkUtenteMittente");
			return (Criteria) this;
		}

		public Criteria andFkUtenteMittenteNotBetween(Long value1, Long value2) {
			addCriterion("fk_utente_mittente not between", value1, value2, "fkUtenteMittente");
			return (Criteria) this;
		}

		public Criteria andFkUtenteDestinatarioIsNull() {
			addCriterion("fk_utente_destinatario is null");
			return (Criteria) this;
		}

		public Criteria andFkUtenteDestinatarioIsNotNull() {
			addCriterion("fk_utente_destinatario is not null");
			return (Criteria) this;
		}

		public Criteria andFkUtenteDestinatarioEqualTo(Long value) {
			addCriterion("fk_utente_destinatario =", value, "fkUtenteDestinatario");
			return (Criteria) this;
		}

		public Criteria andFkUtenteDestinatarioNotEqualTo(Long value) {
			addCriterion("fk_utente_destinatario <>", value, "fkUtenteDestinatario");
			return (Criteria) this;
		}

		public Criteria andFkUtenteDestinatarioGreaterThan(Long value) {
			addCriterion("fk_utente_destinatario >", value, "fkUtenteDestinatario");
			return (Criteria) this;
		}

		public Criteria andFkUtenteDestinatarioGreaterThanOrEqualTo(Long value) {
			addCriterion("fk_utente_destinatario >=", value, "fkUtenteDestinatario");
			return (Criteria) this;
		}

		public Criteria andFkUtenteDestinatarioLessThan(Long value) {
			addCriterion("fk_utente_destinatario <", value, "fkUtenteDestinatario");
			return (Criteria) this;
		}

		public Criteria andFkUtenteDestinatarioLessThanOrEqualTo(Long value) {
			addCriterion("fk_utente_destinatario <=", value, "fkUtenteDestinatario");
			return (Criteria) this;
		}

		public Criteria andFkUtenteDestinatarioIn(List<Long> values) {
			addCriterion("fk_utente_destinatario in", values, "fkUtenteDestinatario");
			return (Criteria) this;
		}

		public Criteria andFkUtenteDestinatarioNotIn(List<Long> values) {
			addCriterion("fk_utente_destinatario not in", values, "fkUtenteDestinatario");
			return (Criteria) this;
		}

		public Criteria andFkUtenteDestinatarioBetween(Long value1, Long value2) {
			addCriterion("fk_utente_destinatario between", value1, value2, "fkUtenteDestinatario");
			return (Criteria) this;
		}

		public Criteria andFkUtenteDestinatarioNotBetween(Long value1, Long value2) {
			addCriterion("fk_utente_destinatario not between", value1, value2, "fkUtenteDestinatario");
			return (Criteria) this;
		}

		public Criteria andFkVariazAutobusIsNull() {
			addCriterion("fk_variaz_autobus is null");
			return (Criteria) this;
		}

		public Criteria andFkVariazAutobusIsNotNull() {
			addCriterion("fk_variaz_autobus is not null");
			return (Criteria) this;
		}

		public Criteria andFkVariazAutobusEqualTo(Long value) {
			addCriterion("fk_variaz_autobus =", value, "fkVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkVariazAutobusNotEqualTo(Long value) {
			addCriterion("fk_variaz_autobus <>", value, "fkVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkVariazAutobusGreaterThan(Long value) {
			addCriterion("fk_variaz_autobus >", value, "fkVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkVariazAutobusGreaterThanOrEqualTo(Long value) {
			addCriterion("fk_variaz_autobus >=", value, "fkVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkVariazAutobusLessThan(Long value) {
			addCriterion("fk_variaz_autobus <", value, "fkVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkVariazAutobusLessThanOrEqualTo(Long value) {
			addCriterion("fk_variaz_autobus <=", value, "fkVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkVariazAutobusIn(List<Long> values) {
			addCriterion("fk_variaz_autobus in", values, "fkVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkVariazAutobusNotIn(List<Long> values) {
			addCriterion("fk_variaz_autobus not in", values, "fkVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkVariazAutobusBetween(Long value1, Long value2) {
			addCriterion("fk_variaz_autobus between", value1, value2, "fkVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkVariazAutobusNotBetween(Long value1, Long value2) {
			addCriterion("fk_variaz_autobus not between", value1, value2, "fkVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusIsNull() {
			addCriterion("fk_storia_variaz_autobus is null");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusIsNotNull() {
			addCriterion("fk_storia_variaz_autobus is not null");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusEqualTo(Long value) {
			addCriterion("fk_storia_variaz_autobus =", value, "fkStoriaVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusNotEqualTo(Long value) {
			addCriterion("fk_storia_variaz_autobus <>", value, "fkStoriaVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusGreaterThan(Long value) {
			addCriterion("fk_storia_variaz_autobus >", value, "fkStoriaVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusGreaterThanOrEqualTo(Long value) {
			addCriterion("fk_storia_variaz_autobus >=", value, "fkStoriaVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusLessThan(Long value) {
			addCriterion("fk_storia_variaz_autobus <", value, "fkStoriaVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusLessThanOrEqualTo(Long value) {
			addCriterion("fk_storia_variaz_autobus <=", value, "fkStoriaVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusIn(List<Long> values) {
			addCriterion("fk_storia_variaz_autobus in", values, "fkStoriaVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusNotIn(List<Long> values) {
			addCriterion("fk_storia_variaz_autobus not in", values, "fkStoriaVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusBetween(Long value1, Long value2) {
			addCriterion("fk_storia_variaz_autobus between", value1, value2, "fkStoriaVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusNotBetween(Long value1, Long value2) {
			addCriterion("fk_storia_variaz_autobus not between", value1, value2, "fkStoriaVariazAutobus");
			return (Criteria) this;
		}

		public Criteria andMessaggioIsNull() {
			addCriterion("messaggio is null");
			return (Criteria) this;
		}

		public Criteria andMessaggioIsNotNull() {
			addCriterion("messaggio is not null");
			return (Criteria) this;
		}

		public Criteria andMessaggioEqualTo(String value) {
			addCriterion("messaggio =", value, "messaggio");
			return (Criteria) this;
		}

		public Criteria andMessaggioNotEqualTo(String value) {
			addCriterion("messaggio <>", value, "messaggio");
			return (Criteria) this;
		}

		public Criteria andMessaggioGreaterThan(String value) {
			addCriterion("messaggio >", value, "messaggio");
			return (Criteria) this;
		}

		public Criteria andMessaggioGreaterThanOrEqualTo(String value) {
			addCriterion("messaggio >=", value, "messaggio");
			return (Criteria) this;
		}

		public Criteria andMessaggioLessThan(String value) {
			addCriterion("messaggio <", value, "messaggio");
			return (Criteria) this;
		}

		public Criteria andMessaggioLessThanOrEqualTo(String value) {
			addCriterion("messaggio <=", value, "messaggio");
			return (Criteria) this;
		}

		public Criteria andMessaggioLike(String value) {
			addCriterion("messaggio like", value, "messaggio");
			return (Criteria) this;
		}

		public Criteria andMessaggioNotLike(String value) {
			addCriterion("messaggio not like", value, "messaggio");
			return (Criteria) this;
		}

		public Criteria andMessaggioIn(List<String> values) {
			addCriterion("messaggio in", values, "messaggio");
			return (Criteria) this;
		}

		public Criteria andMessaggioNotIn(List<String> values) {
			addCriterion("messaggio not in", values, "messaggio");
			return (Criteria) this;
		}

		public Criteria andMessaggioBetween(String value1, String value2) {
			addCriterion("messaggio between", value1, value2, "messaggio");
			return (Criteria) this;
		}

		public Criteria andMessaggioNotBetween(String value1, String value2) {
			addCriterion("messaggio not between", value1, value2, "messaggio");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneIsNull() {
			addCriterion("data_creazione is null");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneIsNotNull() {
			addCriterion("data_creazione is not null");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneEqualTo(Date value) {
			addCriterion("data_creazione =", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneNotEqualTo(Date value) {
			addCriterion("data_creazione <>", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneGreaterThan(Date value) {
			addCriterion("data_creazione >", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneGreaterThanOrEqualTo(Date value) {
			addCriterion("data_creazione >=", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneLessThan(Date value) {
			addCriterion("data_creazione <", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneLessThanOrEqualTo(Date value) {
			addCriterion("data_creazione <=", value, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneIn(List<Date> values) {
			addCriterion("data_creazione in", values, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneNotIn(List<Date> values) {
			addCriterion("data_creazione not in", values, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneBetween(Date value1, Date value2) {
			addCriterion("data_creazione between", value1, value2, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andDataCreazioneNotBetween(Date value1, Date value2) {
			addCriterion("data_creazione not between", value1, value2, "dataCreazione");
			return (Criteria) this;
		}

		public Criteria andFlgLettoIsNull() {
			addCriterion("flg_letto is null");
			return (Criteria) this;
		}

		public Criteria andFlgLettoIsNotNull() {
			addCriterion("flg_letto is not null");
			return (Criteria) this;
		}

		public Criteria andFlgLettoEqualTo(String value) {
			addCriterion("flg_letto =", value, "flgLetto");
			return (Criteria) this;
		}

		public Criteria andFlgLettoNotEqualTo(String value) {
			addCriterion("flg_letto <>", value, "flgLetto");
			return (Criteria) this;
		}

		public Criteria andFlgLettoGreaterThan(String value) {
			addCriterion("flg_letto >", value, "flgLetto");
			return (Criteria) this;
		}

		public Criteria andFlgLettoGreaterThanOrEqualTo(String value) {
			addCriterion("flg_letto >=", value, "flgLetto");
			return (Criteria) this;
		}

		public Criteria andFlgLettoLessThan(String value) {
			addCriterion("flg_letto <", value, "flgLetto");
			return (Criteria) this;
		}

		public Criteria andFlgLettoLessThanOrEqualTo(String value) {
			addCriterion("flg_letto <=", value, "flgLetto");
			return (Criteria) this;
		}

		public Criteria andFlgLettoLike(String value) {
			addCriterion("flg_letto like", value, "flgLetto");
			return (Criteria) this;
		}

		public Criteria andFlgLettoNotLike(String value) {
			addCriterion("flg_letto not like", value, "flgLetto");
			return (Criteria) this;
		}

		public Criteria andFlgLettoIn(List<String> values) {
			addCriterion("flg_letto in", values, "flgLetto");
			return (Criteria) this;
		}

		public Criteria andFlgLettoNotIn(List<String> values) {
			addCriterion("flg_letto not in", values, "flgLetto");
			return (Criteria) this;
		}

		public Criteria andFlgLettoBetween(String value1, String value2) {
			addCriterion("flg_letto between", value1, value2, "flgLetto");
			return (Criteria) this;
		}

		public Criteria andFlgLettoNotBetween(String value1, String value2) {
			addCriterion("flg_letto not between", value1, value2, "flgLetto");
			return (Criteria) this;
		}

		public Criteria andDataLetturaIsNull() {
			addCriterion("data_lettura is null");
			return (Criteria) this;
		}

		public Criteria andDataLetturaIsNotNull() {
			addCriterion("data_lettura is not null");
			return (Criteria) this;
		}

		public Criteria andDataLetturaEqualTo(Date value) {
			addCriterion("data_lettura =", value, "dataLettura");
			return (Criteria) this;
		}

		public Criteria andDataLetturaNotEqualTo(Date value) {
			addCriterion("data_lettura <>", value, "dataLettura");
			return (Criteria) this;
		}

		public Criteria andDataLetturaGreaterThan(Date value) {
			addCriterion("data_lettura >", value, "dataLettura");
			return (Criteria) this;
		}

		public Criteria andDataLetturaGreaterThanOrEqualTo(Date value) {
			addCriterion("data_lettura >=", value, "dataLettura");
			return (Criteria) this;
		}

		public Criteria andDataLetturaLessThan(Date value) {
			addCriterion("data_lettura <", value, "dataLettura");
			return (Criteria) this;
		}

		public Criteria andDataLetturaLessThanOrEqualTo(Date value) {
			addCriterion("data_lettura <=", value, "dataLettura");
			return (Criteria) this;
		}

		public Criteria andDataLetturaIn(List<Date> values) {
			addCriterion("data_lettura in", values, "dataLettura");
			return (Criteria) this;
		}

		public Criteria andDataLetturaNotIn(List<Date> values) {
			addCriterion("data_lettura not in", values, "dataLettura");
			return (Criteria) this;
		}

		public Criteria andDataLetturaBetween(Date value1, Date value2) {
			addCriterion("data_lettura between", value1, value2, "dataLettura");
			return (Criteria) this;
		}

		public Criteria andDataLetturaNotBetween(Date value1, Date value2) {
			addCriterion("data_lettura not between", value1, value2, "dataLettura");
			return (Criteria) this;
		}

		public Criteria andFlgArchiviatoIsNull() {
			addCriterion("flg_archiviato is null");
			return (Criteria) this;
		}

		public Criteria andFlgArchiviatoIsNotNull() {
			addCriterion("flg_archiviato is not null");
			return (Criteria) this;
		}

		public Criteria andFlgArchiviatoEqualTo(String value) {
			addCriterion("flg_archiviato =", value, "flgArchiviato");
			return (Criteria) this;
		}

		public Criteria andFlgArchiviatoNotEqualTo(String value) {
			addCriterion("flg_archiviato <>", value, "flgArchiviato");
			return (Criteria) this;
		}

		public Criteria andFlgArchiviatoGreaterThan(String value) {
			addCriterion("flg_archiviato >", value, "flgArchiviato");
			return (Criteria) this;
		}

		public Criteria andFlgArchiviatoGreaterThanOrEqualTo(String value) {
			addCriterion("flg_archiviato >=", value, "flgArchiviato");
			return (Criteria) this;
		}

		public Criteria andFlgArchiviatoLessThan(String value) {
			addCriterion("flg_archiviato <", value, "flgArchiviato");
			return (Criteria) this;
		}

		public Criteria andFlgArchiviatoLessThanOrEqualTo(String value) {
			addCriterion("flg_archiviato <=", value, "flgArchiviato");
			return (Criteria) this;
		}

		public Criteria andFlgArchiviatoLike(String value) {
			addCriterion("flg_archiviato like", value, "flgArchiviato");
			return (Criteria) this;
		}

		public Criteria andFlgArchiviatoNotLike(String value) {
			addCriterion("flg_archiviato not like", value, "flgArchiviato");
			return (Criteria) this;
		}

		public Criteria andFlgArchiviatoIn(List<String> values) {
			addCriterion("flg_archiviato in", values, "flgArchiviato");
			return (Criteria) this;
		}

		public Criteria andFlgArchiviatoNotIn(List<String> values) {
			addCriterion("flg_archiviato not in", values, "flgArchiviato");
			return (Criteria) this;
		}

		public Criteria andFlgArchiviatoBetween(String value1, String value2) {
			addCriterion("flg_archiviato between", value1, value2, "flgArchiviato");
			return (Criteria) this;
		}

		public Criteria andFlgArchiviatoNotBetween(String value1, String value2) {
			addCriterion("flg_archiviato not between", value1, value2, "flgArchiviato");
			return (Criteria) this;
		}

		public Criteria andDataArchiviazioneIsNull() {
			addCriterion("data_archiviazione is null");
			return (Criteria) this;
		}

		public Criteria andDataArchiviazioneIsNotNull() {
			addCriterion("data_archiviazione is not null");
			return (Criteria) this;
		}

		public Criteria andDataArchiviazioneEqualTo(Date value) {
			addCriterion("data_archiviazione =", value, "dataArchiviazione");
			return (Criteria) this;
		}

		public Criteria andDataArchiviazioneNotEqualTo(Date value) {
			addCriterion("data_archiviazione <>", value, "dataArchiviazione");
			return (Criteria) this;
		}

		public Criteria andDataArchiviazioneGreaterThan(Date value) {
			addCriterion("data_archiviazione >", value, "dataArchiviazione");
			return (Criteria) this;
		}

		public Criteria andDataArchiviazioneGreaterThanOrEqualTo(Date value) {
			addCriterion("data_archiviazione >=", value, "dataArchiviazione");
			return (Criteria) this;
		}

		public Criteria andDataArchiviazioneLessThan(Date value) {
			addCriterion("data_archiviazione <", value, "dataArchiviazione");
			return (Criteria) this;
		}

		public Criteria andDataArchiviazioneLessThanOrEqualTo(Date value) {
			addCriterion("data_archiviazione <=", value, "dataArchiviazione");
			return (Criteria) this;
		}

		public Criteria andDataArchiviazioneIn(List<Date> values) {
			addCriterion("data_archiviazione in", values, "dataArchiviazione");
			return (Criteria) this;
		}

		public Criteria andDataArchiviazioneNotIn(List<Date> values) {
			addCriterion("data_archiviazione not in", values, "dataArchiviazione");
			return (Criteria) this;
		}

		public Criteria andDataArchiviazioneBetween(Date value1, Date value2) {
			addCriterion("data_archiviazione between", value1, value2, "dataArchiviazione");
			return (Criteria) this;
		}

		public Criteria andDataArchiviazioneNotBetween(Date value1, Date value2) {
			addCriterion("data_archiviazione not between", value1, value2, "dataArchiviazione");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusSuccIsNull() {
			addCriterion("fk_storia_variaz_autobus_succ is null");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusSuccIsNotNull() {
			addCriterion("fk_storia_variaz_autobus_succ is not null");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusSuccEqualTo(Long value) {
			addCriterion("fk_storia_variaz_autobus_succ =", value, "fkStoriaVariazAutobusSucc");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusSuccNotEqualTo(Long value) {
			addCriterion("fk_storia_variaz_autobus_succ <>", value, "fkStoriaVariazAutobusSucc");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusSuccGreaterThan(Long value) {
			addCriterion("fk_storia_variaz_autobus_succ >", value, "fkStoriaVariazAutobusSucc");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusSuccGreaterThanOrEqualTo(Long value) {
			addCriterion("fk_storia_variaz_autobus_succ >=", value, "fkStoriaVariazAutobusSucc");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusSuccLessThan(Long value) {
			addCriterion("fk_storia_variaz_autobus_succ <", value, "fkStoriaVariazAutobusSucc");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusSuccLessThanOrEqualTo(Long value) {
			addCriterion("fk_storia_variaz_autobus_succ <=", value, "fkStoriaVariazAutobusSucc");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusSuccIn(List<Long> values) {
			addCriterion("fk_storia_variaz_autobus_succ in", values, "fkStoriaVariazAutobusSucc");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusSuccNotIn(List<Long> values) {
			addCriterion("fk_storia_variaz_autobus_succ not in", values, "fkStoriaVariazAutobusSucc");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusSuccBetween(Long value1, Long value2) {
			addCriterion("fk_storia_variaz_autobus_succ between", value1, value2, "fkStoriaVariazAutobusSucc");
			return (Criteria) this;
		}

		public Criteria andFkStoriaVariazAutobusSuccNotBetween(Long value1, Long value2) {
			addCriterion("fk_storia_variaz_autobus_succ not between", value1, value2, "fkStoriaVariazAutobusSucc");
			return (Criteria) this;
		}

		public Criteria andFkProcedimentoIsNull() {
			addCriterion("fk_procedimento is null");
			return (Criteria) this;
		}

		public Criteria andFkProcedimentoIsNotNull() {
			addCriterion("fk_procedimento is not null");
			return (Criteria) this;
		}

		public Criteria andFkProcedimentoEqualTo(Long value) {
			addCriterion("fk_procedimento =", value, "fkProcedimento");
			return (Criteria) this;
		}

		public Criteria andFkProcedimentoNotEqualTo(Long value) {
			addCriterion("fk_procedimento <>", value, "fkProcedimento");
			return (Criteria) this;
		}

		public Criteria andFkProcedimentoGreaterThan(Long value) {
			addCriterion("fk_procedimento >", value, "fkProcedimento");
			return (Criteria) this;
		}

		public Criteria andFkProcedimentoGreaterThanOrEqualTo(Long value) {
			addCriterion("fk_procedimento >=", value, "fkProcedimento");
			return (Criteria) this;
		}

		public Criteria andFkProcedimentoLessThan(Long value) {
			addCriterion("fk_procedimento <", value, "fkProcedimento");
			return (Criteria) this;
		}

		public Criteria andFkProcedimentoLessThanOrEqualTo(Long value) {
			addCriterion("fk_procedimento <=", value, "fkProcedimento");
			return (Criteria) this;
		}

		public Criteria andFkProcedimentoIn(List<Long> values) {
			addCriterion("fk_procedimento in", values, "fkProcedimento");
			return (Criteria) this;
		}

		public Criteria andFkProcedimentoNotIn(List<Long> values) {
			addCriterion("fk_procedimento not in", values, "fkProcedimento");
			return (Criteria) this;
		}

		public Criteria andFkProcedimentoBetween(Long value1, Long value2) {
			addCriterion("fk_procedimento between", value1, value2, "fkProcedimento");
			return (Criteria) this;
		}

		public Criteria andFkProcedimentoNotBetween(Long value1, Long value2) {
			addCriterion("fk_procedimento not between", value1, value2, "fkProcedimento");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioSistemaIsNull() {
			addCriterion("fk_tipo_messaggio_sistema is null");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioSistemaIsNotNull() {
			addCriterion("fk_tipo_messaggio_sistema is not null");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioSistemaEqualTo(Long value) {
			addCriterion("fk_tipo_messaggio_sistema =", value, "fkTipoMessaggioSistema");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioSistemaNotEqualTo(Long value) {
			addCriterion("fk_tipo_messaggio_sistema <>", value, "fkTipoMessaggioSistema");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioSistemaGreaterThan(Long value) {
			addCriterion("fk_tipo_messaggio_sistema >", value, "fkTipoMessaggioSistema");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioSistemaGreaterThanOrEqualTo(Long value) {
			addCriterion("fk_tipo_messaggio_sistema >=", value, "fkTipoMessaggioSistema");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioSistemaLessThan(Long value) {
			addCriterion("fk_tipo_messaggio_sistema <", value, "fkTipoMessaggioSistema");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioSistemaLessThanOrEqualTo(Long value) {
			addCriterion("fk_tipo_messaggio_sistema <=", value, "fkTipoMessaggioSistema");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioSistemaIn(List<Long> values) {
			addCriterion("fk_tipo_messaggio_sistema in", values, "fkTipoMessaggioSistema");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioSistemaNotIn(List<Long> values) {
			addCriterion("fk_tipo_messaggio_sistema not in", values, "fkTipoMessaggioSistema");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioSistemaBetween(Long value1, Long value2) {
			addCriterion("fk_tipo_messaggio_sistema between", value1, value2, "fkTipoMessaggioSistema");
			return (Criteria) this;
		}

		public Criteria andFkTipoMessaggioSistemaNotBetween(Long value1, Long value2) {
			addCriterion("fk_tipo_messaggio_sistema not between", value1, value2, "fkTipoMessaggioSistema");
			return (Criteria) this;
		}

		public Criteria andMessaggioLikeInsensitive(String value) {
			addCriterion("upper(messaggio) like", value.toUpperCase(), "messaggio");
			return (Criteria) this;
		}

		public Criteria andFlgLettoLikeInsensitive(String value) {
			addCriterion("upper(flg_letto) like", value.toUpperCase(), "flgLetto");
			return (Criteria) this;
		}

		public Criteria andFlgArchiviatoLikeInsensitive(String value) {
			addCriterion("upper(flg_archiviato) like", value.toUpperCase(), "flgArchiviato");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebus_t_messaggi
     *
     * @mbg.generated do_not_delete_during_merge Mon Oct 21 17:18:12 CEST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}