/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;

public class RebusTEntiDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_enti.id_ente
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	private Long idEnte;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_enti.denominazione
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	private String denominazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebus_t_enti
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_enti.id_ente
	 * @return  the value of rebus_t_enti.id_ente
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public Long getIdEnte() {
		return idEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_enti.id_ente
	 * @param idEnte  the value for rebus_t_enti.id_ente
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public void setIdEnte(Long idEnte) {
		this.idEnte = idEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_enti.denominazione
	 * @return  the value of rebus_t_enti.denominazione
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public String getDenominazione() {
		return denominazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_enti.denominazione
	 * @param denominazione  the value for rebus_t_enti.denominazione
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione == null ? null : denominazione.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_enti
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idEnte=").append(idEnte);
		sb.append(", denominazione=").append(denominazione);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}