/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebuspRProcContrattoDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_r_proc_contratto.id_proc_contratto
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    private Long idProcContratto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_r_proc_contratto.id_procedimento
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    private Long idProcedimento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_r_proc_contratto.id_contratto
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    private Long idContratto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_r_proc_contratto.id_tipo_contratto
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    private Long idTipoContratto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_r_proc_contratto.id_utente_aggiornamento
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    private Long idUtenteAggiornamento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_r_proc_contratto.data_aggiornamento
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    private Date dataAggiornamento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusp_r_proc_contratto
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_r_proc_contratto.id_proc_contratto
     *
     * @return the value of rebusp_r_proc_contratto.id_proc_contratto
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public Long getIdProcContratto() {
        return idProcContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_r_proc_contratto.id_proc_contratto
     *
     * @param idProcContratto the value for rebusp_r_proc_contratto.id_proc_contratto
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public void setIdProcContratto(Long idProcContratto) {
        this.idProcContratto = idProcContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_r_proc_contratto.id_procedimento
     *
     * @return the value of rebusp_r_proc_contratto.id_procedimento
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public Long getIdProcedimento() {
        return idProcedimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_r_proc_contratto.id_procedimento
     *
     * @param idProcedimento the value for rebusp_r_proc_contratto.id_procedimento
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public void setIdProcedimento(Long idProcedimento) {
        this.idProcedimento = idProcedimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_r_proc_contratto.id_contratto
     *
     * @return the value of rebusp_r_proc_contratto.id_contratto
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public Long getIdContratto() {
        return idContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_r_proc_contratto.id_contratto
     *
     * @param idContratto the value for rebusp_r_proc_contratto.id_contratto
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public void setIdContratto(Long idContratto) {
        this.idContratto = idContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_r_proc_contratto.id_tipo_contratto
     *
     * @return the value of rebusp_r_proc_contratto.id_tipo_contratto
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public Long getIdTipoContratto() {
        return idTipoContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_r_proc_contratto.id_tipo_contratto
     *
     * @param idTipoContratto the value for rebusp_r_proc_contratto.id_tipo_contratto
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public void setIdTipoContratto(Long idTipoContratto) {
        this.idTipoContratto = idTipoContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_r_proc_contratto.id_utente_aggiornamento
     *
     * @return the value of rebusp_r_proc_contratto.id_utente_aggiornamento
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public Long getIdUtenteAggiornamento() {
        return idUtenteAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_r_proc_contratto.id_utente_aggiornamento
     *
     * @param idUtenteAggiornamento the value for rebusp_r_proc_contratto.id_utente_aggiornamento
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public void setIdUtenteAggiornamento(Long idUtenteAggiornamento) {
        this.idUtenteAggiornamento = idUtenteAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_r_proc_contratto.data_aggiornamento
     *
     * @return the value of rebusp_r_proc_contratto.data_aggiornamento
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public Date getDataAggiornamento() {
        return dataAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_r_proc_contratto.data_aggiornamento
     *
     * @param dataAggiornamento the value for rebusp_r_proc_contratto.data_aggiornamento
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public void setDataAggiornamento(Date dataAggiornamento) {
        this.dataAggiornamento = dataAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_r_proc_contratto
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idProcContratto=").append(idProcContratto);
        sb.append(", idProcedimento=").append(idProcedimento);
        sb.append(", idContratto=").append(idContratto);
        sb.append(", idTipoContratto=").append(idTipoContratto);
        sb.append(", idUtenteAggiornamento=").append(idUtenteAggiornamento);
        sb.append(", dataAggiornamento=").append(dataAggiornamento);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}