/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebuscTDatoMessaServizioDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_messa_servizio.id_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	private Long idDatoMessaServizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_messa_servizio.id_tipo_sostituzione
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	private Double idTipoSostituzione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_messa_servizio.nr_carta_circolazione
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	private String nrCartaCircolazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_messa_servizio.flg_pannello
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	private Boolean flgPannello;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_messa_servizio.id_utente_aggiornamento
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	private Long idUtenteAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_messa_servizio.data_aggiornamento
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_messa_servizio.primo_telaio_sost
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	private String primoTelaioSost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_messa_servizio.id_dato_messa_servizio
	 * @return  the value of rebusc_t_dato_messa_servizio.id_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public Long getIdDatoMessaServizio() {
		return idDatoMessaServizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_messa_servizio.id_dato_messa_servizio
	 * @param idDatoMessaServizio  the value for rebusc_t_dato_messa_servizio.id_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public void setIdDatoMessaServizio(Long idDatoMessaServizio) {
		this.idDatoMessaServizio = idDatoMessaServizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_messa_servizio.id_tipo_sostituzione
	 * @return  the value of rebusc_t_dato_messa_servizio.id_tipo_sostituzione
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public Double getIdTipoSostituzione() {
		return idTipoSostituzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_messa_servizio.id_tipo_sostituzione
	 * @param idTipoSostituzione  the value for rebusc_t_dato_messa_servizio.id_tipo_sostituzione
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public void setIdTipoSostituzione(Double idTipoSostituzione) {
		this.idTipoSostituzione = idTipoSostituzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_messa_servizio.nr_carta_circolazione
	 * @return  the value of rebusc_t_dato_messa_servizio.nr_carta_circolazione
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public String getNrCartaCircolazione() {
		return nrCartaCircolazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_messa_servizio.nr_carta_circolazione
	 * @param nrCartaCircolazione  the value for rebusc_t_dato_messa_servizio.nr_carta_circolazione
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public void setNrCartaCircolazione(String nrCartaCircolazione) {
		this.nrCartaCircolazione = nrCartaCircolazione == null ? null : nrCartaCircolazione.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_messa_servizio.flg_pannello
	 * @return  the value of rebusc_t_dato_messa_servizio.flg_pannello
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public Boolean getFlgPannello() {
		return flgPannello;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_messa_servizio.flg_pannello
	 * @param flgPannello  the value for rebusc_t_dato_messa_servizio.flg_pannello
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public void setFlgPannello(Boolean flgPannello) {
		this.flgPannello = flgPannello;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_messa_servizio.id_utente_aggiornamento
	 * @return  the value of rebusc_t_dato_messa_servizio.id_utente_aggiornamento
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public Long getIdUtenteAggiornamento() {
		return idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_messa_servizio.id_utente_aggiornamento
	 * @param idUtenteAggiornamento  the value for rebusc_t_dato_messa_servizio.id_utente_aggiornamento
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public void setIdUtenteAggiornamento(Long idUtenteAggiornamento) {
		this.idUtenteAggiornamento = idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_messa_servizio.data_aggiornamento
	 * @return  the value of rebusc_t_dato_messa_servizio.data_aggiornamento
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_messa_servizio.data_aggiornamento
	 * @param dataAggiornamento  the value for rebusc_t_dato_messa_servizio.data_aggiornamento
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_messa_servizio.primo_telaio_sost
	 * @return  the value of rebusc_t_dato_messa_servizio.primo_telaio_sost
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public String getPrimoTelaioSost() {
		return primoTelaioSost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_messa_servizio.primo_telaio_sost
	 * @param primoTelaioSost  the value for rebusc_t_dato_messa_servizio.primo_telaio_sost
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public void setPrimoTelaioSost(String primoTelaioSost) {
		this.primoTelaioSost = primoTelaioSost == null ? null : primoTelaioSost.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idDatoMessaServizio=").append(idDatoMessaServizio);
		sb.append(", idTipoSostituzione=").append(idTipoSostituzione);
		sb.append(", nrCartaCircolazione=").append(nrCartaCircolazione);
		sb.append(", flgPannello=").append(flgPannello);
		sb.append(", idUtenteAggiornamento=").append(idUtenteAggiornamento);
		sb.append(", dataAggiornamento=").append(dataAggiornamento);
		sb.append(", primoTelaioSost=").append(primoTelaioSost);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}