/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebusTUtentiDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_utenti.id_utente
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	private Long idUtente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_utenti.cf
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	private String cf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_utenti.nome
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	private String nome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_utenti.cognome
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	private String cognome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_utenti.data_creazione
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_utenti.data_cancellazione
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	private Date dataCancellazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebus_t_utenti
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_utenti.id_utente
	 * @return  the value of rebus_t_utenti.id_utente
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public Long getIdUtente() {
		return idUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_utenti.id_utente
	 * @param idUtente  the value for rebus_t_utenti.id_utente
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public void setIdUtente(Long idUtente) {
		this.idUtente = idUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_utenti.cf
	 * @return  the value of rebus_t_utenti.cf
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public String getCf() {
		return cf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_utenti.cf
	 * @param cf  the value for rebus_t_utenti.cf
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public void setCf(String cf) {
		this.cf = cf == null ? null : cf.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_utenti.nome
	 * @return  the value of rebus_t_utenti.nome
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public String getNome() {
		return nome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_utenti.nome
	 * @param nome  the value for rebus_t_utenti.nome
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public void setNome(String nome) {
		this.nome = nome == null ? null : nome.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_utenti.cognome
	 * @return  the value of rebus_t_utenti.cognome
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public String getCognome() {
		return cognome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_utenti.cognome
	 * @param cognome  the value for rebus_t_utenti.cognome
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public void setCognome(String cognome) {
		this.cognome = cognome == null ? null : cognome.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_utenti.data_creazione
	 * @return  the value of rebus_t_utenti.data_creazione
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_utenti.data_creazione
	 * @param dataCreazione  the value for rebus_t_utenti.data_creazione
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_utenti.data_cancellazione
	 * @return  the value of rebus_t_utenti.data_cancellazione
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_utenti.data_cancellazione
	 * @param dataCancellazione  the value for rebus_t_utenti.data_cancellazione
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_utenti
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idUtente=").append(idUtente);
		sb.append(", cf=").append(cf);
		sb.append(", nome=").append(nome);
		sb.append(", cognome=").append(cognome);
		sb.append(", dataCreazione=").append(dataCreazione);
		sb.append(", dataCancellazione=").append(dataCancellazione);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}