/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebusTAziendeDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_aziende.id_azienda
	 * @mbg.generated  Wed Nov 27 16:19:42 CET 2019
	 */
	private Long idAzienda;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_aziende.denominazione
	 * @mbg.generated  Wed Nov 27 16:19:42 CET 2019
	 */
	private String denominazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_aziende.natura_giuridica
	 * @mbg.generated  Wed Nov 27 16:19:42 CET 2019
	 */
	private String naturaGiuridica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebus_t_aziende
	 * @mbg.generated  Wed Nov 27 16:19:42 CET 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_aziende.id_azienda
	 * @return  the value of rebus_t_aziende.id_azienda
	 * @mbg.generated  Wed Nov 27 16:19:42 CET 2019
	 */
	public Long getIdAzienda() {
		return idAzienda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_aziende.id_azienda
	 * @param idAzienda  the value for rebus_t_aziende.id_azienda
	 * @mbg.generated  Wed Nov 27 16:19:42 CET 2019
	 */
	public void setIdAzienda(Long idAzienda) {
		this.idAzienda = idAzienda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_aziende.denominazione
	 * @return  the value of rebus_t_aziende.denominazione
	 * @mbg.generated  Wed Nov 27 16:19:42 CET 2019
	 */
	public String getDenominazione() {
		return denominazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_aziende.denominazione
	 * @param denominazione  the value for rebus_t_aziende.denominazione
	 * @mbg.generated  Wed Nov 27 16:19:42 CET 2019
	 */
	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione == null ? null : denominazione.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_aziende.natura_giuridica
	 * @return  the value of rebus_t_aziende.natura_giuridica
	 * @mbg.generated  Wed Nov 27 16:19:42 CET 2019
	 */
	public String getNaturaGiuridica() {
		return naturaGiuridica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_aziende.natura_giuridica
	 * @param naturaGiuridica  the value for rebus_t_aziende.natura_giuridica
	 * @mbg.generated  Wed Nov 27 16:19:42 CET 2019
	 */
	public void setNaturaGiuridica(String naturaGiuridica) {
		this.naturaGiuridica = naturaGiuridica == null ? null : naturaGiuridica.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_aziende
	 * @mbg.generated  Wed Nov 27 16:19:42 CET 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idAzienda=").append(idAzienda);
		sb.append(", denominazione=").append(denominazione);
		sb.append(", naturaGiuridica=").append(naturaGiuridica);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}