/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RebuscTDatoMessaServizioSelector {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public RebuscTDatoMessaServizioSelector() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdDatoMessaServizioIsNull() {
			addCriterion("id_dato_messa_servizio is null");
			return (Criteria) this;
		}

		public Criteria andIdDatoMessaServizioIsNotNull() {
			addCriterion("id_dato_messa_servizio is not null");
			return (Criteria) this;
		}

		public Criteria andIdDatoMessaServizioEqualTo(Long value) {
			addCriterion("id_dato_messa_servizio =", value, "idDatoMessaServizio");
			return (Criteria) this;
		}

		public Criteria andIdDatoMessaServizioNotEqualTo(Long value) {
			addCriterion("id_dato_messa_servizio <>", value, "idDatoMessaServizio");
			return (Criteria) this;
		}

		public Criteria andIdDatoMessaServizioGreaterThan(Long value) {
			addCriterion("id_dato_messa_servizio >", value, "idDatoMessaServizio");
			return (Criteria) this;
		}

		public Criteria andIdDatoMessaServizioGreaterThanOrEqualTo(Long value) {
			addCriterion("id_dato_messa_servizio >=", value, "idDatoMessaServizio");
			return (Criteria) this;
		}

		public Criteria andIdDatoMessaServizioLessThan(Long value) {
			addCriterion("id_dato_messa_servizio <", value, "idDatoMessaServizio");
			return (Criteria) this;
		}

		public Criteria andIdDatoMessaServizioLessThanOrEqualTo(Long value) {
			addCriterion("id_dato_messa_servizio <=", value, "idDatoMessaServizio");
			return (Criteria) this;
		}

		public Criteria andIdDatoMessaServizioIn(List<Long> values) {
			addCriterion("id_dato_messa_servizio in", values, "idDatoMessaServizio");
			return (Criteria) this;
		}

		public Criteria andIdDatoMessaServizioNotIn(List<Long> values) {
			addCriterion("id_dato_messa_servizio not in", values, "idDatoMessaServizio");
			return (Criteria) this;
		}

		public Criteria andIdDatoMessaServizioBetween(Long value1, Long value2) {
			addCriterion("id_dato_messa_servizio between", value1, value2, "idDatoMessaServizio");
			return (Criteria) this;
		}

		public Criteria andIdDatoMessaServizioNotBetween(Long value1, Long value2) {
			addCriterion("id_dato_messa_servizio not between", value1, value2, "idDatoMessaServizio");
			return (Criteria) this;
		}

		public Criteria andIdTipoSostituzioneIsNull() {
			addCriterion("id_tipo_sostituzione is null");
			return (Criteria) this;
		}

		public Criteria andIdTipoSostituzioneIsNotNull() {
			addCriterion("id_tipo_sostituzione is not null");
			return (Criteria) this;
		}

		public Criteria andIdTipoSostituzioneEqualTo(Double value) {
			addCriterion("id_tipo_sostituzione =", value, "idTipoSostituzione");
			return (Criteria) this;
		}

		public Criteria andIdTipoSostituzioneNotEqualTo(Double value) {
			addCriterion("id_tipo_sostituzione <>", value, "idTipoSostituzione");
			return (Criteria) this;
		}

		public Criteria andIdTipoSostituzioneGreaterThan(Double value) {
			addCriterion("id_tipo_sostituzione >", value, "idTipoSostituzione");
			return (Criteria) this;
		}

		public Criteria andIdTipoSostituzioneGreaterThanOrEqualTo(Double value) {
			addCriterion("id_tipo_sostituzione >=", value, "idTipoSostituzione");
			return (Criteria) this;
		}

		public Criteria andIdTipoSostituzioneLessThan(Double value) {
			addCriterion("id_tipo_sostituzione <", value, "idTipoSostituzione");
			return (Criteria) this;
		}

		public Criteria andIdTipoSostituzioneLessThanOrEqualTo(Double value) {
			addCriterion("id_tipo_sostituzione <=", value, "idTipoSostituzione");
			return (Criteria) this;
		}

		public Criteria andIdTipoSostituzioneIn(List<Double> values) {
			addCriterion("id_tipo_sostituzione in", values, "idTipoSostituzione");
			return (Criteria) this;
		}

		public Criteria andIdTipoSostituzioneNotIn(List<Double> values) {
			addCriterion("id_tipo_sostituzione not in", values, "idTipoSostituzione");
			return (Criteria) this;
		}

		public Criteria andIdTipoSostituzioneBetween(Double value1, Double value2) {
			addCriterion("id_tipo_sostituzione between", value1, value2, "idTipoSostituzione");
			return (Criteria) this;
		}

		public Criteria andIdTipoSostituzioneNotBetween(Double value1, Double value2) {
			addCriterion("id_tipo_sostituzione not between", value1, value2, "idTipoSostituzione");
			return (Criteria) this;
		}

		public Criteria andNrCartaCircolazioneIsNull() {
			addCriterion("nr_carta_circolazione is null");
			return (Criteria) this;
		}

		public Criteria andNrCartaCircolazioneIsNotNull() {
			addCriterion("nr_carta_circolazione is not null");
			return (Criteria) this;
		}

		public Criteria andNrCartaCircolazioneEqualTo(String value) {
			addCriterion("nr_carta_circolazione =", value, "nrCartaCircolazione");
			return (Criteria) this;
		}

		public Criteria andNrCartaCircolazioneNotEqualTo(String value) {
			addCriterion("nr_carta_circolazione <>", value, "nrCartaCircolazione");
			return (Criteria) this;
		}

		public Criteria andNrCartaCircolazioneGreaterThan(String value) {
			addCriterion("nr_carta_circolazione >", value, "nrCartaCircolazione");
			return (Criteria) this;
		}

		public Criteria andNrCartaCircolazioneGreaterThanOrEqualTo(String value) {
			addCriterion("nr_carta_circolazione >=", value, "nrCartaCircolazione");
			return (Criteria) this;
		}

		public Criteria andNrCartaCircolazioneLessThan(String value) {
			addCriterion("nr_carta_circolazione <", value, "nrCartaCircolazione");
			return (Criteria) this;
		}

		public Criteria andNrCartaCircolazioneLessThanOrEqualTo(String value) {
			addCriterion("nr_carta_circolazione <=", value, "nrCartaCircolazione");
			return (Criteria) this;
		}

		public Criteria andNrCartaCircolazioneLike(String value) {
			addCriterion("nr_carta_circolazione like", value, "nrCartaCircolazione");
			return (Criteria) this;
		}

		public Criteria andNrCartaCircolazioneNotLike(String value) {
			addCriterion("nr_carta_circolazione not like", value, "nrCartaCircolazione");
			return (Criteria) this;
		}

		public Criteria andNrCartaCircolazioneIn(List<String> values) {
			addCriterion("nr_carta_circolazione in", values, "nrCartaCircolazione");
			return (Criteria) this;
		}

		public Criteria andNrCartaCircolazioneNotIn(List<String> values) {
			addCriterion("nr_carta_circolazione not in", values, "nrCartaCircolazione");
			return (Criteria) this;
		}

		public Criteria andNrCartaCircolazioneBetween(String value1, String value2) {
			addCriterion("nr_carta_circolazione between", value1, value2, "nrCartaCircolazione");
			return (Criteria) this;
		}

		public Criteria andNrCartaCircolazioneNotBetween(String value1, String value2) {
			addCriterion("nr_carta_circolazione not between", value1, value2, "nrCartaCircolazione");
			return (Criteria) this;
		}

		public Criteria andFlgPannelloIsNull() {
			addCriterion("flg_pannello is null");
			return (Criteria) this;
		}

		public Criteria andFlgPannelloIsNotNull() {
			addCriterion("flg_pannello is not null");
			return (Criteria) this;
		}

		public Criteria andFlgPannelloEqualTo(Boolean value) {
			addCriterion("flg_pannello =", value, "flgPannello");
			return (Criteria) this;
		}

		public Criteria andFlgPannelloNotEqualTo(Boolean value) {
			addCriterion("flg_pannello <>", value, "flgPannello");
			return (Criteria) this;
		}

		public Criteria andFlgPannelloGreaterThan(Boolean value) {
			addCriterion("flg_pannello >", value, "flgPannello");
			return (Criteria) this;
		}

		public Criteria andFlgPannelloGreaterThanOrEqualTo(Boolean value) {
			addCriterion("flg_pannello >=", value, "flgPannello");
			return (Criteria) this;
		}

		public Criteria andFlgPannelloLessThan(Boolean value) {
			addCriterion("flg_pannello <", value, "flgPannello");
			return (Criteria) this;
		}

		public Criteria andFlgPannelloLessThanOrEqualTo(Boolean value) {
			addCriterion("flg_pannello <=", value, "flgPannello");
			return (Criteria) this;
		}

		public Criteria andFlgPannelloIn(List<Boolean> values) {
			addCriterion("flg_pannello in", values, "flgPannello");
			return (Criteria) this;
		}

		public Criteria andFlgPannelloNotIn(List<Boolean> values) {
			addCriterion("flg_pannello not in", values, "flgPannello");
			return (Criteria) this;
		}

		public Criteria andFlgPannelloBetween(Boolean value1, Boolean value2) {
			addCriterion("flg_pannello between", value1, value2, "flgPannello");
			return (Criteria) this;
		}

		public Criteria andFlgPannelloNotBetween(Boolean value1, Boolean value2) {
			addCriterion("flg_pannello not between", value1, value2, "flgPannello");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoIsNull() {
			addCriterion("id_utente_aggiornamento is null");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoIsNotNull() {
			addCriterion("id_utente_aggiornamento is not null");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento =", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoNotEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento <>", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoGreaterThan(Long value) {
			addCriterion("id_utente_aggiornamento >", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoGreaterThanOrEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento >=", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoLessThan(Long value) {
			addCriterion("id_utente_aggiornamento <", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoLessThanOrEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento <=", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoIn(List<Long> values) {
			addCriterion("id_utente_aggiornamento in", values, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoNotIn(List<Long> values) {
			addCriterion("id_utente_aggiornamento not in", values, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoBetween(Long value1, Long value2) {
			addCriterion("id_utente_aggiornamento between", value1, value2, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoNotBetween(Long value1, Long value2) {
			addCriterion("id_utente_aggiornamento not between", value1, value2, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoIsNull() {
			addCriterion("data_aggiornamento is null");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoIsNotNull() {
			addCriterion("data_aggiornamento is not null");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoEqualTo(Date value) {
			addCriterionForJDBCDate("data_aggiornamento =", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoNotEqualTo(Date value) {
			addCriterionForJDBCDate("data_aggiornamento <>", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoGreaterThan(Date value) {
			addCriterionForJDBCDate("data_aggiornamento >", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_aggiornamento >=", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoLessThan(Date value) {
			addCriterionForJDBCDate("data_aggiornamento <", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_aggiornamento <=", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoIn(List<Date> values) {
			addCriterionForJDBCDate("data_aggiornamento in", values, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoNotIn(List<Date> values) {
			addCriterionForJDBCDate("data_aggiornamento not in", values, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_aggiornamento between", value1, value2, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_aggiornamento not between", value1, value2, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andPrimoTelaioSostIsNull() {
			addCriterion("primo_telaio_sost is null");
			return (Criteria) this;
		}

		public Criteria andPrimoTelaioSostIsNotNull() {
			addCriterion("primo_telaio_sost is not null");
			return (Criteria) this;
		}

		public Criteria andPrimoTelaioSostEqualTo(String value) {
			addCriterion("primo_telaio_sost =", value, "primoTelaioSost");
			return (Criteria) this;
		}

		public Criteria andPrimoTelaioSostNotEqualTo(String value) {
			addCriterion("primo_telaio_sost <>", value, "primoTelaioSost");
			return (Criteria) this;
		}

		public Criteria andPrimoTelaioSostGreaterThan(String value) {
			addCriterion("primo_telaio_sost >", value, "primoTelaioSost");
			return (Criteria) this;
		}

		public Criteria andPrimoTelaioSostGreaterThanOrEqualTo(String value) {
			addCriterion("primo_telaio_sost >=", value, "primoTelaioSost");
			return (Criteria) this;
		}

		public Criteria andPrimoTelaioSostLessThan(String value) {
			addCriterion("primo_telaio_sost <", value, "primoTelaioSost");
			return (Criteria) this;
		}

		public Criteria andPrimoTelaioSostLessThanOrEqualTo(String value) {
			addCriterion("primo_telaio_sost <=", value, "primoTelaioSost");
			return (Criteria) this;
		}

		public Criteria andPrimoTelaioSostLike(String value) {
			addCriterion("primo_telaio_sost like", value, "primoTelaioSost");
			return (Criteria) this;
		}

		public Criteria andPrimoTelaioSostNotLike(String value) {
			addCriterion("primo_telaio_sost not like", value, "primoTelaioSost");
			return (Criteria) this;
		}

		public Criteria andPrimoTelaioSostIn(List<String> values) {
			addCriterion("primo_telaio_sost in", values, "primoTelaioSost");
			return (Criteria) this;
		}

		public Criteria andPrimoTelaioSostNotIn(List<String> values) {
			addCriterion("primo_telaio_sost not in", values, "primoTelaioSost");
			return (Criteria) this;
		}

		public Criteria andPrimoTelaioSostBetween(String value1, String value2) {
			addCriterion("primo_telaio_sost between", value1, value2, "primoTelaioSost");
			return (Criteria) this;
		}

		public Criteria andPrimoTelaioSostNotBetween(String value1, String value2) {
			addCriterion("primo_telaio_sost not between", value1, value2, "primoTelaioSost");
			return (Criteria) this;
		}

		public Criteria andNrCartaCircolazioneLikeInsensitive(String value) {
			addCriterion("upper(nr_carta_circolazione) like", value.toUpperCase(), "nrCartaCircolazione");
			return (Criteria) this;
		}

		public Criteria andPrimoTelaioSostLikeInsensitive(String value) {
			addCriterion("upper(primo_telaio_sost) like", value.toUpperCase(), "primoTelaioSost");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rebusc_t_dato_messa_servizio
	 * @mbg.generated  Wed Mar 16 10:58:09 CET 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebusc_t_dato_messa_servizio
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 24 17:39:06 CET 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}