/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RebusmTMisurazioneSelector {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public RebusmTMisurazioneSelector() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdMisurazioneIsNull() {
            addCriterion("id_misurazione is null");
            return (Criteria) this;
        }

        public Criteria andIdMisurazioneIsNotNull() {
            addCriterion("id_misurazione is not null");
            return (Criteria) this;
        }

        public Criteria andIdMisurazioneEqualTo(Long value) {
            addCriterion("id_misurazione =", value, "idMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdMisurazioneNotEqualTo(Long value) {
            addCriterion("id_misurazione <>", value, "idMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdMisurazioneGreaterThan(Long value) {
            addCriterion("id_misurazione >", value, "idMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdMisurazioneGreaterThanOrEqualTo(Long value) {
            addCriterion("id_misurazione >=", value, "idMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdMisurazioneLessThan(Long value) {
            addCriterion("id_misurazione <", value, "idMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdMisurazioneLessThanOrEqualTo(Long value) {
            addCriterion("id_misurazione <=", value, "idMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdMisurazioneIn(List<Long> values) {
            addCriterion("id_misurazione in", values, "idMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdMisurazioneNotIn(List<Long> values) {
            addCriterion("id_misurazione not in", values, "idMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdMisurazioneBetween(Long value1, Long value2) {
            addCriterion("id_misurazione between", value1, value2, "idMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdMisurazioneNotBetween(Long value1, Long value2) {
            addCriterion("id_misurazione not between", value1, value2, "idMisurazione");
            return (Criteria) this;
        }

        public Criteria andPrimoTelaioIsNull() {
            addCriterion("primo_telaio is null");
            return (Criteria) this;
        }

        public Criteria andPrimoTelaioIsNotNull() {
            addCriterion("primo_telaio is not null");
            return (Criteria) this;
        }

        public Criteria andPrimoTelaioEqualTo(String value) {
            addCriterion("primo_telaio =", value, "primoTelaio");
            return (Criteria) this;
        }

        public Criteria andPrimoTelaioNotEqualTo(String value) {
            addCriterion("primo_telaio <>", value, "primoTelaio");
            return (Criteria) this;
        }

        public Criteria andPrimoTelaioGreaterThan(String value) {
            addCriterion("primo_telaio >", value, "primoTelaio");
            return (Criteria) this;
        }

        public Criteria andPrimoTelaioGreaterThanOrEqualTo(String value) {
            addCriterion("primo_telaio >=", value, "primoTelaio");
            return (Criteria) this;
        }

        public Criteria andPrimoTelaioLessThan(String value) {
            addCriterion("primo_telaio <", value, "primoTelaio");
            return (Criteria) this;
        }

        public Criteria andPrimoTelaioLessThanOrEqualTo(String value) {
            addCriterion("primo_telaio <=", value, "primoTelaio");
            return (Criteria) this;
        }

        public Criteria andPrimoTelaioLike(String value) {
            addCriterion("primo_telaio like", value, "primoTelaio");
            return (Criteria) this;
        }

        public Criteria andPrimoTelaioNotLike(String value) {
            addCriterion("primo_telaio not like", value, "primoTelaio");
            return (Criteria) this;
        }

        public Criteria andPrimoTelaioIn(List<String> values) {
            addCriterion("primo_telaio in", values, "primoTelaio");
            return (Criteria) this;
        }

        public Criteria andPrimoTelaioNotIn(List<String> values) {
            addCriterion("primo_telaio not in", values, "primoTelaio");
            return (Criteria) this;
        }

        public Criteria andPrimoTelaioBetween(String value1, String value2) {
            addCriterion("primo_telaio between", value1, value2, "primoTelaio");
            return (Criteria) this;
        }

        public Criteria andPrimoTelaioNotBetween(String value1, String value2) {
            addCriterion("primo_telaio not between", value1, value2, "primoTelaio");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneIsNull() {
            addCriterion("id_doc_misurazione is null");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneIsNotNull() {
            addCriterion("id_doc_misurazione is not null");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneEqualTo(Long value) {
            addCriterion("id_doc_misurazione =", value, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneNotEqualTo(Long value) {
            addCriterion("id_doc_misurazione <>", value, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneGreaterThan(Long value) {
            addCriterion("id_doc_misurazione >", value, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneGreaterThanOrEqualTo(Long value) {
            addCriterion("id_doc_misurazione >=", value, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneLessThan(Long value) {
            addCriterion("id_doc_misurazione <", value, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneLessThanOrEqualTo(Long value) {
            addCriterion("id_doc_misurazione <=", value, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneIn(List<Long> values) {
            addCriterion("id_doc_misurazione in", values, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneNotIn(List<Long> values) {
            addCriterion("id_doc_misurazione not in", values, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneBetween(Long value1, Long value2) {
            addCriterion("id_doc_misurazione between", value1, value2, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneNotBetween(Long value1, Long value2) {
            addCriterion("id_doc_misurazione not between", value1, value2, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andDataInizioIsNull() {
            addCriterion("data_inizio is null");
            return (Criteria) this;
        }

        public Criteria andDataInizioIsNotNull() {
            addCriterion("data_inizio is not null");
            return (Criteria) this;
        }

        public Criteria andDataInizioEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio =", value, "dataInizio");
            return (Criteria) this;
        }

        public Criteria andDataInizioNotEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio <>", value, "dataInizio");
            return (Criteria) this;
        }

        public Criteria andDataInizioGreaterThan(Date value) {
            addCriterionForJDBCDate("data_inizio >", value, "dataInizio");
            return (Criteria) this;
        }

        public Criteria andDataInizioGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio >=", value, "dataInizio");
            return (Criteria) this;
        }

        public Criteria andDataInizioLessThan(Date value) {
            addCriterionForJDBCDate("data_inizio <", value, "dataInizio");
            return (Criteria) this;
        }

        public Criteria andDataInizioLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio <=", value, "dataInizio");
            return (Criteria) this;
        }

        public Criteria andDataInizioIn(List<Date> values) {
            addCriterionForJDBCDate("data_inizio in", values, "dataInizio");
            return (Criteria) this;
        }

        public Criteria andDataInizioNotIn(List<Date> values) {
            addCriterionForJDBCDate("data_inizio not in", values, "dataInizio");
            return (Criteria) this;
        }

        public Criteria andDataInizioBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_inizio between", value1, value2, "dataInizio");
            return (Criteria) this;
        }

        public Criteria andDataInizioNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_inizio not between", value1, value2, "dataInizio");
            return (Criteria) this;
        }

        public Criteria andDataFineIsNull() {
            addCriterion("data_fine is null");
            return (Criteria) this;
        }

        public Criteria andDataFineIsNotNull() {
            addCriterion("data_fine is not null");
            return (Criteria) this;
        }

        public Criteria andDataFineEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine =", value, "dataFine");
            return (Criteria) this;
        }

        public Criteria andDataFineNotEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine <>", value, "dataFine");
            return (Criteria) this;
        }

        public Criteria andDataFineGreaterThan(Date value) {
            addCriterionForJDBCDate("data_fine >", value, "dataFine");
            return (Criteria) this;
        }

        public Criteria andDataFineGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine >=", value, "dataFine");
            return (Criteria) this;
        }

        public Criteria andDataFineLessThan(Date value) {
            addCriterionForJDBCDate("data_fine <", value, "dataFine");
            return (Criteria) this;
        }

        public Criteria andDataFineLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine <=", value, "dataFine");
            return (Criteria) this;
        }

        public Criteria andDataFineIn(List<Date> values) {
            addCriterionForJDBCDate("data_fine in", values, "dataFine");
            return (Criteria) this;
        }

        public Criteria andDataFineNotIn(List<Date> values) {
            addCriterionForJDBCDate("data_fine not in", values, "dataFine");
            return (Criteria) this;
        }

        public Criteria andDataFineBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_fine between", value1, value2, "dataFine");
            return (Criteria) this;
        }

        public Criteria andDataFineNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_fine not between", value1, value2, "dataFine");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoIsNull() {
            addCriterion("id_utente_aggiornamento is null");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoIsNotNull() {
            addCriterion("id_utente_aggiornamento is not null");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento =", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoNotEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento <>", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoGreaterThan(Long value) {
            addCriterion("id_utente_aggiornamento >", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoGreaterThanOrEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento >=", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoLessThan(Long value) {
            addCriterion("id_utente_aggiornamento <", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoLessThanOrEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento <=", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoIn(List<Long> values) {
            addCriterion("id_utente_aggiornamento in", values, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoNotIn(List<Long> values) {
            addCriterion("id_utente_aggiornamento not in", values, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoBetween(Long value1, Long value2) {
            addCriterion("id_utente_aggiornamento between", value1, value2, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoNotBetween(Long value1, Long value2) {
            addCriterion("id_utente_aggiornamento not between", value1, value2, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoIsNull() {
            addCriterion("data_aggiornamento is null");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoIsNotNull() {
            addCriterion("data_aggiornamento is not null");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoEqualTo(Date value) {
            addCriterion("data_aggiornamento =", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoNotEqualTo(Date value) {
            addCriterion("data_aggiornamento <>", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoGreaterThan(Date value) {
            addCriterion("data_aggiornamento >", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoGreaterThanOrEqualTo(Date value) {
            addCriterion("data_aggiornamento >=", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoLessThan(Date value) {
            addCriterion("data_aggiornamento <", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoLessThanOrEqualTo(Date value) {
            addCriterion("data_aggiornamento <=", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoIn(List<Date> values) {
            addCriterion("data_aggiornamento in", values, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoNotIn(List<Date> values) {
            addCriterion("data_aggiornamento not in", values, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoBetween(Date value1, Date value2) {
            addCriterion("data_aggiornamento between", value1, value2, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoNotBetween(Date value1, Date value2) {
            addCriterion("data_aggiornamento not between", value1, value2, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andPrimoTelaioLikeInsensitive(String value) {
            addCriterion("upper(primo_telaio) like", value.toUpperCase(), "primoTelaio");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 10 09:58:49 CET 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}