/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RebuspDTransizioneAutomaSelector {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public RebuspDTransizioneAutomaSelector() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdTransizioneAutomaIsNull() {
			addCriterion("id_transizione_automa is null");
			return (Criteria) this;
		}

		public Criteria andIdTransizioneAutomaIsNotNull() {
			addCriterion("id_transizione_automa is not null");
			return (Criteria) this;
		}

		public Criteria andIdTransizioneAutomaEqualTo(Long value) {
			addCriterion("id_transizione_automa =", value, "idTransizioneAutoma");
			return (Criteria) this;
		}

		public Criteria andIdTransizioneAutomaNotEqualTo(Long value) {
			addCriterion("id_transizione_automa <>", value, "idTransizioneAutoma");
			return (Criteria) this;
		}

		public Criteria andIdTransizioneAutomaGreaterThan(Long value) {
			addCriterion("id_transizione_automa >", value, "idTransizioneAutoma");
			return (Criteria) this;
		}

		public Criteria andIdTransizioneAutomaGreaterThanOrEqualTo(Long value) {
			addCriterion("id_transizione_automa >=", value, "idTransizioneAutoma");
			return (Criteria) this;
		}

		public Criteria andIdTransizioneAutomaLessThan(Long value) {
			addCriterion("id_transizione_automa <", value, "idTransizioneAutoma");
			return (Criteria) this;
		}

		public Criteria andIdTransizioneAutomaLessThanOrEqualTo(Long value) {
			addCriterion("id_transizione_automa <=", value, "idTransizioneAutoma");
			return (Criteria) this;
		}

		public Criteria andIdTransizioneAutomaIn(List<Long> values) {
			addCriterion("id_transizione_automa in", values, "idTransizioneAutoma");
			return (Criteria) this;
		}

		public Criteria andIdTransizioneAutomaNotIn(List<Long> values) {
			addCriterion("id_transizione_automa not in", values, "idTransizioneAutoma");
			return (Criteria) this;
		}

		public Criteria andIdTransizioneAutomaBetween(Long value1, Long value2) {
			addCriterion("id_transizione_automa between", value1, value2, "idTransizioneAutoma");
			return (Criteria) this;
		}

		public Criteria andIdTransizioneAutomaNotBetween(Long value1, Long value2) {
			addCriterion("id_transizione_automa not between", value1, value2, "idTransizioneAutoma");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterDaIsNull() {
			addCriterion("id_stato_iter_da is null");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterDaIsNotNull() {
			addCriterion("id_stato_iter_da is not null");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterDaEqualTo(Long value) {
			addCriterion("id_stato_iter_da =", value, "idStatoIterDa");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterDaNotEqualTo(Long value) {
			addCriterion("id_stato_iter_da <>", value, "idStatoIterDa");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterDaGreaterThan(Long value) {
			addCriterion("id_stato_iter_da >", value, "idStatoIterDa");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterDaGreaterThanOrEqualTo(Long value) {
			addCriterion("id_stato_iter_da >=", value, "idStatoIterDa");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterDaLessThan(Long value) {
			addCriterion("id_stato_iter_da <", value, "idStatoIterDa");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterDaLessThanOrEqualTo(Long value) {
			addCriterion("id_stato_iter_da <=", value, "idStatoIterDa");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterDaIn(List<Long> values) {
			addCriterion("id_stato_iter_da in", values, "idStatoIterDa");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterDaNotIn(List<Long> values) {
			addCriterion("id_stato_iter_da not in", values, "idStatoIterDa");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterDaBetween(Long value1, Long value2) {
			addCriterion("id_stato_iter_da between", value1, value2, "idStatoIterDa");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterDaNotBetween(Long value1, Long value2) {
			addCriterion("id_stato_iter_da not between", value1, value2, "idStatoIterDa");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterAIsNull() {
			addCriterion("id_stato_iter_a is null");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterAIsNotNull() {
			addCriterion("id_stato_iter_a is not null");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterAEqualTo(Long value) {
			addCriterion("id_stato_iter_a =", value, "idStatoIterA");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterANotEqualTo(Long value) {
			addCriterion("id_stato_iter_a <>", value, "idStatoIterA");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterAGreaterThan(Long value) {
			addCriterion("id_stato_iter_a >", value, "idStatoIterA");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterAGreaterThanOrEqualTo(Long value) {
			addCriterion("id_stato_iter_a >=", value, "idStatoIterA");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterALessThan(Long value) {
			addCriterion("id_stato_iter_a <", value, "idStatoIterA");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterALessThanOrEqualTo(Long value) {
			addCriterion("id_stato_iter_a <=", value, "idStatoIterA");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterAIn(List<Long> values) {
			addCriterion("id_stato_iter_a in", values, "idStatoIterA");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterANotIn(List<Long> values) {
			addCriterion("id_stato_iter_a not in", values, "idStatoIterA");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterABetween(Long value1, Long value2) {
			addCriterion("id_stato_iter_a between", value1, value2, "idStatoIterA");
			return (Criteria) this;
		}

		public Criteria andIdStatoIterANotBetween(Long value1, Long value2) {
			addCriterion("id_stato_iter_a not between", value1, value2, "idStatoIterA");
			return (Criteria) this;
		}

		public Criteria andTitoloIsNull() {
			addCriterion("titolo is null");
			return (Criteria) this;
		}

		public Criteria andTitoloIsNotNull() {
			addCriterion("titolo is not null");
			return (Criteria) this;
		}

		public Criteria andTitoloEqualTo(String value) {
			addCriterion("titolo =", value, "titolo");
			return (Criteria) this;
		}

		public Criteria andTitoloNotEqualTo(String value) {
			addCriterion("titolo <>", value, "titolo");
			return (Criteria) this;
		}

		public Criteria andTitoloGreaterThan(String value) {
			addCriterion("titolo >", value, "titolo");
			return (Criteria) this;
		}

		public Criteria andTitoloGreaterThanOrEqualTo(String value) {
			addCriterion("titolo >=", value, "titolo");
			return (Criteria) this;
		}

		public Criteria andTitoloLessThan(String value) {
			addCriterion("titolo <", value, "titolo");
			return (Criteria) this;
		}

		public Criteria andTitoloLessThanOrEqualTo(String value) {
			addCriterion("titolo <=", value, "titolo");
			return (Criteria) this;
		}

		public Criteria andTitoloLike(String value) {
			addCriterion("titolo like", value, "titolo");
			return (Criteria) this;
		}

		public Criteria andTitoloNotLike(String value) {
			addCriterion("titolo not like", value, "titolo");
			return (Criteria) this;
		}

		public Criteria andTitoloIn(List<String> values) {
			addCriterion("titolo in", values, "titolo");
			return (Criteria) this;
		}

		public Criteria andTitoloNotIn(List<String> values) {
			addCriterion("titolo not in", values, "titolo");
			return (Criteria) this;
		}

		public Criteria andTitoloBetween(String value1, String value2) {
			addCriterion("titolo between", value1, value2, "titolo");
			return (Criteria) this;
		}

		public Criteria andTitoloNotBetween(String value1, String value2) {
			addCriterion("titolo not between", value1, value2, "titolo");
			return (Criteria) this;
		}

		public Criteria andLabelIsNull() {
			addCriterion("label is null");
			return (Criteria) this;
		}

		public Criteria andLabelIsNotNull() {
			addCriterion("label is not null");
			return (Criteria) this;
		}

		public Criteria andLabelEqualTo(String value) {
			addCriterion("label =", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelNotEqualTo(String value) {
			addCriterion("label <>", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelGreaterThan(String value) {
			addCriterion("label >", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelGreaterThanOrEqualTo(String value) {
			addCriterion("label >=", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelLessThan(String value) {
			addCriterion("label <", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelLessThanOrEqualTo(String value) {
			addCriterion("label <=", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelLike(String value) {
			addCriterion("label like", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelNotLike(String value) {
			addCriterion("label not like", value, "label");
			return (Criteria) this;
		}

		public Criteria andLabelIn(List<String> values) {
			addCriterion("label in", values, "label");
			return (Criteria) this;
		}

		public Criteria andLabelNotIn(List<String> values) {
			addCriterion("label not in", values, "label");
			return (Criteria) this;
		}

		public Criteria andLabelBetween(String value1, String value2) {
			addCriterion("label between", value1, value2, "label");
			return (Criteria) this;
		}

		public Criteria andLabelNotBetween(String value1, String value2) {
			addCriterion("label not between", value1, value2, "label");
			return (Criteria) this;
		}

		public Criteria andTestoIsNull() {
			addCriterion("testo is null");
			return (Criteria) this;
		}

		public Criteria andTestoIsNotNull() {
			addCriterion("testo is not null");
			return (Criteria) this;
		}

		public Criteria andTestoEqualTo(String value) {
			addCriterion("testo =", value, "testo");
			return (Criteria) this;
		}

		public Criteria andTestoNotEqualTo(String value) {
			addCriterion("testo <>", value, "testo");
			return (Criteria) this;
		}

		public Criteria andTestoGreaterThan(String value) {
			addCriterion("testo >", value, "testo");
			return (Criteria) this;
		}

		public Criteria andTestoGreaterThanOrEqualTo(String value) {
			addCriterion("testo >=", value, "testo");
			return (Criteria) this;
		}

		public Criteria andTestoLessThan(String value) {
			addCriterion("testo <", value, "testo");
			return (Criteria) this;
		}

		public Criteria andTestoLessThanOrEqualTo(String value) {
			addCriterion("testo <=", value, "testo");
			return (Criteria) this;
		}

		public Criteria andTestoLike(String value) {
			addCriterion("testo like", value, "testo");
			return (Criteria) this;
		}

		public Criteria andTestoNotLike(String value) {
			addCriterion("testo not like", value, "testo");
			return (Criteria) this;
		}

		public Criteria andTestoIn(List<String> values) {
			addCriterion("testo in", values, "testo");
			return (Criteria) this;
		}

		public Criteria andTestoNotIn(List<String> values) {
			addCriterion("testo not in", values, "testo");
			return (Criteria) this;
		}

		public Criteria andTestoBetween(String value1, String value2) {
			addCriterion("testo between", value1, value2, "testo");
			return (Criteria) this;
		}

		public Criteria andTestoNotBetween(String value1, String value2) {
			addCriterion("testo not between", value1, value2, "testo");
			return (Criteria) this;
		}

		public Criteria andCondizioniIsNull() {
			addCriterion("condizioni is null");
			return (Criteria) this;
		}

		public Criteria andCondizioniIsNotNull() {
			addCriterion("condizioni is not null");
			return (Criteria) this;
		}

		public Criteria andCondizioniEqualTo(String value) {
			addCriterion("condizioni =", value, "condizioni");
			return (Criteria) this;
		}

		public Criteria andCondizioniNotEqualTo(String value) {
			addCriterion("condizioni <>", value, "condizioni");
			return (Criteria) this;
		}

		public Criteria andCondizioniGreaterThan(String value) {
			addCriterion("condizioni >", value, "condizioni");
			return (Criteria) this;
		}

		public Criteria andCondizioniGreaterThanOrEqualTo(String value) {
			addCriterion("condizioni >=", value, "condizioni");
			return (Criteria) this;
		}

		public Criteria andCondizioniLessThan(String value) {
			addCriterion("condizioni <", value, "condizioni");
			return (Criteria) this;
		}

		public Criteria andCondizioniLessThanOrEqualTo(String value) {
			addCriterion("condizioni <=", value, "condizioni");
			return (Criteria) this;
		}

		public Criteria andCondizioniLike(String value) {
			addCriterion("condizioni like", value, "condizioni");
			return (Criteria) this;
		}

		public Criteria andCondizioniNotLike(String value) {
			addCriterion("condizioni not like", value, "condizioni");
			return (Criteria) this;
		}

		public Criteria andCondizioniIn(List<String> values) {
			addCriterion("condizioni in", values, "condizioni");
			return (Criteria) this;
		}

		public Criteria andCondizioniNotIn(List<String> values) {
			addCriterion("condizioni not in", values, "condizioni");
			return (Criteria) this;
		}

		public Criteria andCondizioniBetween(String value1, String value2) {
			addCriterion("condizioni between", value1, value2, "condizioni");
			return (Criteria) this;
		}

		public Criteria andCondizioniNotBetween(String value1, String value2) {
			addCriterion("condizioni not between", value1, value2, "condizioni");
			return (Criteria) this;
		}

		public Criteria andFlgNoteObbligatorieIsNull() {
			addCriterion("flg_note_obbligatorie is null");
			return (Criteria) this;
		}

		public Criteria andFlgNoteObbligatorieIsNotNull() {
			addCriterion("flg_note_obbligatorie is not null");
			return (Criteria) this;
		}

		public Criteria andFlgNoteObbligatorieEqualTo(Boolean value) {
			addCriterion("flg_note_obbligatorie =", value, "flgNoteObbligatorie");
			return (Criteria) this;
		}

		public Criteria andFlgNoteObbligatorieNotEqualTo(Boolean value) {
			addCriterion("flg_note_obbligatorie <>", value, "flgNoteObbligatorie");
			return (Criteria) this;
		}

		public Criteria andFlgNoteObbligatorieGreaterThan(Boolean value) {
			addCriterion("flg_note_obbligatorie >", value, "flgNoteObbligatorie");
			return (Criteria) this;
		}

		public Criteria andFlgNoteObbligatorieGreaterThanOrEqualTo(Boolean value) {
			addCriterion("flg_note_obbligatorie >=", value, "flgNoteObbligatorie");
			return (Criteria) this;
		}

		public Criteria andFlgNoteObbligatorieLessThan(Boolean value) {
			addCriterion("flg_note_obbligatorie <", value, "flgNoteObbligatorie");
			return (Criteria) this;
		}

		public Criteria andFlgNoteObbligatorieLessThanOrEqualTo(Boolean value) {
			addCriterion("flg_note_obbligatorie <=", value, "flgNoteObbligatorie");
			return (Criteria) this;
		}

		public Criteria andFlgNoteObbligatorieIn(List<Boolean> values) {
			addCriterion("flg_note_obbligatorie in", values, "flgNoteObbligatorie");
			return (Criteria) this;
		}

		public Criteria andFlgNoteObbligatorieNotIn(List<Boolean> values) {
			addCriterion("flg_note_obbligatorie not in", values, "flgNoteObbligatorie");
			return (Criteria) this;
		}

		public Criteria andFlgNoteObbligatorieBetween(Boolean value1, Boolean value2) {
			addCriterion("flg_note_obbligatorie between", value1, value2, "flgNoteObbligatorie");
			return (Criteria) this;
		}

		public Criteria andFlgNoteObbligatorieNotBetween(Boolean value1, Boolean value2) {
			addCriterion("flg_note_obbligatorie not between", value1, value2, "flgNoteObbligatorie");
			return (Criteria) this;
		}

		public Criteria andIdTipoMessaggioIsNull() {
			addCriterion("id_tipo_messaggio is null");
			return (Criteria) this;
		}

		public Criteria andIdTipoMessaggioIsNotNull() {
			addCriterion("id_tipo_messaggio is not null");
			return (Criteria) this;
		}

		public Criteria andIdTipoMessaggioEqualTo(Long value) {
			addCriterion("id_tipo_messaggio =", value, "idTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdTipoMessaggioNotEqualTo(Long value) {
			addCriterion("id_tipo_messaggio <>", value, "idTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdTipoMessaggioGreaterThan(Long value) {
			addCriterion("id_tipo_messaggio >", value, "idTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdTipoMessaggioGreaterThanOrEqualTo(Long value) {
			addCriterion("id_tipo_messaggio >=", value, "idTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdTipoMessaggioLessThan(Long value) {
			addCriterion("id_tipo_messaggio <", value, "idTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdTipoMessaggioLessThanOrEqualTo(Long value) {
			addCriterion("id_tipo_messaggio <=", value, "idTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdTipoMessaggioIn(List<Long> values) {
			addCriterion("id_tipo_messaggio in", values, "idTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdTipoMessaggioNotIn(List<Long> values) {
			addCriterion("id_tipo_messaggio not in", values, "idTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdTipoMessaggioBetween(Long value1, Long value2) {
			addCriterion("id_tipo_messaggio between", value1, value2, "idTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andIdTipoMessaggioNotBetween(Long value1, Long value2) {
			addCriterion("id_tipo_messaggio not between", value1, value2, "idTipoMessaggio");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaIsNull() {
			addCriterion("data_inizio_validita is null");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaIsNotNull() {
			addCriterion("data_inizio_validita is not null");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaEqualTo(Date value) {
			addCriterionForJDBCDate("data_inizio_validita =", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaNotEqualTo(Date value) {
			addCriterionForJDBCDate("data_inizio_validita <>", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaGreaterThan(Date value) {
			addCriterionForJDBCDate("data_inizio_validita >", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_inizio_validita >=", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaLessThan(Date value) {
			addCriterionForJDBCDate("data_inizio_validita <", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_inizio_validita <=", value, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaIn(List<Date> values) {
			addCriterionForJDBCDate("data_inizio_validita in", values, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaNotIn(List<Date> values) {
			addCriterionForJDBCDate("data_inizio_validita not in", values, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_inizio_validita between", value1, value2, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataInizioValiditaNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_inizio_validita not between", value1, value2, "dataInizioValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaIsNull() {
			addCriterion("data_fine_validita is null");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaIsNotNull() {
			addCriterion("data_fine_validita is not null");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaEqualTo(Date value) {
			addCriterionForJDBCDate("data_fine_validita =", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaNotEqualTo(Date value) {
			addCriterionForJDBCDate("data_fine_validita <>", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaGreaterThan(Date value) {
			addCriterionForJDBCDate("data_fine_validita >", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_fine_validita >=", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaLessThan(Date value) {
			addCriterionForJDBCDate("data_fine_validita <", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_fine_validita <=", value, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaIn(List<Date> values) {
			addCriterionForJDBCDate("data_fine_validita in", values, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaNotIn(List<Date> values) {
			addCriterionForJDBCDate("data_fine_validita not in", values, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_fine_validita between", value1, value2, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andDataFineValiditaNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_fine_validita not between", value1, value2, "dataFineValidita");
			return (Criteria) this;
		}

		public Criteria andFlagDefaultIsNull() {
			addCriterion("flag_default is null");
			return (Criteria) this;
		}

		public Criteria andFlagDefaultIsNotNull() {
			addCriterion("flag_default is not null");
			return (Criteria) this;
		}

		public Criteria andFlagDefaultEqualTo(Boolean value) {
			addCriterion("flag_default =", value, "flagDefault");
			return (Criteria) this;
		}

		public Criteria andFlagDefaultNotEqualTo(Boolean value) {
			addCriterion("flag_default <>", value, "flagDefault");
			return (Criteria) this;
		}

		public Criteria andFlagDefaultGreaterThan(Boolean value) {
			addCriterion("flag_default >", value, "flagDefault");
			return (Criteria) this;
		}

		public Criteria andFlagDefaultGreaterThanOrEqualTo(Boolean value) {
			addCriterion("flag_default >=", value, "flagDefault");
			return (Criteria) this;
		}

		public Criteria andFlagDefaultLessThan(Boolean value) {
			addCriterion("flag_default <", value, "flagDefault");
			return (Criteria) this;
		}

		public Criteria andFlagDefaultLessThanOrEqualTo(Boolean value) {
			addCriterion("flag_default <=", value, "flagDefault");
			return (Criteria) this;
		}

		public Criteria andFlagDefaultIn(List<Boolean> values) {
			addCriterion("flag_default in", values, "flagDefault");
			return (Criteria) this;
		}

		public Criteria andFlagDefaultNotIn(List<Boolean> values) {
			addCriterion("flag_default not in", values, "flagDefault");
			return (Criteria) this;
		}

		public Criteria andFlagDefaultBetween(Boolean value1, Boolean value2) {
			addCriterion("flag_default between", value1, value2, "flagDefault");
			return (Criteria) this;
		}

		public Criteria andFlagDefaultNotBetween(Boolean value1, Boolean value2) {
			addCriterion("flag_default not between", value1, value2, "flagDefault");
			return (Criteria) this;
		}

		public Criteria andTitoloLikeInsensitive(String value) {
			addCriterion("upper(titolo) like", value.toUpperCase(), "titolo");
			return (Criteria) this;
		}

		public Criteria andLabelLikeInsensitive(String value) {
			addCriterion("upper(label) like", value.toUpperCase(), "label");
			return (Criteria) this;
		}

		public Criteria andTestoLikeInsensitive(String value) {
			addCriterion("upper(testo) like", value.toUpperCase(), "testo");
			return (Criteria) this;
		}

		public Criteria andCondizioniLikeInsensitive(String value) {
			addCriterion("upper(condizioni) like", value.toUpperCase(), "condizioni");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebusp_d_transizione_automa
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 19 11:47:08 CET 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}