/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebuscDSistemaLocalizzazioneDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusc_d_sistema_localizzazione.id_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    private Double idSistemaLocalizzazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusc_d_sistema_localizzazione.desc_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    private String descSistemaLocalizzazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusc_d_sistema_localizzazione.data_inizio_validita
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    private Date dataInizioValidita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusc_d_sistema_localizzazione.data_fine_validita
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    private Date dataFineValidita;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusc_d_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusc_d_sistema_localizzazione.id_sistema_localizzazione
     *
     * @return the value of rebusc_d_sistema_localizzazione.id_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    public Double getIdSistemaLocalizzazione() {
        return idSistemaLocalizzazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusc_d_sistema_localizzazione.id_sistema_localizzazione
     *
     * @param idSistemaLocalizzazione the value for rebusc_d_sistema_localizzazione.id_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    public void setIdSistemaLocalizzazione(Double idSistemaLocalizzazione) {
        this.idSistemaLocalizzazione = idSistemaLocalizzazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusc_d_sistema_localizzazione.desc_sistema_localizzazione
     *
     * @return the value of rebusc_d_sistema_localizzazione.desc_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    public String getDescSistemaLocalizzazione() {
        return descSistemaLocalizzazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusc_d_sistema_localizzazione.desc_sistema_localizzazione
     *
     * @param descSistemaLocalizzazione the value for rebusc_d_sistema_localizzazione.desc_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    public void setDescSistemaLocalizzazione(String descSistemaLocalizzazione) {
        this.descSistemaLocalizzazione = descSistemaLocalizzazione == null ? null : descSistemaLocalizzazione.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusc_d_sistema_localizzazione.data_inizio_validita
     *
     * @return the value of rebusc_d_sistema_localizzazione.data_inizio_validita
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    public Date getDataInizioValidita() {
        return dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusc_d_sistema_localizzazione.data_inizio_validita
     *
     * @param dataInizioValidita the value for rebusc_d_sistema_localizzazione.data_inizio_validita
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    public void setDataInizioValidita(Date dataInizioValidita) {
        this.dataInizioValidita = dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusc_d_sistema_localizzazione.data_fine_validita
     *
     * @return the value of rebusc_d_sistema_localizzazione.data_fine_validita
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    public Date getDataFineValidita() {
        return dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusc_d_sistema_localizzazione.data_fine_validita
     *
     * @param dataFineValidita the value for rebusc_d_sistema_localizzazione.data_fine_validita
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    public void setDataFineValidita(Date dataFineValidita) {
        this.dataFineValidita = dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idSistemaLocalizzazione=").append(idSistemaLocalizzazione);
        sb.append(", descSistemaLocalizzazione=").append(descSistemaLocalizzazione);
        sb.append(", dataInizioValidita=").append(dataInizioValidita);
        sb.append(", dataFineValidita=").append(dataFineValidita);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}