/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RebusmRDocMisurazioneSelector {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public RebusmRDocMisurazioneSelector() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdDocMisurazioneIsNull() {
            addCriterion("id_doc_misurazione is null");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneIsNotNull() {
            addCriterion("id_doc_misurazione is not null");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneEqualTo(Long value) {
            addCriterion("id_doc_misurazione =", value, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneNotEqualTo(Long value) {
            addCriterion("id_doc_misurazione <>", value, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneGreaterThan(Long value) {
            addCriterion("id_doc_misurazione >", value, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneGreaterThanOrEqualTo(Long value) {
            addCriterion("id_doc_misurazione >=", value, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneLessThan(Long value) {
            addCriterion("id_doc_misurazione <", value, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneLessThanOrEqualTo(Long value) {
            addCriterion("id_doc_misurazione <=", value, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneIn(List<Long> values) {
            addCriterion("id_doc_misurazione in", values, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneNotIn(List<Long> values) {
            addCriterion("id_doc_misurazione not in", values, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneBetween(Long value1, Long value2) {
            addCriterion("id_doc_misurazione between", value1, value2, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdDocMisurazioneNotBetween(Long value1, Long value2) {
            addCriterion("id_doc_misurazione not between", value1, value2, "idDocMisurazione");
            return (Criteria) this;
        }

        public Criteria andIdTipoDocumentoIsNull() {
            addCriterion("id_tipo_documento is null");
            return (Criteria) this;
        }

        public Criteria andIdTipoDocumentoIsNotNull() {
            addCriterion("id_tipo_documento is not null");
            return (Criteria) this;
        }

        public Criteria andIdTipoDocumentoEqualTo(Long value) {
            addCriterion("id_tipo_documento =", value, "idTipoDocumento");
            return (Criteria) this;
        }

        public Criteria andIdTipoDocumentoNotEqualTo(Long value) {
            addCriterion("id_tipo_documento <>", value, "idTipoDocumento");
            return (Criteria) this;
        }

        public Criteria andIdTipoDocumentoGreaterThan(Long value) {
            addCriterion("id_tipo_documento >", value, "idTipoDocumento");
            return (Criteria) this;
        }

        public Criteria andIdTipoDocumentoGreaterThanOrEqualTo(Long value) {
            addCriterion("id_tipo_documento >=", value, "idTipoDocumento");
            return (Criteria) this;
        }

        public Criteria andIdTipoDocumentoLessThan(Long value) {
            addCriterion("id_tipo_documento <", value, "idTipoDocumento");
            return (Criteria) this;
        }

        public Criteria andIdTipoDocumentoLessThanOrEqualTo(Long value) {
            addCriterion("id_tipo_documento <=", value, "idTipoDocumento");
            return (Criteria) this;
        }

        public Criteria andIdTipoDocumentoIn(List<Long> values) {
            addCriterion("id_tipo_documento in", values, "idTipoDocumento");
            return (Criteria) this;
        }

        public Criteria andIdTipoDocumentoNotIn(List<Long> values) {
            addCriterion("id_tipo_documento not in", values, "idTipoDocumento");
            return (Criteria) this;
        }

        public Criteria andIdTipoDocumentoBetween(Long value1, Long value2) {
            addCriterion("id_tipo_documento between", value1, value2, "idTipoDocumento");
            return (Criteria) this;
        }

        public Criteria andIdTipoDocumentoNotBetween(Long value1, Long value2) {
            addCriterion("id_tipo_documento not between", value1, value2, "idTipoDocumento");
            return (Criteria) this;
        }

        public Criteria andNomeFileIsNull() {
            addCriterion("nome_file is null");
            return (Criteria) this;
        }

        public Criteria andNomeFileIsNotNull() {
            addCriterion("nome_file is not null");
            return (Criteria) this;
        }

        public Criteria andNomeFileEqualTo(String value) {
            addCriterion("nome_file =", value, "nomeFile");
            return (Criteria) this;
        }

        public Criteria andNomeFileNotEqualTo(String value) {
            addCriterion("nome_file <>", value, "nomeFile");
            return (Criteria) this;
        }

        public Criteria andNomeFileGreaterThan(String value) {
            addCriterion("nome_file >", value, "nomeFile");
            return (Criteria) this;
        }

        public Criteria andNomeFileGreaterThanOrEqualTo(String value) {
            addCriterion("nome_file >=", value, "nomeFile");
            return (Criteria) this;
        }

        public Criteria andNomeFileLessThan(String value) {
            addCriterion("nome_file <", value, "nomeFile");
            return (Criteria) this;
        }

        public Criteria andNomeFileLessThanOrEqualTo(String value) {
            addCriterion("nome_file <=", value, "nomeFile");
            return (Criteria) this;
        }

        public Criteria andNomeFileLike(String value) {
            addCriterion("nome_file like", value, "nomeFile");
            return (Criteria) this;
        }

        public Criteria andNomeFileNotLike(String value) {
            addCriterion("nome_file not like", value, "nomeFile");
            return (Criteria) this;
        }

        public Criteria andNomeFileIn(List<String> values) {
            addCriterion("nome_file in", values, "nomeFile");
            return (Criteria) this;
        }

        public Criteria andNomeFileNotIn(List<String> values) {
            addCriterion("nome_file not in", values, "nomeFile");
            return (Criteria) this;
        }

        public Criteria andNomeFileBetween(String value1, String value2) {
            addCriterion("nome_file between", value1, value2, "nomeFile");
            return (Criteria) this;
        }

        public Criteria andNomeFileNotBetween(String value1, String value2) {
            addCriterion("nome_file not between", value1, value2, "nomeFile");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoIsNull() {
            addCriterion("id_utente_aggiornamento is null");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoIsNotNull() {
            addCriterion("id_utente_aggiornamento is not null");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento =", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoNotEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento <>", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoGreaterThan(Long value) {
            addCriterion("id_utente_aggiornamento >", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoGreaterThanOrEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento >=", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoLessThan(Long value) {
            addCriterion("id_utente_aggiornamento <", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoLessThanOrEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento <=", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoIn(List<Long> values) {
            addCriterion("id_utente_aggiornamento in", values, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoNotIn(List<Long> values) {
            addCriterion("id_utente_aggiornamento not in", values, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoBetween(Long value1, Long value2) {
            addCriterion("id_utente_aggiornamento between", value1, value2, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoNotBetween(Long value1, Long value2) {
            addCriterion("id_utente_aggiornamento not between", value1, value2, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataCaricamentoIsNull() {
            addCriterion("data_caricamento is null");
            return (Criteria) this;
        }

        public Criteria andDataCaricamentoIsNotNull() {
            addCriterion("data_caricamento is not null");
            return (Criteria) this;
        }

        public Criteria andDataCaricamentoEqualTo(Date value) {
            addCriterion("data_caricamento =", value, "dataCaricamento");
            return (Criteria) this;
        }

        public Criteria andDataCaricamentoNotEqualTo(Date value) {
            addCriterion("data_caricamento <>", value, "dataCaricamento");
            return (Criteria) this;
        }

        public Criteria andDataCaricamentoGreaterThan(Date value) {
            addCriterion("data_caricamento >", value, "dataCaricamento");
            return (Criteria) this;
        }

        public Criteria andDataCaricamentoGreaterThanOrEqualTo(Date value) {
            addCriterion("data_caricamento >=", value, "dataCaricamento");
            return (Criteria) this;
        }

        public Criteria andDataCaricamentoLessThan(Date value) {
            addCriterion("data_caricamento <", value, "dataCaricamento");
            return (Criteria) this;
        }

        public Criteria andDataCaricamentoLessThanOrEqualTo(Date value) {
            addCriterion("data_caricamento <=", value, "dataCaricamento");
            return (Criteria) this;
        }

        public Criteria andDataCaricamentoIn(List<Date> values) {
            addCriterion("data_caricamento in", values, "dataCaricamento");
            return (Criteria) this;
        }

        public Criteria andDataCaricamentoNotIn(List<Date> values) {
            addCriterion("data_caricamento not in", values, "dataCaricamento");
            return (Criteria) this;
        }

        public Criteria andDataCaricamentoBetween(Date value1, Date value2) {
            addCriterion("data_caricamento between", value1, value2, "dataCaricamento");
            return (Criteria) this;
        }

        public Criteria andDataCaricamentoNotBetween(Date value1, Date value2) {
            addCriterion("data_caricamento not between", value1, value2, "dataCaricamento");
            return (Criteria) this;
        }

        public Criteria andNomeFileLikeInsensitive(String value) {
            addCriterion("upper(nome_file) like", value.toUpperCase(), "nomeFile");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 10 10:30:29 CET 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebusm_r_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}