/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebuscTOrdineAcquistoDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_ordine_acquisto.id_ordine_acquisto
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Long idOrdineAcquisto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_ordine_acquisto.cup_master
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private String cupMaster;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_ordine_acquisto.cup
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private String cup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_ordine_acquisto.cig
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private String cig;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_ordine_acquisto.data_aggiudicazione
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Date dataAggiudicazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_ordine_acquisto.data_stipula
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Date dataStipula;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_ordine_acquisto.numero_ordine
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private String numeroOrdine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_ordine_acquisto.data_ordine
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Date dataOrdine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_ordine_acquisto.fornitore
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private String fornitore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_ordine_acquisto.id_utente_aggiornamento
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Long idUtenteAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_ordine_acquisto.data_aggiornamento
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusc_t_ordine_acquisto
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_ordine_acquisto.id_ordine_acquisto
	 * @return  the value of rebusc_t_ordine_acquisto.id_ordine_acquisto
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Long getIdOrdineAcquisto() {
		return idOrdineAcquisto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_ordine_acquisto.id_ordine_acquisto
	 * @param idOrdineAcquisto  the value for rebusc_t_ordine_acquisto.id_ordine_acquisto
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setIdOrdineAcquisto(Long idOrdineAcquisto) {
		this.idOrdineAcquisto = idOrdineAcquisto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_ordine_acquisto.cup_master
	 * @return  the value of rebusc_t_ordine_acquisto.cup_master
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public String getCupMaster() {
		return cupMaster;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_ordine_acquisto.cup_master
	 * @param cupMaster  the value for rebusc_t_ordine_acquisto.cup_master
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setCupMaster(String cupMaster) {
		this.cupMaster = cupMaster == null ? null : cupMaster.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_ordine_acquisto.cup
	 * @return  the value of rebusc_t_ordine_acquisto.cup
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public String getCup() {
		return cup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_ordine_acquisto.cup
	 * @param cup  the value for rebusc_t_ordine_acquisto.cup
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setCup(String cup) {
		this.cup = cup == null ? null : cup.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_ordine_acquisto.cig
	 * @return  the value of rebusc_t_ordine_acquisto.cig
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public String getCig() {
		return cig;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_ordine_acquisto.cig
	 * @param cig  the value for rebusc_t_ordine_acquisto.cig
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setCig(String cig) {
		this.cig = cig == null ? null : cig.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_ordine_acquisto.data_aggiudicazione
	 * @return  the value of rebusc_t_ordine_acquisto.data_aggiudicazione
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Date getDataAggiudicazione() {
		return dataAggiudicazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_ordine_acquisto.data_aggiudicazione
	 * @param dataAggiudicazione  the value for rebusc_t_ordine_acquisto.data_aggiudicazione
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setDataAggiudicazione(Date dataAggiudicazione) {
		this.dataAggiudicazione = dataAggiudicazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_ordine_acquisto.data_stipula
	 * @return  the value of rebusc_t_ordine_acquisto.data_stipula
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Date getDataStipula() {
		return dataStipula;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_ordine_acquisto.data_stipula
	 * @param dataStipula  the value for rebusc_t_ordine_acquisto.data_stipula
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setDataStipula(Date dataStipula) {
		this.dataStipula = dataStipula;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_ordine_acquisto.numero_ordine
	 * @return  the value of rebusc_t_ordine_acquisto.numero_ordine
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public String getNumeroOrdine() {
		return numeroOrdine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_ordine_acquisto.numero_ordine
	 * @param numeroOrdine  the value for rebusc_t_ordine_acquisto.numero_ordine
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setNumeroOrdine(String numeroOrdine) {
		this.numeroOrdine = numeroOrdine == null ? null : numeroOrdine.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_ordine_acquisto.data_ordine
	 * @return  the value of rebusc_t_ordine_acquisto.data_ordine
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Date getDataOrdine() {
		return dataOrdine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_ordine_acquisto.data_ordine
	 * @param dataOrdine  the value for rebusc_t_ordine_acquisto.data_ordine
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setDataOrdine(Date dataOrdine) {
		this.dataOrdine = dataOrdine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_ordine_acquisto.fornitore
	 * @return  the value of rebusc_t_ordine_acquisto.fornitore
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public String getFornitore() {
		return fornitore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_ordine_acquisto.fornitore
	 * @param fornitore  the value for rebusc_t_ordine_acquisto.fornitore
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setFornitore(String fornitore) {
		this.fornitore = fornitore == null ? null : fornitore.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_ordine_acquisto.id_utente_aggiornamento
	 * @return  the value of rebusc_t_ordine_acquisto.id_utente_aggiornamento
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Long getIdUtenteAggiornamento() {
		return idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_ordine_acquisto.id_utente_aggiornamento
	 * @param idUtenteAggiornamento  the value for rebusc_t_ordine_acquisto.id_utente_aggiornamento
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setIdUtenteAggiornamento(Long idUtenteAggiornamento) {
		this.idUtenteAggiornamento = idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_ordine_acquisto.data_aggiornamento
	 * @return  the value of rebusc_t_ordine_acquisto.data_aggiornamento
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_ordine_acquisto.data_aggiornamento
	 * @param dataAggiornamento  the value for rebusc_t_ordine_acquisto.data_aggiornamento
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_ordine_acquisto
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idOrdineAcquisto=").append(idOrdineAcquisto);
		sb.append(", cupMaster=").append(cupMaster);
		sb.append(", cup=").append(cup);
		sb.append(", cig=").append(cig);
		sb.append(", dataAggiudicazione=").append(dataAggiudicazione);
		sb.append(", dataStipula=").append(dataStipula);
		sb.append(", numeroOrdine=").append(numeroOrdine);
		sb.append(", dataOrdine=").append(dataOrdine);
		sb.append(", fornitore=").append(fornitore);
		sb.append(", idUtenteAggiornamento=").append(idUtenteAggiornamento);
		sb.append(", dataAggiornamento=").append(dataAggiornamento);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}