/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.util.ArrayList;
import java.util.List;

public class RebusDCategoriaVeicoloSelector {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public RebusDCategoriaVeicoloSelector() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdCategoriaVeicoloIsNull() {
			addCriterion("id_categoria_veicolo is null");
			return (Criteria) this;
		}

		public Criteria andIdCategoriaVeicoloIsNotNull() {
			addCriterion("id_categoria_veicolo is not null");
			return (Criteria) this;
		}

		public Criteria andIdCategoriaVeicoloEqualTo(Long value) {
			addCriterion("id_categoria_veicolo =", value, "idCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andIdCategoriaVeicoloNotEqualTo(Long value) {
			addCriterion("id_categoria_veicolo <>", value, "idCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andIdCategoriaVeicoloGreaterThan(Long value) {
			addCriterion("id_categoria_veicolo >", value, "idCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andIdCategoriaVeicoloGreaterThanOrEqualTo(Long value) {
			addCriterion("id_categoria_veicolo >=", value, "idCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andIdCategoriaVeicoloLessThan(Long value) {
			addCriterion("id_categoria_veicolo <", value, "idCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andIdCategoriaVeicoloLessThanOrEqualTo(Long value) {
			addCriterion("id_categoria_veicolo <=", value, "idCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andIdCategoriaVeicoloIn(List<Long> values) {
			addCriterion("id_categoria_veicolo in", values, "idCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andIdCategoriaVeicoloNotIn(List<Long> values) {
			addCriterion("id_categoria_veicolo not in", values, "idCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andIdCategoriaVeicoloBetween(Long value1, Long value2) {
			addCriterion("id_categoria_veicolo between", value1, value2, "idCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andIdCategoriaVeicoloNotBetween(Long value1, Long value2) {
			addCriterion("id_categoria_veicolo not between", value1, value2, "idCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCodCategoriaVeicoloIsNull() {
			addCriterion("cod_categoria_veicolo is null");
			return (Criteria) this;
		}

		public Criteria andCodCategoriaVeicoloIsNotNull() {
			addCriterion("cod_categoria_veicolo is not null");
			return (Criteria) this;
		}

		public Criteria andCodCategoriaVeicoloEqualTo(String value) {
			addCriterion("cod_categoria_veicolo =", value, "codCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCodCategoriaVeicoloNotEqualTo(String value) {
			addCriterion("cod_categoria_veicolo <>", value, "codCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCodCategoriaVeicoloGreaterThan(String value) {
			addCriterion("cod_categoria_veicolo >", value, "codCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCodCategoriaVeicoloGreaterThanOrEqualTo(String value) {
			addCriterion("cod_categoria_veicolo >=", value, "codCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCodCategoriaVeicoloLessThan(String value) {
			addCriterion("cod_categoria_veicolo <", value, "codCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCodCategoriaVeicoloLessThanOrEqualTo(String value) {
			addCriterion("cod_categoria_veicolo <=", value, "codCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCodCategoriaVeicoloLike(String value) {
			addCriterion("cod_categoria_veicolo like", value, "codCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCodCategoriaVeicoloNotLike(String value) {
			addCriterion("cod_categoria_veicolo not like", value, "codCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCodCategoriaVeicoloIn(List<String> values) {
			addCriterion("cod_categoria_veicolo in", values, "codCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCodCategoriaVeicoloNotIn(List<String> values) {
			addCriterion("cod_categoria_veicolo not in", values, "codCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCodCategoriaVeicoloBetween(String value1, String value2) {
			addCriterion("cod_categoria_veicolo between", value1, value2, "codCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCodCategoriaVeicoloNotBetween(String value1, String value2) {
			addCriterion("cod_categoria_veicolo not between", value1, value2, "codCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCategoriaVeicoloIsNull() {
			addCriterion("categoria_veicolo is null");
			return (Criteria) this;
		}

		public Criteria andCategoriaVeicoloIsNotNull() {
			addCriterion("categoria_veicolo is not null");
			return (Criteria) this;
		}

		public Criteria andCategoriaVeicoloEqualTo(String value) {
			addCriterion("categoria_veicolo =", value, "categoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCategoriaVeicoloNotEqualTo(String value) {
			addCriterion("categoria_veicolo <>", value, "categoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCategoriaVeicoloGreaterThan(String value) {
			addCriterion("categoria_veicolo >", value, "categoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCategoriaVeicoloGreaterThanOrEqualTo(String value) {
			addCriterion("categoria_veicolo >=", value, "categoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCategoriaVeicoloLessThan(String value) {
			addCriterion("categoria_veicolo <", value, "categoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCategoriaVeicoloLessThanOrEqualTo(String value) {
			addCriterion("categoria_veicolo <=", value, "categoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCategoriaVeicoloLike(String value) {
			addCriterion("categoria_veicolo like", value, "categoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCategoriaVeicoloNotLike(String value) {
			addCriterion("categoria_veicolo not like", value, "categoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCategoriaVeicoloIn(List<String> values) {
			addCriterion("categoria_veicolo in", values, "categoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCategoriaVeicoloNotIn(List<String> values) {
			addCriterion("categoria_veicolo not in", values, "categoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCategoriaVeicoloBetween(String value1, String value2) {
			addCriterion("categoria_veicolo between", value1, value2, "categoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCategoriaVeicoloNotBetween(String value1, String value2) {
			addCriterion("categoria_veicolo not between", value1, value2, "categoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCodCategoriaVeicoloLikeInsensitive(String value) {
			addCriterion("upper(cod_categoria_veicolo) like", value.toUpperCase(), "codCategoriaVeicolo");
			return (Criteria) this;
		}

		public Criteria andCategoriaVeicoloLikeInsensitive(String value) {
			addCriterion("upper(categoria_veicolo) like", value.toUpperCase(), "categoriaVeicolo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rebus_d_categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebus_d_categoria_veicolo
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 08 11:32:38 CET 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}