/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;
import java.math.BigDecimal;

public class RebusRUtenteAzEnteDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_r_utente_az_ente.id_r_utente_az_ente
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	private Long idRUtenteAzEnte;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_r_utente_az_ente.fk_utente
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	private Long fkUtente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_r_utente_az_ente.fk_azienda
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	private Long fkAzienda;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_r_utente_az_ente.fk_ente
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	private Long fkEnte;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_r_utente_az_ente.data_appartenenza
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	private Date dataAppartenenza;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_r_utente_az_ente.data_fine_validita
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	private Date dataFineValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebus_r_utente_az_ente
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_r_utente_az_ente.id_r_utente_az_ente
	 * @return  the value of rebus_r_utente_az_ente.id_r_utente_az_ente
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	public Long getIdRUtenteAzEnte() {
		return idRUtenteAzEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_r_utente_az_ente.id_r_utente_az_ente
	 * @param idRUtenteAzEnte  the value for rebus_r_utente_az_ente.id_r_utente_az_ente
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	public void setIdRUtenteAzEnte(Long idRUtenteAzEnte) {
		this.idRUtenteAzEnte = idRUtenteAzEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_r_utente_az_ente.fk_utente
	 * @return  the value of rebus_r_utente_az_ente.fk_utente
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	public Long getFkUtente() {
		return fkUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_r_utente_az_ente.fk_utente
	 * @param fkUtente  the value for rebus_r_utente_az_ente.fk_utente
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	public void setFkUtente(Long fkUtente) {
		this.fkUtente = fkUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_r_utente_az_ente.fk_azienda
	 * @return  the value of rebus_r_utente_az_ente.fk_azienda
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	public Long getFkAzienda() {
		return fkAzienda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_r_utente_az_ente.fk_azienda
	 * @param fkAzienda  the value for rebus_r_utente_az_ente.fk_azienda
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	public void setFkAzienda(Long fkAzienda) {
		this.fkAzienda = fkAzienda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_r_utente_az_ente.fk_ente
	 * @return  the value of rebus_r_utente_az_ente.fk_ente
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	public Long getFkEnte() {
		return fkEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_r_utente_az_ente.fk_ente
	 * @param fkEnte  the value for rebus_r_utente_az_ente.fk_ente
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	public void setFkEnte(Long fkEnte) {
		this.fkEnte = fkEnte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_r_utente_az_ente.data_appartenenza
	 * @return  the value of rebus_r_utente_az_ente.data_appartenenza
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	public Date getDataAppartenenza() {
		return dataAppartenenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_r_utente_az_ente.data_appartenenza
	 * @param dataAppartenenza  the value for rebus_r_utente_az_ente.data_appartenenza
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	public void setDataAppartenenza(Date dataAppartenenza) {
		this.dataAppartenenza = dataAppartenenza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_r_utente_az_ente.data_fine_validita
	 * @return  the value of rebus_r_utente_az_ente.data_fine_validita
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	public Date getDataFineValidita() {
		return dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_r_utente_az_ente.data_fine_validita
	 * @param dataFineValidita  the value for rebus_r_utente_az_ente.data_fine_validita
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	public void setDataFineValidita(Date dataFineValidita) {
		this.dataFineValidita = dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_utente_az_ente
	 * @mbg.generated  Wed Mar 11 13:11:14 CET 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idRUtenteAzEnte=").append(idRUtenteAzEnte);
		sb.append(", fkUtente=").append(fkUtente);
		sb.append(", fkAzienda=").append(fkAzienda);
		sb.append(", fkEnte=").append(fkEnte);
		sb.append(", dataAppartenenza=").append(dataAppartenenza);
		sb.append(", dataFineValidita=").append(dataFineValidita);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}