/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RebuscTDatoSpesaSelector {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public RebuscTDatoSpesaSelector() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdDatoSpesaIsNull() {
			addCriterion("id_dato_spesa is null");
			return (Criteria) this;
		}

		public Criteria andIdDatoSpesaIsNotNull() {
			addCriterion("id_dato_spesa is not null");
			return (Criteria) this;
		}

		public Criteria andIdDatoSpesaEqualTo(Long value) {
			addCriterion("id_dato_spesa =", value, "idDatoSpesa");
			return (Criteria) this;
		}

		public Criteria andIdDatoSpesaNotEqualTo(Long value) {
			addCriterion("id_dato_spesa <>", value, "idDatoSpesa");
			return (Criteria) this;
		}

		public Criteria andIdDatoSpesaGreaterThan(Long value) {
			addCriterion("id_dato_spesa >", value, "idDatoSpesa");
			return (Criteria) this;
		}

		public Criteria andIdDatoSpesaGreaterThanOrEqualTo(Long value) {
			addCriterion("id_dato_spesa >=", value, "idDatoSpesa");
			return (Criteria) this;
		}

		public Criteria andIdDatoSpesaLessThan(Long value) {
			addCriterion("id_dato_spesa <", value, "idDatoSpesa");
			return (Criteria) this;
		}

		public Criteria andIdDatoSpesaLessThanOrEqualTo(Long value) {
			addCriterion("id_dato_spesa <=", value, "idDatoSpesa");
			return (Criteria) this;
		}

		public Criteria andIdDatoSpesaIn(List<Long> values) {
			addCriterion("id_dato_spesa in", values, "idDatoSpesa");
			return (Criteria) this;
		}

		public Criteria andIdDatoSpesaNotIn(List<Long> values) {
			addCriterion("id_dato_spesa not in", values, "idDatoSpesa");
			return (Criteria) this;
		}

		public Criteria andIdDatoSpesaBetween(Long value1, Long value2) {
			addCriterion("id_dato_spesa between", value1, value2, "idDatoSpesa");
			return (Criteria) this;
		}

		public Criteria andIdDatoSpesaNotBetween(Long value1, Long value2) {
			addCriterion("id_dato_spesa not between", value1, value2, "idDatoSpesa");
			return (Criteria) this;
		}

		public Criteria andContributoErogabileRegIsNull() {
			addCriterion("contributo_erogabile_reg is null");
			return (Criteria) this;
		}

		public Criteria andContributoErogabileRegIsNotNull() {
			addCriterion("contributo_erogabile_reg is not null");
			return (Criteria) this;
		}

		public Criteria andContributoErogabileRegEqualTo(Double value) {
			addCriterion("contributo_erogabile_reg =", value, "contributoErogabileReg");
			return (Criteria) this;
		}

		public Criteria andContributoErogabileRegNotEqualTo(Double value) {
			addCriterion("contributo_erogabile_reg <>", value, "contributoErogabileReg");
			return (Criteria) this;
		}

		public Criteria andContributoErogabileRegGreaterThan(Double value) {
			addCriterion("contributo_erogabile_reg >", value, "contributoErogabileReg");
			return (Criteria) this;
		}

		public Criteria andContributoErogabileRegGreaterThanOrEqualTo(Double value) {
			addCriterion("contributo_erogabile_reg >=", value, "contributoErogabileReg");
			return (Criteria) this;
		}

		public Criteria andContributoErogabileRegLessThan(Double value) {
			addCriterion("contributo_erogabile_reg <", value, "contributoErogabileReg");
			return (Criteria) this;
		}

		public Criteria andContributoErogabileRegLessThanOrEqualTo(Double value) {
			addCriterion("contributo_erogabile_reg <=", value, "contributoErogabileReg");
			return (Criteria) this;
		}

		public Criteria andContributoErogabileRegIn(List<Double> values) {
			addCriterion("contributo_erogabile_reg in", values, "contributoErogabileReg");
			return (Criteria) this;
		}

		public Criteria andContributoErogabileRegNotIn(List<Double> values) {
			addCriterion("contributo_erogabile_reg not in", values, "contributoErogabileReg");
			return (Criteria) this;
		}

		public Criteria andContributoErogabileRegBetween(Double value1, Double value2) {
			addCriterion("contributo_erogabile_reg between", value1, value2, "contributoErogabileReg");
			return (Criteria) this;
		}

		public Criteria andContributoErogabileRegNotBetween(Double value1, Double value2) {
			addCriterion("contributo_erogabile_reg not between", value1, value2, "contributoErogabileReg");
			return (Criteria) this;
		}

		public Criteria andContributoRegionaleFfIsNull() {
			addCriterion("contributo_regionale_ff is null");
			return (Criteria) this;
		}

		public Criteria andContributoRegionaleFfIsNotNull() {
			addCriterion("contributo_regionale_ff is not null");
			return (Criteria) this;
		}

		public Criteria andContributoRegionaleFfEqualTo(Double value) {
			addCriterion("contributo_regionale_ff =", value, "contributoRegionaleFf");
			return (Criteria) this;
		}

		public Criteria andContributoRegionaleFfNotEqualTo(Double value) {
			addCriterion("contributo_regionale_ff <>", value, "contributoRegionaleFf");
			return (Criteria) this;
		}

		public Criteria andContributoRegionaleFfGreaterThan(Double value) {
			addCriterion("contributo_regionale_ff >", value, "contributoRegionaleFf");
			return (Criteria) this;
		}

		public Criteria andContributoRegionaleFfGreaterThanOrEqualTo(Double value) {
			addCriterion("contributo_regionale_ff >=", value, "contributoRegionaleFf");
			return (Criteria) this;
		}

		public Criteria andContributoRegionaleFfLessThan(Double value) {
			addCriterion("contributo_regionale_ff <", value, "contributoRegionaleFf");
			return (Criteria) this;
		}

		public Criteria andContributoRegionaleFfLessThanOrEqualTo(Double value) {
			addCriterion("contributo_regionale_ff <=", value, "contributoRegionaleFf");
			return (Criteria) this;
		}

		public Criteria andContributoRegionaleFfIn(List<Double> values) {
			addCriterion("contributo_regionale_ff in", values, "contributoRegionaleFf");
			return (Criteria) this;
		}

		public Criteria andContributoRegionaleFfNotIn(List<Double> values) {
			addCriterion("contributo_regionale_ff not in", values, "contributoRegionaleFf");
			return (Criteria) this;
		}

		public Criteria andContributoRegionaleFfBetween(Double value1, Double value2) {
			addCriterion("contributo_regionale_ff between", value1, value2, "contributoRegionaleFf");
			return (Criteria) this;
		}

		public Criteria andContributoRegionaleFfNotBetween(Double value1, Double value2) {
			addCriterion("contributo_regionale_ff not between", value1, value2, "contributoRegionaleFf");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpAntIsNull() {
			addCriterion("nr_atto_liquidazione_rp_amp_ant is null");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpAntIsNotNull() {
			addCriterion("nr_atto_liquidazione_rp_amp_ant is not null");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpAntEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_ant =", value, "nrAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpAntNotEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_ant <>", value, "nrAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpAntGreaterThan(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_ant >", value, "nrAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpAntGreaterThanOrEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_ant >=", value, "nrAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpAntLessThan(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_ant <", value, "nrAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpAntLessThanOrEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_ant <=", value, "nrAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpAntLike(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_ant like", value, "nrAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpAntNotLike(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_ant not like", value, "nrAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpAntIn(List<String> values) {
			addCriterion("nr_atto_liquidazione_rp_amp_ant in", values, "nrAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpAntNotIn(List<String> values) {
			addCriterion("nr_atto_liquidazione_rp_amp_ant not in", values, "nrAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpAntBetween(String value1, String value2) {
			addCriterion("nr_atto_liquidazione_rp_amp_ant between", value1, value2, "nrAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpAntNotBetween(String value1, String value2) {
			addCriterion("nr_atto_liquidazione_rp_amp_ant not between", value1, value2, "nrAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpSalIsNull() {
			addCriterion("nr_atto_liquidazione_rp_amp_sal is null");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpSalIsNotNull() {
			addCriterion("nr_atto_liquidazione_rp_amp_sal is not null");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpSalEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_sal =", value, "nrAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpSalNotEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_sal <>", value, "nrAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpSalGreaterThan(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_sal >", value, "nrAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpSalGreaterThanOrEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_sal >=", value, "nrAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpSalLessThan(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_sal <", value, "nrAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpSalLessThanOrEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_sal <=", value, "nrAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpSalLike(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_sal like", value, "nrAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpSalNotLike(String value) {
			addCriterion("nr_atto_liquidazione_rp_amp_sal not like", value, "nrAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpSalIn(List<String> values) {
			addCriterion("nr_atto_liquidazione_rp_amp_sal in", values, "nrAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpSalNotIn(List<String> values) {
			addCriterion("nr_atto_liquidazione_rp_amp_sal not in", values, "nrAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpSalBetween(String value1, String value2) {
			addCriterion("nr_atto_liquidazione_rp_amp_sal between", value1, value2, "nrAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpSalNotBetween(String value1, String value2) {
			addCriterion("nr_atto_liquidazione_rp_amp_sal not between", value1, value2, "nrAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpAntIsNull() {
			addCriterion("data_atto_liquidazione_rp_amp_ant is null");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpAntIsNotNull() {
			addCriterion("data_atto_liquidazione_rp_amp_ant is not null");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpAntEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_ant =", value, "dataAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpAntNotEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_ant <>", value, "dataAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpAntGreaterThan(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_ant >", value, "dataAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpAntGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_ant >=", value, "dataAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpAntLessThan(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_ant <", value, "dataAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpAntLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_ant <=", value, "dataAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpAntIn(List<Date> values) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_ant in", values, "dataAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpAntNotIn(List<Date> values) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_ant not in", values, "dataAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpAntBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_ant between", value1, value2,
					"dataAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpAntNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_ant not between", value1, value2,
					"dataAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpSalIsNull() {
			addCriterion("data_atto_liquidazione_rp_amp_sal is null");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpSalIsNotNull() {
			addCriterion("data_atto_liquidazione_rp_amp_sal is not null");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpSalEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_sal =", value, "dataAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpSalNotEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_sal <>", value, "dataAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpSalGreaterThan(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_sal >", value, "dataAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpSalGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_sal >=", value, "dataAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpSalLessThan(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_sal <", value, "dataAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpSalLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_sal <=", value, "dataAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpSalIn(List<Date> values) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_sal in", values, "dataAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpSalNotIn(List<Date> values) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_sal not in", values, "dataAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpSalBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_sal between", value1, value2,
					"dataAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneRpAmpSalNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_atto_liquidazione_rp_amp_sal not between", value1, value2,
					"dataAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpAntIsNull() {
			addCriterion("nr_determina_rp_amp_ant is null");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpAntIsNotNull() {
			addCriterion("nr_determina_rp_amp_ant is not null");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpAntEqualTo(String value) {
			addCriterion("nr_determina_rp_amp_ant =", value, "nrDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpAntNotEqualTo(String value) {
			addCriterion("nr_determina_rp_amp_ant <>", value, "nrDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpAntGreaterThan(String value) {
			addCriterion("nr_determina_rp_amp_ant >", value, "nrDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpAntGreaterThanOrEqualTo(String value) {
			addCriterion("nr_determina_rp_amp_ant >=", value, "nrDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpAntLessThan(String value) {
			addCriterion("nr_determina_rp_amp_ant <", value, "nrDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpAntLessThanOrEqualTo(String value) {
			addCriterion("nr_determina_rp_amp_ant <=", value, "nrDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpAntLike(String value) {
			addCriterion("nr_determina_rp_amp_ant like", value, "nrDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpAntNotLike(String value) {
			addCriterion("nr_determina_rp_amp_ant not like", value, "nrDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpAntIn(List<String> values) {
			addCriterion("nr_determina_rp_amp_ant in", values, "nrDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpAntNotIn(List<String> values) {
			addCriterion("nr_determina_rp_amp_ant not in", values, "nrDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpAntBetween(String value1, String value2) {
			addCriterion("nr_determina_rp_amp_ant between", value1, value2, "nrDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpAntNotBetween(String value1, String value2) {
			addCriterion("nr_determina_rp_amp_ant not between", value1, value2, "nrDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpSalIsNull() {
			addCriterion("nr_determina_rp_amp_sal is null");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpSalIsNotNull() {
			addCriterion("nr_determina_rp_amp_sal is not null");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpSalEqualTo(String value) {
			addCriterion("nr_determina_rp_amp_sal =", value, "nrDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpSalNotEqualTo(String value) {
			addCriterion("nr_determina_rp_amp_sal <>", value, "nrDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpSalGreaterThan(String value) {
			addCriterion("nr_determina_rp_amp_sal >", value, "nrDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpSalGreaterThanOrEqualTo(String value) {
			addCriterion("nr_determina_rp_amp_sal >=", value, "nrDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpSalLessThan(String value) {
			addCriterion("nr_determina_rp_amp_sal <", value, "nrDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpSalLessThanOrEqualTo(String value) {
			addCriterion("nr_determina_rp_amp_sal <=", value, "nrDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpSalLike(String value) {
			addCriterion("nr_determina_rp_amp_sal like", value, "nrDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpSalNotLike(String value) {
			addCriterion("nr_determina_rp_amp_sal not like", value, "nrDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpSalIn(List<String> values) {
			addCriterion("nr_determina_rp_amp_sal in", values, "nrDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpSalNotIn(List<String> values) {
			addCriterion("nr_determina_rp_amp_sal not in", values, "nrDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpSalBetween(String value1, String value2) {
			addCriterion("nr_determina_rp_amp_sal between", value1, value2, "nrDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpSalNotBetween(String value1, String value2) {
			addCriterion("nr_determina_rp_amp_sal not between", value1, value2, "nrDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpAntIsNull() {
			addCriterion("data_determina_rp_amp_ant is null");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpAntIsNotNull() {
			addCriterion("data_determina_rp_amp_ant is not null");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpAntEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_rp_amp_ant =", value, "dataDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpAntNotEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_rp_amp_ant <>", value, "dataDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpAntGreaterThan(Date value) {
			addCriterionForJDBCDate("data_determina_rp_amp_ant >", value, "dataDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpAntGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_rp_amp_ant >=", value, "dataDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpAntLessThan(Date value) {
			addCriterionForJDBCDate("data_determina_rp_amp_ant <", value, "dataDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpAntLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_rp_amp_ant <=", value, "dataDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpAntIn(List<Date> values) {
			addCriterionForJDBCDate("data_determina_rp_amp_ant in", values, "dataDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpAntNotIn(List<Date> values) {
			addCriterionForJDBCDate("data_determina_rp_amp_ant not in", values, "dataDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpAntBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_determina_rp_amp_ant between", value1, value2, "dataDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpAntNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_determina_rp_amp_ant not between", value1, value2, "dataDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpSalIsNull() {
			addCriterion("data_determina_rp_amp_sal is null");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpSalIsNotNull() {
			addCriterion("data_determina_rp_amp_sal is not null");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpSalEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_rp_amp_sal =", value, "dataDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpSalNotEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_rp_amp_sal <>", value, "dataDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpSalGreaterThan(Date value) {
			addCriterionForJDBCDate("data_determina_rp_amp_sal >", value, "dataDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpSalGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_rp_amp_sal >=", value, "dataDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpSalLessThan(Date value) {
			addCriterionForJDBCDate("data_determina_rp_amp_sal <", value, "dataDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpSalLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_rp_amp_sal <=", value, "dataDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpSalIn(List<Date> values) {
			addCriterionForJDBCDate("data_determina_rp_amp_sal in", values, "dataDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpSalNotIn(List<Date> values) {
			addCriterionForJDBCDate("data_determina_rp_amp_sal not in", values, "dataDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpSalBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_determina_rp_amp_sal between", value1, value2, "dataDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaRpAmpSalNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_determina_rp_amp_sal not between", value1, value2, "dataDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzAntIsNull() {
			addCriterion("nr_atto_liquidazione_amp_az_ant is null");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzAntIsNotNull() {
			addCriterion("nr_atto_liquidazione_amp_az_ant is not null");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzAntEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_ant =", value, "nrAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzAntNotEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_ant <>", value, "nrAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzAntGreaterThan(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_ant >", value, "nrAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzAntGreaterThanOrEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_ant >=", value, "nrAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzAntLessThan(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_ant <", value, "nrAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzAntLessThanOrEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_ant <=", value, "nrAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzAntLike(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_ant like", value, "nrAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzAntNotLike(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_ant not like", value, "nrAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzAntIn(List<String> values) {
			addCriterion("nr_atto_liquidazione_amp_az_ant in", values, "nrAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzAntNotIn(List<String> values) {
			addCriterion("nr_atto_liquidazione_amp_az_ant not in", values, "nrAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzAntBetween(String value1, String value2) {
			addCriterion("nr_atto_liquidazione_amp_az_ant between", value1, value2, "nrAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzAntNotBetween(String value1, String value2) {
			addCriterion("nr_atto_liquidazione_amp_az_ant not between", value1, value2, "nrAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzSalIsNull() {
			addCriterion("nr_atto_liquidazione_amp_az_sal is null");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzSalIsNotNull() {
			addCriterion("nr_atto_liquidazione_amp_az_sal is not null");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzSalEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_sal =", value, "nrAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzSalNotEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_sal <>", value, "nrAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzSalGreaterThan(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_sal >", value, "nrAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzSalGreaterThanOrEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_sal >=", value, "nrAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzSalLessThan(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_sal <", value, "nrAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzSalLessThanOrEqualTo(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_sal <=", value, "nrAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzSalLike(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_sal like", value, "nrAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzSalNotLike(String value) {
			addCriterion("nr_atto_liquidazione_amp_az_sal not like", value, "nrAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzSalIn(List<String> values) {
			addCriterion("nr_atto_liquidazione_amp_az_sal in", values, "nrAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzSalNotIn(List<String> values) {
			addCriterion("nr_atto_liquidazione_amp_az_sal not in", values, "nrAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzSalBetween(String value1, String value2) {
			addCriterion("nr_atto_liquidazione_amp_az_sal between", value1, value2, "nrAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzSalNotBetween(String value1, String value2) {
			addCriterion("nr_atto_liquidazione_amp_az_sal not between", value1, value2, "nrAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzAntIsNull() {
			addCriterion("data_atto_liquidazione_amp_az_ant is null");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzAntIsNotNull() {
			addCriterion("data_atto_liquidazione_amp_az_ant is not null");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzAntEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_ant =", value, "dataAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzAntNotEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_ant <>", value, "dataAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzAntGreaterThan(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_ant >", value, "dataAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzAntGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_ant >=", value, "dataAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzAntLessThan(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_ant <", value, "dataAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzAntLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_ant <=", value, "dataAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzAntIn(List<Date> values) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_ant in", values, "dataAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzAntNotIn(List<Date> values) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_ant not in", values, "dataAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzAntBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_ant between", value1, value2,
					"dataAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzAntNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_ant not between", value1, value2,
					"dataAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzSalIsNull() {
			addCriterion("data_atto_liquidazione_amp_az_sal is null");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzSalIsNotNull() {
			addCriterion("data_atto_liquidazione_amp_az_sal is not null");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzSalEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_sal =", value, "dataAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzSalNotEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_sal <>", value, "dataAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzSalGreaterThan(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_sal >", value, "dataAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzSalGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_sal >=", value, "dataAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzSalLessThan(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_sal <", value, "dataAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzSalLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_sal <=", value, "dataAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzSalIn(List<Date> values) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_sal in", values, "dataAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzSalNotIn(List<Date> values) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_sal not in", values, "dataAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzSalBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_sal between", value1, value2,
					"dataAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataAttoLiquidazioneAmpAzSalNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_atto_liquidazione_amp_az_sal not between", value1, value2,
					"dataAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzAntIsNull() {
			addCriterion("nr_determina_amp_az_ant is null");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzAntIsNotNull() {
			addCriterion("nr_determina_amp_az_ant is not null");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzAntEqualTo(String value) {
			addCriterion("nr_determina_amp_az_ant =", value, "nrDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzAntNotEqualTo(String value) {
			addCriterion("nr_determina_amp_az_ant <>", value, "nrDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzAntGreaterThan(String value) {
			addCriterion("nr_determina_amp_az_ant >", value, "nrDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzAntGreaterThanOrEqualTo(String value) {
			addCriterion("nr_determina_amp_az_ant >=", value, "nrDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzAntLessThan(String value) {
			addCriterion("nr_determina_amp_az_ant <", value, "nrDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzAntLessThanOrEqualTo(String value) {
			addCriterion("nr_determina_amp_az_ant <=", value, "nrDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzAntLike(String value) {
			addCriterion("nr_determina_amp_az_ant like", value, "nrDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzAntNotLike(String value) {
			addCriterion("nr_determina_amp_az_ant not like", value, "nrDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzAntIn(List<String> values) {
			addCriterion("nr_determina_amp_az_ant in", values, "nrDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzAntNotIn(List<String> values) {
			addCriterion("nr_determina_amp_az_ant not in", values, "nrDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzAntBetween(String value1, String value2) {
			addCriterion("nr_determina_amp_az_ant between", value1, value2, "nrDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzAntNotBetween(String value1, String value2) {
			addCriterion("nr_determina_amp_az_ant not between", value1, value2, "nrDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzSalIsNull() {
			addCriterion("nr_determina_amp_az_sal is null");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzSalIsNotNull() {
			addCriterion("nr_determina_amp_az_sal is not null");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzSalEqualTo(String value) {
			addCriterion("nr_determina_amp_az_sal =", value, "nrDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzSalNotEqualTo(String value) {
			addCriterion("nr_determina_amp_az_sal <>", value, "nrDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzSalGreaterThan(String value) {
			addCriterion("nr_determina_amp_az_sal >", value, "nrDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzSalGreaterThanOrEqualTo(String value) {
			addCriterion("nr_determina_amp_az_sal >=", value, "nrDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzSalLessThan(String value) {
			addCriterion("nr_determina_amp_az_sal <", value, "nrDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzSalLessThanOrEqualTo(String value) {
			addCriterion("nr_determina_amp_az_sal <=", value, "nrDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzSalLike(String value) {
			addCriterion("nr_determina_amp_az_sal like", value, "nrDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzSalNotLike(String value) {
			addCriterion("nr_determina_amp_az_sal not like", value, "nrDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzSalIn(List<String> values) {
			addCriterion("nr_determina_amp_az_sal in", values, "nrDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzSalNotIn(List<String> values) {
			addCriterion("nr_determina_amp_az_sal not in", values, "nrDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzSalBetween(String value1, String value2) {
			addCriterion("nr_determina_amp_az_sal between", value1, value2, "nrDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzSalNotBetween(String value1, String value2) {
			addCriterion("nr_determina_amp_az_sal not between", value1, value2, "nrDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzAntIsNull() {
			addCriterion("data_determina_amp_az_ant is null");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzAntIsNotNull() {
			addCriterion("data_determina_amp_az_ant is not null");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzAntEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_amp_az_ant =", value, "dataDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzAntNotEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_amp_az_ant <>", value, "dataDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzAntGreaterThan(Date value) {
			addCriterionForJDBCDate("data_determina_amp_az_ant >", value, "dataDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzAntGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_amp_az_ant >=", value, "dataDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzAntLessThan(Date value) {
			addCriterionForJDBCDate("data_determina_amp_az_ant <", value, "dataDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzAntLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_amp_az_ant <=", value, "dataDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzAntIn(List<Date> values) {
			addCriterionForJDBCDate("data_determina_amp_az_ant in", values, "dataDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzAntNotIn(List<Date> values) {
			addCriterionForJDBCDate("data_determina_amp_az_ant not in", values, "dataDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzAntBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_determina_amp_az_ant between", value1, value2, "dataDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzAntNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_determina_amp_az_ant not between", value1, value2, "dataDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzSalIsNull() {
			addCriterion("data_determina_amp_az_sal is null");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzSalIsNotNull() {
			addCriterion("data_determina_amp_az_sal is not null");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzSalEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_amp_az_sal =", value, "dataDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzSalNotEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_amp_az_sal <>", value, "dataDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzSalGreaterThan(Date value) {
			addCriterionForJDBCDate("data_determina_amp_az_sal >", value, "dataDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzSalGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_amp_az_sal >=", value, "dataDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzSalLessThan(Date value) {
			addCriterionForJDBCDate("data_determina_amp_az_sal <", value, "dataDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzSalLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("data_determina_amp_az_sal <=", value, "dataDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzSalIn(List<Date> values) {
			addCriterionForJDBCDate("data_determina_amp_az_sal in", values, "dataDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzSalNotIn(List<Date> values) {
			addCriterionForJDBCDate("data_determina_amp_az_sal not in", values, "dataDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzSalBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_determina_amp_az_sal between", value1, value2, "dataDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andDataDeterminaAmpAzSalNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("data_determina_amp_az_sal not between", value1, value2, "dataDeterminaAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andImportoAnticipoIsNull() {
			addCriterion("importo_anticipo is null");
			return (Criteria) this;
		}

		public Criteria andImportoAnticipoIsNotNull() {
			addCriterion("importo_anticipo is not null");
			return (Criteria) this;
		}

		public Criteria andImportoAnticipoEqualTo(Double value) {
			addCriterion("importo_anticipo =", value, "importoAnticipo");
			return (Criteria) this;
		}

		public Criteria andImportoAnticipoNotEqualTo(Double value) {
			addCriterion("importo_anticipo <>", value, "importoAnticipo");
			return (Criteria) this;
		}

		public Criteria andImportoAnticipoGreaterThan(Double value) {
			addCriterion("importo_anticipo >", value, "importoAnticipo");
			return (Criteria) this;
		}

		public Criteria andImportoAnticipoGreaterThanOrEqualTo(Double value) {
			addCriterion("importo_anticipo >=", value, "importoAnticipo");
			return (Criteria) this;
		}

		public Criteria andImportoAnticipoLessThan(Double value) {
			addCriterion("importo_anticipo <", value, "importoAnticipo");
			return (Criteria) this;
		}

		public Criteria andImportoAnticipoLessThanOrEqualTo(Double value) {
			addCriterion("importo_anticipo <=", value, "importoAnticipo");
			return (Criteria) this;
		}

		public Criteria andImportoAnticipoIn(List<Double> values) {
			addCriterion("importo_anticipo in", values, "importoAnticipo");
			return (Criteria) this;
		}

		public Criteria andImportoAnticipoNotIn(List<Double> values) {
			addCriterion("importo_anticipo not in", values, "importoAnticipo");
			return (Criteria) this;
		}

		public Criteria andImportoAnticipoBetween(Double value1, Double value2) {
			addCriterion("importo_anticipo between", value1, value2, "importoAnticipo");
			return (Criteria) this;
		}

		public Criteria andImportoAnticipoNotBetween(Double value1, Double value2) {
			addCriterion("importo_anticipo not between", value1, value2, "importoAnticipo");
			return (Criteria) this;
		}

		public Criteria andImportoSaldoIsNull() {
			addCriterion("importo_saldo is null");
			return (Criteria) this;
		}

		public Criteria andImportoSaldoIsNotNull() {
			addCriterion("importo_saldo is not null");
			return (Criteria) this;
		}

		public Criteria andImportoSaldoEqualTo(Double value) {
			addCriterion("importo_saldo =", value, "importoSaldo");
			return (Criteria) this;
		}

		public Criteria andImportoSaldoNotEqualTo(Double value) {
			addCriterion("importo_saldo <>", value, "importoSaldo");
			return (Criteria) this;
		}

		public Criteria andImportoSaldoGreaterThan(Double value) {
			addCriterion("importo_saldo >", value, "importoSaldo");
			return (Criteria) this;
		}

		public Criteria andImportoSaldoGreaterThanOrEqualTo(Double value) {
			addCriterion("importo_saldo >=", value, "importoSaldo");
			return (Criteria) this;
		}

		public Criteria andImportoSaldoLessThan(Double value) {
			addCriterion("importo_saldo <", value, "importoSaldo");
			return (Criteria) this;
		}

		public Criteria andImportoSaldoLessThanOrEqualTo(Double value) {
			addCriterion("importo_saldo <=", value, "importoSaldo");
			return (Criteria) this;
		}

		public Criteria andImportoSaldoIn(List<Double> values) {
			addCriterion("importo_saldo in", values, "importoSaldo");
			return (Criteria) this;
		}

		public Criteria andImportoSaldoNotIn(List<Double> values) {
			addCriterion("importo_saldo not in", values, "importoSaldo");
			return (Criteria) this;
		}

		public Criteria andImportoSaldoBetween(Double value1, Double value2) {
			addCriterion("importo_saldo between", value1, value2, "importoSaldo");
			return (Criteria) this;
		}

		public Criteria andImportoSaldoNotBetween(Double value1, Double value2) {
			addCriterion("importo_saldo not between", value1, value2, "importoSaldo");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoIsNull() {
			addCriterion("id_utente_aggiornamento is null");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoIsNotNull() {
			addCriterion("id_utente_aggiornamento is not null");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento =", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoNotEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento <>", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoGreaterThan(Long value) {
			addCriterion("id_utente_aggiornamento >", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoGreaterThanOrEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento >=", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoLessThan(Long value) {
			addCriterion("id_utente_aggiornamento <", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoLessThanOrEqualTo(Long value) {
			addCriterion("id_utente_aggiornamento <=", value, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoIn(List<Long> values) {
			addCriterion("id_utente_aggiornamento in", values, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoNotIn(List<Long> values) {
			addCriterion("id_utente_aggiornamento not in", values, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoBetween(Long value1, Long value2) {
			addCriterion("id_utente_aggiornamento between", value1, value2, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andIdUtenteAggiornamentoNotBetween(Long value1, Long value2) {
			addCriterion("id_utente_aggiornamento not between", value1, value2, "idUtenteAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoIsNull() {
			addCriterion("data_aggiornamento is null");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoIsNotNull() {
			addCriterion("data_aggiornamento is not null");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoEqualTo(Date value) {
			addCriterion("data_aggiornamento =", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoNotEqualTo(Date value) {
			addCriterion("data_aggiornamento <>", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoGreaterThan(Date value) {
			addCriterion("data_aggiornamento >", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoGreaterThanOrEqualTo(Date value) {
			addCriterion("data_aggiornamento >=", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoLessThan(Date value) {
			addCriterion("data_aggiornamento <", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoLessThanOrEqualTo(Date value) {
			addCriterion("data_aggiornamento <=", value, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoIn(List<Date> values) {
			addCriterion("data_aggiornamento in", values, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoNotIn(List<Date> values) {
			addCriterion("data_aggiornamento not in", values, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoBetween(Date value1, Date value2) {
			addCriterion("data_aggiornamento between", value1, value2, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andDataAggiornamentoNotBetween(Date value1, Date value2) {
			addCriterion("data_aggiornamento not between", value1, value2, "dataAggiornamento");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpAntLikeInsensitive(String value) {
			addCriterion("upper(nr_atto_liquidazione_rp_amp_ant) like", value.toUpperCase(),
					"nrAttoLiquidazioneRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneRpAmpSalLikeInsensitive(String value) {
			addCriterion("upper(nr_atto_liquidazione_rp_amp_sal) like", value.toUpperCase(),
					"nrAttoLiquidazioneRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpAntLikeInsensitive(String value) {
			addCriterion("upper(nr_determina_rp_amp_ant) like", value.toUpperCase(), "nrDeterminaRpAmpAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaRpAmpSalLikeInsensitive(String value) {
			addCriterion("upper(nr_determina_rp_amp_sal) like", value.toUpperCase(), "nrDeterminaRpAmpSal");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzAntLikeInsensitive(String value) {
			addCriterion("upper(nr_atto_liquidazione_amp_az_ant) like", value.toUpperCase(),
					"nrAttoLiquidazioneAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrAttoLiquidazioneAmpAzSalLikeInsensitive(String value) {
			addCriterion("upper(nr_atto_liquidazione_amp_az_sal) like", value.toUpperCase(),
					"nrAttoLiquidazioneAmpAzSal");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzAntLikeInsensitive(String value) {
			addCriterion("upper(nr_determina_amp_az_ant) like", value.toUpperCase(), "nrDeterminaAmpAzAnt");
			return (Criteria) this;
		}

		public Criteria andNrDeterminaAmpAzSalLikeInsensitive(String value) {
			addCriterion("upper(nr_determina_amp_az_sal) like", value.toUpperCase(), "nrDeterminaAmpAzSal");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebusc_t_dato_spesa
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 24 17:18:29 CET 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}