/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;

public class RebusDTipoMessaggioSistemaDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebus_d_tipo_messaggio_sistema.id_tipo_messaggio_sistema
     *
     * @mbg.generated Thu Nov 05 12:18:32 CET 2020
     */
    private Long idTipoMessaggioSistema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebus_d_tipo_messaggio_sistema.testo
     *
     * @mbg.generated Thu Nov 05 12:18:32 CET 2020
     */
    private String testo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebus_d_tipo_messaggio_sistema
     *
     * @mbg.generated Thu Nov 05 12:18:32 CET 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebus_d_tipo_messaggio_sistema.id_tipo_messaggio_sistema
     *
     * @return the value of rebus_d_tipo_messaggio_sistema.id_tipo_messaggio_sistema
     *
     * @mbg.generated Thu Nov 05 12:18:32 CET 2020
     */
    public Long getIdTipoMessaggioSistema() {
        return idTipoMessaggioSistema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebus_d_tipo_messaggio_sistema.id_tipo_messaggio_sistema
     *
     * @param idTipoMessaggioSistema the value for rebus_d_tipo_messaggio_sistema.id_tipo_messaggio_sistema
     *
     * @mbg.generated Thu Nov 05 12:18:32 CET 2020
     */
    public void setIdTipoMessaggioSistema(Long idTipoMessaggioSistema) {
        this.idTipoMessaggioSistema = idTipoMessaggioSistema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebus_d_tipo_messaggio_sistema.testo
     *
     * @return the value of rebus_d_tipo_messaggio_sistema.testo
     *
     * @mbg.generated Thu Nov 05 12:18:32 CET 2020
     */
    public String getTesto() {
        return testo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebus_d_tipo_messaggio_sistema.testo
     *
     * @param testo the value for rebus_d_tipo_messaggio_sistema.testo
     *
     * @mbg.generated Thu Nov 05 12:18:32 CET 2020
     */
    public void setTesto(String testo) {
        this.testo = testo == null ? null : testo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebus_d_tipo_messaggio_sistema
     *
     * @mbg.generated Thu Nov 05 12:18:32 CET 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idTipoMessaggioSistema=").append(idTipoMessaggioSistema);
        sb.append(", testo=").append(testo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}