/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebuspDTipoStampaDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_d_tipo_stampa.id_tipo_stampa
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    private Long idTipoStampa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_d_tipo_stampa.descrizione
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    private String descrizione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_d_tipo_stampa.data_inizio_validita
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    private Date dataInizioValidita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_d_tipo_stampa.data_fine_validita
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    private Date dataFineValidita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_d_tipo_stampa.template
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    private byte[] template;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusp_d_tipo_stampa
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_d_tipo_stampa.id_tipo_stampa
     *
     * @return the value of rebusp_d_tipo_stampa.id_tipo_stampa
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    public Long getIdTipoStampa() {
        return idTipoStampa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_d_tipo_stampa.id_tipo_stampa
     *
     * @param idTipoStampa the value for rebusp_d_tipo_stampa.id_tipo_stampa
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    public void setIdTipoStampa(Long idTipoStampa) {
        this.idTipoStampa = idTipoStampa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_d_tipo_stampa.descrizione
     *
     * @return the value of rebusp_d_tipo_stampa.descrizione
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_d_tipo_stampa.descrizione
     *
     * @param descrizione the value for rebusp_d_tipo_stampa.descrizione
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione == null ? null : descrizione.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_d_tipo_stampa.data_inizio_validita
     *
     * @return the value of rebusp_d_tipo_stampa.data_inizio_validita
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    public Date getDataInizioValidita() {
        return dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_d_tipo_stampa.data_inizio_validita
     *
     * @param dataInizioValidita the value for rebusp_d_tipo_stampa.data_inizio_validita
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    public void setDataInizioValidita(Date dataInizioValidita) {
        this.dataInizioValidita = dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_d_tipo_stampa.data_fine_validita
     *
     * @return the value of rebusp_d_tipo_stampa.data_fine_validita
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    public Date getDataFineValidita() {
        return dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_d_tipo_stampa.data_fine_validita
     *
     * @param dataFineValidita the value for rebusp_d_tipo_stampa.data_fine_validita
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    public void setDataFineValidita(Date dataFineValidita) {
        this.dataFineValidita = dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_d_tipo_stampa.template
     *
     * @return the value of rebusp_d_tipo_stampa.template
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    public byte[] getTemplate() {
        return template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_d_tipo_stampa.template
     *
     * @param template the value for rebusp_d_tipo_stampa.template
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    public void setTemplate(byte[] template) {
        this.template = template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_d_tipo_stampa
     *
     * @mbg.generated Tue Mar 03 17:30:32 CET 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idTipoStampa=").append(idTipoStampa);
        sb.append(", descrizione=").append(descrizione);
        sb.append(", dataInizioValidita=").append(dataInizioValidita);
        sb.append(", dataFineValidita=").append(dataFineValidita);
        sb.append(", template=").append(template);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}