/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebusmTMisurazioneDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_t_misurazione.id_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    private Long idMisurazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_t_misurazione.primo_telaio
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    private String primoTelaio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_t_misurazione.id_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    private Long idDocMisurazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_t_misurazione.data_inizio
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    private Date dataInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_t_misurazione.data_fine
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    private Date dataFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_t_misurazione.id_utente_aggiornamento
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    private Long idUtenteAggiornamento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_t_misurazione.data_aggiornamento
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    private Date dataAggiornamento;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_t_misurazione.id_misurazione
     *
     * @return the value of rebusm_t_misurazione.id_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public Long getIdMisurazione() {
        return idMisurazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_t_misurazione.id_misurazione
     *
     * @param idMisurazione the value for rebusm_t_misurazione.id_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public void setIdMisurazione(Long idMisurazione) {
        this.idMisurazione = idMisurazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_t_misurazione.primo_telaio
     *
     * @return the value of rebusm_t_misurazione.primo_telaio
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public String getPrimoTelaio() {
        return primoTelaio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_t_misurazione.primo_telaio
     *
     * @param primoTelaio the value for rebusm_t_misurazione.primo_telaio
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public void setPrimoTelaio(String primoTelaio) {
        this.primoTelaio = primoTelaio == null ? null : primoTelaio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_t_misurazione.id_doc_misurazione
     *
     * @return the value of rebusm_t_misurazione.id_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public Long getIdDocMisurazione() {
        return idDocMisurazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_t_misurazione.id_doc_misurazione
     *
     * @param idDocMisurazione the value for rebusm_t_misurazione.id_doc_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public void setIdDocMisurazione(Long idDocMisurazione) {
        this.idDocMisurazione = idDocMisurazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_t_misurazione.data_inizio
     *
     * @return the value of rebusm_t_misurazione.data_inizio
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public Date getDataInizio() {
        return dataInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_t_misurazione.data_inizio
     *
     * @param dataInizio the value for rebusm_t_misurazione.data_inizio
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public void setDataInizio(Date dataInizio) {
        this.dataInizio = dataInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_t_misurazione.data_fine
     *
     * @return the value of rebusm_t_misurazione.data_fine
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public Date getDataFine() {
        return dataFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_t_misurazione.data_fine
     *
     * @param dataFine the value for rebusm_t_misurazione.data_fine
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public void setDataFine(Date dataFine) {
        this.dataFine = dataFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_t_misurazione.id_utente_aggiornamento
     *
     * @return the value of rebusm_t_misurazione.id_utente_aggiornamento
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public Long getIdUtenteAggiornamento() {
        return idUtenteAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_t_misurazione.id_utente_aggiornamento
     *
     * @param idUtenteAggiornamento the value for rebusm_t_misurazione.id_utente_aggiornamento
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public void setIdUtenteAggiornamento(Long idUtenteAggiornamento) {
        this.idUtenteAggiornamento = idUtenteAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_t_misurazione.data_aggiornamento
     *
     * @return the value of rebusm_t_misurazione.data_aggiornamento
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public Date getDataAggiornamento() {
        return dataAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_t_misurazione.data_aggiornamento
     *
     * @param dataAggiornamento the value for rebusm_t_misurazione.data_aggiornamento
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    public void setDataAggiornamento(Date dataAggiornamento) {
        this.dataAggiornamento = dataAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idMisurazione=").append(idMisurazione);
        sb.append(", primoTelaio=").append(primoTelaio);
        sb.append(", idDocMisurazione=").append(idDocMisurazione);
        sb.append(", dataInizio=").append(dataInizio);
        sb.append(", dataFine=").append(dataFine);
        sb.append(", idUtenteAggiornamento=").append(idUtenteAggiornamento);
        sb.append(", dataAggiornamento=").append(dataAggiornamento);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}