/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebuscTDatoSpesaDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.id_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Long idDatoSpesa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.contributo_erogabile_reg
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Double contributoErogabileReg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.contributo_regionale_ff
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Double contributoRegionaleFf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.nr_atto_liquidazione_rp_amp_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private String nrAttoLiquidazioneRpAmpAnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.nr_atto_liquidazione_rp_amp_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private String nrAttoLiquidazioneRpAmpSal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.data_atto_liquidazione_rp_amp_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Date dataAttoLiquidazioneRpAmpAnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.data_atto_liquidazione_rp_amp_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Date dataAttoLiquidazioneRpAmpSal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.nr_determina_rp_amp_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private String nrDeterminaRpAmpAnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.nr_determina_rp_amp_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private String nrDeterminaRpAmpSal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.data_determina_rp_amp_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Date dataDeterminaRpAmpAnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.data_determina_rp_amp_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Date dataDeterminaRpAmpSal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.nr_atto_liquidazione_amp_az_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private String nrAttoLiquidazioneAmpAzAnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.nr_atto_liquidazione_amp_az_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private String nrAttoLiquidazioneAmpAzSal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.data_atto_liquidazione_amp_az_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Date dataAttoLiquidazioneAmpAzAnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.data_atto_liquidazione_amp_az_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Date dataAttoLiquidazioneAmpAzSal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.nr_determina_amp_az_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private String nrDeterminaAmpAzAnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.nr_determina_amp_az_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private String nrDeterminaAmpAzSal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.data_determina_amp_az_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Date dataDeterminaAmpAzAnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.data_determina_amp_az_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Date dataDeterminaAmpAzSal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.importo_anticipo
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Double importoAnticipo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.importo_saldo
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Double importoSaldo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.id_utente_aggiornamento
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Long idUtenteAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusc_t_dato_spesa.data_aggiornamento
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.id_dato_spesa
	 * @return  the value of rebusc_t_dato_spesa.id_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Long getIdDatoSpesa() {
		return idDatoSpesa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.id_dato_spesa
	 * @param idDatoSpesa  the value for rebusc_t_dato_spesa.id_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setIdDatoSpesa(Long idDatoSpesa) {
		this.idDatoSpesa = idDatoSpesa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.contributo_erogabile_reg
	 * @return  the value of rebusc_t_dato_spesa.contributo_erogabile_reg
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Double getContributoErogabileReg() {
		return contributoErogabileReg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.contributo_erogabile_reg
	 * @param contributoErogabileReg  the value for rebusc_t_dato_spesa.contributo_erogabile_reg
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setContributoErogabileReg(Double contributoErogabileReg) {
		this.contributoErogabileReg = contributoErogabileReg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.contributo_regionale_ff
	 * @return  the value of rebusc_t_dato_spesa.contributo_regionale_ff
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Double getContributoRegionaleFf() {
		return contributoRegionaleFf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.contributo_regionale_ff
	 * @param contributoRegionaleFf  the value for rebusc_t_dato_spesa.contributo_regionale_ff
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setContributoRegionaleFf(Double contributoRegionaleFf) {
		this.contributoRegionaleFf = contributoRegionaleFf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.nr_atto_liquidazione_rp_amp_ant
	 * @return  the value of rebusc_t_dato_spesa.nr_atto_liquidazione_rp_amp_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public String getNrAttoLiquidazioneRpAmpAnt() {
		return nrAttoLiquidazioneRpAmpAnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.nr_atto_liquidazione_rp_amp_ant
	 * @param nrAttoLiquidazioneRpAmpAnt  the value for rebusc_t_dato_spesa.nr_atto_liquidazione_rp_amp_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setNrAttoLiquidazioneRpAmpAnt(String nrAttoLiquidazioneRpAmpAnt) {
		this.nrAttoLiquidazioneRpAmpAnt = nrAttoLiquidazioneRpAmpAnt == null ? null : nrAttoLiquidazioneRpAmpAnt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.nr_atto_liquidazione_rp_amp_sal
	 * @return  the value of rebusc_t_dato_spesa.nr_atto_liquidazione_rp_amp_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public String getNrAttoLiquidazioneRpAmpSal() {
		return nrAttoLiquidazioneRpAmpSal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.nr_atto_liquidazione_rp_amp_sal
	 * @param nrAttoLiquidazioneRpAmpSal  the value for rebusc_t_dato_spesa.nr_atto_liquidazione_rp_amp_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setNrAttoLiquidazioneRpAmpSal(String nrAttoLiquidazioneRpAmpSal) {
		this.nrAttoLiquidazioneRpAmpSal = nrAttoLiquidazioneRpAmpSal == null ? null : nrAttoLiquidazioneRpAmpSal.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.data_atto_liquidazione_rp_amp_ant
	 * @return  the value of rebusc_t_dato_spesa.data_atto_liquidazione_rp_amp_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Date getDataAttoLiquidazioneRpAmpAnt() {
		return dataAttoLiquidazioneRpAmpAnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.data_atto_liquidazione_rp_amp_ant
	 * @param dataAttoLiquidazioneRpAmpAnt  the value for rebusc_t_dato_spesa.data_atto_liquidazione_rp_amp_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setDataAttoLiquidazioneRpAmpAnt(Date dataAttoLiquidazioneRpAmpAnt) {
		this.dataAttoLiquidazioneRpAmpAnt = dataAttoLiquidazioneRpAmpAnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.data_atto_liquidazione_rp_amp_sal
	 * @return  the value of rebusc_t_dato_spesa.data_atto_liquidazione_rp_amp_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Date getDataAttoLiquidazioneRpAmpSal() {
		return dataAttoLiquidazioneRpAmpSal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.data_atto_liquidazione_rp_amp_sal
	 * @param dataAttoLiquidazioneRpAmpSal  the value for rebusc_t_dato_spesa.data_atto_liquidazione_rp_amp_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setDataAttoLiquidazioneRpAmpSal(Date dataAttoLiquidazioneRpAmpSal) {
		this.dataAttoLiquidazioneRpAmpSal = dataAttoLiquidazioneRpAmpSal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.nr_determina_rp_amp_ant
	 * @return  the value of rebusc_t_dato_spesa.nr_determina_rp_amp_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public String getNrDeterminaRpAmpAnt() {
		return nrDeterminaRpAmpAnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.nr_determina_rp_amp_ant
	 * @param nrDeterminaRpAmpAnt  the value for rebusc_t_dato_spesa.nr_determina_rp_amp_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setNrDeterminaRpAmpAnt(String nrDeterminaRpAmpAnt) {
		this.nrDeterminaRpAmpAnt = nrDeterminaRpAmpAnt == null ? null : nrDeterminaRpAmpAnt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.nr_determina_rp_amp_sal
	 * @return  the value of rebusc_t_dato_spesa.nr_determina_rp_amp_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public String getNrDeterminaRpAmpSal() {
		return nrDeterminaRpAmpSal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.nr_determina_rp_amp_sal
	 * @param nrDeterminaRpAmpSal  the value for rebusc_t_dato_spesa.nr_determina_rp_amp_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setNrDeterminaRpAmpSal(String nrDeterminaRpAmpSal) {
		this.nrDeterminaRpAmpSal = nrDeterminaRpAmpSal == null ? null : nrDeterminaRpAmpSal.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.data_determina_rp_amp_ant
	 * @return  the value of rebusc_t_dato_spesa.data_determina_rp_amp_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Date getDataDeterminaRpAmpAnt() {
		return dataDeterminaRpAmpAnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.data_determina_rp_amp_ant
	 * @param dataDeterminaRpAmpAnt  the value for rebusc_t_dato_spesa.data_determina_rp_amp_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setDataDeterminaRpAmpAnt(Date dataDeterminaRpAmpAnt) {
		this.dataDeterminaRpAmpAnt = dataDeterminaRpAmpAnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.data_determina_rp_amp_sal
	 * @return  the value of rebusc_t_dato_spesa.data_determina_rp_amp_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Date getDataDeterminaRpAmpSal() {
		return dataDeterminaRpAmpSal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.data_determina_rp_amp_sal
	 * @param dataDeterminaRpAmpSal  the value for rebusc_t_dato_spesa.data_determina_rp_amp_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setDataDeterminaRpAmpSal(Date dataDeterminaRpAmpSal) {
		this.dataDeterminaRpAmpSal = dataDeterminaRpAmpSal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.nr_atto_liquidazione_amp_az_ant
	 * @return  the value of rebusc_t_dato_spesa.nr_atto_liquidazione_amp_az_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public String getNrAttoLiquidazioneAmpAzAnt() {
		return nrAttoLiquidazioneAmpAzAnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.nr_atto_liquidazione_amp_az_ant
	 * @param nrAttoLiquidazioneAmpAzAnt  the value for rebusc_t_dato_spesa.nr_atto_liquidazione_amp_az_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setNrAttoLiquidazioneAmpAzAnt(String nrAttoLiquidazioneAmpAzAnt) {
		this.nrAttoLiquidazioneAmpAzAnt = nrAttoLiquidazioneAmpAzAnt == null ? null : nrAttoLiquidazioneAmpAzAnt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.nr_atto_liquidazione_amp_az_sal
	 * @return  the value of rebusc_t_dato_spesa.nr_atto_liquidazione_amp_az_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public String getNrAttoLiquidazioneAmpAzSal() {
		return nrAttoLiquidazioneAmpAzSal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.nr_atto_liquidazione_amp_az_sal
	 * @param nrAttoLiquidazioneAmpAzSal  the value for rebusc_t_dato_spesa.nr_atto_liquidazione_amp_az_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setNrAttoLiquidazioneAmpAzSal(String nrAttoLiquidazioneAmpAzSal) {
		this.nrAttoLiquidazioneAmpAzSal = nrAttoLiquidazioneAmpAzSal == null ? null : nrAttoLiquidazioneAmpAzSal.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.data_atto_liquidazione_amp_az_ant
	 * @return  the value of rebusc_t_dato_spesa.data_atto_liquidazione_amp_az_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Date getDataAttoLiquidazioneAmpAzAnt() {
		return dataAttoLiquidazioneAmpAzAnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.data_atto_liquidazione_amp_az_ant
	 * @param dataAttoLiquidazioneAmpAzAnt  the value for rebusc_t_dato_spesa.data_atto_liquidazione_amp_az_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setDataAttoLiquidazioneAmpAzAnt(Date dataAttoLiquidazioneAmpAzAnt) {
		this.dataAttoLiquidazioneAmpAzAnt = dataAttoLiquidazioneAmpAzAnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.data_atto_liquidazione_amp_az_sal
	 * @return  the value of rebusc_t_dato_spesa.data_atto_liquidazione_amp_az_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Date getDataAttoLiquidazioneAmpAzSal() {
		return dataAttoLiquidazioneAmpAzSal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.data_atto_liquidazione_amp_az_sal
	 * @param dataAttoLiquidazioneAmpAzSal  the value for rebusc_t_dato_spesa.data_atto_liquidazione_amp_az_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setDataAttoLiquidazioneAmpAzSal(Date dataAttoLiquidazioneAmpAzSal) {
		this.dataAttoLiquidazioneAmpAzSal = dataAttoLiquidazioneAmpAzSal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.nr_determina_amp_az_ant
	 * @return  the value of rebusc_t_dato_spesa.nr_determina_amp_az_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public String getNrDeterminaAmpAzAnt() {
		return nrDeterminaAmpAzAnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.nr_determina_amp_az_ant
	 * @param nrDeterminaAmpAzAnt  the value for rebusc_t_dato_spesa.nr_determina_amp_az_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setNrDeterminaAmpAzAnt(String nrDeterminaAmpAzAnt) {
		this.nrDeterminaAmpAzAnt = nrDeterminaAmpAzAnt == null ? null : nrDeterminaAmpAzAnt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.nr_determina_amp_az_sal
	 * @return  the value of rebusc_t_dato_spesa.nr_determina_amp_az_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public String getNrDeterminaAmpAzSal() {
		return nrDeterminaAmpAzSal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.nr_determina_amp_az_sal
	 * @param nrDeterminaAmpAzSal  the value for rebusc_t_dato_spesa.nr_determina_amp_az_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setNrDeterminaAmpAzSal(String nrDeterminaAmpAzSal) {
		this.nrDeterminaAmpAzSal = nrDeterminaAmpAzSal == null ? null : nrDeterminaAmpAzSal.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.data_determina_amp_az_ant
	 * @return  the value of rebusc_t_dato_spesa.data_determina_amp_az_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Date getDataDeterminaAmpAzAnt() {
		return dataDeterminaAmpAzAnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.data_determina_amp_az_ant
	 * @param dataDeterminaAmpAzAnt  the value for rebusc_t_dato_spesa.data_determina_amp_az_ant
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setDataDeterminaAmpAzAnt(Date dataDeterminaAmpAzAnt) {
		this.dataDeterminaAmpAzAnt = dataDeterminaAmpAzAnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.data_determina_amp_az_sal
	 * @return  the value of rebusc_t_dato_spesa.data_determina_amp_az_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Date getDataDeterminaAmpAzSal() {
		return dataDeterminaAmpAzSal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.data_determina_amp_az_sal
	 * @param dataDeterminaAmpAzSal  the value for rebusc_t_dato_spesa.data_determina_amp_az_sal
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setDataDeterminaAmpAzSal(Date dataDeterminaAmpAzSal) {
		this.dataDeterminaAmpAzSal = dataDeterminaAmpAzSal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.importo_anticipo
	 * @return  the value of rebusc_t_dato_spesa.importo_anticipo
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Double getImportoAnticipo() {
		return importoAnticipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.importo_anticipo
	 * @param importoAnticipo  the value for rebusc_t_dato_spesa.importo_anticipo
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setImportoAnticipo(Double importoAnticipo) {
		this.importoAnticipo = importoAnticipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.importo_saldo
	 * @return  the value of rebusc_t_dato_spesa.importo_saldo
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Double getImportoSaldo() {
		return importoSaldo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.importo_saldo
	 * @param importoSaldo  the value for rebusc_t_dato_spesa.importo_saldo
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setImportoSaldo(Double importoSaldo) {
		this.importoSaldo = importoSaldo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.id_utente_aggiornamento
	 * @return  the value of rebusc_t_dato_spesa.id_utente_aggiornamento
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Long getIdUtenteAggiornamento() {
		return idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.id_utente_aggiornamento
	 * @param idUtenteAggiornamento  the value for rebusc_t_dato_spesa.id_utente_aggiornamento
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setIdUtenteAggiornamento(Long idUtenteAggiornamento) {
		this.idUtenteAggiornamento = idUtenteAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusc_t_dato_spesa.data_aggiornamento
	 * @return  the value of rebusc_t_dato_spesa.data_aggiornamento
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusc_t_dato_spesa.data_aggiornamento
	 * @param dataAggiornamento  the value for rebusc_t_dato_spesa.data_aggiornamento
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_dato_spesa
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idDatoSpesa=").append(idDatoSpesa);
		sb.append(", contributoErogabileReg=").append(contributoErogabileReg);
		sb.append(", contributoRegionaleFf=").append(contributoRegionaleFf);
		sb.append(", nrAttoLiquidazioneRpAmpAnt=").append(nrAttoLiquidazioneRpAmpAnt);
		sb.append(", nrAttoLiquidazioneRpAmpSal=").append(nrAttoLiquidazioneRpAmpSal);
		sb.append(", dataAttoLiquidazioneRpAmpAnt=").append(dataAttoLiquidazioneRpAmpAnt);
		sb.append(", dataAttoLiquidazioneRpAmpSal=").append(dataAttoLiquidazioneRpAmpSal);
		sb.append(", nrDeterminaRpAmpAnt=").append(nrDeterminaRpAmpAnt);
		sb.append(", nrDeterminaRpAmpSal=").append(nrDeterminaRpAmpSal);
		sb.append(", dataDeterminaRpAmpAnt=").append(dataDeterminaRpAmpAnt);
		sb.append(", dataDeterminaRpAmpSal=").append(dataDeterminaRpAmpSal);
		sb.append(", nrAttoLiquidazioneAmpAzAnt=").append(nrAttoLiquidazioneAmpAzAnt);
		sb.append(", nrAttoLiquidazioneAmpAzSal=").append(nrAttoLiquidazioneAmpAzSal);
		sb.append(", dataAttoLiquidazioneAmpAzAnt=").append(dataAttoLiquidazioneAmpAzAnt);
		sb.append(", dataAttoLiquidazioneAmpAzSal=").append(dataAttoLiquidazioneAmpAzSal);
		sb.append(", nrDeterminaAmpAzAnt=").append(nrDeterminaAmpAzAnt);
		sb.append(", nrDeterminaAmpAzSal=").append(nrDeterminaAmpAzSal);
		sb.append(", dataDeterminaAmpAzAnt=").append(dataDeterminaAmpAzAnt);
		sb.append(", dataDeterminaAmpAzSal=").append(dataDeterminaAmpAzSal);
		sb.append(", importoAnticipo=").append(importoAnticipo);
		sb.append(", importoSaldo=").append(importoSaldo);
		sb.append(", idUtenteAggiornamento=").append(idUtenteAggiornamento);
		sb.append(", dataAggiornamento=").append(dataAggiornamento);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}