/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebuspDStatoIterDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_d_stato_iter.id_stato_iter
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    private Long idStatoIter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_d_stato_iter.desc_stato_iter
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    private String descStatoIter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_d_stato_iter.data_inizio_validita
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    private Date dataInizioValidita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_d_stato_iter.data_fine_validita
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    private Date dataFineValidita;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusp_d_stato_iter
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_d_stato_iter.id_stato_iter
     *
     * @return the value of rebusp_d_stato_iter.id_stato_iter
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public Long getIdStatoIter() {
        return idStatoIter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_d_stato_iter.id_stato_iter
     *
     * @param idStatoIter the value for rebusp_d_stato_iter.id_stato_iter
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public void setIdStatoIter(Long idStatoIter) {
        this.idStatoIter = idStatoIter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_d_stato_iter.desc_stato_iter
     *
     * @return the value of rebusp_d_stato_iter.desc_stato_iter
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public String getDescStatoIter() {
        return descStatoIter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_d_stato_iter.desc_stato_iter
     *
     * @param descStatoIter the value for rebusp_d_stato_iter.desc_stato_iter
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public void setDescStatoIter(String descStatoIter) {
        this.descStatoIter = descStatoIter == null ? null : descStatoIter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_d_stato_iter.data_inizio_validita
     *
     * @return the value of rebusp_d_stato_iter.data_inizio_validita
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public Date getDataInizioValidita() {
        return dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_d_stato_iter.data_inizio_validita
     *
     * @param dataInizioValidita the value for rebusp_d_stato_iter.data_inizio_validita
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public void setDataInizioValidita(Date dataInizioValidita) {
        this.dataInizioValidita = dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_d_stato_iter.data_fine_validita
     *
     * @return the value of rebusp_d_stato_iter.data_fine_validita
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public Date getDataFineValidita() {
        return dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_d_stato_iter.data_fine_validita
     *
     * @param dataFineValidita the value for rebusp_d_stato_iter.data_fine_validita
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    public void setDataFineValidita(Date dataFineValidita) {
        this.dataFineValidita = dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_d_stato_iter
     *
     * @mbg.generated Wed Jan 22 16:49:54 CET 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idStatoIter=").append(idStatoIter);
        sb.append(", descStatoIter=").append(descStatoIter);
        sb.append(", dataInizioValidita=").append(dataInizioValidita);
        sb.append(", dataFineValidita=").append(dataFineValidita);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}