/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;

public class RebusmRCampagnaMisurazioneKey extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_r_campagna_misurazione.id_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    private Long idCampagna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_r_campagna_misurazione.id_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    private Long idMisurazione;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusm_r_campagna_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_r_campagna_misurazione.id_campagna
     *
     * @return the value of rebusm_r_campagna_misurazione.id_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public Long getIdCampagna() {
        return idCampagna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_r_campagna_misurazione.id_campagna
     *
     * @param idCampagna the value for rebusm_r_campagna_misurazione.id_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void setIdCampagna(Long idCampagna) {
        this.idCampagna = idCampagna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_r_campagna_misurazione.id_misurazione
     *
     * @return the value of rebusm_r_campagna_misurazione.id_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public Long getIdMisurazione() {
        return idMisurazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_r_campagna_misurazione.id_misurazione
     *
     * @param idMisurazione the value for rebusm_r_campagna_misurazione.id_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void setIdMisurazione(Long idMisurazione) {
        this.idMisurazione = idMisurazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_r_campagna_misurazione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idCampagna=").append(idCampagna);
        sb.append(", idMisurazione=").append(idMisurazione);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}