/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebuspDTipoContrattoDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_d_tipo_contratto.id_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    private Long idTipoContratto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_d_tipo_contratto.desc_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    private String descTipoContratto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_d_tipo_contratto.data_inizio_validita
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    private Date dataInizioValidita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusp_d_tipo_contratto.data_fine_validita
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    private Date dataFineValidita;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusp_d_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_d_tipo_contratto.id_tipo_contratto
     *
     * @return the value of rebusp_d_tipo_contratto.id_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    public Long getIdTipoContratto() {
        return idTipoContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_d_tipo_contratto.id_tipo_contratto
     *
     * @param idTipoContratto the value for rebusp_d_tipo_contratto.id_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    public void setIdTipoContratto(Long idTipoContratto) {
        this.idTipoContratto = idTipoContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_d_tipo_contratto.desc_tipo_contratto
     *
     * @return the value of rebusp_d_tipo_contratto.desc_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    public String getDescTipoContratto() {
        return descTipoContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_d_tipo_contratto.desc_tipo_contratto
     *
     * @param descTipoContratto the value for rebusp_d_tipo_contratto.desc_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    public void setDescTipoContratto(String descTipoContratto) {
        this.descTipoContratto = descTipoContratto == null ? null : descTipoContratto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_d_tipo_contratto.data_inizio_validita
     *
     * @return the value of rebusp_d_tipo_contratto.data_inizio_validita
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    public Date getDataInizioValidita() {
        return dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_d_tipo_contratto.data_inizio_validita
     *
     * @param dataInizioValidita the value for rebusp_d_tipo_contratto.data_inizio_validita
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    public void setDataInizioValidita(Date dataInizioValidita) {
        this.dataInizioValidita = dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusp_d_tipo_contratto.data_fine_validita
     *
     * @return the value of rebusp_d_tipo_contratto.data_fine_validita
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    public Date getDataFineValidita() {
        return dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusp_d_tipo_contratto.data_fine_validita
     *
     * @param dataFineValidita the value for rebusp_d_tipo_contratto.data_fine_validita
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    public void setDataFineValidita(Date dataFineValidita) {
        this.dataFineValidita = dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_d_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idTipoContratto=").append(idTipoContratto);
        sb.append(", descTipoContratto=").append(descTipoContratto);
        sb.append(", dataInizioValidita=").append(dataInizioValidita);
        sb.append(", dataFineValidita=").append(dataFineValidita);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}