/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RebusmDCampagnaSelector {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public RebusmDCampagnaSelector() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdCampagnaIsNull() {
            addCriterion("id_campagna is null");
            return (Criteria) this;
        }

        public Criteria andIdCampagnaIsNotNull() {
            addCriterion("id_campagna is not null");
            return (Criteria) this;
        }

        public Criteria andIdCampagnaEqualTo(Long value) {
            addCriterion("id_campagna =", value, "idCampagna");
            return (Criteria) this;
        }

        public Criteria andIdCampagnaNotEqualTo(Long value) {
            addCriterion("id_campagna <>", value, "idCampagna");
            return (Criteria) this;
        }

        public Criteria andIdCampagnaGreaterThan(Long value) {
            addCriterion("id_campagna >", value, "idCampagna");
            return (Criteria) this;
        }

        public Criteria andIdCampagnaGreaterThanOrEqualTo(Long value) {
            addCriterion("id_campagna >=", value, "idCampagna");
            return (Criteria) this;
        }

        public Criteria andIdCampagnaLessThan(Long value) {
            addCriterion("id_campagna <", value, "idCampagna");
            return (Criteria) this;
        }

        public Criteria andIdCampagnaLessThanOrEqualTo(Long value) {
            addCriterion("id_campagna <=", value, "idCampagna");
            return (Criteria) this;
        }

        public Criteria andIdCampagnaIn(List<Long> values) {
            addCriterion("id_campagna in", values, "idCampagna");
            return (Criteria) this;
        }

        public Criteria andIdCampagnaNotIn(List<Long> values) {
            addCriterion("id_campagna not in", values, "idCampagna");
            return (Criteria) this;
        }

        public Criteria andIdCampagnaBetween(Long value1, Long value2) {
            addCriterion("id_campagna between", value1, value2, "idCampagna");
            return (Criteria) this;
        }

        public Criteria andIdCampagnaNotBetween(Long value1, Long value2) {
            addCriterion("id_campagna not between", value1, value2, "idCampagna");
            return (Criteria) this;
        }

        public Criteria andDescrizioneIsNull() {
            addCriterion("descrizione is null");
            return (Criteria) this;
        }

        public Criteria andDescrizioneIsNotNull() {
            addCriterion("descrizione is not null");
            return (Criteria) this;
        }

        public Criteria andDescrizioneEqualTo(String value) {
            addCriterion("descrizione =", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneNotEqualTo(String value) {
            addCriterion("descrizione <>", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneGreaterThan(String value) {
            addCriterion("descrizione >", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneGreaterThanOrEqualTo(String value) {
            addCriterion("descrizione >=", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneLessThan(String value) {
            addCriterion("descrizione <", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneLessThanOrEqualTo(String value) {
            addCriterion("descrizione <=", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneLike(String value) {
            addCriterion("descrizione like", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneNotLike(String value) {
            addCriterion("descrizione not like", value, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneIn(List<String> values) {
            addCriterion("descrizione in", values, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneNotIn(List<String> values) {
            addCriterion("descrizione not in", values, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneBetween(String value1, String value2) {
            addCriterion("descrizione between", value1, value2, "descrizione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneNotBetween(String value1, String value2) {
            addCriterion("descrizione not between", value1, value2, "descrizione");
            return (Criteria) this;
        }

        public Criteria andIdTipoMonitoraggioIsNull() {
            addCriterion("id_tipo_monitoraggio is null");
            return (Criteria) this;
        }

        public Criteria andIdTipoMonitoraggioIsNotNull() {
            addCriterion("id_tipo_monitoraggio is not null");
            return (Criteria) this;
        }

        public Criteria andIdTipoMonitoraggioEqualTo(Long value) {
            addCriterion("id_tipo_monitoraggio =", value, "idTipoMonitoraggio");
            return (Criteria) this;
        }

        public Criteria andIdTipoMonitoraggioNotEqualTo(Long value) {
            addCriterion("id_tipo_monitoraggio <>", value, "idTipoMonitoraggio");
            return (Criteria) this;
        }

        public Criteria andIdTipoMonitoraggioGreaterThan(Long value) {
            addCriterion("id_tipo_monitoraggio >", value, "idTipoMonitoraggio");
            return (Criteria) this;
        }

        public Criteria andIdTipoMonitoraggioGreaterThanOrEqualTo(Long value) {
            addCriterion("id_tipo_monitoraggio >=", value, "idTipoMonitoraggio");
            return (Criteria) this;
        }

        public Criteria andIdTipoMonitoraggioLessThan(Long value) {
            addCriterion("id_tipo_monitoraggio <", value, "idTipoMonitoraggio");
            return (Criteria) this;
        }

        public Criteria andIdTipoMonitoraggioLessThanOrEqualTo(Long value) {
            addCriterion("id_tipo_monitoraggio <=", value, "idTipoMonitoraggio");
            return (Criteria) this;
        }

        public Criteria andIdTipoMonitoraggioIn(List<Long> values) {
            addCriterion("id_tipo_monitoraggio in", values, "idTipoMonitoraggio");
            return (Criteria) this;
        }

        public Criteria andIdTipoMonitoraggioNotIn(List<Long> values) {
            addCriterion("id_tipo_monitoraggio not in", values, "idTipoMonitoraggio");
            return (Criteria) this;
        }

        public Criteria andIdTipoMonitoraggioBetween(Long value1, Long value2) {
            addCriterion("id_tipo_monitoraggio between", value1, value2, "idTipoMonitoraggio");
            return (Criteria) this;
        }

        public Criteria andIdTipoMonitoraggioNotBetween(Long value1, Long value2) {
            addCriterion("id_tipo_monitoraggio not between", value1, value2, "idTipoMonitoraggio");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaIsNull() {
            addCriterion("data_inizio_validita is null");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaIsNotNull() {
            addCriterion("data_inizio_validita is not null");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_validita =", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaNotEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_validita <>", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaGreaterThan(Date value) {
            addCriterionForJDBCDate("data_inizio_validita >", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_validita >=", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaLessThan(Date value) {
            addCriterionForJDBCDate("data_inizio_validita <", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_validita <=", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaIn(List<Date> values) {
            addCriterionForJDBCDate("data_inizio_validita in", values, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaNotIn(List<Date> values) {
            addCriterionForJDBCDate("data_inizio_validita not in", values, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_inizio_validita between", value1, value2, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_inizio_validita not between", value1, value2, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaIsNull() {
            addCriterion("data_fine_validita is null");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaIsNotNull() {
            addCriterion("data_fine_validita is not null");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_validita =", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaNotEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_validita <>", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaGreaterThan(Date value) {
            addCriterionForJDBCDate("data_fine_validita >", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_validita >=", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaLessThan(Date value) {
            addCriterionForJDBCDate("data_fine_validita <", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_validita <=", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaIn(List<Date> values) {
            addCriterionForJDBCDate("data_fine_validita in", values, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaNotIn(List<Date> values) {
            addCriterionForJDBCDate("data_fine_validita not in", values, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_fine_validita between", value1, value2, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_fine_validita not between", value1, value2, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioRestituzioneIsNull() {
            addCriterion("data_inizio_restituzione is null");
            return (Criteria) this;
        }

        public Criteria andDataInizioRestituzioneIsNotNull() {
            addCriterion("data_inizio_restituzione is not null");
            return (Criteria) this;
        }

        public Criteria andDataInizioRestituzioneEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_restituzione =", value, "dataInizioRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataInizioRestituzioneNotEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_restituzione <>", value, "dataInizioRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataInizioRestituzioneGreaterThan(Date value) {
            addCriterionForJDBCDate("data_inizio_restituzione >", value, "dataInizioRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataInizioRestituzioneGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_restituzione >=", value, "dataInizioRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataInizioRestituzioneLessThan(Date value) {
            addCriterionForJDBCDate("data_inizio_restituzione <", value, "dataInizioRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataInizioRestituzioneLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_restituzione <=", value, "dataInizioRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataInizioRestituzioneIn(List<Date> values) {
            addCriterionForJDBCDate("data_inizio_restituzione in", values, "dataInizioRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataInizioRestituzioneNotIn(List<Date> values) {
            addCriterionForJDBCDate("data_inizio_restituzione not in", values, "dataInizioRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataInizioRestituzioneBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_inizio_restituzione between", value1, value2, "dataInizioRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataInizioRestituzioneNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_inizio_restituzione not between", value1, value2, "dataInizioRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataFineRestituzioneIsNull() {
            addCriterion("data_fine_restituzione is null");
            return (Criteria) this;
        }

        public Criteria andDataFineRestituzioneIsNotNull() {
            addCriterion("data_fine_restituzione is not null");
            return (Criteria) this;
        }

        public Criteria andDataFineRestituzioneEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_restituzione =", value, "dataFineRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataFineRestituzioneNotEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_restituzione <>", value, "dataFineRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataFineRestituzioneGreaterThan(Date value) {
            addCriterionForJDBCDate("data_fine_restituzione >", value, "dataFineRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataFineRestituzioneGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_restituzione >=", value, "dataFineRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataFineRestituzioneLessThan(Date value) {
            addCriterionForJDBCDate("data_fine_restituzione <", value, "dataFineRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataFineRestituzioneLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_restituzione <=", value, "dataFineRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataFineRestituzioneIn(List<Date> values) {
            addCriterionForJDBCDate("data_fine_restituzione in", values, "dataFineRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataFineRestituzioneNotIn(List<Date> values) {
            addCriterionForJDBCDate("data_fine_restituzione not in", values, "dataFineRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataFineRestituzioneBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_fine_restituzione between", value1, value2, "dataFineRestituzione");
            return (Criteria) this;
        }

        public Criteria andDataFineRestituzioneNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_fine_restituzione not between", value1, value2, "dataFineRestituzione");
            return (Criteria) this;
        }

        public Criteria andDescrizioneLikeInsensitive(String value) {
            addCriterion("upper(descrizione) like", value.toUpperCase(), "descrizione");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 10 10:30:29 CET 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}