/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebusTVariazAutobusDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.id_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long idVariazAutobus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_azienda
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long fkAzienda;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.n_telaio
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String nTelaio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.n_targa
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String nTarga;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.data_ultima_immatricolazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Date dataUltimaImmatricolazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_tipo_alimentazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long fkTipoAlimentazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.n_posti_sedere
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long nPostiSedere;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.n_posti_in_piedi
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long nPostiInPiedi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.n_posti_riservati
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long nPostiRiservati;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.omologazione_direttiva_europea
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String omologazioneDirettivaEuropea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_classe_ambientale_euro
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long fkClasseAmbientaleEuro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_filtro_fap
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String flgFiltroFap;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_dotazione_disabili
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long fkDotazioneDisabili;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_impianti_audio
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long fkImpiantiAudio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_impianti_visivi
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long fkImpiantiVisivi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_rilevatore_bip
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String flgRilevatoreBip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.prezzo_tot_acquisto
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Double prezzoTotAcquisto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.contributo_pubblico_acquisto
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Double contributoPubblicoAcquisto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_veicolo_assicurato
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String flgVeicoloAssicurato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.data_ultima_revisione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Date dataUltimaRevisione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.note
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.primo_telaio
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String primoTelaio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.n_matricola_aziendale
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String nMatricolaAziendale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_tipo_immatricolazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long fkTipoImmatricolazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.ente_autorizz_prima_imm
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String enteAutorizzPrimaImm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_classe_veicolo
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long fkClasseVeicolo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_due_piani
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String flgDuePiani;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_snodato
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String flgSnodato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.caratteristiche_particolari
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String caratteristicheParticolari;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.altra_alimentazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String altraAlimentazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_tipo_allestimento
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long fkTipoAllestimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.progr_tipo_dimens
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long progrTipoDimens;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.lunghezza
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Double lunghezza;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.numero_porte
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long numeroPorte;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.posti_carrozzina
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long postiCarrozzina;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_impianto_condizionamento
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String flgImpiantoCondizionamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_cabina_guida_isolata
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String flgCabinaGuidaIsolata;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.altri_dispositivi_prevenz_inc
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String altriDispositiviPrevenzInc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_otx
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String flgOtx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_avm
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String flgAvm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_contapasseggeri
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String flgContapasseggeri;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_proprieta_leasing
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long fkProprietaLeasing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_conteggiato_miv
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String flgConteggiatoMiv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_deposito
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long fkDeposito;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.tmp_indirizzo_dep
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String tmpIndirizzoDep;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.nota_riservata_azienda
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String notaRiservataAzienda;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.nota_riservata_amp
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String notaRiservataAmp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.nota_riservata_rp
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String notaRiservataRp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.data_aggiornamento
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_verificato_azienda
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String flgVerificatoAzienda;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_verificato_amp
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String flgVerificatoAmp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_alienato
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String flgAlienato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_richiesta_contr
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String flgRichiestaContr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.anno_sost_prog
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long annoSostProg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_utente
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long fkUtente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.data_inserimento
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Date dataInserimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.motivazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String motivazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_portabici
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Double fkPortabici;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_sistema_videosorveglianza
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Double fkSistemaVideosorveglianza;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_sistema_localizzazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Double fkSistemaLocalizzazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_bip_cablato
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Boolean flgBipCablato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_contapasseggeri_integrato
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Boolean flgContapasseggeriIntegrato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_sistemi_protezione_autista
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Boolean flgSistemiProtezioneAutista;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.altri_allestimenti
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private String altriAllestimenti;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.flg_contribuzione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Boolean flgContribuzione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebus_t_variaz_autobus.fk_categoria_veicolo
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private Long fkCategoriaVeicolo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebus_t_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.id_variaz_autobus
	 * @return  the value of rebus_t_variaz_autobus.id_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getIdVariazAutobus() {
		return idVariazAutobus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.id_variaz_autobus
	 * @param idVariazAutobus  the value for rebus_t_variaz_autobus.id_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setIdVariazAutobus(Long idVariazAutobus) {
		this.idVariazAutobus = idVariazAutobus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_azienda
	 * @return  the value of rebus_t_variaz_autobus.fk_azienda
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getFkAzienda() {
		return fkAzienda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_azienda
	 * @param fkAzienda  the value for rebus_t_variaz_autobus.fk_azienda
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkAzienda(Long fkAzienda) {
		this.fkAzienda = fkAzienda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.n_telaio
	 * @return  the value of rebus_t_variaz_autobus.n_telaio
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getnTelaio() {
		return nTelaio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.n_telaio
	 * @param nTelaio  the value for rebus_t_variaz_autobus.n_telaio
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setnTelaio(String nTelaio) {
		this.nTelaio = nTelaio == null ? null : nTelaio.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.n_targa
	 * @return  the value of rebus_t_variaz_autobus.n_targa
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getnTarga() {
		return nTarga;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.n_targa
	 * @param nTarga  the value for rebus_t_variaz_autobus.n_targa
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setnTarga(String nTarga) {
		this.nTarga = nTarga == null ? null : nTarga.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.data_ultima_immatricolazione
	 * @return  the value of rebus_t_variaz_autobus.data_ultima_immatricolazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Date getDataUltimaImmatricolazione() {
		return dataUltimaImmatricolazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.data_ultima_immatricolazione
	 * @param dataUltimaImmatricolazione  the value for rebus_t_variaz_autobus.data_ultima_immatricolazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setDataUltimaImmatricolazione(Date dataUltimaImmatricolazione) {
		this.dataUltimaImmatricolazione = dataUltimaImmatricolazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_tipo_alimentazione
	 * @return  the value of rebus_t_variaz_autobus.fk_tipo_alimentazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getFkTipoAlimentazione() {
		return fkTipoAlimentazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_tipo_alimentazione
	 * @param fkTipoAlimentazione  the value for rebus_t_variaz_autobus.fk_tipo_alimentazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkTipoAlimentazione(Long fkTipoAlimentazione) {
		this.fkTipoAlimentazione = fkTipoAlimentazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.n_posti_sedere
	 * @return  the value of rebus_t_variaz_autobus.n_posti_sedere
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getnPostiSedere() {
		return nPostiSedere;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.n_posti_sedere
	 * @param nPostiSedere  the value for rebus_t_variaz_autobus.n_posti_sedere
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setnPostiSedere(Long nPostiSedere) {
		this.nPostiSedere = nPostiSedere;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.n_posti_in_piedi
	 * @return  the value of rebus_t_variaz_autobus.n_posti_in_piedi
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getnPostiInPiedi() {
		return nPostiInPiedi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.n_posti_in_piedi
	 * @param nPostiInPiedi  the value for rebus_t_variaz_autobus.n_posti_in_piedi
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setnPostiInPiedi(Long nPostiInPiedi) {
		this.nPostiInPiedi = nPostiInPiedi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.n_posti_riservati
	 * @return  the value of rebus_t_variaz_autobus.n_posti_riservati
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getnPostiRiservati() {
		return nPostiRiservati;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.n_posti_riservati
	 * @param nPostiRiservati  the value for rebus_t_variaz_autobus.n_posti_riservati
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setnPostiRiservati(Long nPostiRiservati) {
		this.nPostiRiservati = nPostiRiservati;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.omologazione_direttiva_europea
	 * @return  the value of rebus_t_variaz_autobus.omologazione_direttiva_europea
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getOmologazioneDirettivaEuropea() {
		return omologazioneDirettivaEuropea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.omologazione_direttiva_europea
	 * @param omologazioneDirettivaEuropea  the value for rebus_t_variaz_autobus.omologazione_direttiva_europea
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setOmologazioneDirettivaEuropea(String omologazioneDirettivaEuropea) {
		this.omologazioneDirettivaEuropea = omologazioneDirettivaEuropea == null ? null
				: omologazioneDirettivaEuropea.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_classe_ambientale_euro
	 * @return  the value of rebus_t_variaz_autobus.fk_classe_ambientale_euro
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getFkClasseAmbientaleEuro() {
		return fkClasseAmbientaleEuro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_classe_ambientale_euro
	 * @param fkClasseAmbientaleEuro  the value for rebus_t_variaz_autobus.fk_classe_ambientale_euro
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkClasseAmbientaleEuro(Long fkClasseAmbientaleEuro) {
		this.fkClasseAmbientaleEuro = fkClasseAmbientaleEuro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_filtro_fap
	 * @return  the value of rebus_t_variaz_autobus.flg_filtro_fap
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getFlgFiltroFap() {
		return flgFiltroFap;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_filtro_fap
	 * @param flgFiltroFap  the value for rebus_t_variaz_autobus.flg_filtro_fap
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgFiltroFap(String flgFiltroFap) {
		this.flgFiltroFap = flgFiltroFap == null ? null : flgFiltroFap.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_dotazione_disabili
	 * @return  the value of rebus_t_variaz_autobus.fk_dotazione_disabili
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getFkDotazioneDisabili() {
		return fkDotazioneDisabili;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_dotazione_disabili
	 * @param fkDotazioneDisabili  the value for rebus_t_variaz_autobus.fk_dotazione_disabili
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkDotazioneDisabili(Long fkDotazioneDisabili) {
		this.fkDotazioneDisabili = fkDotazioneDisabili;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_impianti_audio
	 * @return  the value of rebus_t_variaz_autobus.fk_impianti_audio
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getFkImpiantiAudio() {
		return fkImpiantiAudio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_impianti_audio
	 * @param fkImpiantiAudio  the value for rebus_t_variaz_autobus.fk_impianti_audio
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkImpiantiAudio(Long fkImpiantiAudio) {
		this.fkImpiantiAudio = fkImpiantiAudio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_impianti_visivi
	 * @return  the value of rebus_t_variaz_autobus.fk_impianti_visivi
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getFkImpiantiVisivi() {
		return fkImpiantiVisivi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_impianti_visivi
	 * @param fkImpiantiVisivi  the value for rebus_t_variaz_autobus.fk_impianti_visivi
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkImpiantiVisivi(Long fkImpiantiVisivi) {
		this.fkImpiantiVisivi = fkImpiantiVisivi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_rilevatore_bip
	 * @return  the value of rebus_t_variaz_autobus.flg_rilevatore_bip
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getFlgRilevatoreBip() {
		return flgRilevatoreBip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_rilevatore_bip
	 * @param flgRilevatoreBip  the value for rebus_t_variaz_autobus.flg_rilevatore_bip
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgRilevatoreBip(String flgRilevatoreBip) {
		this.flgRilevatoreBip = flgRilevatoreBip == null ? null : flgRilevatoreBip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.prezzo_tot_acquisto
	 * @return  the value of rebus_t_variaz_autobus.prezzo_tot_acquisto
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Double getPrezzoTotAcquisto() {
		return prezzoTotAcquisto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.prezzo_tot_acquisto
	 * @param prezzoTotAcquisto  the value for rebus_t_variaz_autobus.prezzo_tot_acquisto
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setPrezzoTotAcquisto(Double prezzoTotAcquisto) {
		this.prezzoTotAcquisto = prezzoTotAcquisto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.contributo_pubblico_acquisto
	 * @return  the value of rebus_t_variaz_autobus.contributo_pubblico_acquisto
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Double getContributoPubblicoAcquisto() {
		return contributoPubblicoAcquisto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.contributo_pubblico_acquisto
	 * @param contributoPubblicoAcquisto  the value for rebus_t_variaz_autobus.contributo_pubblico_acquisto
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setContributoPubblicoAcquisto(Double contributoPubblicoAcquisto) {
		this.contributoPubblicoAcquisto = contributoPubblicoAcquisto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_veicolo_assicurato
	 * @return  the value of rebus_t_variaz_autobus.flg_veicolo_assicurato
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getFlgVeicoloAssicurato() {
		return flgVeicoloAssicurato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_veicolo_assicurato
	 * @param flgVeicoloAssicurato  the value for rebus_t_variaz_autobus.flg_veicolo_assicurato
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgVeicoloAssicurato(String flgVeicoloAssicurato) {
		this.flgVeicoloAssicurato = flgVeicoloAssicurato == null ? null : flgVeicoloAssicurato.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.data_ultima_revisione
	 * @return  the value of rebus_t_variaz_autobus.data_ultima_revisione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Date getDataUltimaRevisione() {
		return dataUltimaRevisione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.data_ultima_revisione
	 * @param dataUltimaRevisione  the value for rebus_t_variaz_autobus.data_ultima_revisione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setDataUltimaRevisione(Date dataUltimaRevisione) {
		this.dataUltimaRevisione = dataUltimaRevisione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.note
	 * @return  the value of rebus_t_variaz_autobus.note
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.note
	 * @param note  the value for rebus_t_variaz_autobus.note
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.primo_telaio
	 * @return  the value of rebus_t_variaz_autobus.primo_telaio
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getPrimoTelaio() {
		return primoTelaio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.primo_telaio
	 * @param primoTelaio  the value for rebus_t_variaz_autobus.primo_telaio
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setPrimoTelaio(String primoTelaio) {
		this.primoTelaio = primoTelaio == null ? null : primoTelaio.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.n_matricola_aziendale
	 * @return  the value of rebus_t_variaz_autobus.n_matricola_aziendale
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getnMatricolaAziendale() {
		return nMatricolaAziendale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.n_matricola_aziendale
	 * @param nMatricolaAziendale  the value for rebus_t_variaz_autobus.n_matricola_aziendale
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setnMatricolaAziendale(String nMatricolaAziendale) {
		this.nMatricolaAziendale = nMatricolaAziendale == null ? null : nMatricolaAziendale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_tipo_immatricolazione
	 * @return  the value of rebus_t_variaz_autobus.fk_tipo_immatricolazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getFkTipoImmatricolazione() {
		return fkTipoImmatricolazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_tipo_immatricolazione
	 * @param fkTipoImmatricolazione  the value for rebus_t_variaz_autobus.fk_tipo_immatricolazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkTipoImmatricolazione(Long fkTipoImmatricolazione) {
		this.fkTipoImmatricolazione = fkTipoImmatricolazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.ente_autorizz_prima_imm
	 * @return  the value of rebus_t_variaz_autobus.ente_autorizz_prima_imm
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getEnteAutorizzPrimaImm() {
		return enteAutorizzPrimaImm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.ente_autorizz_prima_imm
	 * @param enteAutorizzPrimaImm  the value for rebus_t_variaz_autobus.ente_autorizz_prima_imm
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setEnteAutorizzPrimaImm(String enteAutorizzPrimaImm) {
		this.enteAutorizzPrimaImm = enteAutorizzPrimaImm == null ? null : enteAutorizzPrimaImm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_classe_veicolo
	 * @return  the value of rebus_t_variaz_autobus.fk_classe_veicolo
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getFkClasseVeicolo() {
		return fkClasseVeicolo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_classe_veicolo
	 * @param fkClasseVeicolo  the value for rebus_t_variaz_autobus.fk_classe_veicolo
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkClasseVeicolo(Long fkClasseVeicolo) {
		this.fkClasseVeicolo = fkClasseVeicolo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_due_piani
	 * @return  the value of rebus_t_variaz_autobus.flg_due_piani
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getFlgDuePiani() {
		return flgDuePiani;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_due_piani
	 * @param flgDuePiani  the value for rebus_t_variaz_autobus.flg_due_piani
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgDuePiani(String flgDuePiani) {
		this.flgDuePiani = flgDuePiani == null ? null : flgDuePiani.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_snodato
	 * @return  the value of rebus_t_variaz_autobus.flg_snodato
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getFlgSnodato() {
		return flgSnodato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_snodato
	 * @param flgSnodato  the value for rebus_t_variaz_autobus.flg_snodato
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgSnodato(String flgSnodato) {
		this.flgSnodato = flgSnodato == null ? null : flgSnodato.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.caratteristiche_particolari
	 * @return  the value of rebus_t_variaz_autobus.caratteristiche_particolari
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getCaratteristicheParticolari() {
		return caratteristicheParticolari;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.caratteristiche_particolari
	 * @param caratteristicheParticolari  the value for rebus_t_variaz_autobus.caratteristiche_particolari
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setCaratteristicheParticolari(String caratteristicheParticolari) {
		this.caratteristicheParticolari = caratteristicheParticolari == null ? null : caratteristicheParticolari.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.altra_alimentazione
	 * @return  the value of rebus_t_variaz_autobus.altra_alimentazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getAltraAlimentazione() {
		return altraAlimentazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.altra_alimentazione
	 * @param altraAlimentazione  the value for rebus_t_variaz_autobus.altra_alimentazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setAltraAlimentazione(String altraAlimentazione) {
		this.altraAlimentazione = altraAlimentazione == null ? null : altraAlimentazione.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_tipo_allestimento
	 * @return  the value of rebus_t_variaz_autobus.fk_tipo_allestimento
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getFkTipoAllestimento() {
		return fkTipoAllestimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_tipo_allestimento
	 * @param fkTipoAllestimento  the value for rebus_t_variaz_autobus.fk_tipo_allestimento
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkTipoAllestimento(Long fkTipoAllestimento) {
		this.fkTipoAllestimento = fkTipoAllestimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.progr_tipo_dimens
	 * @return  the value of rebus_t_variaz_autobus.progr_tipo_dimens
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getProgrTipoDimens() {
		return progrTipoDimens;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.progr_tipo_dimens
	 * @param progrTipoDimens  the value for rebus_t_variaz_autobus.progr_tipo_dimens
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setProgrTipoDimens(Long progrTipoDimens) {
		this.progrTipoDimens = progrTipoDimens;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.lunghezza
	 * @return  the value of rebus_t_variaz_autobus.lunghezza
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Double getLunghezza() {
		return lunghezza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.lunghezza
	 * @param lunghezza  the value for rebus_t_variaz_autobus.lunghezza
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setLunghezza(Double lunghezza) {
		this.lunghezza = lunghezza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.numero_porte
	 * @return  the value of rebus_t_variaz_autobus.numero_porte
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getNumeroPorte() {
		return numeroPorte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.numero_porte
	 * @param numeroPorte  the value for rebus_t_variaz_autobus.numero_porte
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setNumeroPorte(Long numeroPorte) {
		this.numeroPorte = numeroPorte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.posti_carrozzina
	 * @return  the value of rebus_t_variaz_autobus.posti_carrozzina
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getPostiCarrozzina() {
		return postiCarrozzina;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.posti_carrozzina
	 * @param postiCarrozzina  the value for rebus_t_variaz_autobus.posti_carrozzina
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setPostiCarrozzina(Long postiCarrozzina) {
		this.postiCarrozzina = postiCarrozzina;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_impianto_condizionamento
	 * @return  the value of rebus_t_variaz_autobus.flg_impianto_condizionamento
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getFlgImpiantoCondizionamento() {
		return flgImpiantoCondizionamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_impianto_condizionamento
	 * @param flgImpiantoCondizionamento  the value for rebus_t_variaz_autobus.flg_impianto_condizionamento
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgImpiantoCondizionamento(String flgImpiantoCondizionamento) {
		this.flgImpiantoCondizionamento = flgImpiantoCondizionamento == null ? null : flgImpiantoCondizionamento.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_cabina_guida_isolata
	 * @return  the value of rebus_t_variaz_autobus.flg_cabina_guida_isolata
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getFlgCabinaGuidaIsolata() {
		return flgCabinaGuidaIsolata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_cabina_guida_isolata
	 * @param flgCabinaGuidaIsolata  the value for rebus_t_variaz_autobus.flg_cabina_guida_isolata
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgCabinaGuidaIsolata(String flgCabinaGuidaIsolata) {
		this.flgCabinaGuidaIsolata = flgCabinaGuidaIsolata == null ? null : flgCabinaGuidaIsolata.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.altri_dispositivi_prevenz_inc
	 * @return  the value of rebus_t_variaz_autobus.altri_dispositivi_prevenz_inc
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getAltriDispositiviPrevenzInc() {
		return altriDispositiviPrevenzInc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.altri_dispositivi_prevenz_inc
	 * @param altriDispositiviPrevenzInc  the value for rebus_t_variaz_autobus.altri_dispositivi_prevenz_inc
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setAltriDispositiviPrevenzInc(String altriDispositiviPrevenzInc) {
		this.altriDispositiviPrevenzInc = altriDispositiviPrevenzInc == null ? null : altriDispositiviPrevenzInc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_otx
	 * @return  the value of rebus_t_variaz_autobus.flg_otx
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getFlgOtx() {
		return flgOtx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_otx
	 * @param flgOtx  the value for rebus_t_variaz_autobus.flg_otx
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgOtx(String flgOtx) {
		this.flgOtx = flgOtx == null ? null : flgOtx.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_avm
	 * @return  the value of rebus_t_variaz_autobus.flg_avm
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getFlgAvm() {
		return flgAvm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_avm
	 * @param flgAvm  the value for rebus_t_variaz_autobus.flg_avm
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgAvm(String flgAvm) {
		this.flgAvm = flgAvm == null ? null : flgAvm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_contapasseggeri
	 * @return  the value of rebus_t_variaz_autobus.flg_contapasseggeri
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getFlgContapasseggeri() {
		return flgContapasseggeri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_contapasseggeri
	 * @param flgContapasseggeri  the value for rebus_t_variaz_autobus.flg_contapasseggeri
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgContapasseggeri(String flgContapasseggeri) {
		this.flgContapasseggeri = flgContapasseggeri == null ? null : flgContapasseggeri.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_proprieta_leasing
	 * @return  the value of rebus_t_variaz_autobus.fk_proprieta_leasing
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getFkProprietaLeasing() {
		return fkProprietaLeasing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_proprieta_leasing
	 * @param fkProprietaLeasing  the value for rebus_t_variaz_autobus.fk_proprieta_leasing
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkProprietaLeasing(Long fkProprietaLeasing) {
		this.fkProprietaLeasing = fkProprietaLeasing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_conteggiato_miv
	 * @return  the value of rebus_t_variaz_autobus.flg_conteggiato_miv
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getFlgConteggiatoMiv() {
		return flgConteggiatoMiv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_conteggiato_miv
	 * @param flgConteggiatoMiv  the value for rebus_t_variaz_autobus.flg_conteggiato_miv
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgConteggiatoMiv(String flgConteggiatoMiv) {
		this.flgConteggiatoMiv = flgConteggiatoMiv == null ? null : flgConteggiatoMiv.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_deposito
	 * @return  the value of rebus_t_variaz_autobus.fk_deposito
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getFkDeposito() {
		return fkDeposito;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_deposito
	 * @param fkDeposito  the value for rebus_t_variaz_autobus.fk_deposito
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkDeposito(Long fkDeposito) {
		this.fkDeposito = fkDeposito;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.tmp_indirizzo_dep
	 * @return  the value of rebus_t_variaz_autobus.tmp_indirizzo_dep
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getTmpIndirizzoDep() {
		return tmpIndirizzoDep;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.tmp_indirizzo_dep
	 * @param tmpIndirizzoDep  the value for rebus_t_variaz_autobus.tmp_indirizzo_dep
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setTmpIndirizzoDep(String tmpIndirizzoDep) {
		this.tmpIndirizzoDep = tmpIndirizzoDep == null ? null : tmpIndirizzoDep.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.nota_riservata_azienda
	 * @return  the value of rebus_t_variaz_autobus.nota_riservata_azienda
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getNotaRiservataAzienda() {
		return notaRiservataAzienda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.nota_riservata_azienda
	 * @param notaRiservataAzienda  the value for rebus_t_variaz_autobus.nota_riservata_azienda
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setNotaRiservataAzienda(String notaRiservataAzienda) {
		this.notaRiservataAzienda = notaRiservataAzienda == null ? null : notaRiservataAzienda.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.nota_riservata_amp
	 * @return  the value of rebus_t_variaz_autobus.nota_riservata_amp
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getNotaRiservataAmp() {
		return notaRiservataAmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.nota_riservata_amp
	 * @param notaRiservataAmp  the value for rebus_t_variaz_autobus.nota_riservata_amp
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setNotaRiservataAmp(String notaRiservataAmp) {
		this.notaRiservataAmp = notaRiservataAmp == null ? null : notaRiservataAmp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.nota_riservata_rp
	 * @return  the value of rebus_t_variaz_autobus.nota_riservata_rp
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getNotaRiservataRp() {
		return notaRiservataRp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.nota_riservata_rp
	 * @param notaRiservataRp  the value for rebus_t_variaz_autobus.nota_riservata_rp
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setNotaRiservataRp(String notaRiservataRp) {
		this.notaRiservataRp = notaRiservataRp == null ? null : notaRiservataRp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.data_aggiornamento
	 * @return  the value of rebus_t_variaz_autobus.data_aggiornamento
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.data_aggiornamento
	 * @param dataAggiornamento  the value for rebus_t_variaz_autobus.data_aggiornamento
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_verificato_azienda
	 * @return  the value of rebus_t_variaz_autobus.flg_verificato_azienda
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getFlgVerificatoAzienda() {
		return flgVerificatoAzienda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_verificato_azienda
	 * @param flgVerificatoAzienda  the value for rebus_t_variaz_autobus.flg_verificato_azienda
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgVerificatoAzienda(String flgVerificatoAzienda) {
		this.flgVerificatoAzienda = flgVerificatoAzienda == null ? null : flgVerificatoAzienda.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_verificato_amp
	 * @return  the value of rebus_t_variaz_autobus.flg_verificato_amp
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getFlgVerificatoAmp() {
		return flgVerificatoAmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_verificato_amp
	 * @param flgVerificatoAmp  the value for rebus_t_variaz_autobus.flg_verificato_amp
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgVerificatoAmp(String flgVerificatoAmp) {
		this.flgVerificatoAmp = flgVerificatoAmp == null ? null : flgVerificatoAmp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_alienato
	 * @return  the value of rebus_t_variaz_autobus.flg_alienato
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getFlgAlienato() {
		return flgAlienato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_alienato
	 * @param flgAlienato  the value for rebus_t_variaz_autobus.flg_alienato
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgAlienato(String flgAlienato) {
		this.flgAlienato = flgAlienato == null ? null : flgAlienato.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_richiesta_contr
	 * @return  the value of rebus_t_variaz_autobus.flg_richiesta_contr
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getFlgRichiestaContr() {
		return flgRichiestaContr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_richiesta_contr
	 * @param flgRichiestaContr  the value for rebus_t_variaz_autobus.flg_richiesta_contr
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgRichiestaContr(String flgRichiestaContr) {
		this.flgRichiestaContr = flgRichiestaContr == null ? null : flgRichiestaContr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.anno_sost_prog
	 * @return  the value of rebus_t_variaz_autobus.anno_sost_prog
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getAnnoSostProg() {
		return annoSostProg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.anno_sost_prog
	 * @param annoSostProg  the value for rebus_t_variaz_autobus.anno_sost_prog
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setAnnoSostProg(Long annoSostProg) {
		this.annoSostProg = annoSostProg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_utente
	 * @return  the value of rebus_t_variaz_autobus.fk_utente
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getFkUtente() {
		return fkUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_utente
	 * @param fkUtente  the value for rebus_t_variaz_autobus.fk_utente
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkUtente(Long fkUtente) {
		this.fkUtente = fkUtente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.data_inserimento
	 * @return  the value of rebus_t_variaz_autobus.data_inserimento
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Date getDataInserimento() {
		return dataInserimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.data_inserimento
	 * @param dataInserimento  the value for rebus_t_variaz_autobus.data_inserimento
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setDataInserimento(Date dataInserimento) {
		this.dataInserimento = dataInserimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.motivazione
	 * @return  the value of rebus_t_variaz_autobus.motivazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getMotivazione() {
		return motivazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.motivazione
	 * @param motivazione  the value for rebus_t_variaz_autobus.motivazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setMotivazione(String motivazione) {
		this.motivazione = motivazione == null ? null : motivazione.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_portabici
	 * @return  the value of rebus_t_variaz_autobus.fk_portabici
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Double getFkPortabici() {
		return fkPortabici;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_portabici
	 * @param fkPortabici  the value for rebus_t_variaz_autobus.fk_portabici
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkPortabici(Double fkPortabici) {
		this.fkPortabici = fkPortabici;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_sistema_videosorveglianza
	 * @return  the value of rebus_t_variaz_autobus.fk_sistema_videosorveglianza
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Double getFkSistemaVideosorveglianza() {
		return fkSistemaVideosorveglianza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_sistema_videosorveglianza
	 * @param fkSistemaVideosorveglianza  the value for rebus_t_variaz_autobus.fk_sistema_videosorveglianza
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkSistemaVideosorveglianza(Double fkSistemaVideosorveglianza) {
		this.fkSistemaVideosorveglianza = fkSistemaVideosorveglianza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_sistema_localizzazione
	 * @return  the value of rebus_t_variaz_autobus.fk_sistema_localizzazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Double getFkSistemaLocalizzazione() {
		return fkSistemaLocalizzazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_sistema_localizzazione
	 * @param fkSistemaLocalizzazione  the value for rebus_t_variaz_autobus.fk_sistema_localizzazione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkSistemaLocalizzazione(Double fkSistemaLocalizzazione) {
		this.fkSistemaLocalizzazione = fkSistemaLocalizzazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_bip_cablato
	 * @return  the value of rebus_t_variaz_autobus.flg_bip_cablato
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Boolean getFlgBipCablato() {
		return flgBipCablato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_bip_cablato
	 * @param flgBipCablato  the value for rebus_t_variaz_autobus.flg_bip_cablato
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgBipCablato(Boolean flgBipCablato) {
		this.flgBipCablato = flgBipCablato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_contapasseggeri_integrato
	 * @return  the value of rebus_t_variaz_autobus.flg_contapasseggeri_integrato
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Boolean getFlgContapasseggeriIntegrato() {
		return flgContapasseggeriIntegrato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_contapasseggeri_integrato
	 * @param flgContapasseggeriIntegrato  the value for rebus_t_variaz_autobus.flg_contapasseggeri_integrato
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgContapasseggeriIntegrato(Boolean flgContapasseggeriIntegrato) {
		this.flgContapasseggeriIntegrato = flgContapasseggeriIntegrato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_sistemi_protezione_autista
	 * @return  the value of rebus_t_variaz_autobus.flg_sistemi_protezione_autista
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Boolean getFlgSistemiProtezioneAutista() {
		return flgSistemiProtezioneAutista;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_sistemi_protezione_autista
	 * @param flgSistemiProtezioneAutista  the value for rebus_t_variaz_autobus.flg_sistemi_protezione_autista
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgSistemiProtezioneAutista(Boolean flgSistemiProtezioneAutista) {
		this.flgSistemiProtezioneAutista = flgSistemiProtezioneAutista;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.altri_allestimenti
	 * @return  the value of rebus_t_variaz_autobus.altri_allestimenti
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public String getAltriAllestimenti() {
		return altriAllestimenti;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.altri_allestimenti
	 * @param altriAllestimenti  the value for rebus_t_variaz_autobus.altri_allestimenti
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setAltriAllestimenti(String altriAllestimenti) {
		this.altriAllestimenti = altriAllestimenti == null ? null : altriAllestimenti.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.flg_contribuzione
	 * @return  the value of rebus_t_variaz_autobus.flg_contribuzione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Boolean getFlgContribuzione() {
		return flgContribuzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.flg_contribuzione
	 * @param flgContribuzione  the value for rebus_t_variaz_autobus.flg_contribuzione
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFlgContribuzione(Boolean flgContribuzione) {
		this.flgContribuzione = flgContribuzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebus_t_variaz_autobus.fk_categoria_veicolo
	 * @return  the value of rebus_t_variaz_autobus.fk_categoria_veicolo
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public Long getFkCategoriaVeicolo() {
		return fkCategoriaVeicolo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebus_t_variaz_autobus.fk_categoria_veicolo
	 * @param fkCategoriaVeicolo  the value for rebus_t_variaz_autobus.fk_categoria_veicolo
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	public void setFkCategoriaVeicolo(Long fkCategoriaVeicolo) {
		this.fkCategoriaVeicolo = fkCategoriaVeicolo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idVariazAutobus=").append(idVariazAutobus);
		sb.append(", fkAzienda=").append(fkAzienda);
		sb.append(", nTelaio=").append(nTelaio);
		sb.append(", nTarga=").append(nTarga);
		sb.append(", dataUltimaImmatricolazione=").append(dataUltimaImmatricolazione);
		sb.append(", fkTipoAlimentazione=").append(fkTipoAlimentazione);
		sb.append(", nPostiSedere=").append(nPostiSedere);
		sb.append(", nPostiInPiedi=").append(nPostiInPiedi);
		sb.append(", nPostiRiservati=").append(nPostiRiservati);
		sb.append(", omologazioneDirettivaEuropea=").append(omologazioneDirettivaEuropea);
		sb.append(", fkClasseAmbientaleEuro=").append(fkClasseAmbientaleEuro);
		sb.append(", flgFiltroFap=").append(flgFiltroFap);
		sb.append(", fkDotazioneDisabili=").append(fkDotazioneDisabili);
		sb.append(", fkImpiantiAudio=").append(fkImpiantiAudio);
		sb.append(", fkImpiantiVisivi=").append(fkImpiantiVisivi);
		sb.append(", flgRilevatoreBip=").append(flgRilevatoreBip);
		sb.append(", prezzoTotAcquisto=").append(prezzoTotAcquisto);
		sb.append(", contributoPubblicoAcquisto=").append(contributoPubblicoAcquisto);
		sb.append(", flgVeicoloAssicurato=").append(flgVeicoloAssicurato);
		sb.append(", dataUltimaRevisione=").append(dataUltimaRevisione);
		sb.append(", note=").append(note);
		sb.append(", primoTelaio=").append(primoTelaio);
		sb.append(", nMatricolaAziendale=").append(nMatricolaAziendale);
		sb.append(", fkTipoImmatricolazione=").append(fkTipoImmatricolazione);
		sb.append(", enteAutorizzPrimaImm=").append(enteAutorizzPrimaImm);
		sb.append(", fkClasseVeicolo=").append(fkClasseVeicolo);
		sb.append(", flgDuePiani=").append(flgDuePiani);
		sb.append(", flgSnodato=").append(flgSnodato);
		sb.append(", caratteristicheParticolari=").append(caratteristicheParticolari);
		sb.append(", altraAlimentazione=").append(altraAlimentazione);
		sb.append(", fkTipoAllestimento=").append(fkTipoAllestimento);
		sb.append(", progrTipoDimens=").append(progrTipoDimens);
		sb.append(", lunghezza=").append(lunghezza);
		sb.append(", numeroPorte=").append(numeroPorte);
		sb.append(", postiCarrozzina=").append(postiCarrozzina);
		sb.append(", flgImpiantoCondizionamento=").append(flgImpiantoCondizionamento);
		sb.append(", flgCabinaGuidaIsolata=").append(flgCabinaGuidaIsolata);
		sb.append(", altriDispositiviPrevenzInc=").append(altriDispositiviPrevenzInc);
		sb.append(", flgOtx=").append(flgOtx);
		sb.append(", flgAvm=").append(flgAvm);
		sb.append(", flgContapasseggeri=").append(flgContapasseggeri);
		sb.append(", fkProprietaLeasing=").append(fkProprietaLeasing);
		sb.append(", flgConteggiatoMiv=").append(flgConteggiatoMiv);
		sb.append(", fkDeposito=").append(fkDeposito);
		sb.append(", tmpIndirizzoDep=").append(tmpIndirizzoDep);
		sb.append(", notaRiservataAzienda=").append(notaRiservataAzienda);
		sb.append(", notaRiservataAmp=").append(notaRiservataAmp);
		sb.append(", notaRiservataRp=").append(notaRiservataRp);
		sb.append(", dataAggiornamento=").append(dataAggiornamento);
		sb.append(", flgVerificatoAzienda=").append(flgVerificatoAzienda);
		sb.append(", flgVerificatoAmp=").append(flgVerificatoAmp);
		sb.append(", flgAlienato=").append(flgAlienato);
		sb.append(", flgRichiestaContr=").append(flgRichiestaContr);
		sb.append(", annoSostProg=").append(annoSostProg);
		sb.append(", fkUtente=").append(fkUtente);
		sb.append(", dataInserimento=").append(dataInserimento);
		sb.append(", motivazione=").append(motivazione);
		sb.append(", fkPortabici=").append(fkPortabici);
		sb.append(", fkSistemaVideosorveglianza=").append(fkSistemaVideosorveglianza);
		sb.append(", fkSistemaLocalizzazione=").append(fkSistemaLocalizzazione);
		sb.append(", flgBipCablato=").append(flgBipCablato);
		sb.append(", flgContapasseggeriIntegrato=").append(flgContapasseggeriIntegrato);
		sb.append(", flgSistemiProtezioneAutista=").append(flgSistemiProtezioneAutista);
		sb.append(", altriAllestimenti=").append(altriAllestimenti);
		sb.append(", flgContribuzione=").append(flgContribuzione);
		sb.append(", fkCategoriaVeicolo=").append(fkCategoriaVeicolo);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}