/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;

public class RebuscROggettoFatturaKey extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusc_r_oggetto_fattura.id_dato_fattura
     *
     * @mbg.generated Thu Dec 02 15:29:59 CET 2021
     */
    private Long idDatoFattura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusc_r_oggetto_fattura.id_voce_costo_fornitura
     *
     * @mbg.generated Thu Dec 02 15:29:59 CET 2021
     */
    private Long idVoceCostoFornitura;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusc_r_oggetto_fattura
     *
     * @mbg.generated Thu Dec 02 15:29:59 CET 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusc_r_oggetto_fattura.id_dato_fattura
     *
     * @return the value of rebusc_r_oggetto_fattura.id_dato_fattura
     *
     * @mbg.generated Thu Dec 02 15:29:59 CET 2021
     */
    public Long getIdDatoFattura() {
        return idDatoFattura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusc_r_oggetto_fattura.id_dato_fattura
     *
     * @param idDatoFattura the value for rebusc_r_oggetto_fattura.id_dato_fattura
     *
     * @mbg.generated Thu Dec 02 15:29:59 CET 2021
     */
    public void setIdDatoFattura(Long idDatoFattura) {
        this.idDatoFattura = idDatoFattura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusc_r_oggetto_fattura.id_voce_costo_fornitura
     *
     * @return the value of rebusc_r_oggetto_fattura.id_voce_costo_fornitura
     *
     * @mbg.generated Thu Dec 02 15:29:59 CET 2021
     */
    public Long getIdVoceCostoFornitura() {
        return idVoceCostoFornitura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusc_r_oggetto_fattura.id_voce_costo_fornitura
     *
     * @param idVoceCostoFornitura the value for rebusc_r_oggetto_fattura.id_voce_costo_fornitura
     *
     * @mbg.generated Thu Dec 02 15:29:59 CET 2021
     */
    public void setIdVoceCostoFornitura(Long idVoceCostoFornitura) {
        this.idVoceCostoFornitura = idVoceCostoFornitura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_r_oggetto_fattura
     *
     * @mbg.generated Thu Dec 02 15:29:59 CET 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idDatoFattura=").append(idDatoFattura);
        sb.append(", idVoceCostoFornitura=").append(idVoceCostoFornitura);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}