/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebuspDMotivazioneDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_motivazione.id_motivazione
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	private Long idMotivazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_motivazione.desc_motivazione
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	private String descMotivazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_motivazione.flg_motiv_altro
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	private Boolean flgMotivAltro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_motivazione.data_inizio_validita
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	private Date dataInizioValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_motivazione.data_fine_validita
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	private Date dataFineValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_motivazione.id_tipo_procedimento
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	private Long idTipoProcedimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusp_d_motivazione
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_motivazione.id_motivazione
	 * @return  the value of rebusp_d_motivazione.id_motivazione
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	public Long getIdMotivazione() {
		return idMotivazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_motivazione.id_motivazione
	 * @param idMotivazione  the value for rebusp_d_motivazione.id_motivazione
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	public void setIdMotivazione(Long idMotivazione) {
		this.idMotivazione = idMotivazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_motivazione.desc_motivazione
	 * @return  the value of rebusp_d_motivazione.desc_motivazione
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	public String getDescMotivazione() {
		return descMotivazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_motivazione.desc_motivazione
	 * @param descMotivazione  the value for rebusp_d_motivazione.desc_motivazione
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	public void setDescMotivazione(String descMotivazione) {
		this.descMotivazione = descMotivazione == null ? null : descMotivazione.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_motivazione.flg_motiv_altro
	 * @return  the value of rebusp_d_motivazione.flg_motiv_altro
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	public Boolean getFlgMotivAltro() {
		return flgMotivAltro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_motivazione.flg_motiv_altro
	 * @param flgMotivAltro  the value for rebusp_d_motivazione.flg_motiv_altro
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	public void setFlgMotivAltro(Boolean flgMotivAltro) {
		this.flgMotivAltro = flgMotivAltro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_motivazione.data_inizio_validita
	 * @return  the value of rebusp_d_motivazione.data_inizio_validita
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	public Date getDataInizioValidita() {
		return dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_motivazione.data_inizio_validita
	 * @param dataInizioValidita  the value for rebusp_d_motivazione.data_inizio_validita
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	public void setDataInizioValidita(Date dataInizioValidita) {
		this.dataInizioValidita = dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_motivazione.data_fine_validita
	 * @return  the value of rebusp_d_motivazione.data_fine_validita
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	public Date getDataFineValidita() {
		return dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_motivazione.data_fine_validita
	 * @param dataFineValidita  the value for rebusp_d_motivazione.data_fine_validita
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	public void setDataFineValidita(Date dataFineValidita) {
		this.dataFineValidita = dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_motivazione.id_tipo_procedimento
	 * @return  the value of rebusp_d_motivazione.id_tipo_procedimento
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	public Long getIdTipoProcedimento() {
		return idTipoProcedimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_motivazione.id_tipo_procedimento
	 * @param idTipoProcedimento  the value for rebusp_d_motivazione.id_tipo_procedimento
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	public void setIdTipoProcedimento(Long idTipoProcedimento) {
		this.idTipoProcedimento = idTipoProcedimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_motivazione
	 * @mbg.generated  Fri Jan 24 16:11:33 CET 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idMotivazione=").append(idMotivazione);
		sb.append(", descMotivazione=").append(descMotivazione);
		sb.append(", flgMotivAltro=").append(flgMotivAltro);
		sb.append(", dataInizioValidita=").append(dataInizioValidita);
		sb.append(", dataFineValidita=").append(dataFineValidita);
		sb.append(", idTipoProcedimento=").append(idTipoProcedimento);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}