/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebusmDCampagnaDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_d_campagna.id_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    private Long idCampagna;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_d_campagna.descrizione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    private String descrizione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_d_campagna.id_tipo_monitoraggio
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    private Long idTipoMonitoraggio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_d_campagna.data_inizio_validita
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    private Date dataInizioValidita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_d_campagna.data_fine_validita
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    private Date dataFineValidita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_d_campagna.data_inizio_restituzione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    private Date dataInizioRestituzione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebusm_d_campagna.data_fine_restituzione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    private Date dataFineRestituzione;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_d_campagna.id_campagna
     *
     * @return the value of rebusm_d_campagna.id_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public Long getIdCampagna() {
        return idCampagna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_d_campagna.id_campagna
     *
     * @param idCampagna the value for rebusm_d_campagna.id_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void setIdCampagna(Long idCampagna) {
        this.idCampagna = idCampagna;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_d_campagna.descrizione
     *
     * @return the value of rebusm_d_campagna.descrizione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public String getDescrizione() {
        return descrizione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_d_campagna.descrizione
     *
     * @param descrizione the value for rebusm_d_campagna.descrizione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione == null ? null : descrizione.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_d_campagna.id_tipo_monitoraggio
     *
     * @return the value of rebusm_d_campagna.id_tipo_monitoraggio
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public Long getIdTipoMonitoraggio() {
        return idTipoMonitoraggio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_d_campagna.id_tipo_monitoraggio
     *
     * @param idTipoMonitoraggio the value for rebusm_d_campagna.id_tipo_monitoraggio
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void setIdTipoMonitoraggio(Long idTipoMonitoraggio) {
        this.idTipoMonitoraggio = idTipoMonitoraggio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_d_campagna.data_inizio_validita
     *
     * @return the value of rebusm_d_campagna.data_inizio_validita
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public Date getDataInizioValidita() {
        return dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_d_campagna.data_inizio_validita
     *
     * @param dataInizioValidita the value for rebusm_d_campagna.data_inizio_validita
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void setDataInizioValidita(Date dataInizioValidita) {
        this.dataInizioValidita = dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_d_campagna.data_fine_validita
     *
     * @return the value of rebusm_d_campagna.data_fine_validita
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public Date getDataFineValidita() {
        return dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_d_campagna.data_fine_validita
     *
     * @param dataFineValidita the value for rebusm_d_campagna.data_fine_validita
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void setDataFineValidita(Date dataFineValidita) {
        this.dataFineValidita = dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_d_campagna.data_inizio_restituzione
     *
     * @return the value of rebusm_d_campagna.data_inizio_restituzione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public Date getDataInizioRestituzione() {
        return dataInizioRestituzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_d_campagna.data_inizio_restituzione
     *
     * @param dataInizioRestituzione the value for rebusm_d_campagna.data_inizio_restituzione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void setDataInizioRestituzione(Date dataInizioRestituzione) {
        this.dataInizioRestituzione = dataInizioRestituzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebusm_d_campagna.data_fine_restituzione
     *
     * @return the value of rebusm_d_campagna.data_fine_restituzione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public Date getDataFineRestituzione() {
        return dataFineRestituzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebusm_d_campagna.data_fine_restituzione
     *
     * @param dataFineRestituzione the value for rebusm_d_campagna.data_fine_restituzione
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    public void setDataFineRestituzione(Date dataFineRestituzione) {
        this.dataFineRestituzione = dataFineRestituzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_campagna
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idCampagna=").append(idCampagna);
        sb.append(", descrizione=").append(descrizione);
        sb.append(", idTipoMonitoraggio=").append(idTipoMonitoraggio);
        sb.append(", dataInizioValidita=").append(dataInizioValidita);
        sb.append(", dataFineValidita=").append(dataFineValidita);
        sb.append(", dataInizioRestituzione=").append(dataInizioRestituzione);
        sb.append(", dataFineRestituzione=").append(dataFineRestituzione);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}