/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class RebuspDMotorizzazioneDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_motorizzazione.id_motorizzazione
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	private Long idMotorizzazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_motorizzazione.desc_motorizzazione
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	private String descMotorizzazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_motorizzazione.indirizzo
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	private String indirizzo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_motorizzazione.data_inizio_validita
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	private Date dataInizioValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_motorizzazione.data_fine_validita
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	private Date dataFineValidita;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column rebusp_d_motorizzazione.pec
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	private String pec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table rebusp_d_motorizzazione
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_motorizzazione.id_motorizzazione
	 * @return  the value of rebusp_d_motorizzazione.id_motorizzazione
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	public Long getIdMotorizzazione() {
		return idMotorizzazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_motorizzazione.id_motorizzazione
	 * @param idMotorizzazione  the value for rebusp_d_motorizzazione.id_motorizzazione
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	public void setIdMotorizzazione(Long idMotorizzazione) {
		this.idMotorizzazione = idMotorizzazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_motorizzazione.desc_motorizzazione
	 * @return  the value of rebusp_d_motorizzazione.desc_motorizzazione
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	public String getDescMotorizzazione() {
		return descMotorizzazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_motorizzazione.desc_motorizzazione
	 * @param descMotorizzazione  the value for rebusp_d_motorizzazione.desc_motorizzazione
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	public void setDescMotorizzazione(String descMotorizzazione) {
		this.descMotorizzazione = descMotorizzazione == null ? null : descMotorizzazione.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_motorizzazione.indirizzo
	 * @return  the value of rebusp_d_motorizzazione.indirizzo
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	public String getIndirizzo() {
		return indirizzo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_motorizzazione.indirizzo
	 * @param indirizzo  the value for rebusp_d_motorizzazione.indirizzo
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo == null ? null : indirizzo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_motorizzazione.data_inizio_validita
	 * @return  the value of rebusp_d_motorizzazione.data_inizio_validita
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	public Date getDataInizioValidita() {
		return dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_motorizzazione.data_inizio_validita
	 * @param dataInizioValidita  the value for rebusp_d_motorizzazione.data_inizio_validita
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	public void setDataInizioValidita(Date dataInizioValidita) {
		this.dataInizioValidita = dataInizioValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_motorizzazione.data_fine_validita
	 * @return  the value of rebusp_d_motorizzazione.data_fine_validita
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	public Date getDataFineValidita() {
		return dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_motorizzazione.data_fine_validita
	 * @param dataFineValidita  the value for rebusp_d_motorizzazione.data_fine_validita
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	public void setDataFineValidita(Date dataFineValidita) {
		this.dataFineValidita = dataFineValidita;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column rebusp_d_motorizzazione.pec
	 * @return  the value of rebusp_d_motorizzazione.pec
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	public String getPec() {
		return pec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column rebusp_d_motorizzazione.pec
	 * @param pec  the value for rebusp_d_motorizzazione.pec
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	public void setPec(String pec) {
		this.pec = pec == null ? null : pec.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_motorizzazione
	 * @mbg.generated  Mon Nov 02 13:29:57 CET 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idMotorizzazione=").append(idMotorizzazione);
		sb.append(", descMotorizzazione=").append(descMotorizzazione);
		sb.append(", indirizzo=").append(indirizzo);
		sb.append(", dataInizioValidita=").append(dataInizioValidita);
		sb.append(", dataFineValidita=").append(dataFineValidita);
		sb.append(", pec=").append(pec);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}