/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;

public class SirtplcRContrattoRaggruppDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_r_contratto_raggrupp.id_contratto_raggrupp
     *
     * @mbg.generated Wed Mar 11 12:29:46 CET 2020
     */
    private Long idContrattoRaggrupp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_r_contratto_raggrupp.id_contratto
     *
     * @mbg.generated Wed Mar 11 12:29:46 CET 2020
     */
    private Long idContratto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_r_contratto_raggrupp.id_soggetto_giuridico
     *
     * @mbg.generated Wed Mar 11 12:29:46 CET 2020
     */
    private Long idSoggettoGiuridico;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_r_contratto_raggrupp.capofila
     *
     * @mbg.generated Wed Mar 11 12:29:46 CET 2020
     */
    private Boolean capofila;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirtplc_r_contratto_raggrupp
     *
     * @mbg.generated Wed Mar 11 12:29:46 CET 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_r_contratto_raggrupp.id_contratto_raggrupp
     *
     * @return the value of sirtplc_r_contratto_raggrupp.id_contratto_raggrupp
     *
     * @mbg.generated Wed Mar 11 12:29:46 CET 2020
     */
    public Long getIdContrattoRaggrupp() {
        return idContrattoRaggrupp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_r_contratto_raggrupp.id_contratto_raggrupp
     *
     * @param idContrattoRaggrupp the value for sirtplc_r_contratto_raggrupp.id_contratto_raggrupp
     *
     * @mbg.generated Wed Mar 11 12:29:46 CET 2020
     */
    public void setIdContrattoRaggrupp(Long idContrattoRaggrupp) {
        this.idContrattoRaggrupp = idContrattoRaggrupp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_r_contratto_raggrupp.id_contratto
     *
     * @return the value of sirtplc_r_contratto_raggrupp.id_contratto
     *
     * @mbg.generated Wed Mar 11 12:29:46 CET 2020
     */
    public Long getIdContratto() {
        return idContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_r_contratto_raggrupp.id_contratto
     *
     * @param idContratto the value for sirtplc_r_contratto_raggrupp.id_contratto
     *
     * @mbg.generated Wed Mar 11 12:29:46 CET 2020
     */
    public void setIdContratto(Long idContratto) {
        this.idContratto = idContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_r_contratto_raggrupp.id_soggetto_giuridico
     *
     * @return the value of sirtplc_r_contratto_raggrupp.id_soggetto_giuridico
     *
     * @mbg.generated Wed Mar 11 12:29:46 CET 2020
     */
    public Long getIdSoggettoGiuridico() {
        return idSoggettoGiuridico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_r_contratto_raggrupp.id_soggetto_giuridico
     *
     * @param idSoggettoGiuridico the value for sirtplc_r_contratto_raggrupp.id_soggetto_giuridico
     *
     * @mbg.generated Wed Mar 11 12:29:46 CET 2020
     */
    public void setIdSoggettoGiuridico(Long idSoggettoGiuridico) {
        this.idSoggettoGiuridico = idSoggettoGiuridico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_r_contratto_raggrupp.capofila
     *
     * @return the value of sirtplc_r_contratto_raggrupp.capofila
     *
     * @mbg.generated Wed Mar 11 12:29:46 CET 2020
     */
    public Boolean getCapofila() {
        return capofila;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_r_contratto_raggrupp.capofila
     *
     * @param capofila the value for sirtplc_r_contratto_raggrupp.capofila
     *
     * @mbg.generated Wed Mar 11 12:29:46 CET 2020
     */
    public void setCapofila(Boolean capofila) {
        this.capofila = capofila;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_contratto_raggrupp
     *
     * @mbg.generated Wed Mar 11 12:29:46 CET 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idContrattoRaggrupp=").append(idContrattoRaggrupp);
        sb.append(", idContratto=").append(idContratto);
        sb.append(", idSoggettoGiuridico=").append(idSoggettoGiuridico);
        sb.append(", capofila=").append(capofila);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}