/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class SirtplDProvinciaDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtpl_d_provincia.id_provincia
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    private Long idProvincia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtpl_d_provincia.cod_istat_provincia
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    private String codIstatProvincia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtpl_d_provincia.denom_provincia
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    private String denomProvincia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtpl_d_provincia.sigla_provincia
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    private String siglaProvincia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtpl_d_provincia.id_regione
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    private Long idRegione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtpl_d_provincia.data_inizio_validita
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    private Date dataInizioValidita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtpl_d_provincia.data_fine_validita
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    private Date dataFineValidita;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirtpl_d_provincia
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtpl_d_provincia.id_provincia
     *
     * @return the value of sirtpl_d_provincia.id_provincia
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    public Long getIdProvincia() {
        return idProvincia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtpl_d_provincia.id_provincia
     *
     * @param idProvincia the value for sirtpl_d_provincia.id_provincia
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    public void setIdProvincia(Long idProvincia) {
        this.idProvincia = idProvincia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtpl_d_provincia.cod_istat_provincia
     *
     * @return the value of sirtpl_d_provincia.cod_istat_provincia
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    public String getCodIstatProvincia() {
        return codIstatProvincia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtpl_d_provincia.cod_istat_provincia
     *
     * @param codIstatProvincia the value for sirtpl_d_provincia.cod_istat_provincia
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    public void setCodIstatProvincia(String codIstatProvincia) {
        this.codIstatProvincia = codIstatProvincia == null ? null : codIstatProvincia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtpl_d_provincia.denom_provincia
     *
     * @return the value of sirtpl_d_provincia.denom_provincia
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    public String getDenomProvincia() {
        return denomProvincia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtpl_d_provincia.denom_provincia
     *
     * @param denomProvincia the value for sirtpl_d_provincia.denom_provincia
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    public void setDenomProvincia(String denomProvincia) {
        this.denomProvincia = denomProvincia == null ? null : denomProvincia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtpl_d_provincia.sigla_provincia
     *
     * @return the value of sirtpl_d_provincia.sigla_provincia
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    public String getSiglaProvincia() {
        return siglaProvincia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtpl_d_provincia.sigla_provincia
     *
     * @param siglaProvincia the value for sirtpl_d_provincia.sigla_provincia
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    public void setSiglaProvincia(String siglaProvincia) {
        this.siglaProvincia = siglaProvincia == null ? null : siglaProvincia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtpl_d_provincia.id_regione
     *
     * @return the value of sirtpl_d_provincia.id_regione
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    public Long getIdRegione() {
        return idRegione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtpl_d_provincia.id_regione
     *
     * @param idRegione the value for sirtpl_d_provincia.id_regione
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    public void setIdRegione(Long idRegione) {
        this.idRegione = idRegione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtpl_d_provincia.data_inizio_validita
     *
     * @return the value of sirtpl_d_provincia.data_inizio_validita
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    public Date getDataInizioValidita() {
        return dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtpl_d_provincia.data_inizio_validita
     *
     * @param dataInizioValidita the value for sirtpl_d_provincia.data_inizio_validita
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    public void setDataInizioValidita(Date dataInizioValidita) {
        this.dataInizioValidita = dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtpl_d_provincia.data_fine_validita
     *
     * @return the value of sirtpl_d_provincia.data_fine_validita
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    public Date getDataFineValidita() {
        return dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtpl_d_provincia.data_fine_validita
     *
     * @param dataFineValidita the value for sirtpl_d_provincia.data_fine_validita
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    public void setDataFineValidita(Date dataFineValidita) {
        this.dataFineValidita = dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_d_provincia
     *
     * @mbg.generated Tue Aug 25 15:25:33 CEST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idProvincia=").append(idProvincia);
        sb.append(", codIstatProvincia=").append(codIstatProvincia);
        sb.append(", denomProvincia=").append(denomProvincia);
        sb.append(", siglaProvincia=").append(siglaProvincia);
        sb.append(", idRegione=").append(idRegione);
        sb.append(", dataInizioValidita=").append(dataInizioValidita);
        sb.append(", dataFineValidita=").append(dataFineValidita);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}