/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class SirtplcTContrattoDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.id_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private Long idContratto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.id_contratto_padre
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private Long idContrattoPadre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.cod_id_nazionale
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private String codIdNazionale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.cod_id_regionale
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private String codIdRegionale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.num_repertorio
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private String numRepertorio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.id_sog_giurid_committente
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private Long idSogGiuridCommittente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.id_sog_giurid_esecutore
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private Long idSogGiuridEsecutore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.id_tipo_sog_giurid_esec
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private Long idTipoSogGiuridEsec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.id_tipo_raggr_sog_giurid_esec
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private Long idTipoRaggrSogGiuridEsec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.id_tipo_affidamento
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private Long idTipoAffidamento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.id_modalita_affidamento
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private Long idModalitaAffidamento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.accordo_programma
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private String accordoProgramma;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.gross_cost
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private Boolean grossCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.cig
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private String cig;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.data_stipula
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private Date dataStipula;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.desc_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private String descContratto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.id_bacino
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private Long idBacino;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.id_utente_aggiornamento
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private Long idUtenteAggiornamento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.data_aggiornamento
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private Date dataAggiornamento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.data_inizio_validita
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private Date dataInizioValidita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_t_contratto.data_fine_validita
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private Date dataFineValidita;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.id_contratto
     *
     * @return the value of sirtplc_t_contratto.id_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Long getIdContratto() {
        return idContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.id_contratto
     *
     * @param idContratto the value for sirtplc_t_contratto.id_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setIdContratto(Long idContratto) {
        this.idContratto = idContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.id_contratto_padre
     *
     * @return the value of sirtplc_t_contratto.id_contratto_padre
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Long getIdContrattoPadre() {
        return idContrattoPadre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.id_contratto_padre
     *
     * @param idContrattoPadre the value for sirtplc_t_contratto.id_contratto_padre
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setIdContrattoPadre(Long idContrattoPadre) {
        this.idContrattoPadre = idContrattoPadre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.cod_id_nazionale
     *
     * @return the value of sirtplc_t_contratto.cod_id_nazionale
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public String getCodIdNazionale() {
        return codIdNazionale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.cod_id_nazionale
     *
     * @param codIdNazionale the value for sirtplc_t_contratto.cod_id_nazionale
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setCodIdNazionale(String codIdNazionale) {
        this.codIdNazionale = codIdNazionale == null ? null : codIdNazionale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.cod_id_regionale
     *
     * @return the value of sirtplc_t_contratto.cod_id_regionale
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public String getCodIdRegionale() {
        return codIdRegionale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.cod_id_regionale
     *
     * @param codIdRegionale the value for sirtplc_t_contratto.cod_id_regionale
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setCodIdRegionale(String codIdRegionale) {
        this.codIdRegionale = codIdRegionale == null ? null : codIdRegionale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.num_repertorio
     *
     * @return the value of sirtplc_t_contratto.num_repertorio
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public String getNumRepertorio() {
        return numRepertorio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.num_repertorio
     *
     * @param numRepertorio the value for sirtplc_t_contratto.num_repertorio
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setNumRepertorio(String numRepertorio) {
        this.numRepertorio = numRepertorio == null ? null : numRepertorio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.id_sog_giurid_committente
     *
     * @return the value of sirtplc_t_contratto.id_sog_giurid_committente
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Long getIdSogGiuridCommittente() {
        return idSogGiuridCommittente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.id_sog_giurid_committente
     *
     * @param idSogGiuridCommittente the value for sirtplc_t_contratto.id_sog_giurid_committente
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setIdSogGiuridCommittente(Long idSogGiuridCommittente) {
        this.idSogGiuridCommittente = idSogGiuridCommittente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.id_sog_giurid_esecutore
     *
     * @return the value of sirtplc_t_contratto.id_sog_giurid_esecutore
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Long getIdSogGiuridEsecutore() {
        return idSogGiuridEsecutore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.id_sog_giurid_esecutore
     *
     * @param idSogGiuridEsecutore the value for sirtplc_t_contratto.id_sog_giurid_esecutore
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setIdSogGiuridEsecutore(Long idSogGiuridEsecutore) {
        this.idSogGiuridEsecutore = idSogGiuridEsecutore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.id_tipo_sog_giurid_esec
     *
     * @return the value of sirtplc_t_contratto.id_tipo_sog_giurid_esec
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Long getIdTipoSogGiuridEsec() {
        return idTipoSogGiuridEsec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.id_tipo_sog_giurid_esec
     *
     * @param idTipoSogGiuridEsec the value for sirtplc_t_contratto.id_tipo_sog_giurid_esec
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setIdTipoSogGiuridEsec(Long idTipoSogGiuridEsec) {
        this.idTipoSogGiuridEsec = idTipoSogGiuridEsec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.id_tipo_raggr_sog_giurid_esec
     *
     * @return the value of sirtplc_t_contratto.id_tipo_raggr_sog_giurid_esec
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Long getIdTipoRaggrSogGiuridEsec() {
        return idTipoRaggrSogGiuridEsec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.id_tipo_raggr_sog_giurid_esec
     *
     * @param idTipoRaggrSogGiuridEsec the value for sirtplc_t_contratto.id_tipo_raggr_sog_giurid_esec
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setIdTipoRaggrSogGiuridEsec(Long idTipoRaggrSogGiuridEsec) {
        this.idTipoRaggrSogGiuridEsec = idTipoRaggrSogGiuridEsec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.id_tipo_affidamento
     *
     * @return the value of sirtplc_t_contratto.id_tipo_affidamento
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Long getIdTipoAffidamento() {
        return idTipoAffidamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.id_tipo_affidamento
     *
     * @param idTipoAffidamento the value for sirtplc_t_contratto.id_tipo_affidamento
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setIdTipoAffidamento(Long idTipoAffidamento) {
        this.idTipoAffidamento = idTipoAffidamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.id_modalita_affidamento
     *
     * @return the value of sirtplc_t_contratto.id_modalita_affidamento
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Long getIdModalitaAffidamento() {
        return idModalitaAffidamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.id_modalita_affidamento
     *
     * @param idModalitaAffidamento the value for sirtplc_t_contratto.id_modalita_affidamento
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setIdModalitaAffidamento(Long idModalitaAffidamento) {
        this.idModalitaAffidamento = idModalitaAffidamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.accordo_programma
     *
     * @return the value of sirtplc_t_contratto.accordo_programma
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public String getAccordoProgramma() {
        return accordoProgramma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.accordo_programma
     *
     * @param accordoProgramma the value for sirtplc_t_contratto.accordo_programma
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setAccordoProgramma(String accordoProgramma) {
        this.accordoProgramma = accordoProgramma == null ? null : accordoProgramma.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.gross_cost
     *
     * @return the value of sirtplc_t_contratto.gross_cost
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Boolean getGrossCost() {
        return grossCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.gross_cost
     *
     * @param grossCost the value for sirtplc_t_contratto.gross_cost
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setGrossCost(Boolean grossCost) {
        this.grossCost = grossCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.cig
     *
     * @return the value of sirtplc_t_contratto.cig
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public String getCig() {
        return cig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.cig
     *
     * @param cig the value for sirtplc_t_contratto.cig
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setCig(String cig) {
        this.cig = cig == null ? null : cig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.data_stipula
     *
     * @return the value of sirtplc_t_contratto.data_stipula
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Date getDataStipula() {
        return dataStipula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.data_stipula
     *
     * @param dataStipula the value for sirtplc_t_contratto.data_stipula
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setDataStipula(Date dataStipula) {
        this.dataStipula = dataStipula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.desc_contratto
     *
     * @return the value of sirtplc_t_contratto.desc_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public String getDescContratto() {
        return descContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.desc_contratto
     *
     * @param descContratto the value for sirtplc_t_contratto.desc_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setDescContratto(String descContratto) {
        this.descContratto = descContratto == null ? null : descContratto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.id_bacino
     *
     * @return the value of sirtplc_t_contratto.id_bacino
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Long getIdBacino() {
        return idBacino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.id_bacino
     *
     * @param idBacino the value for sirtplc_t_contratto.id_bacino
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setIdBacino(Long idBacino) {
        this.idBacino = idBacino;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.id_utente_aggiornamento
     *
     * @return the value of sirtplc_t_contratto.id_utente_aggiornamento
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Long getIdUtenteAggiornamento() {
        return idUtenteAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.id_utente_aggiornamento
     *
     * @param idUtenteAggiornamento the value for sirtplc_t_contratto.id_utente_aggiornamento
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setIdUtenteAggiornamento(Long idUtenteAggiornamento) {
        this.idUtenteAggiornamento = idUtenteAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.data_aggiornamento
     *
     * @return the value of sirtplc_t_contratto.data_aggiornamento
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Date getDataAggiornamento() {
        return dataAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.data_aggiornamento
     *
     * @param dataAggiornamento the value for sirtplc_t_contratto.data_aggiornamento
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setDataAggiornamento(Date dataAggiornamento) {
        this.dataAggiornamento = dataAggiornamento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.data_inizio_validita
     *
     * @return the value of sirtplc_t_contratto.data_inizio_validita
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Date getDataInizioValidita() {
        return dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.data_inizio_validita
     *
     * @param dataInizioValidita the value for sirtplc_t_contratto.data_inizio_validita
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setDataInizioValidita(Date dataInizioValidita) {
        this.dataInizioValidita = dataInizioValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_t_contratto.data_fine_validita
     *
     * @return the value of sirtplc_t_contratto.data_fine_validita
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Date getDataFineValidita() {
        return dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_t_contratto.data_fine_validita
     *
     * @param dataFineValidita the value for sirtplc_t_contratto.data_fine_validita
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setDataFineValidita(Date dataFineValidita) {
        this.dataFineValidita = dataFineValidita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idContratto=").append(idContratto);
        sb.append(", idContrattoPadre=").append(idContrattoPadre);
        sb.append(", codIdNazionale=").append(codIdNazionale);
        sb.append(", codIdRegionale=").append(codIdRegionale);
        sb.append(", numRepertorio=").append(numRepertorio);
        sb.append(", idSogGiuridCommittente=").append(idSogGiuridCommittente);
        sb.append(", idSogGiuridEsecutore=").append(idSogGiuridEsecutore);
        sb.append(", idTipoSogGiuridEsec=").append(idTipoSogGiuridEsec);
        sb.append(", idTipoRaggrSogGiuridEsec=").append(idTipoRaggrSogGiuridEsec);
        sb.append(", idTipoAffidamento=").append(idTipoAffidamento);
        sb.append(", idModalitaAffidamento=").append(idModalitaAffidamento);
        sb.append(", accordoProgramma=").append(accordoProgramma);
        sb.append(", grossCost=").append(grossCost);
        sb.append(", cig=").append(cig);
        sb.append(", dataStipula=").append(dataStipula);
        sb.append(", descContratto=").append(descContratto);
        sb.append(", idBacino=").append(idBacino);
        sb.append(", idUtenteAggiornamento=").append(idUtenteAggiornamento);
        sb.append(", dataAggiornamento=").append(dataAggiornamento);
        sb.append(", dataInizioValidita=").append(dataInizioValidita);
        sb.append(", dataFineValidita=").append(dataFineValidita);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}