/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class SirtplcRSostSogContrRaggrDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtplc_r_sost_sog_contr_raggr.id_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	private Long idSostSogContrRaggr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtplc_r_sost_sog_contr_raggr.id_contratto_raggrupp
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	private Long idContrattoRaggrupp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtplc_r_sost_sog_contr_raggr.id_soggetto_giuridico
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	private Long idSoggettoGiuridico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtplc_r_sost_sog_contr_raggr.atto_sostituzione
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	private String attoSostituzione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtplc_r_sost_sog_contr_raggr.data_sostituzione
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	private Date dataSostituzione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sirtplc_r_sost_sog_contr_raggr.id_tipo_sostituzione
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	private Long idTipoSostituzione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table sirtplc_r_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtplc_r_sost_sog_contr_raggr.id_sost_sog_contr_raggr
	 * @return  the value of sirtplc_r_sost_sog_contr_raggr.id_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	public Long getIdSostSogContrRaggr() {
		return idSostSogContrRaggr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtplc_r_sost_sog_contr_raggr.id_sost_sog_contr_raggr
	 * @param idSostSogContrRaggr  the value for sirtplc_r_sost_sog_contr_raggr.id_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	public void setIdSostSogContrRaggr(Long idSostSogContrRaggr) {
		this.idSostSogContrRaggr = idSostSogContrRaggr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtplc_r_sost_sog_contr_raggr.id_contratto_raggrupp
	 * @return  the value of sirtplc_r_sost_sog_contr_raggr.id_contratto_raggrupp
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	public Long getIdContrattoRaggrupp() {
		return idContrattoRaggrupp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtplc_r_sost_sog_contr_raggr.id_contratto_raggrupp
	 * @param idContrattoRaggrupp  the value for sirtplc_r_sost_sog_contr_raggr.id_contratto_raggrupp
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	public void setIdContrattoRaggrupp(Long idContrattoRaggrupp) {
		this.idContrattoRaggrupp = idContrattoRaggrupp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtplc_r_sost_sog_contr_raggr.id_soggetto_giuridico
	 * @return  the value of sirtplc_r_sost_sog_contr_raggr.id_soggetto_giuridico
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	public Long getIdSoggettoGiuridico() {
		return idSoggettoGiuridico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtplc_r_sost_sog_contr_raggr.id_soggetto_giuridico
	 * @param idSoggettoGiuridico  the value for sirtplc_r_sost_sog_contr_raggr.id_soggetto_giuridico
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	public void setIdSoggettoGiuridico(Long idSoggettoGiuridico) {
		this.idSoggettoGiuridico = idSoggettoGiuridico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtplc_r_sost_sog_contr_raggr.atto_sostituzione
	 * @return  the value of sirtplc_r_sost_sog_contr_raggr.atto_sostituzione
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	public String getAttoSostituzione() {
		return attoSostituzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtplc_r_sost_sog_contr_raggr.atto_sostituzione
	 * @param attoSostituzione  the value for sirtplc_r_sost_sog_contr_raggr.atto_sostituzione
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	public void setAttoSostituzione(String attoSostituzione) {
		this.attoSostituzione = attoSostituzione == null ? null : attoSostituzione.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtplc_r_sost_sog_contr_raggr.data_sostituzione
	 * @return  the value of sirtplc_r_sost_sog_contr_raggr.data_sostituzione
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	public Date getDataSostituzione() {
		return dataSostituzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtplc_r_sost_sog_contr_raggr.data_sostituzione
	 * @param dataSostituzione  the value for sirtplc_r_sost_sog_contr_raggr.data_sostituzione
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	public void setDataSostituzione(Date dataSostituzione) {
		this.dataSostituzione = dataSostituzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sirtplc_r_sost_sog_contr_raggr.id_tipo_sostituzione
	 * @return  the value of sirtplc_r_sost_sog_contr_raggr.id_tipo_sostituzione
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	public Long getIdTipoSostituzione() {
		return idTipoSostituzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sirtplc_r_sost_sog_contr_raggr.id_tipo_sostituzione
	 * @param idTipoSostituzione  the value for sirtplc_r_sost_sog_contr_raggr.id_tipo_sostituzione
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	public void setIdTipoSostituzione(Long idTipoSostituzione) {
		this.idTipoSostituzione = idTipoSostituzione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", idSostSogContrRaggr=").append(idSostSogContrRaggr);
		sb.append(", idContrattoRaggrupp=").append(idContrattoRaggrupp);
		sb.append(", idSoggettoGiuridico=").append(idSoggettoGiuridico);
		sb.append(", attoSostituzione=").append(attoSostituzione);
		sb.append(", dataSostituzione=").append(dataSostituzione);
		sb.append(", idTipoSostituzione=").append(idTipoSostituzione);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}