/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class SirtplcRSostSogContrDTO extends ParentDTO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_r_sost_sog_contr.id_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    private Long idSostSogContr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_r_sost_sog_contr.id_contratto
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    private Long idContratto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_r_sost_sog_contr.id_sog_giurid_committente
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    private Long idSogGiuridCommittente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_r_sost_sog_contr.id_sog_giurid_esecutore
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    private Long idSogGiuridEsecutore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_r_sost_sog_contr.atto_sostituzione
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    private String attoSostituzione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_r_sost_sog_contr.data_sostituzione
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    private Date dataSostituzione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sirtplc_r_sost_sog_contr.id_tipo_sostituzione
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    private Long idTipoSostituzione;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirtplc_r_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_r_sost_sog_contr.id_sost_sog_contr
     *
     * @return the value of sirtplc_r_sost_sog_contr.id_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    public Long getIdSostSogContr() {
        return idSostSogContr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_r_sost_sog_contr.id_sost_sog_contr
     *
     * @param idSostSogContr the value for sirtplc_r_sost_sog_contr.id_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    public void setIdSostSogContr(Long idSostSogContr) {
        this.idSostSogContr = idSostSogContr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_r_sost_sog_contr.id_contratto
     *
     * @return the value of sirtplc_r_sost_sog_contr.id_contratto
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    public Long getIdContratto() {
        return idContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_r_sost_sog_contr.id_contratto
     *
     * @param idContratto the value for sirtplc_r_sost_sog_contr.id_contratto
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    public void setIdContratto(Long idContratto) {
        this.idContratto = idContratto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_r_sost_sog_contr.id_sog_giurid_committente
     *
     * @return the value of sirtplc_r_sost_sog_contr.id_sog_giurid_committente
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    public Long getIdSogGiuridCommittente() {
        return idSogGiuridCommittente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_r_sost_sog_contr.id_sog_giurid_committente
     *
     * @param idSogGiuridCommittente the value for sirtplc_r_sost_sog_contr.id_sog_giurid_committente
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    public void setIdSogGiuridCommittente(Long idSogGiuridCommittente) {
        this.idSogGiuridCommittente = idSogGiuridCommittente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_r_sost_sog_contr.id_sog_giurid_esecutore
     *
     * @return the value of sirtplc_r_sost_sog_contr.id_sog_giurid_esecutore
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    public Long getIdSogGiuridEsecutore() {
        return idSogGiuridEsecutore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_r_sost_sog_contr.id_sog_giurid_esecutore
     *
     * @param idSogGiuridEsecutore the value for sirtplc_r_sost_sog_contr.id_sog_giurid_esecutore
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    public void setIdSogGiuridEsecutore(Long idSogGiuridEsecutore) {
        this.idSogGiuridEsecutore = idSogGiuridEsecutore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_r_sost_sog_contr.atto_sostituzione
     *
     * @return the value of sirtplc_r_sost_sog_contr.atto_sostituzione
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    public String getAttoSostituzione() {
        return attoSostituzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_r_sost_sog_contr.atto_sostituzione
     *
     * @param attoSostituzione the value for sirtplc_r_sost_sog_contr.atto_sostituzione
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    public void setAttoSostituzione(String attoSostituzione) {
        this.attoSostituzione = attoSostituzione == null ? null : attoSostituzione.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_r_sost_sog_contr.data_sostituzione
     *
     * @return the value of sirtplc_r_sost_sog_contr.data_sostituzione
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    public Date getDataSostituzione() {
        return dataSostituzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_r_sost_sog_contr.data_sostituzione
     *
     * @param dataSostituzione the value for sirtplc_r_sost_sog_contr.data_sostituzione
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    public void setDataSostituzione(Date dataSostituzione) {
        this.dataSostituzione = dataSostituzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sirtplc_r_sost_sog_contr.id_tipo_sostituzione
     *
     * @return the value of sirtplc_r_sost_sog_contr.id_tipo_sostituzione
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    public Long getIdTipoSostituzione() {
        return idTipoSostituzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sirtplc_r_sost_sog_contr.id_tipo_sostituzione
     *
     * @param idTipoSostituzione the value for sirtplc_r_sost_sog_contr.id_tipo_sostituzione
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    public void setIdTipoSostituzione(Long idTipoSostituzione) {
        this.idTipoSostituzione = idTipoSostituzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", idSostSogContr=").append(idSostSogContr);
        sb.append(", idContratto=").append(idContratto);
        sb.append(", idSogGiuridCommittente=").append(idSogGiuridCommittente);
        sb.append(", idSogGiuridEsecutore=").append(idSogGiuridEsecutore);
        sb.append(", attoSostituzione=").append(attoSostituzione);
        sb.append(", dataSostituzione=").append(dataSostituzione);
        sb.append(", idTipoSostituzione=").append(idTipoSostituzione);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}