/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SirtplcTContrattoSelector {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public SirtplcTContrattoSelector() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdContrattoIsNull() {
            addCriterion("id_contratto is null");
            return (Criteria) this;
        }

        public Criteria andIdContrattoIsNotNull() {
            addCriterion("id_contratto is not null");
            return (Criteria) this;
        }

        public Criteria andIdContrattoEqualTo(Long value) {
            addCriterion("id_contratto =", value, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoNotEqualTo(Long value) {
            addCriterion("id_contratto <>", value, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoGreaterThan(Long value) {
            addCriterion("id_contratto >", value, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoGreaterThanOrEqualTo(Long value) {
            addCriterion("id_contratto >=", value, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoLessThan(Long value) {
            addCriterion("id_contratto <", value, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoLessThanOrEqualTo(Long value) {
            addCriterion("id_contratto <=", value, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoIn(List<Long> values) {
            addCriterion("id_contratto in", values, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoNotIn(List<Long> values) {
            addCriterion("id_contratto not in", values, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoBetween(Long value1, Long value2) {
            addCriterion("id_contratto between", value1, value2, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoNotBetween(Long value1, Long value2) {
            addCriterion("id_contratto not between", value1, value2, "idContratto");
            return (Criteria) this;
        }

        public Criteria andIdContrattoPadreIsNull() {
            addCriterion("id_contratto_padre is null");
            return (Criteria) this;
        }

        public Criteria andIdContrattoPadreIsNotNull() {
            addCriterion("id_contratto_padre is not null");
            return (Criteria) this;
        }

        public Criteria andIdContrattoPadreEqualTo(Long value) {
            addCriterion("id_contratto_padre =", value, "idContrattoPadre");
            return (Criteria) this;
        }

        public Criteria andIdContrattoPadreNotEqualTo(Long value) {
            addCriterion("id_contratto_padre <>", value, "idContrattoPadre");
            return (Criteria) this;
        }

        public Criteria andIdContrattoPadreGreaterThan(Long value) {
            addCriterion("id_contratto_padre >", value, "idContrattoPadre");
            return (Criteria) this;
        }

        public Criteria andIdContrattoPadreGreaterThanOrEqualTo(Long value) {
            addCriterion("id_contratto_padre >=", value, "idContrattoPadre");
            return (Criteria) this;
        }

        public Criteria andIdContrattoPadreLessThan(Long value) {
            addCriterion("id_contratto_padre <", value, "idContrattoPadre");
            return (Criteria) this;
        }

        public Criteria andIdContrattoPadreLessThanOrEqualTo(Long value) {
            addCriterion("id_contratto_padre <=", value, "idContrattoPadre");
            return (Criteria) this;
        }

        public Criteria andIdContrattoPadreIn(List<Long> values) {
            addCriterion("id_contratto_padre in", values, "idContrattoPadre");
            return (Criteria) this;
        }

        public Criteria andIdContrattoPadreNotIn(List<Long> values) {
            addCriterion("id_contratto_padre not in", values, "idContrattoPadre");
            return (Criteria) this;
        }

        public Criteria andIdContrattoPadreBetween(Long value1, Long value2) {
            addCriterion("id_contratto_padre between", value1, value2, "idContrattoPadre");
            return (Criteria) this;
        }

        public Criteria andIdContrattoPadreNotBetween(Long value1, Long value2) {
            addCriterion("id_contratto_padre not between", value1, value2, "idContrattoPadre");
            return (Criteria) this;
        }

        public Criteria andCodIdNazionaleIsNull() {
            addCriterion("cod_id_nazionale is null");
            return (Criteria) this;
        }

        public Criteria andCodIdNazionaleIsNotNull() {
            addCriterion("cod_id_nazionale is not null");
            return (Criteria) this;
        }

        public Criteria andCodIdNazionaleEqualTo(String value) {
            addCriterion("cod_id_nazionale =", value, "codIdNazionale");
            return (Criteria) this;
        }

        public Criteria andCodIdNazionaleNotEqualTo(String value) {
            addCriterion("cod_id_nazionale <>", value, "codIdNazionale");
            return (Criteria) this;
        }

        public Criteria andCodIdNazionaleGreaterThan(String value) {
            addCriterion("cod_id_nazionale >", value, "codIdNazionale");
            return (Criteria) this;
        }

        public Criteria andCodIdNazionaleGreaterThanOrEqualTo(String value) {
            addCriterion("cod_id_nazionale >=", value, "codIdNazionale");
            return (Criteria) this;
        }

        public Criteria andCodIdNazionaleLessThan(String value) {
            addCriterion("cod_id_nazionale <", value, "codIdNazionale");
            return (Criteria) this;
        }

        public Criteria andCodIdNazionaleLessThanOrEqualTo(String value) {
            addCriterion("cod_id_nazionale <=", value, "codIdNazionale");
            return (Criteria) this;
        }

        public Criteria andCodIdNazionaleLike(String value) {
            addCriterion("cod_id_nazionale like", value, "codIdNazionale");
            return (Criteria) this;
        }

        public Criteria andCodIdNazionaleNotLike(String value) {
            addCriterion("cod_id_nazionale not like", value, "codIdNazionale");
            return (Criteria) this;
        }

        public Criteria andCodIdNazionaleIn(List<String> values) {
            addCriterion("cod_id_nazionale in", values, "codIdNazionale");
            return (Criteria) this;
        }

        public Criteria andCodIdNazionaleNotIn(List<String> values) {
            addCriterion("cod_id_nazionale not in", values, "codIdNazionale");
            return (Criteria) this;
        }

        public Criteria andCodIdNazionaleBetween(String value1, String value2) {
            addCriterion("cod_id_nazionale between", value1, value2, "codIdNazionale");
            return (Criteria) this;
        }

        public Criteria andCodIdNazionaleNotBetween(String value1, String value2) {
            addCriterion("cod_id_nazionale not between", value1, value2, "codIdNazionale");
            return (Criteria) this;
        }

        public Criteria andCodIdRegionaleIsNull() {
            addCriterion("cod_id_regionale is null");
            return (Criteria) this;
        }

        public Criteria andCodIdRegionaleIsNotNull() {
            addCriterion("cod_id_regionale is not null");
            return (Criteria) this;
        }

        public Criteria andCodIdRegionaleEqualTo(String value) {
            addCriterion("cod_id_regionale =", value, "codIdRegionale");
            return (Criteria) this;
        }

        public Criteria andCodIdRegionaleNotEqualTo(String value) {
            addCriterion("cod_id_regionale <>", value, "codIdRegionale");
            return (Criteria) this;
        }

        public Criteria andCodIdRegionaleGreaterThan(String value) {
            addCriterion("cod_id_regionale >", value, "codIdRegionale");
            return (Criteria) this;
        }

        public Criteria andCodIdRegionaleGreaterThanOrEqualTo(String value) {
            addCriterion("cod_id_regionale >=", value, "codIdRegionale");
            return (Criteria) this;
        }

        public Criteria andCodIdRegionaleLessThan(String value) {
            addCriterion("cod_id_regionale <", value, "codIdRegionale");
            return (Criteria) this;
        }

        public Criteria andCodIdRegionaleLessThanOrEqualTo(String value) {
            addCriterion("cod_id_regionale <=", value, "codIdRegionale");
            return (Criteria) this;
        }

        public Criteria andCodIdRegionaleLike(String value) {
            addCriterion("cod_id_regionale like", value, "codIdRegionale");
            return (Criteria) this;
        }

        public Criteria andCodIdRegionaleNotLike(String value) {
            addCriterion("cod_id_regionale not like", value, "codIdRegionale");
            return (Criteria) this;
        }

        public Criteria andCodIdRegionaleIn(List<String> values) {
            addCriterion("cod_id_regionale in", values, "codIdRegionale");
            return (Criteria) this;
        }

        public Criteria andCodIdRegionaleNotIn(List<String> values) {
            addCriterion("cod_id_regionale not in", values, "codIdRegionale");
            return (Criteria) this;
        }

        public Criteria andCodIdRegionaleBetween(String value1, String value2) {
            addCriterion("cod_id_regionale between", value1, value2, "codIdRegionale");
            return (Criteria) this;
        }

        public Criteria andCodIdRegionaleNotBetween(String value1, String value2) {
            addCriterion("cod_id_regionale not between", value1, value2, "codIdRegionale");
            return (Criteria) this;
        }

        public Criteria andNumRepertorioIsNull() {
            addCriterion("num_repertorio is null");
            return (Criteria) this;
        }

        public Criteria andNumRepertorioIsNotNull() {
            addCriterion("num_repertorio is not null");
            return (Criteria) this;
        }

        public Criteria andNumRepertorioEqualTo(String value) {
            addCriterion("num_repertorio =", value, "numRepertorio");
            return (Criteria) this;
        }

        public Criteria andNumRepertorioNotEqualTo(String value) {
            addCriterion("num_repertorio <>", value, "numRepertorio");
            return (Criteria) this;
        }

        public Criteria andNumRepertorioGreaterThan(String value) {
            addCriterion("num_repertorio >", value, "numRepertorio");
            return (Criteria) this;
        }

        public Criteria andNumRepertorioGreaterThanOrEqualTo(String value) {
            addCriterion("num_repertorio >=", value, "numRepertorio");
            return (Criteria) this;
        }

        public Criteria andNumRepertorioLessThan(String value) {
            addCriterion("num_repertorio <", value, "numRepertorio");
            return (Criteria) this;
        }

        public Criteria andNumRepertorioLessThanOrEqualTo(String value) {
            addCriterion("num_repertorio <=", value, "numRepertorio");
            return (Criteria) this;
        }

        public Criteria andNumRepertorioLike(String value) {
            addCriterion("num_repertorio like", value, "numRepertorio");
            return (Criteria) this;
        }

        public Criteria andNumRepertorioNotLike(String value) {
            addCriterion("num_repertorio not like", value, "numRepertorio");
            return (Criteria) this;
        }

        public Criteria andNumRepertorioIn(List<String> values) {
            addCriterion("num_repertorio in", values, "numRepertorio");
            return (Criteria) this;
        }

        public Criteria andNumRepertorioNotIn(List<String> values) {
            addCriterion("num_repertorio not in", values, "numRepertorio");
            return (Criteria) this;
        }

        public Criteria andNumRepertorioBetween(String value1, String value2) {
            addCriterion("num_repertorio between", value1, value2, "numRepertorio");
            return (Criteria) this;
        }

        public Criteria andNumRepertorioNotBetween(String value1, String value2) {
            addCriterion("num_repertorio not between", value1, value2, "numRepertorio");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridCommittenteIsNull() {
            addCriterion("id_sog_giurid_committente is null");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridCommittenteIsNotNull() {
            addCriterion("id_sog_giurid_committente is not null");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridCommittenteEqualTo(Long value) {
            addCriterion("id_sog_giurid_committente =", value, "idSogGiuridCommittente");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridCommittenteNotEqualTo(Long value) {
            addCriterion("id_sog_giurid_committente <>", value, "idSogGiuridCommittente");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridCommittenteGreaterThan(Long value) {
            addCriterion("id_sog_giurid_committente >", value, "idSogGiuridCommittente");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridCommittenteGreaterThanOrEqualTo(Long value) {
            addCriterion("id_sog_giurid_committente >=", value, "idSogGiuridCommittente");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridCommittenteLessThan(Long value) {
            addCriterion("id_sog_giurid_committente <", value, "idSogGiuridCommittente");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridCommittenteLessThanOrEqualTo(Long value) {
            addCriterion("id_sog_giurid_committente <=", value, "idSogGiuridCommittente");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridCommittenteIn(List<Long> values) {
            addCriterion("id_sog_giurid_committente in", values, "idSogGiuridCommittente");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridCommittenteNotIn(List<Long> values) {
            addCriterion("id_sog_giurid_committente not in", values, "idSogGiuridCommittente");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridCommittenteBetween(Long value1, Long value2) {
            addCriterion("id_sog_giurid_committente between", value1, value2, "idSogGiuridCommittente");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridCommittenteNotBetween(Long value1, Long value2) {
            addCriterion("id_sog_giurid_committente not between", value1, value2, "idSogGiuridCommittente");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridEsecutoreIsNull() {
            addCriterion("id_sog_giurid_esecutore is null");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridEsecutoreIsNotNull() {
            addCriterion("id_sog_giurid_esecutore is not null");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridEsecutoreEqualTo(Long value) {
            addCriterion("id_sog_giurid_esecutore =", value, "idSogGiuridEsecutore");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridEsecutoreNotEqualTo(Long value) {
            addCriterion("id_sog_giurid_esecutore <>", value, "idSogGiuridEsecutore");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridEsecutoreGreaterThan(Long value) {
            addCriterion("id_sog_giurid_esecutore >", value, "idSogGiuridEsecutore");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridEsecutoreGreaterThanOrEqualTo(Long value) {
            addCriterion("id_sog_giurid_esecutore >=", value, "idSogGiuridEsecutore");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridEsecutoreLessThan(Long value) {
            addCriterion("id_sog_giurid_esecutore <", value, "idSogGiuridEsecutore");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridEsecutoreLessThanOrEqualTo(Long value) {
            addCriterion("id_sog_giurid_esecutore <=", value, "idSogGiuridEsecutore");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridEsecutoreIn(List<Long> values) {
            addCriterion("id_sog_giurid_esecutore in", values, "idSogGiuridEsecutore");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridEsecutoreNotIn(List<Long> values) {
            addCriterion("id_sog_giurid_esecutore not in", values, "idSogGiuridEsecutore");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridEsecutoreBetween(Long value1, Long value2) {
            addCriterion("id_sog_giurid_esecutore between", value1, value2, "idSogGiuridEsecutore");
            return (Criteria) this;
        }

        public Criteria andIdSogGiuridEsecutoreNotBetween(Long value1, Long value2) {
            addCriterion("id_sog_giurid_esecutore not between", value1, value2, "idSogGiuridEsecutore");
            return (Criteria) this;
        }

        public Criteria andIdTipoSogGiuridEsecIsNull() {
            addCriterion("id_tipo_sog_giurid_esec is null");
            return (Criteria) this;
        }

        public Criteria andIdTipoSogGiuridEsecIsNotNull() {
            addCriterion("id_tipo_sog_giurid_esec is not null");
            return (Criteria) this;
        }

        public Criteria andIdTipoSogGiuridEsecEqualTo(Long value) {
            addCriterion("id_tipo_sog_giurid_esec =", value, "idTipoSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoSogGiuridEsecNotEqualTo(Long value) {
            addCriterion("id_tipo_sog_giurid_esec <>", value, "idTipoSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoSogGiuridEsecGreaterThan(Long value) {
            addCriterion("id_tipo_sog_giurid_esec >", value, "idTipoSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoSogGiuridEsecGreaterThanOrEqualTo(Long value) {
            addCriterion("id_tipo_sog_giurid_esec >=", value, "idTipoSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoSogGiuridEsecLessThan(Long value) {
            addCriterion("id_tipo_sog_giurid_esec <", value, "idTipoSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoSogGiuridEsecLessThanOrEqualTo(Long value) {
            addCriterion("id_tipo_sog_giurid_esec <=", value, "idTipoSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoSogGiuridEsecIn(List<Long> values) {
            addCriterion("id_tipo_sog_giurid_esec in", values, "idTipoSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoSogGiuridEsecNotIn(List<Long> values) {
            addCriterion("id_tipo_sog_giurid_esec not in", values, "idTipoSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoSogGiuridEsecBetween(Long value1, Long value2) {
            addCriterion("id_tipo_sog_giurid_esec between", value1, value2, "idTipoSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoSogGiuridEsecNotBetween(Long value1, Long value2) {
            addCriterion("id_tipo_sog_giurid_esec not between", value1, value2, "idTipoSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoRaggrSogGiuridEsecIsNull() {
            addCriterion("id_tipo_raggr_sog_giurid_esec is null");
            return (Criteria) this;
        }

        public Criteria andIdTipoRaggrSogGiuridEsecIsNotNull() {
            addCriterion("id_tipo_raggr_sog_giurid_esec is not null");
            return (Criteria) this;
        }

        public Criteria andIdTipoRaggrSogGiuridEsecEqualTo(Long value) {
            addCriterion("id_tipo_raggr_sog_giurid_esec =", value, "idTipoRaggrSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoRaggrSogGiuridEsecNotEqualTo(Long value) {
            addCriterion("id_tipo_raggr_sog_giurid_esec <>", value, "idTipoRaggrSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoRaggrSogGiuridEsecGreaterThan(Long value) {
            addCriterion("id_tipo_raggr_sog_giurid_esec >", value, "idTipoRaggrSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoRaggrSogGiuridEsecGreaterThanOrEqualTo(Long value) {
            addCriterion("id_tipo_raggr_sog_giurid_esec >=", value, "idTipoRaggrSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoRaggrSogGiuridEsecLessThan(Long value) {
            addCriterion("id_tipo_raggr_sog_giurid_esec <", value, "idTipoRaggrSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoRaggrSogGiuridEsecLessThanOrEqualTo(Long value) {
            addCriterion("id_tipo_raggr_sog_giurid_esec <=", value, "idTipoRaggrSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoRaggrSogGiuridEsecIn(List<Long> values) {
            addCriterion("id_tipo_raggr_sog_giurid_esec in", values, "idTipoRaggrSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoRaggrSogGiuridEsecNotIn(List<Long> values) {
            addCriterion("id_tipo_raggr_sog_giurid_esec not in", values, "idTipoRaggrSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoRaggrSogGiuridEsecBetween(Long value1, Long value2) {
            addCriterion("id_tipo_raggr_sog_giurid_esec between", value1, value2, "idTipoRaggrSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoRaggrSogGiuridEsecNotBetween(Long value1, Long value2) {
            addCriterion("id_tipo_raggr_sog_giurid_esec not between", value1, value2, "idTipoRaggrSogGiuridEsec");
            return (Criteria) this;
        }

        public Criteria andIdTipoAffidamentoIsNull() {
            addCriterion("id_tipo_affidamento is null");
            return (Criteria) this;
        }

        public Criteria andIdTipoAffidamentoIsNotNull() {
            addCriterion("id_tipo_affidamento is not null");
            return (Criteria) this;
        }

        public Criteria andIdTipoAffidamentoEqualTo(Long value) {
            addCriterion("id_tipo_affidamento =", value, "idTipoAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdTipoAffidamentoNotEqualTo(Long value) {
            addCriterion("id_tipo_affidamento <>", value, "idTipoAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdTipoAffidamentoGreaterThan(Long value) {
            addCriterion("id_tipo_affidamento >", value, "idTipoAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdTipoAffidamentoGreaterThanOrEqualTo(Long value) {
            addCriterion("id_tipo_affidamento >=", value, "idTipoAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdTipoAffidamentoLessThan(Long value) {
            addCriterion("id_tipo_affidamento <", value, "idTipoAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdTipoAffidamentoLessThanOrEqualTo(Long value) {
            addCriterion("id_tipo_affidamento <=", value, "idTipoAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdTipoAffidamentoIn(List<Long> values) {
            addCriterion("id_tipo_affidamento in", values, "idTipoAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdTipoAffidamentoNotIn(List<Long> values) {
            addCriterion("id_tipo_affidamento not in", values, "idTipoAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdTipoAffidamentoBetween(Long value1, Long value2) {
            addCriterion("id_tipo_affidamento between", value1, value2, "idTipoAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdTipoAffidamentoNotBetween(Long value1, Long value2) {
            addCriterion("id_tipo_affidamento not between", value1, value2, "idTipoAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdModalitaAffidamentoIsNull() {
            addCriterion("id_modalita_affidamento is null");
            return (Criteria) this;
        }

        public Criteria andIdModalitaAffidamentoIsNotNull() {
            addCriterion("id_modalita_affidamento is not null");
            return (Criteria) this;
        }

        public Criteria andIdModalitaAffidamentoEqualTo(Long value) {
            addCriterion("id_modalita_affidamento =", value, "idModalitaAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdModalitaAffidamentoNotEqualTo(Long value) {
            addCriterion("id_modalita_affidamento <>", value, "idModalitaAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdModalitaAffidamentoGreaterThan(Long value) {
            addCriterion("id_modalita_affidamento >", value, "idModalitaAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdModalitaAffidamentoGreaterThanOrEqualTo(Long value) {
            addCriterion("id_modalita_affidamento >=", value, "idModalitaAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdModalitaAffidamentoLessThan(Long value) {
            addCriterion("id_modalita_affidamento <", value, "idModalitaAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdModalitaAffidamentoLessThanOrEqualTo(Long value) {
            addCriterion("id_modalita_affidamento <=", value, "idModalitaAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdModalitaAffidamentoIn(List<Long> values) {
            addCriterion("id_modalita_affidamento in", values, "idModalitaAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdModalitaAffidamentoNotIn(List<Long> values) {
            addCriterion("id_modalita_affidamento not in", values, "idModalitaAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdModalitaAffidamentoBetween(Long value1, Long value2) {
            addCriterion("id_modalita_affidamento between", value1, value2, "idModalitaAffidamento");
            return (Criteria) this;
        }

        public Criteria andIdModalitaAffidamentoNotBetween(Long value1, Long value2) {
            addCriterion("id_modalita_affidamento not between", value1, value2, "idModalitaAffidamento");
            return (Criteria) this;
        }

        public Criteria andAccordoProgrammaIsNull() {
            addCriterion("accordo_programma is null");
            return (Criteria) this;
        }

        public Criteria andAccordoProgrammaIsNotNull() {
            addCriterion("accordo_programma is not null");
            return (Criteria) this;
        }

        public Criteria andAccordoProgrammaEqualTo(String value) {
            addCriterion("accordo_programma =", value, "accordoProgramma");
            return (Criteria) this;
        }

        public Criteria andAccordoProgrammaNotEqualTo(String value) {
            addCriterion("accordo_programma <>", value, "accordoProgramma");
            return (Criteria) this;
        }

        public Criteria andAccordoProgrammaGreaterThan(String value) {
            addCriterion("accordo_programma >", value, "accordoProgramma");
            return (Criteria) this;
        }

        public Criteria andAccordoProgrammaGreaterThanOrEqualTo(String value) {
            addCriterion("accordo_programma >=", value, "accordoProgramma");
            return (Criteria) this;
        }

        public Criteria andAccordoProgrammaLessThan(String value) {
            addCriterion("accordo_programma <", value, "accordoProgramma");
            return (Criteria) this;
        }

        public Criteria andAccordoProgrammaLessThanOrEqualTo(String value) {
            addCriterion("accordo_programma <=", value, "accordoProgramma");
            return (Criteria) this;
        }

        public Criteria andAccordoProgrammaLike(String value) {
            addCriterion("accordo_programma like", value, "accordoProgramma");
            return (Criteria) this;
        }

        public Criteria andAccordoProgrammaNotLike(String value) {
            addCriterion("accordo_programma not like", value, "accordoProgramma");
            return (Criteria) this;
        }

        public Criteria andAccordoProgrammaIn(List<String> values) {
            addCriterion("accordo_programma in", values, "accordoProgramma");
            return (Criteria) this;
        }

        public Criteria andAccordoProgrammaNotIn(List<String> values) {
            addCriterion("accordo_programma not in", values, "accordoProgramma");
            return (Criteria) this;
        }

        public Criteria andAccordoProgrammaBetween(String value1, String value2) {
            addCriterion("accordo_programma between", value1, value2, "accordoProgramma");
            return (Criteria) this;
        }

        public Criteria andAccordoProgrammaNotBetween(String value1, String value2) {
            addCriterion("accordo_programma not between", value1, value2, "accordoProgramma");
            return (Criteria) this;
        }

        public Criteria andGrossCostIsNull() {
            addCriterion("gross_cost is null");
            return (Criteria) this;
        }

        public Criteria andGrossCostIsNotNull() {
            addCriterion("gross_cost is not null");
            return (Criteria) this;
        }

        public Criteria andGrossCostEqualTo(Boolean value) {
            addCriterion("gross_cost =", value, "grossCost");
            return (Criteria) this;
        }

        public Criteria andGrossCostNotEqualTo(Boolean value) {
            addCriterion("gross_cost <>", value, "grossCost");
            return (Criteria) this;
        }

        public Criteria andGrossCostGreaterThan(Boolean value) {
            addCriterion("gross_cost >", value, "grossCost");
            return (Criteria) this;
        }

        public Criteria andGrossCostGreaterThanOrEqualTo(Boolean value) {
            addCriterion("gross_cost >=", value, "grossCost");
            return (Criteria) this;
        }

        public Criteria andGrossCostLessThan(Boolean value) {
            addCriterion("gross_cost <", value, "grossCost");
            return (Criteria) this;
        }

        public Criteria andGrossCostLessThanOrEqualTo(Boolean value) {
            addCriterion("gross_cost <=", value, "grossCost");
            return (Criteria) this;
        }

        public Criteria andGrossCostIn(List<Boolean> values) {
            addCriterion("gross_cost in", values, "grossCost");
            return (Criteria) this;
        }

        public Criteria andGrossCostNotIn(List<Boolean> values) {
            addCriterion("gross_cost not in", values, "grossCost");
            return (Criteria) this;
        }

        public Criteria andGrossCostBetween(Boolean value1, Boolean value2) {
            addCriterion("gross_cost between", value1, value2, "grossCost");
            return (Criteria) this;
        }

        public Criteria andGrossCostNotBetween(Boolean value1, Boolean value2) {
            addCriterion("gross_cost not between", value1, value2, "grossCost");
            return (Criteria) this;
        }

        public Criteria andCigIsNull() {
            addCriterion("cig is null");
            return (Criteria) this;
        }

        public Criteria andCigIsNotNull() {
            addCriterion("cig is not null");
            return (Criteria) this;
        }

        public Criteria andCigEqualTo(String value) {
            addCriterion("cig =", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigNotEqualTo(String value) {
            addCriterion("cig <>", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigGreaterThan(String value) {
            addCriterion("cig >", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigGreaterThanOrEqualTo(String value) {
            addCriterion("cig >=", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigLessThan(String value) {
            addCriterion("cig <", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigLessThanOrEqualTo(String value) {
            addCriterion("cig <=", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigLike(String value) {
            addCriterion("cig like", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigNotLike(String value) {
            addCriterion("cig not like", value, "cig");
            return (Criteria) this;
        }

        public Criteria andCigIn(List<String> values) {
            addCriterion("cig in", values, "cig");
            return (Criteria) this;
        }

        public Criteria andCigNotIn(List<String> values) {
            addCriterion("cig not in", values, "cig");
            return (Criteria) this;
        }

        public Criteria andCigBetween(String value1, String value2) {
            addCriterion("cig between", value1, value2, "cig");
            return (Criteria) this;
        }

        public Criteria andCigNotBetween(String value1, String value2) {
            addCriterion("cig not between", value1, value2, "cig");
            return (Criteria) this;
        }

        public Criteria andDataStipulaIsNull() {
            addCriterion("data_stipula is null");
            return (Criteria) this;
        }

        public Criteria andDataStipulaIsNotNull() {
            addCriterion("data_stipula is not null");
            return (Criteria) this;
        }

        public Criteria andDataStipulaEqualTo(Date value) {
            addCriterionForJDBCDate("data_stipula =", value, "dataStipula");
            return (Criteria) this;
        }

        public Criteria andDataStipulaNotEqualTo(Date value) {
            addCriterionForJDBCDate("data_stipula <>", value, "dataStipula");
            return (Criteria) this;
        }

        public Criteria andDataStipulaGreaterThan(Date value) {
            addCriterionForJDBCDate("data_stipula >", value, "dataStipula");
            return (Criteria) this;
        }

        public Criteria andDataStipulaGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_stipula >=", value, "dataStipula");
            return (Criteria) this;
        }

        public Criteria andDataStipulaLessThan(Date value) {
            addCriterionForJDBCDate("data_stipula <", value, "dataStipula");
            return (Criteria) this;
        }

        public Criteria andDataStipulaLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_stipula <=", value, "dataStipula");
            return (Criteria) this;
        }

        public Criteria andDataStipulaIn(List<Date> values) {
            addCriterionForJDBCDate("data_stipula in", values, "dataStipula");
            return (Criteria) this;
        }

        public Criteria andDataStipulaNotIn(List<Date> values) {
            addCriterionForJDBCDate("data_stipula not in", values, "dataStipula");
            return (Criteria) this;
        }

        public Criteria andDataStipulaBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_stipula between", value1, value2, "dataStipula");
            return (Criteria) this;
        }

        public Criteria andDataStipulaNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_stipula not between", value1, value2, "dataStipula");
            return (Criteria) this;
        }

        public Criteria andDescContrattoIsNull() {
            addCriterion("desc_contratto is null");
            return (Criteria) this;
        }

        public Criteria andDescContrattoIsNotNull() {
            addCriterion("desc_contratto is not null");
            return (Criteria) this;
        }

        public Criteria andDescContrattoEqualTo(String value) {
            addCriterion("desc_contratto =", value, "descContratto");
            return (Criteria) this;
        }

        public Criteria andDescContrattoNotEqualTo(String value) {
            addCriterion("desc_contratto <>", value, "descContratto");
            return (Criteria) this;
        }

        public Criteria andDescContrattoGreaterThan(String value) {
            addCriterion("desc_contratto >", value, "descContratto");
            return (Criteria) this;
        }

        public Criteria andDescContrattoGreaterThanOrEqualTo(String value) {
            addCriterion("desc_contratto >=", value, "descContratto");
            return (Criteria) this;
        }

        public Criteria andDescContrattoLessThan(String value) {
            addCriterion("desc_contratto <", value, "descContratto");
            return (Criteria) this;
        }

        public Criteria andDescContrattoLessThanOrEqualTo(String value) {
            addCriterion("desc_contratto <=", value, "descContratto");
            return (Criteria) this;
        }

        public Criteria andDescContrattoLike(String value) {
            addCriterion("desc_contratto like", value, "descContratto");
            return (Criteria) this;
        }

        public Criteria andDescContrattoNotLike(String value) {
            addCriterion("desc_contratto not like", value, "descContratto");
            return (Criteria) this;
        }

        public Criteria andDescContrattoIn(List<String> values) {
            addCriterion("desc_contratto in", values, "descContratto");
            return (Criteria) this;
        }

        public Criteria andDescContrattoNotIn(List<String> values) {
            addCriterion("desc_contratto not in", values, "descContratto");
            return (Criteria) this;
        }

        public Criteria andDescContrattoBetween(String value1, String value2) {
            addCriterion("desc_contratto between", value1, value2, "descContratto");
            return (Criteria) this;
        }

        public Criteria andDescContrattoNotBetween(String value1, String value2) {
            addCriterion("desc_contratto not between", value1, value2, "descContratto");
            return (Criteria) this;
        }

        public Criteria andIdBacinoIsNull() {
            addCriterion("id_bacino is null");
            return (Criteria) this;
        }

        public Criteria andIdBacinoIsNotNull() {
            addCriterion("id_bacino is not null");
            return (Criteria) this;
        }

        public Criteria andIdBacinoEqualTo(Long value) {
            addCriterion("id_bacino =", value, "idBacino");
            return (Criteria) this;
        }

        public Criteria andIdBacinoNotEqualTo(Long value) {
            addCriterion("id_bacino <>", value, "idBacino");
            return (Criteria) this;
        }

        public Criteria andIdBacinoGreaterThan(Long value) {
            addCriterion("id_bacino >", value, "idBacino");
            return (Criteria) this;
        }

        public Criteria andIdBacinoGreaterThanOrEqualTo(Long value) {
            addCriterion("id_bacino >=", value, "idBacino");
            return (Criteria) this;
        }

        public Criteria andIdBacinoLessThan(Long value) {
            addCriterion("id_bacino <", value, "idBacino");
            return (Criteria) this;
        }

        public Criteria andIdBacinoLessThanOrEqualTo(Long value) {
            addCriterion("id_bacino <=", value, "idBacino");
            return (Criteria) this;
        }

        public Criteria andIdBacinoIn(List<Long> values) {
            addCriterion("id_bacino in", values, "idBacino");
            return (Criteria) this;
        }

        public Criteria andIdBacinoNotIn(List<Long> values) {
            addCriterion("id_bacino not in", values, "idBacino");
            return (Criteria) this;
        }

        public Criteria andIdBacinoBetween(Long value1, Long value2) {
            addCriterion("id_bacino between", value1, value2, "idBacino");
            return (Criteria) this;
        }

        public Criteria andIdBacinoNotBetween(Long value1, Long value2) {
            addCriterion("id_bacino not between", value1, value2, "idBacino");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoIsNull() {
            addCriterion("id_utente_aggiornamento is null");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoIsNotNull() {
            addCriterion("id_utente_aggiornamento is not null");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento =", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoNotEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento <>", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoGreaterThan(Long value) {
            addCriterion("id_utente_aggiornamento >", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoGreaterThanOrEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento >=", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoLessThan(Long value) {
            addCriterion("id_utente_aggiornamento <", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoLessThanOrEqualTo(Long value) {
            addCriterion("id_utente_aggiornamento <=", value, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoIn(List<Long> values) {
            addCriterion("id_utente_aggiornamento in", values, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoNotIn(List<Long> values) {
            addCriterion("id_utente_aggiornamento not in", values, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoBetween(Long value1, Long value2) {
            addCriterion("id_utente_aggiornamento between", value1, value2, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andIdUtenteAggiornamentoNotBetween(Long value1, Long value2) {
            addCriterion("id_utente_aggiornamento not between", value1, value2, "idUtenteAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoIsNull() {
            addCriterion("data_aggiornamento is null");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoIsNotNull() {
            addCriterion("data_aggiornamento is not null");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoEqualTo(Date value) {
            addCriterion("data_aggiornamento =", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoNotEqualTo(Date value) {
            addCriterion("data_aggiornamento <>", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoGreaterThan(Date value) {
            addCriterion("data_aggiornamento >", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoGreaterThanOrEqualTo(Date value) {
            addCriterion("data_aggiornamento >=", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoLessThan(Date value) {
            addCriterion("data_aggiornamento <", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoLessThanOrEqualTo(Date value) {
            addCriterion("data_aggiornamento <=", value, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoIn(List<Date> values) {
            addCriterion("data_aggiornamento in", values, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoNotIn(List<Date> values) {
            addCriterion("data_aggiornamento not in", values, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoBetween(Date value1, Date value2) {
            addCriterion("data_aggiornamento between", value1, value2, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataAggiornamentoNotBetween(Date value1, Date value2) {
            addCriterion("data_aggiornamento not between", value1, value2, "dataAggiornamento");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaIsNull() {
            addCriterion("data_inizio_validita is null");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaIsNotNull() {
            addCriterion("data_inizio_validita is not null");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_validita =", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaNotEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_validita <>", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaGreaterThan(Date value) {
            addCriterionForJDBCDate("data_inizio_validita >", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_validita >=", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaLessThan(Date value) {
            addCriterionForJDBCDate("data_inizio_validita <", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_inizio_validita <=", value, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaIn(List<Date> values) {
            addCriterionForJDBCDate("data_inizio_validita in", values, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaNotIn(List<Date> values) {
            addCriterionForJDBCDate("data_inizio_validita not in", values, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_inizio_validita between", value1, value2, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataInizioValiditaNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_inizio_validita not between", value1, value2, "dataInizioValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaIsNull() {
            addCriterion("data_fine_validita is null");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaIsNotNull() {
            addCriterion("data_fine_validita is not null");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_validita =", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaNotEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_validita <>", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaGreaterThan(Date value) {
            addCriterionForJDBCDate("data_fine_validita >", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_validita >=", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaLessThan(Date value) {
            addCriterionForJDBCDate("data_fine_validita <", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("data_fine_validita <=", value, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaIn(List<Date> values) {
            addCriterionForJDBCDate("data_fine_validita in", values, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaNotIn(List<Date> values) {
            addCriterionForJDBCDate("data_fine_validita not in", values, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_fine_validita between", value1, value2, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andDataFineValiditaNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("data_fine_validita not between", value1, value2, "dataFineValidita");
            return (Criteria) this;
        }

        public Criteria andCodIdNazionaleLikeInsensitive(String value) {
            addCriterion("upper(cod_id_nazionale) like", value.toUpperCase(), "codIdNazionale");
            return (Criteria) this;
        }

        public Criteria andCodIdRegionaleLikeInsensitive(String value) {
            addCriterion("upper(cod_id_regionale) like", value.toUpperCase(), "codIdRegionale");
            return (Criteria) this;
        }

        public Criteria andNumRepertorioLikeInsensitive(String value) {
            addCriterion("upper(num_repertorio) like", value.toUpperCase(), "numRepertorio");
            return (Criteria) this;
        }

        public Criteria andAccordoProgrammaLikeInsensitive(String value) {
            addCriterion("upper(accordo_programma) like", value.toUpperCase(), "accordoProgramma");
            return (Criteria) this;
        }

        public Criteria andCigLikeInsensitive(String value) {
            addCriterion("upper(cig) like", value.toUpperCase(), "cig");
            return (Criteria) this;
        }

        public Criteria andDescContrattoLikeInsensitive(String value) {
            addCriterion("upper(desc_contratto) like", value.toUpperCase(), "descContratto");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 30 11:42:39 CET 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}