/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dto;

import java.io.Serializable;
import java.util.Date;

public class VExportRicercaStoriaAutobusDTO extends ParentDTO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.data_aggiornamento
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Date dataAggiornamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.id_azienda
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Long idAzienda;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.denominazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String denominazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.n_telaio
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String nTelaio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.n_targa
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String nTarga;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.data_prima_immatricolazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Date dataPrimaImmatricolazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.data_ultima_immatricolazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Date dataUltimaImmatricolazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.alimentazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String alimentazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.n_posti_sedere
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Long nPostiSedere;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.n_posti_in_piedi
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Long nPostiInPiedi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.n_posti_riservati
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Long nPostiRiservati;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.omologazione_direttiva_europea
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String omologazioneDirettivaEuropea;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.omologazione_classe
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String omologazioneClasse;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.flg_filtro_fap
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String flgFiltroFap;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.facilitazione_disabili
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String facilitazioneDisabili;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.impianti_audio
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String impiantiAudio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.impianti_visivi
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String impiantiVisivi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.flg_rilevatore_bip
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String flgRilevatoreBip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.prezzo_tot_acquisto
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Double prezzoTotAcquisto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.contributo_pubblico_acquisto
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Double contributoPubblicoAcquisto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.flg_veicolo_assicurato
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String flgVeicoloAssicurato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.data_ultima_revisione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Date dataUltimaRevisione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.note
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.primo_telaio
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String primoTelaio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.n_matricola_aziendale
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String nMatricolaAziendale;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.tipo_immatricolazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String tipoImmatricolazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.ente_autorizz_prima_imm
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String enteAutorizzPrimaImm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.classe_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String classeVeicolo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.marca
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String marca;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.modello
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String modello;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.flg_due_piani
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String flgDuePiani;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.flg_snodato
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String flgSnodato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.caratteristiche_particolari
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String caratteristicheParticolari;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.fk_tipo_alimentazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Long fkTipoAlimentazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.altra_alimentazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String altraAlimentazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.tipo_allestimento
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String tipoAllestimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.lunghezza
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Double lunghezza;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.numero_porte
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Long numeroPorte;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.posti_carrozzina
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Long postiCarrozzina;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.flg_impianto_condizionamento
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String flgImpiantoCondizionamento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.flg_cabina_guida_isolata
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String flgCabinaGuidaIsolata;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.dispositivi_prevenz
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String dispositiviPrevenz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.altri_dispositivi_prevenz_inc
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String altriDispositiviPrevenzInc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.flg_otx
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String flgOtx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.flg_avm
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String flgAvm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.flg_contapasseggeri
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String flgContapasseggeri;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.proprieta_leasing
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String proprietaLeasing;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.flg_conteggiato_miv
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String flgConteggiatoMiv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.deposito
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String deposito;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.tipologia_dimens
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String tipologiaDimens;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.stato_tpl
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String statoTpl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.data_alienazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Date dataAlienazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.contribuito
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String contribuito;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.scad_vincoli_no_alien
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Date scadVincoliNoAlien;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.nota_riservata_azienda
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String notaRiservataAzienda;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.nota_riservata_amp
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String notaRiservataAmp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.nota_riservata_rp
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String notaRiservataRp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.flg_richiesta_contr
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String flgRichiestaContr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.anno_sost_prog
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Long annoSostProg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.data_inserimento
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Date dataInserimento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.data_aggiornamento_storia
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private Date dataAggiornamentoStoria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.flg_verificato_azienda
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String flgVerificatoAzienda;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.flg_verificato_amp
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String flgVerificatoAmp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.motivazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String motivazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column v_export_ricerca_storia_autobus.categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private String categoriaVeicolo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table v_export_ricerca_storia_autobus
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.data_aggiornamento
	 * @return  the value of v_export_ricerca_storia_autobus.data_aggiornamento
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.data_aggiornamento
	 * @param dataAggiornamento  the value for v_export_ricerca_storia_autobus.data_aggiornamento
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.id_azienda
	 * @return  the value of v_export_ricerca_storia_autobus.id_azienda
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Long getIdAzienda() {
		return idAzienda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.id_azienda
	 * @param idAzienda  the value for v_export_ricerca_storia_autobus.id_azienda
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setIdAzienda(Long idAzienda) {
		this.idAzienda = idAzienda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.denominazione
	 * @return  the value of v_export_ricerca_storia_autobus.denominazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getDenominazione() {
		return denominazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.denominazione
	 * @param denominazione  the value for v_export_ricerca_storia_autobus.denominazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione == null ? null : denominazione.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.n_telaio
	 * @return  the value of v_export_ricerca_storia_autobus.n_telaio
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getnTelaio() {
		return nTelaio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.n_telaio
	 * @param nTelaio  the value for v_export_ricerca_storia_autobus.n_telaio
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setnTelaio(String nTelaio) {
		this.nTelaio = nTelaio == null ? null : nTelaio.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.n_targa
	 * @return  the value of v_export_ricerca_storia_autobus.n_targa
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getnTarga() {
		return nTarga;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.n_targa
	 * @param nTarga  the value for v_export_ricerca_storia_autobus.n_targa
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setnTarga(String nTarga) {
		this.nTarga = nTarga == null ? null : nTarga.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.data_prima_immatricolazione
	 * @return  the value of v_export_ricerca_storia_autobus.data_prima_immatricolazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Date getDataPrimaImmatricolazione() {
		return dataPrimaImmatricolazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.data_prima_immatricolazione
	 * @param dataPrimaImmatricolazione  the value for v_export_ricerca_storia_autobus.data_prima_immatricolazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setDataPrimaImmatricolazione(Date dataPrimaImmatricolazione) {
		this.dataPrimaImmatricolazione = dataPrimaImmatricolazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.data_ultima_immatricolazione
	 * @return  the value of v_export_ricerca_storia_autobus.data_ultima_immatricolazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Date getDataUltimaImmatricolazione() {
		return dataUltimaImmatricolazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.data_ultima_immatricolazione
	 * @param dataUltimaImmatricolazione  the value for v_export_ricerca_storia_autobus.data_ultima_immatricolazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setDataUltimaImmatricolazione(Date dataUltimaImmatricolazione) {
		this.dataUltimaImmatricolazione = dataUltimaImmatricolazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.alimentazione
	 * @return  the value of v_export_ricerca_storia_autobus.alimentazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getAlimentazione() {
		return alimentazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.alimentazione
	 * @param alimentazione  the value for v_export_ricerca_storia_autobus.alimentazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setAlimentazione(String alimentazione) {
		this.alimentazione = alimentazione == null ? null : alimentazione.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.n_posti_sedere
	 * @return  the value of v_export_ricerca_storia_autobus.n_posti_sedere
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Long getnPostiSedere() {
		return nPostiSedere;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.n_posti_sedere
	 * @param nPostiSedere  the value for v_export_ricerca_storia_autobus.n_posti_sedere
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setnPostiSedere(Long nPostiSedere) {
		this.nPostiSedere = nPostiSedere;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.n_posti_in_piedi
	 * @return  the value of v_export_ricerca_storia_autobus.n_posti_in_piedi
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Long getnPostiInPiedi() {
		return nPostiInPiedi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.n_posti_in_piedi
	 * @param nPostiInPiedi  the value for v_export_ricerca_storia_autobus.n_posti_in_piedi
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setnPostiInPiedi(Long nPostiInPiedi) {
		this.nPostiInPiedi = nPostiInPiedi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.n_posti_riservati
	 * @return  the value of v_export_ricerca_storia_autobus.n_posti_riservati
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Long getnPostiRiservati() {
		return nPostiRiservati;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.n_posti_riservati
	 * @param nPostiRiservati  the value for v_export_ricerca_storia_autobus.n_posti_riservati
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setnPostiRiservati(Long nPostiRiservati) {
		this.nPostiRiservati = nPostiRiservati;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.omologazione_direttiva_europea
	 * @return  the value of v_export_ricerca_storia_autobus.omologazione_direttiva_europea
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getOmologazioneDirettivaEuropea() {
		return omologazioneDirettivaEuropea;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.omologazione_direttiva_europea
	 * @param omologazioneDirettivaEuropea  the value for v_export_ricerca_storia_autobus.omologazione_direttiva_europea
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setOmologazioneDirettivaEuropea(String omologazioneDirettivaEuropea) {
		this.omologazioneDirettivaEuropea = omologazioneDirettivaEuropea == null ? null
				: omologazioneDirettivaEuropea.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.omologazione_classe
	 * @return  the value of v_export_ricerca_storia_autobus.omologazione_classe
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getOmologazioneClasse() {
		return omologazioneClasse;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.omologazione_classe
	 * @param omologazioneClasse  the value for v_export_ricerca_storia_autobus.omologazione_classe
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setOmologazioneClasse(String omologazioneClasse) {
		this.omologazioneClasse = omologazioneClasse == null ? null : omologazioneClasse.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.flg_filtro_fap
	 * @return  the value of v_export_ricerca_storia_autobus.flg_filtro_fap
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getFlgFiltroFap() {
		return flgFiltroFap;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.flg_filtro_fap
	 * @param flgFiltroFap  the value for v_export_ricerca_storia_autobus.flg_filtro_fap
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFlgFiltroFap(String flgFiltroFap) {
		this.flgFiltroFap = flgFiltroFap == null ? null : flgFiltroFap.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.facilitazione_disabili
	 * @return  the value of v_export_ricerca_storia_autobus.facilitazione_disabili
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getFacilitazioneDisabili() {
		return facilitazioneDisabili;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.facilitazione_disabili
	 * @param facilitazioneDisabili  the value for v_export_ricerca_storia_autobus.facilitazione_disabili
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFacilitazioneDisabili(String facilitazioneDisabili) {
		this.facilitazioneDisabili = facilitazioneDisabili == null ? null : facilitazioneDisabili.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.impianti_audio
	 * @return  the value of v_export_ricerca_storia_autobus.impianti_audio
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getImpiantiAudio() {
		return impiantiAudio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.impianti_audio
	 * @param impiantiAudio  the value for v_export_ricerca_storia_autobus.impianti_audio
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setImpiantiAudio(String impiantiAudio) {
		this.impiantiAudio = impiantiAudio == null ? null : impiantiAudio.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.impianti_visivi
	 * @return  the value of v_export_ricerca_storia_autobus.impianti_visivi
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getImpiantiVisivi() {
		return impiantiVisivi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.impianti_visivi
	 * @param impiantiVisivi  the value for v_export_ricerca_storia_autobus.impianti_visivi
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setImpiantiVisivi(String impiantiVisivi) {
		this.impiantiVisivi = impiantiVisivi == null ? null : impiantiVisivi.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.flg_rilevatore_bip
	 * @return  the value of v_export_ricerca_storia_autobus.flg_rilevatore_bip
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getFlgRilevatoreBip() {
		return flgRilevatoreBip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.flg_rilevatore_bip
	 * @param flgRilevatoreBip  the value for v_export_ricerca_storia_autobus.flg_rilevatore_bip
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFlgRilevatoreBip(String flgRilevatoreBip) {
		this.flgRilevatoreBip = flgRilevatoreBip == null ? null : flgRilevatoreBip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.prezzo_tot_acquisto
	 * @return  the value of v_export_ricerca_storia_autobus.prezzo_tot_acquisto
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Double getPrezzoTotAcquisto() {
		return prezzoTotAcquisto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.prezzo_tot_acquisto
	 * @param prezzoTotAcquisto  the value for v_export_ricerca_storia_autobus.prezzo_tot_acquisto
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setPrezzoTotAcquisto(Double prezzoTotAcquisto) {
		this.prezzoTotAcquisto = prezzoTotAcquisto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.contributo_pubblico_acquisto
	 * @return  the value of v_export_ricerca_storia_autobus.contributo_pubblico_acquisto
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Double getContributoPubblicoAcquisto() {
		return contributoPubblicoAcquisto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.contributo_pubblico_acquisto
	 * @param contributoPubblicoAcquisto  the value for v_export_ricerca_storia_autobus.contributo_pubblico_acquisto
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setContributoPubblicoAcquisto(Double contributoPubblicoAcquisto) {
		this.contributoPubblicoAcquisto = contributoPubblicoAcquisto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.flg_veicolo_assicurato
	 * @return  the value of v_export_ricerca_storia_autobus.flg_veicolo_assicurato
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getFlgVeicoloAssicurato() {
		return flgVeicoloAssicurato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.flg_veicolo_assicurato
	 * @param flgVeicoloAssicurato  the value for v_export_ricerca_storia_autobus.flg_veicolo_assicurato
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFlgVeicoloAssicurato(String flgVeicoloAssicurato) {
		this.flgVeicoloAssicurato = flgVeicoloAssicurato == null ? null : flgVeicoloAssicurato.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.data_ultima_revisione
	 * @return  the value of v_export_ricerca_storia_autobus.data_ultima_revisione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Date getDataUltimaRevisione() {
		return dataUltimaRevisione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.data_ultima_revisione
	 * @param dataUltimaRevisione  the value for v_export_ricerca_storia_autobus.data_ultima_revisione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setDataUltimaRevisione(Date dataUltimaRevisione) {
		this.dataUltimaRevisione = dataUltimaRevisione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.note
	 * @return  the value of v_export_ricerca_storia_autobus.note
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.note
	 * @param note  the value for v_export_ricerca_storia_autobus.note
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.primo_telaio
	 * @return  the value of v_export_ricerca_storia_autobus.primo_telaio
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getPrimoTelaio() {
		return primoTelaio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.primo_telaio
	 * @param primoTelaio  the value for v_export_ricerca_storia_autobus.primo_telaio
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setPrimoTelaio(String primoTelaio) {
		this.primoTelaio = primoTelaio == null ? null : primoTelaio.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.n_matricola_aziendale
	 * @return  the value of v_export_ricerca_storia_autobus.n_matricola_aziendale
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getnMatricolaAziendale() {
		return nMatricolaAziendale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.n_matricola_aziendale
	 * @param nMatricolaAziendale  the value for v_export_ricerca_storia_autobus.n_matricola_aziendale
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setnMatricolaAziendale(String nMatricolaAziendale) {
		this.nMatricolaAziendale = nMatricolaAziendale == null ? null : nMatricolaAziendale.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.tipo_immatricolazione
	 * @return  the value of v_export_ricerca_storia_autobus.tipo_immatricolazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getTipoImmatricolazione() {
		return tipoImmatricolazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.tipo_immatricolazione
	 * @param tipoImmatricolazione  the value for v_export_ricerca_storia_autobus.tipo_immatricolazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setTipoImmatricolazione(String tipoImmatricolazione) {
		this.tipoImmatricolazione = tipoImmatricolazione == null ? null : tipoImmatricolazione.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.ente_autorizz_prima_imm
	 * @return  the value of v_export_ricerca_storia_autobus.ente_autorizz_prima_imm
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getEnteAutorizzPrimaImm() {
		return enteAutorizzPrimaImm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.ente_autorizz_prima_imm
	 * @param enteAutorizzPrimaImm  the value for v_export_ricerca_storia_autobus.ente_autorizz_prima_imm
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setEnteAutorizzPrimaImm(String enteAutorizzPrimaImm) {
		this.enteAutorizzPrimaImm = enteAutorizzPrimaImm == null ? null : enteAutorizzPrimaImm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.classe_veicolo
	 * @return  the value of v_export_ricerca_storia_autobus.classe_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getClasseVeicolo() {
		return classeVeicolo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.classe_veicolo
	 * @param classeVeicolo  the value for v_export_ricerca_storia_autobus.classe_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setClasseVeicolo(String classeVeicolo) {
		this.classeVeicolo = classeVeicolo == null ? null : classeVeicolo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.marca
	 * @return  the value of v_export_ricerca_storia_autobus.marca
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getMarca() {
		return marca;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.marca
	 * @param marca  the value for v_export_ricerca_storia_autobus.marca
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setMarca(String marca) {
		this.marca = marca == null ? null : marca.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.modello
	 * @return  the value of v_export_ricerca_storia_autobus.modello
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getModello() {
		return modello;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.modello
	 * @param modello  the value for v_export_ricerca_storia_autobus.modello
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setModello(String modello) {
		this.modello = modello == null ? null : modello.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.flg_due_piani
	 * @return  the value of v_export_ricerca_storia_autobus.flg_due_piani
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getFlgDuePiani() {
		return flgDuePiani;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.flg_due_piani
	 * @param flgDuePiani  the value for v_export_ricerca_storia_autobus.flg_due_piani
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFlgDuePiani(String flgDuePiani) {
		this.flgDuePiani = flgDuePiani == null ? null : flgDuePiani.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.flg_snodato
	 * @return  the value of v_export_ricerca_storia_autobus.flg_snodato
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getFlgSnodato() {
		return flgSnodato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.flg_snodato
	 * @param flgSnodato  the value for v_export_ricerca_storia_autobus.flg_snodato
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFlgSnodato(String flgSnodato) {
		this.flgSnodato = flgSnodato == null ? null : flgSnodato.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.caratteristiche_particolari
	 * @return  the value of v_export_ricerca_storia_autobus.caratteristiche_particolari
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getCaratteristicheParticolari() {
		return caratteristicheParticolari;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.caratteristiche_particolari
	 * @param caratteristicheParticolari  the value for v_export_ricerca_storia_autobus.caratteristiche_particolari
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setCaratteristicheParticolari(String caratteristicheParticolari) {
		this.caratteristicheParticolari = caratteristicheParticolari == null ? null : caratteristicheParticolari.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.fk_tipo_alimentazione
	 * @return  the value of v_export_ricerca_storia_autobus.fk_tipo_alimentazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Long getFkTipoAlimentazione() {
		return fkTipoAlimentazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.fk_tipo_alimentazione
	 * @param fkTipoAlimentazione  the value for v_export_ricerca_storia_autobus.fk_tipo_alimentazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFkTipoAlimentazione(Long fkTipoAlimentazione) {
		this.fkTipoAlimentazione = fkTipoAlimentazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.altra_alimentazione
	 * @return  the value of v_export_ricerca_storia_autobus.altra_alimentazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getAltraAlimentazione() {
		return altraAlimentazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.altra_alimentazione
	 * @param altraAlimentazione  the value for v_export_ricerca_storia_autobus.altra_alimentazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setAltraAlimentazione(String altraAlimentazione) {
		this.altraAlimentazione = altraAlimentazione == null ? null : altraAlimentazione.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.tipo_allestimento
	 * @return  the value of v_export_ricerca_storia_autobus.tipo_allestimento
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getTipoAllestimento() {
		return tipoAllestimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.tipo_allestimento
	 * @param tipoAllestimento  the value for v_export_ricerca_storia_autobus.tipo_allestimento
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setTipoAllestimento(String tipoAllestimento) {
		this.tipoAllestimento = tipoAllestimento == null ? null : tipoAllestimento.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.lunghezza
	 * @return  the value of v_export_ricerca_storia_autobus.lunghezza
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Double getLunghezza() {
		return lunghezza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.lunghezza
	 * @param lunghezza  the value for v_export_ricerca_storia_autobus.lunghezza
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setLunghezza(Double lunghezza) {
		this.lunghezza = lunghezza;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.numero_porte
	 * @return  the value of v_export_ricerca_storia_autobus.numero_porte
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Long getNumeroPorte() {
		return numeroPorte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.numero_porte
	 * @param numeroPorte  the value for v_export_ricerca_storia_autobus.numero_porte
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setNumeroPorte(Long numeroPorte) {
		this.numeroPorte = numeroPorte;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.posti_carrozzina
	 * @return  the value of v_export_ricerca_storia_autobus.posti_carrozzina
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Long getPostiCarrozzina() {
		return postiCarrozzina;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.posti_carrozzina
	 * @param postiCarrozzina  the value for v_export_ricerca_storia_autobus.posti_carrozzina
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setPostiCarrozzina(Long postiCarrozzina) {
		this.postiCarrozzina = postiCarrozzina;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.flg_impianto_condizionamento
	 * @return  the value of v_export_ricerca_storia_autobus.flg_impianto_condizionamento
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getFlgImpiantoCondizionamento() {
		return flgImpiantoCondizionamento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.flg_impianto_condizionamento
	 * @param flgImpiantoCondizionamento  the value for v_export_ricerca_storia_autobus.flg_impianto_condizionamento
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFlgImpiantoCondizionamento(String flgImpiantoCondizionamento) {
		this.flgImpiantoCondizionamento = flgImpiantoCondizionamento == null ? null : flgImpiantoCondizionamento.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.flg_cabina_guida_isolata
	 * @return  the value of v_export_ricerca_storia_autobus.flg_cabina_guida_isolata
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getFlgCabinaGuidaIsolata() {
		return flgCabinaGuidaIsolata;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.flg_cabina_guida_isolata
	 * @param flgCabinaGuidaIsolata  the value for v_export_ricerca_storia_autobus.flg_cabina_guida_isolata
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFlgCabinaGuidaIsolata(String flgCabinaGuidaIsolata) {
		this.flgCabinaGuidaIsolata = flgCabinaGuidaIsolata == null ? null : flgCabinaGuidaIsolata.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.dispositivi_prevenz
	 * @return  the value of v_export_ricerca_storia_autobus.dispositivi_prevenz
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getDispositiviPrevenz() {
		return dispositiviPrevenz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.dispositivi_prevenz
	 * @param dispositiviPrevenz  the value for v_export_ricerca_storia_autobus.dispositivi_prevenz
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setDispositiviPrevenz(String dispositiviPrevenz) {
		this.dispositiviPrevenz = dispositiviPrevenz == null ? null : dispositiviPrevenz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.altri_dispositivi_prevenz_inc
	 * @return  the value of v_export_ricerca_storia_autobus.altri_dispositivi_prevenz_inc
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getAltriDispositiviPrevenzInc() {
		return altriDispositiviPrevenzInc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.altri_dispositivi_prevenz_inc
	 * @param altriDispositiviPrevenzInc  the value for v_export_ricerca_storia_autobus.altri_dispositivi_prevenz_inc
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setAltriDispositiviPrevenzInc(String altriDispositiviPrevenzInc) {
		this.altriDispositiviPrevenzInc = altriDispositiviPrevenzInc == null ? null : altriDispositiviPrevenzInc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.flg_otx
	 * @return  the value of v_export_ricerca_storia_autobus.flg_otx
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getFlgOtx() {
		return flgOtx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.flg_otx
	 * @param flgOtx  the value for v_export_ricerca_storia_autobus.flg_otx
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFlgOtx(String flgOtx) {
		this.flgOtx = flgOtx == null ? null : flgOtx.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.flg_avm
	 * @return  the value of v_export_ricerca_storia_autobus.flg_avm
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getFlgAvm() {
		return flgAvm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.flg_avm
	 * @param flgAvm  the value for v_export_ricerca_storia_autobus.flg_avm
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFlgAvm(String flgAvm) {
		this.flgAvm = flgAvm == null ? null : flgAvm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.flg_contapasseggeri
	 * @return  the value of v_export_ricerca_storia_autobus.flg_contapasseggeri
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getFlgContapasseggeri() {
		return flgContapasseggeri;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.flg_contapasseggeri
	 * @param flgContapasseggeri  the value for v_export_ricerca_storia_autobus.flg_contapasseggeri
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFlgContapasseggeri(String flgContapasseggeri) {
		this.flgContapasseggeri = flgContapasseggeri == null ? null : flgContapasseggeri.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.proprieta_leasing
	 * @return  the value of v_export_ricerca_storia_autobus.proprieta_leasing
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getProprietaLeasing() {
		return proprietaLeasing;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.proprieta_leasing
	 * @param proprietaLeasing  the value for v_export_ricerca_storia_autobus.proprieta_leasing
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setProprietaLeasing(String proprietaLeasing) {
		this.proprietaLeasing = proprietaLeasing == null ? null : proprietaLeasing.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.flg_conteggiato_miv
	 * @return  the value of v_export_ricerca_storia_autobus.flg_conteggiato_miv
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getFlgConteggiatoMiv() {
		return flgConteggiatoMiv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.flg_conteggiato_miv
	 * @param flgConteggiatoMiv  the value for v_export_ricerca_storia_autobus.flg_conteggiato_miv
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFlgConteggiatoMiv(String flgConteggiatoMiv) {
		this.flgConteggiatoMiv = flgConteggiatoMiv == null ? null : flgConteggiatoMiv.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.deposito
	 * @return  the value of v_export_ricerca_storia_autobus.deposito
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getDeposito() {
		return deposito;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.deposito
	 * @param deposito  the value for v_export_ricerca_storia_autobus.deposito
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setDeposito(String deposito) {
		this.deposito = deposito == null ? null : deposito.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.tipologia_dimens
	 * @return  the value of v_export_ricerca_storia_autobus.tipologia_dimens
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getTipologiaDimens() {
		return tipologiaDimens;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.tipologia_dimens
	 * @param tipologiaDimens  the value for v_export_ricerca_storia_autobus.tipologia_dimens
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setTipologiaDimens(String tipologiaDimens) {
		this.tipologiaDimens = tipologiaDimens == null ? null : tipologiaDimens.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.stato_tpl
	 * @return  the value of v_export_ricerca_storia_autobus.stato_tpl
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getStatoTpl() {
		return statoTpl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.stato_tpl
	 * @param statoTpl  the value for v_export_ricerca_storia_autobus.stato_tpl
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setStatoTpl(String statoTpl) {
		this.statoTpl = statoTpl == null ? null : statoTpl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.data_alienazione
	 * @return  the value of v_export_ricerca_storia_autobus.data_alienazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Date getDataAlienazione() {
		return dataAlienazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.data_alienazione
	 * @param dataAlienazione  the value for v_export_ricerca_storia_autobus.data_alienazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setDataAlienazione(Date dataAlienazione) {
		this.dataAlienazione = dataAlienazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.contribuito
	 * @return  the value of v_export_ricerca_storia_autobus.contribuito
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getContribuito() {
		return contribuito;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.contribuito
	 * @param contribuito  the value for v_export_ricerca_storia_autobus.contribuito
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setContribuito(String contribuito) {
		this.contribuito = contribuito == null ? null : contribuito.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.scad_vincoli_no_alien
	 * @return  the value of v_export_ricerca_storia_autobus.scad_vincoli_no_alien
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Date getScadVincoliNoAlien() {
		return scadVincoliNoAlien;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.scad_vincoli_no_alien
	 * @param scadVincoliNoAlien  the value for v_export_ricerca_storia_autobus.scad_vincoli_no_alien
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setScadVincoliNoAlien(Date scadVincoliNoAlien) {
		this.scadVincoliNoAlien = scadVincoliNoAlien;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.nota_riservata_azienda
	 * @return  the value of v_export_ricerca_storia_autobus.nota_riservata_azienda
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getNotaRiservataAzienda() {
		return notaRiservataAzienda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.nota_riservata_azienda
	 * @param notaRiservataAzienda  the value for v_export_ricerca_storia_autobus.nota_riservata_azienda
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setNotaRiservataAzienda(String notaRiservataAzienda) {
		this.notaRiservataAzienda = notaRiservataAzienda == null ? null : notaRiservataAzienda.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.nota_riservata_amp
	 * @return  the value of v_export_ricerca_storia_autobus.nota_riservata_amp
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getNotaRiservataAmp() {
		return notaRiservataAmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.nota_riservata_amp
	 * @param notaRiservataAmp  the value for v_export_ricerca_storia_autobus.nota_riservata_amp
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setNotaRiservataAmp(String notaRiservataAmp) {
		this.notaRiservataAmp = notaRiservataAmp == null ? null : notaRiservataAmp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.nota_riservata_rp
	 * @return  the value of v_export_ricerca_storia_autobus.nota_riservata_rp
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getNotaRiservataRp() {
		return notaRiservataRp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.nota_riservata_rp
	 * @param notaRiservataRp  the value for v_export_ricerca_storia_autobus.nota_riservata_rp
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setNotaRiservataRp(String notaRiservataRp) {
		this.notaRiservataRp = notaRiservataRp == null ? null : notaRiservataRp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.flg_richiesta_contr
	 * @return  the value of v_export_ricerca_storia_autobus.flg_richiesta_contr
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getFlgRichiestaContr() {
		return flgRichiestaContr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.flg_richiesta_contr
	 * @param flgRichiestaContr  the value for v_export_ricerca_storia_autobus.flg_richiesta_contr
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFlgRichiestaContr(String flgRichiestaContr) {
		this.flgRichiestaContr = flgRichiestaContr == null ? null : flgRichiestaContr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.anno_sost_prog
	 * @return  the value of v_export_ricerca_storia_autobus.anno_sost_prog
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Long getAnnoSostProg() {
		return annoSostProg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.anno_sost_prog
	 * @param annoSostProg  the value for v_export_ricerca_storia_autobus.anno_sost_prog
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setAnnoSostProg(Long annoSostProg) {
		this.annoSostProg = annoSostProg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.data_inserimento
	 * @return  the value of v_export_ricerca_storia_autobus.data_inserimento
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Date getDataInserimento() {
		return dataInserimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.data_inserimento
	 * @param dataInserimento  the value for v_export_ricerca_storia_autobus.data_inserimento
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setDataInserimento(Date dataInserimento) {
		this.dataInserimento = dataInserimento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.data_aggiornamento_storia
	 * @return  the value of v_export_ricerca_storia_autobus.data_aggiornamento_storia
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public Date getDataAggiornamentoStoria() {
		return dataAggiornamentoStoria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.data_aggiornamento_storia
	 * @param dataAggiornamentoStoria  the value for v_export_ricerca_storia_autobus.data_aggiornamento_storia
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setDataAggiornamentoStoria(Date dataAggiornamentoStoria) {
		this.dataAggiornamentoStoria = dataAggiornamentoStoria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.flg_verificato_azienda
	 * @return  the value of v_export_ricerca_storia_autobus.flg_verificato_azienda
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getFlgVerificatoAzienda() {
		return flgVerificatoAzienda;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.flg_verificato_azienda
	 * @param flgVerificatoAzienda  the value for v_export_ricerca_storia_autobus.flg_verificato_azienda
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFlgVerificatoAzienda(String flgVerificatoAzienda) {
		this.flgVerificatoAzienda = flgVerificatoAzienda == null ? null : flgVerificatoAzienda.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.flg_verificato_amp
	 * @return  the value of v_export_ricerca_storia_autobus.flg_verificato_amp
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getFlgVerificatoAmp() {
		return flgVerificatoAmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.flg_verificato_amp
	 * @param flgVerificatoAmp  the value for v_export_ricerca_storia_autobus.flg_verificato_amp
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setFlgVerificatoAmp(String flgVerificatoAmp) {
		this.flgVerificatoAmp = flgVerificatoAmp == null ? null : flgVerificatoAmp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.motivazione
	 * @return  the value of v_export_ricerca_storia_autobus.motivazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getMotivazione() {
		return motivazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.motivazione
	 * @param motivazione  the value for v_export_ricerca_storia_autobus.motivazione
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setMotivazione(String motivazione) {
		this.motivazione = motivazione == null ? null : motivazione.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column v_export_ricerca_storia_autobus.categoria_veicolo
	 * @return  the value of v_export_ricerca_storia_autobus.categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public String getCategoriaVeicolo() {
		return categoriaVeicolo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column v_export_ricerca_storia_autobus.categoria_veicolo
	 * @param categoriaVeicolo  the value for v_export_ricerca_storia_autobus.categoria_veicolo
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	public void setCategoriaVeicolo(String categoriaVeicolo) {
		this.categoriaVeicolo = categoriaVeicolo == null ? null : categoriaVeicolo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_export_ricerca_storia_autobus
	 * @mbg.generated  Fri Mar 11 10:23:20 CET 2022
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", dataAggiornamento=").append(dataAggiornamento);
		sb.append(", idAzienda=").append(idAzienda);
		sb.append(", denominazione=").append(denominazione);
		sb.append(", nTelaio=").append(nTelaio);
		sb.append(", nTarga=").append(nTarga);
		sb.append(", dataPrimaImmatricolazione=").append(dataPrimaImmatricolazione);
		sb.append(", dataUltimaImmatricolazione=").append(dataUltimaImmatricolazione);
		sb.append(", alimentazione=").append(alimentazione);
		sb.append(", nPostiSedere=").append(nPostiSedere);
		sb.append(", nPostiInPiedi=").append(nPostiInPiedi);
		sb.append(", nPostiRiservati=").append(nPostiRiservati);
		sb.append(", omologazioneDirettivaEuropea=").append(omologazioneDirettivaEuropea);
		sb.append(", omologazioneClasse=").append(omologazioneClasse);
		sb.append(", flgFiltroFap=").append(flgFiltroFap);
		sb.append(", facilitazioneDisabili=").append(facilitazioneDisabili);
		sb.append(", impiantiAudio=").append(impiantiAudio);
		sb.append(", impiantiVisivi=").append(impiantiVisivi);
		sb.append(", flgRilevatoreBip=").append(flgRilevatoreBip);
		sb.append(", prezzoTotAcquisto=").append(prezzoTotAcquisto);
		sb.append(", contributoPubblicoAcquisto=").append(contributoPubblicoAcquisto);
		sb.append(", flgVeicoloAssicurato=").append(flgVeicoloAssicurato);
		sb.append(", dataUltimaRevisione=").append(dataUltimaRevisione);
		sb.append(", note=").append(note);
		sb.append(", primoTelaio=").append(primoTelaio);
		sb.append(", nMatricolaAziendale=").append(nMatricolaAziendale);
		sb.append(", tipoImmatricolazione=").append(tipoImmatricolazione);
		sb.append(", enteAutorizzPrimaImm=").append(enteAutorizzPrimaImm);
		sb.append(", classeVeicolo=").append(classeVeicolo);
		sb.append(", marca=").append(marca);
		sb.append(", modello=").append(modello);
		sb.append(", flgDuePiani=").append(flgDuePiani);
		sb.append(", flgSnodato=").append(flgSnodato);
		sb.append(", caratteristicheParticolari=").append(caratteristicheParticolari);
		sb.append(", fkTipoAlimentazione=").append(fkTipoAlimentazione);
		sb.append(", altraAlimentazione=").append(altraAlimentazione);
		sb.append(", tipoAllestimento=").append(tipoAllestimento);
		sb.append(", lunghezza=").append(lunghezza);
		sb.append(", numeroPorte=").append(numeroPorte);
		sb.append(", postiCarrozzina=").append(postiCarrozzina);
		sb.append(", flgImpiantoCondizionamento=").append(flgImpiantoCondizionamento);
		sb.append(", flgCabinaGuidaIsolata=").append(flgCabinaGuidaIsolata);
		sb.append(", dispositiviPrevenz=").append(dispositiviPrevenz);
		sb.append(", altriDispositiviPrevenzInc=").append(altriDispositiviPrevenzInc);
		sb.append(", flgOtx=").append(flgOtx);
		sb.append(", flgAvm=").append(flgAvm);
		sb.append(", flgContapasseggeri=").append(flgContapasseggeri);
		sb.append(", proprietaLeasing=").append(proprietaLeasing);
		sb.append(", flgConteggiatoMiv=").append(flgConteggiatoMiv);
		sb.append(", deposito=").append(deposito);
		sb.append(", tipologiaDimens=").append(tipologiaDimens);
		sb.append(", statoTpl=").append(statoTpl);
		sb.append(", dataAlienazione=").append(dataAlienazione);
		sb.append(", contribuito=").append(contribuito);
		sb.append(", scadVincoliNoAlien=").append(scadVincoliNoAlien);
		sb.append(", notaRiservataAzienda=").append(notaRiservataAzienda);
		sb.append(", notaRiservataAmp=").append(notaRiservataAmp);
		sb.append(", notaRiservataRp=").append(notaRiservataRp);
		sb.append(", flgRichiestaContr=").append(flgRichiestaContr);
		sb.append(", annoSostProg=").append(annoSostProg);
		sb.append(", dataInserimento=").append(dataInserimento);
		sb.append(", dataAggiornamentoStoria=").append(dataAggiornamentoStoria);
		sb.append(", flgVerificatoAzienda=").append(flgVerificatoAzienda);
		sb.append(", flgVerificatoAmp=").append(flgVerificatoAmp);
		sb.append(", motivazione=").append(motivazione);
		sb.append(", categoriaVeicolo=").append(categoriaVeicolo);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}