/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuspRProcVeicoloDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuspRProcVeicoloKey;
import it.csi.rebus.rebuscrus.integration.dto.RebuspRProcVeicoloSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuspRProcVeicoloDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_r_proc_veicolo
     *
     * @mbg.generated Tue Jan 28 16:32:41 CET 2020
     */
    long countByExample(RebuspRProcVeicoloSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_r_proc_veicolo
     *
     * @mbg.generated Tue Jan 28 16:32:41 CET 2020
     */
    int deleteByExample(RebuspRProcVeicoloSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_r_proc_veicolo
     *
     * @mbg.generated Tue Jan 28 16:32:41 CET 2020
     */
    int deleteByPrimaryKey(RebuspRProcVeicoloKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_r_proc_veicolo
     *
     * @mbg.generated Tue Jan 28 16:32:41 CET 2020
     */
    int insert(RebuspRProcVeicoloDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_r_proc_veicolo
     *
     * @mbg.generated Tue Jan 28 16:32:41 CET 2020
     */
    int insertSelective(RebuspRProcVeicoloDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_r_proc_veicolo
     *
     * @mbg.generated Tue Jan 28 16:32:41 CET 2020
     */
    List<RebuspRProcVeicoloDTO> selectByExample(RebuspRProcVeicoloSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_r_proc_veicolo
     *
     * @mbg.generated Tue Jan 28 16:32:41 CET 2020
     */
    RebuspRProcVeicoloDTO selectByPrimaryKey(RebuspRProcVeicoloKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_r_proc_veicolo
     *
     * @mbg.generated Tue Jan 28 16:32:41 CET 2020
     */
    int updateByExampleSelective(@Param("record") RebuspRProcVeicoloDTO record, @Param("example") RebuspRProcVeicoloSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_r_proc_veicolo
     *
     * @mbg.generated Tue Jan 28 16:32:41 CET 2020
     */
    int updateByExample(@Param("record") RebuspRProcVeicoloDTO record, @Param("example") RebuspRProcVeicoloSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_r_proc_veicolo
     *
     * @mbg.generated Tue Jan 28 16:32:41 CET 2020
     */
    int updateByPrimaryKeySelective(RebuspRProcVeicoloDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_r_proc_veicolo
     *
     * @mbg.generated Tue Jan 28 16:32:41 CET 2020
     */
    int updateByPrimaryKey(RebuspRProcVeicoloDTO record);
}