/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusTVariazAutobusDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebusTVariazAutobusSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusTVariazAutobusDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	long countByExample(RebusTVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	int deleteByExample(RebusTVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	int deleteByPrimaryKey(Long idVariazAutobus);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	int insert(RebusTVariazAutobusDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	int insertSelective(RebusTVariazAutobusDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	List<RebusTVariazAutobusDTO> selectByExample(RebusTVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	RebusTVariazAutobusDTO selectByPrimaryKey(Long idVariazAutobus);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	int updateByExampleSelective(@Param("record") RebusTVariazAutobusDTO record,
			@Param("example") RebusTVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	int updateByExample(@Param("record") RebusTVariazAutobusDTO record,
			@Param("example") RebusTVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	int updateByPrimaryKeySelective(RebusTVariazAutobusDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_variaz_autobus
	 * @mbg.generated  Tue Mar 08 16:08:15 CET 2022
	 */
	int updateByPrimaryKey(RebusTVariazAutobusDTO record);
}