/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusmTMisPortabiciDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebusmTMisPortabiciSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusmTMisPortabiciDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_portabici
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    long countByExample(RebusmTMisPortabiciSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_portabici
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int deleteByExample(RebusmTMisPortabiciSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_portabici
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int deleteByPrimaryKey(Long idMisurazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_portabici
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int insert(RebusmTMisPortabiciDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_portabici
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int insertSelective(RebusmTMisPortabiciDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_portabici
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    List<RebusmTMisPortabiciDTO> selectByExample(RebusmTMisPortabiciSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_portabici
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    RebusmTMisPortabiciDTO selectByPrimaryKey(Long idMisurazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_portabici
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int updateByExampleSelective(@Param("record") RebusmTMisPortabiciDTO record, @Param("example") RebusmTMisPortabiciSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_portabici
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int updateByExample(@Param("record") RebusmTMisPortabiciDTO record, @Param("example") RebusmTMisPortabiciSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_portabici
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int updateByPrimaryKeySelective(RebusmTMisPortabiciDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_portabici
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int updateByPrimaryKey(RebusmTMisPortabiciDTO record);
}