/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuspTProcedimentoDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuspTProcedimentoSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuspTProcedimentoDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	long countByExample(RebuspTProcedimentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	int deleteByExample(RebuspTProcedimentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	int deleteByPrimaryKey(Long idProcedimento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	int insert(RebuspTProcedimentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	int insertSelective(RebuspTProcedimentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	List<RebuspTProcedimentoDTO> selectByExample(RebuspTProcedimentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	RebuspTProcedimentoDTO selectByPrimaryKey(Long idProcedimento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	int updateByExampleSelective(@Param("record") RebuspTProcedimentoDTO record,
			@Param("example") RebuspTProcedimentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	int updateByExample(@Param("record") RebuspTProcedimentoDTO record,
			@Param("example") RebuspTProcedimentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	int updateByPrimaryKeySelective(RebuspTProcedimentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_procedimento
	 * @mbg.generated  Fri Jun 03 15:03:20 CEST 2022
	 */
	int updateByPrimaryKey(RebuspTProcedimentoDTO record);
}