/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuspTDocumentoDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuspTDocumentoSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuspTDocumentoDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_documento
	 * @mbg.generated  Tue Apr 14 11:06:44 CEST 2020
	 */
	long countByExample(RebuspTDocumentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_documento
	 * @mbg.generated  Tue Apr 14 11:06:44 CEST 2020
	 */
	int deleteByExample(RebuspTDocumentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_documento
	 * @mbg.generated  Tue Apr 14 11:06:44 CEST 2020
	 */
	int deleteByPrimaryKey(Long idDocumento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_documento
	 * @mbg.generated  Tue Apr 14 11:06:44 CEST 2020
	 */
	int insert(RebuspTDocumentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_documento
	 * @mbg.generated  Tue Apr 14 11:06:44 CEST 2020
	 */
	int insertSelective(RebuspTDocumentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_documento
	 * @mbg.generated  Tue Apr 14 11:06:44 CEST 2020
	 */
	List<RebuspTDocumentoDTO> selectByExampleWithBLOBs(RebuspTDocumentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_documento
	 * @mbg.generated  Tue Apr 14 11:06:44 CEST 2020
	 */
	List<RebuspTDocumentoDTO> selectByExample(RebuspTDocumentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_documento
	 * @mbg.generated  Tue Apr 14 11:06:44 CEST 2020
	 */
	RebuspTDocumentoDTO selectByPrimaryKey(Long idDocumento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_documento
	 * @mbg.generated  Tue Apr 14 11:06:44 CEST 2020
	 */
	int updateByExampleSelective(@Param("record") RebuspTDocumentoDTO record,
			@Param("example") RebuspTDocumentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_documento
	 * @mbg.generated  Tue Apr 14 11:06:44 CEST 2020
	 */
	int updateByExampleWithBLOBs(@Param("record") RebuspTDocumentoDTO record,
			@Param("example") RebuspTDocumentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_documento
	 * @mbg.generated  Tue Apr 14 11:06:44 CEST 2020
	 */
	int updateByExample(@Param("record") RebuspTDocumentoDTO record,
			@Param("example") RebuspTDocumentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_documento
	 * @mbg.generated  Tue Apr 14 11:06:44 CEST 2020
	 */
	int updateByPrimaryKeySelective(RebuspTDocumentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_documento
	 * @mbg.generated  Tue Apr 14 11:06:44 CEST 2020
	 */
	int updateByPrimaryKeyWithBLOBs(RebuspTDocumentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_documento
	 * @mbg.generated  Tue Apr 14 11:06:44 CEST 2020
	 */
	int updateByPrimaryKey(RebuspTDocumentoDTO record);
}