/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuspDTipoContrattoDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuspDTipoContrattoSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuspDTipoContrattoDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_d_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    long countByExample(RebuspDTipoContrattoSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_d_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    int deleteByExample(RebuspDTipoContrattoSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_d_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    int deleteByPrimaryKey(Long idTipoContratto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_d_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    int insert(RebuspDTipoContrattoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_d_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    int insertSelective(RebuspDTipoContrattoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_d_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    List<RebuspDTipoContrattoDTO> selectByExample(RebuspDTipoContrattoSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_d_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    RebuspDTipoContrattoDTO selectByPrimaryKey(Long idTipoContratto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_d_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    int updateByExampleSelective(@Param("record") RebuspDTipoContrattoDTO record, @Param("example") RebuspDTipoContrattoSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_d_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    int updateByExample(@Param("record") RebuspDTipoContrattoDTO record, @Param("example") RebuspDTipoContrattoSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_d_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    int updateByPrimaryKeySelective(RebuspDTipoContrattoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_d_tipo_contratto
     *
     * @mbg.generated Thu Feb 13 11:01:29 CET 2020
     */
    int updateByPrimaryKey(RebuspDTipoContrattoDTO record);
}