/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusTMessaggiDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebusTMessaggiSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusTMessaggiDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	long countByExample(RebusTMessaggiSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	int deleteByExample(RebusTMessaggiSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	int deleteByPrimaryKey(Long idMessaggio);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	int insert(RebusTMessaggiDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	int insertSelective(RebusTMessaggiDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	List<RebusTMessaggiDTO> selectByExample(RebusTMessaggiSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	RebusTMessaggiDTO selectByPrimaryKey(Long idMessaggio);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	int updateByExampleSelective(@Param("record") RebusTMessaggiDTO record, @Param("example") RebusTMessaggiSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	int updateByExample(@Param("record") RebusTMessaggiDTO record, @Param("example") RebusTMessaggiSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	int updateByPrimaryKeySelective(RebusTMessaggiDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_messaggi
	 * @mbg.generated  Thu Nov 05 12:40:05 CET 2020
	 */
	int updateByPrimaryKey(RebusTMessaggiDTO record);
}