/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusmTMisurazioneDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebusmTMisurazioneSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusmTMisurazioneDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    long countByExample(RebusmTMisurazioneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    int deleteByExample(RebusmTMisurazioneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    int deleteByPrimaryKey(Long idMisurazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    int insert(RebusmTMisurazioneDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    int insertSelective(RebusmTMisurazioneDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    List<RebusmTMisurazioneDTO> selectByExample(RebusmTMisurazioneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    RebusmTMisurazioneDTO selectByPrimaryKey(Long idMisurazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    int updateByExampleSelective(@Param("record") RebusmTMisurazioneDTO record, @Param("example") RebusmTMisurazioneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    int updateByExample(@Param("record") RebusmTMisurazioneDTO record, @Param("example") RebusmTMisurazioneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    int updateByPrimaryKeySelective(RebusmTMisurazioneDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_misurazione
     *
     * @mbg.generated Fri Dec 10 09:58:49 CET 2021
     */
    int updateByPrimaryKey(RebusmTMisurazioneDTO record);
}