/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusDImpiantiAudioDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebusDImpiantiAudioSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusDImpiantiAudioDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_impianti_audio
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	long countByExample(RebusDImpiantiAudioSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_impianti_audio
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByExample(RebusDImpiantiAudioSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_impianti_audio
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByPrimaryKey(Long idImpiantiAudio);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_impianti_audio
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insert(RebusDImpiantiAudioDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_impianti_audio
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insertSelective(RebusDImpiantiAudioDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_impianti_audio
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	List<RebusDImpiantiAudioDTO> selectByExample(RebusDImpiantiAudioSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_impianti_audio
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	RebusDImpiantiAudioDTO selectByPrimaryKey(Long idImpiantiAudio);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_impianti_audio
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExampleSelective(@Param("record") RebusDImpiantiAudioDTO record, @Param("example") RebusDImpiantiAudioSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_impianti_audio
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExample(@Param("record") RebusDImpiantiAudioDTO record, @Param("example") RebusDImpiantiAudioSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_impianti_audio
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByPrimaryKeySelective(RebusDImpiantiAudioDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_impianti_audio
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByPrimaryKey(RebusDImpiantiAudioDTO record);
}