/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusmTMisEmissioniDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebusmTMisEmissioniSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusmTMisEmissioniDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_emissioni
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    long countByExample(RebusmTMisEmissioniSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_emissioni
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int deleteByExample(RebusmTMisEmissioniSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_emissioni
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int deleteByPrimaryKey(Long idMisurazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_emissioni
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int insert(RebusmTMisEmissioniDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_emissioni
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int insertSelective(RebusmTMisEmissioniDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_emissioni
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    List<RebusmTMisEmissioniDTO> selectByExample(RebusmTMisEmissioniSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_emissioni
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    RebusmTMisEmissioniDTO selectByPrimaryKey(Long idMisurazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_emissioni
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int updateByExampleSelective(@Param("record") RebusmTMisEmissioniDTO record, @Param("example") RebusmTMisEmissioniSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_emissioni
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int updateByExample(@Param("record") RebusmTMisEmissioniDTO record, @Param("example") RebusmTMisEmissioniSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_emissioni
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int updateByPrimaryKeySelective(RebusmTMisEmissioniDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_t_mis_emissioni
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int updateByPrimaryKey(RebusmTMisEmissioniDTO record);
}