/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuspRProcDocumentoDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuspRProcDocumentoKey;
import it.csi.rebus.rebuscrus.integration.dto.RebuspRProcDocumentoSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuspRProcDocumentoDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_r_proc_documento
	 * @mbg.generated  Tue Mar 31 12:22:34 CEST 2020
	 */
	long countByExample(RebuspRProcDocumentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_r_proc_documento
	 * @mbg.generated  Tue Mar 31 12:22:34 CEST 2020
	 */
	int deleteByExample(RebuspRProcDocumentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_r_proc_documento
	 * @mbg.generated  Tue Mar 31 12:22:34 CEST 2020
	 */
	int deleteByPrimaryKey(RebuspRProcDocumentoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_r_proc_documento
	 * @mbg.generated  Tue Mar 31 12:22:34 CEST 2020
	 */
	int insert(RebuspRProcDocumentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_r_proc_documento
	 * @mbg.generated  Tue Mar 31 12:22:34 CEST 2020
	 */
	int insertSelective(RebuspRProcDocumentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_r_proc_documento
	 * @mbg.generated  Tue Mar 31 12:22:34 CEST 2020
	 */
	List<RebuspRProcDocumentoDTO> selectByExampleWithBLOBs(RebuspRProcDocumentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_r_proc_documento
	 * @mbg.generated  Tue Mar 31 12:22:34 CEST 2020
	 */
	List<RebuspRProcDocumentoDTO> selectByExample(RebuspRProcDocumentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_r_proc_documento
	 * @mbg.generated  Tue Mar 31 12:22:34 CEST 2020
	 */
	RebuspRProcDocumentoDTO selectByPrimaryKey(RebuspRProcDocumentoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_r_proc_documento
	 * @mbg.generated  Tue Mar 31 12:22:34 CEST 2020
	 */
	int updateByExampleSelective(@Param("record") RebuspRProcDocumentoDTO record, @Param("example") RebuspRProcDocumentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_r_proc_documento
	 * @mbg.generated  Tue Mar 31 12:22:34 CEST 2020
	 */
	int updateByExampleWithBLOBs(@Param("record") RebuspRProcDocumentoDTO record, @Param("example") RebuspRProcDocumentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_r_proc_documento
	 * @mbg.generated  Tue Mar 31 12:22:34 CEST 2020
	 */
	int updateByExample(@Param("record") RebuspRProcDocumentoDTO record, @Param("example") RebuspRProcDocumentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_r_proc_documento
	 * @mbg.generated  Tue Mar 31 12:22:34 CEST 2020
	 */
	int updateByPrimaryKeySelective(RebuspRProcDocumentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_r_proc_documento
	 * @mbg.generated  Tue Mar 31 12:22:34 CEST 2020
	 */
	int updateByPrimaryKeyWithBLOBs(RebuspRProcDocumentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_r_proc_documento
	 * @mbg.generated  Tue Mar 31 12:22:34 CEST 2020
	 */
	int updateByPrimaryKey(RebuspRProcDocumentoDTO record);
}