/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuscDSistemaBigliettazioneDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuscDSistemaBigliettazioneSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuscDSistemaBigliettazioneDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_bigliettazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    long countByExample(RebuscDSistemaBigliettazioneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_bigliettazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int deleteByExample(RebuscDSistemaBigliettazioneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_bigliettazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int deleteByPrimaryKey(Double idSistemaBigliettazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_bigliettazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int insert(RebuscDSistemaBigliettazioneDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_bigliettazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int insertSelective(RebuscDSistemaBigliettazioneDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_bigliettazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    List<RebuscDSistemaBigliettazioneDTO> selectByExample(RebuscDSistemaBigliettazioneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_bigliettazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    RebuscDSistemaBigliettazioneDTO selectByPrimaryKey(Double idSistemaBigliettazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_bigliettazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int updateByExampleSelective(@Param("record") RebuscDSistemaBigliettazioneDTO record, @Param("example") RebuscDSistemaBigliettazioneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_bigliettazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int updateByExample(@Param("record") RebuscDSistemaBigliettazioneDTO record, @Param("example") RebuscDSistemaBigliettazioneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_bigliettazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int updateByPrimaryKeySelective(RebuscDSistemaBigliettazioneDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_bigliettazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int updateByPrimaryKey(RebuscDSistemaBigliettazioneDTO record);
}