/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuscRDocContribuzioneDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuscRDocContribuzioneSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuscRDocContribuzioneDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_doc_contribuzione
	 * @mbg.generated  Thu Dec 16 16:26:20 CET 2021
	 */
	long countByExample(RebuscRDocContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_doc_contribuzione
	 * @mbg.generated  Thu Dec 16 16:26:20 CET 2021
	 */
	int deleteByExample(RebuscRDocContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_doc_contribuzione
	 * @mbg.generated  Thu Dec 16 16:26:20 CET 2021
	 */
	int deleteByPrimaryKey(Long idDocContribuzione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_doc_contribuzione
	 * @mbg.generated  Thu Dec 16 16:26:20 CET 2021
	 */
	int insert(RebuscRDocContribuzioneDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_doc_contribuzione
	 * @mbg.generated  Thu Dec 16 16:26:20 CET 2021
	 */
	int insertSelective(RebuscRDocContribuzioneDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_doc_contribuzione
	 * @mbg.generated  Thu Dec 16 16:26:20 CET 2021
	 */
	List<RebuscRDocContribuzioneDTO> selectByExampleWithBLOBs(RebuscRDocContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_doc_contribuzione
	 * @mbg.generated  Thu Dec 16 16:26:20 CET 2021
	 */
	List<RebuscRDocContribuzioneDTO> selectByExample(RebuscRDocContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_doc_contribuzione
	 * @mbg.generated  Thu Dec 16 16:26:20 CET 2021
	 */
	RebuscRDocContribuzioneDTO selectByPrimaryKey(Long idDocContribuzione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_doc_contribuzione
	 * @mbg.generated  Thu Dec 16 16:26:20 CET 2021
	 */
	int updateByExampleSelective(@Param("record") RebuscRDocContribuzioneDTO record,
			@Param("example") RebuscRDocContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_doc_contribuzione
	 * @mbg.generated  Thu Dec 16 16:26:20 CET 2021
	 */
	int updateByExampleWithBLOBs(@Param("record") RebuscRDocContribuzioneDTO record,
			@Param("example") RebuscRDocContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_doc_contribuzione
	 * @mbg.generated  Thu Dec 16 16:26:20 CET 2021
	 */
	int updateByExample(@Param("record") RebuscRDocContribuzioneDTO record,
			@Param("example") RebuscRDocContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_doc_contribuzione
	 * @mbg.generated  Thu Dec 16 16:26:20 CET 2021
	 */
	int updateByPrimaryKeySelective(RebuscRDocContribuzioneDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_doc_contribuzione
	 * @mbg.generated  Thu Dec 16 16:26:20 CET 2021
	 */
	int updateByPrimaryKeyWithBLOBs(RebuscRDocContribuzioneDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_doc_contribuzione
	 * @mbg.generated  Thu Dec 16 16:26:20 CET 2021
	 */
	int updateByPrimaryKey(RebuscRDocContribuzioneDTO record);
}