/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusDTipoImmatricolDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebusDTipoImmatricolSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusDTipoImmatricolDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_immatricol
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	long countByExample(RebusDTipoImmatricolSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_immatricol
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByExample(RebusDTipoImmatricolSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_immatricol
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByPrimaryKey(Long idTipoImmatricolazione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_immatricol
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insert(RebusDTipoImmatricolDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_immatricol
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insertSelective(RebusDTipoImmatricolDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_immatricol
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	List<RebusDTipoImmatricolDTO> selectByExample(RebusDTipoImmatricolSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_immatricol
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	RebusDTipoImmatricolDTO selectByPrimaryKey(Long idTipoImmatricolazione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_immatricol
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExampleSelective(@Param("record") RebusDTipoImmatricolDTO record, @Param("example") RebusDTipoImmatricolSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_immatricol
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExample(@Param("record") RebusDTipoImmatricolDTO record, @Param("example") RebusDTipoImmatricolSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_immatricol
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByPrimaryKeySelective(RebusDTipoImmatricolDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_immatricol
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByPrimaryKey(RebusDTipoImmatricolDTO record);
}