/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuscDTipoSostituzioneDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuscDTipoSostituzioneSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuscDTipoSostituzioneDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_sostituzione
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	long countByExample(RebuscDTipoSostituzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_sostituzione
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int deleteByExample(RebuscDTipoSostituzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_sostituzione
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int deleteByPrimaryKey(Double idTipoSostituzione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_sostituzione
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int insert(RebuscDTipoSostituzioneDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_sostituzione
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int insertSelective(RebuscDTipoSostituzioneDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_sostituzione
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	List<RebuscDTipoSostituzioneDTO> selectByExample(RebuscDTipoSostituzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_sostituzione
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	RebuscDTipoSostituzioneDTO selectByPrimaryKey(Double idTipoSostituzione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_sostituzione
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int updateByExampleSelective(@Param("record") RebuscDTipoSostituzioneDTO record,
			@Param("example") RebuscDTipoSostituzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_sostituzione
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int updateByExample(@Param("record") RebuscDTipoSostituzioneDTO record,
			@Param("example") RebuscDTipoSostituzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_sostituzione
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int updateByPrimaryKeySelective(RebuscDTipoSostituzioneDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_sostituzione
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int updateByPrimaryKey(RebuscDTipoSostituzioneDTO record);
}