/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuscDPortabiciDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuscDPortabiciSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuscDPortabiciDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_portabici
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    long countByExample(RebuscDPortabiciSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_portabici
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int deleteByExample(RebuscDPortabiciSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_portabici
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int deleteByPrimaryKey(Double idPortabici);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_portabici
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int insert(RebuscDPortabiciDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_portabici
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int insertSelective(RebuscDPortabiciDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_portabici
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    List<RebuscDPortabiciDTO> selectByExample(RebuscDPortabiciSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_portabici
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    RebuscDPortabiciDTO selectByPrimaryKey(Double idPortabici);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_portabici
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int updateByExampleSelective(@Param("record") RebuscDPortabiciDTO record, @Param("example") RebuscDPortabiciSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_portabici
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int updateByExample(@Param("record") RebuscDPortabiciDTO record, @Param("example") RebuscDPortabiciSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_portabici
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int updateByPrimaryKeySelective(RebuscDPortabiciDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_portabici
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int updateByPrimaryKey(RebuscDPortabiciDTO record);
}