/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusmDTipoMonitoraggioDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebusmDTipoMonitoraggioSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusmDTipoMonitoraggioDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_tipo_monitoraggio
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    long countByExample(RebusmDTipoMonitoraggioSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_tipo_monitoraggio
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int deleteByExample(RebusmDTipoMonitoraggioSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_tipo_monitoraggio
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int deleteByPrimaryKey(Long idTipoMonitoraggio);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_tipo_monitoraggio
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int insert(RebusmDTipoMonitoraggioDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_tipo_monitoraggio
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int insertSelective(RebusmDTipoMonitoraggioDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_tipo_monitoraggio
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    List<RebusmDTipoMonitoraggioDTO> selectByExample(RebusmDTipoMonitoraggioSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_tipo_monitoraggio
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    RebusmDTipoMonitoraggioDTO selectByPrimaryKey(Long idTipoMonitoraggio);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_tipo_monitoraggio
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int updateByExampleSelective(@Param("record") RebusmDTipoMonitoraggioDTO record, @Param("example") RebusmDTipoMonitoraggioSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_tipo_monitoraggio
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int updateByExample(@Param("record") RebusmDTipoMonitoraggioDTO record, @Param("example") RebusmDTipoMonitoraggioSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_tipo_monitoraggio
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int updateByPrimaryKeySelective(RebusmDTipoMonitoraggioDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusm_d_tipo_monitoraggio
     *
     * @mbg.generated Fri Dec 10 10:30:29 CET 2021
     */
    int updateByPrimaryKey(RebusmDTipoMonitoraggioDTO record);
}