/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusRDocVariazAutobusDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebusRDocVariazAutobusKey;
import it.csi.rebus.rebuscrus.integration.dto.RebusRDocVariazAutobusSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusRDocVariazAutobusDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_doc_variaz_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	long countByExample(RebusRDocVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_doc_variaz_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByExample(RebusRDocVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_doc_variaz_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByPrimaryKey(RebusRDocVariazAutobusKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_doc_variaz_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insert(RebusRDocVariazAutobusDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_doc_variaz_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insertSelective(RebusRDocVariazAutobusDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_doc_variaz_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	List<RebusRDocVariazAutobusDTO> selectByExampleWithBLOBs(RebusRDocVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_doc_variaz_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	List<RebusRDocVariazAutobusDTO> selectByExample(RebusRDocVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_doc_variaz_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	RebusRDocVariazAutobusDTO selectByPrimaryKey(RebusRDocVariazAutobusKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_doc_variaz_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExampleSelective(@Param("record") RebusRDocVariazAutobusDTO record,
	        @Param("example") RebusRDocVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_doc_variaz_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExampleWithBLOBs(@Param("record") RebusRDocVariazAutobusDTO record,
	        @Param("example") RebusRDocVariazAutobusSelector example);
	

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_doc_variaz_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExample(@Param("record") RebusRDocVariazAutobusDTO record, @Param("example") RebusRDocVariazAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_doc_variaz_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByPrimaryKeySelective(RebusRDocVariazAutobusDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_doc_variaz_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByPrimaryKeyWithBLOBs(RebusRDocVariazAutobusDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_doc_variaz_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByPrimaryKey(RebusRDocVariazAutobusDTO record);
	
	int updateDocument(RebusRDocVariazAutobusDTO record);


}