/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusDTipoAlimentazioneDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebusDTipoAlimentazioneSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusDTipoAlimentazioneDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_alimentazione
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	long countByExample(RebusDTipoAlimentazioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_alimentazione
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByExample(RebusDTipoAlimentazioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_alimentazione
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByPrimaryKey(Long idTipoAlimentazione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_alimentazione
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insert(RebusDTipoAlimentazioneDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_alimentazione
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insertSelective(RebusDTipoAlimentazioneDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_alimentazione
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	List<RebusDTipoAlimentazioneDTO> selectByExample(RebusDTipoAlimentazioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_alimentazione
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	RebusDTipoAlimentazioneDTO selectByPrimaryKey(Long idTipoAlimentazione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_alimentazione
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExampleSelective(@Param("record") RebusDTipoAlimentazioneDTO record,
	        @Param("example") RebusDTipoAlimentazioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_alimentazione
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExample(@Param("record") RebusDTipoAlimentazioneDTO record, @Param("example") RebusDTipoAlimentazioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_alimentazione
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByPrimaryKeySelective(RebusDTipoAlimentazioneDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_alimentazione
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByPrimaryKey(RebusDTipoAlimentazioneDTO record);
}