/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuscTContribuzioneDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuscTContribuzioneSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuscTContribuzioneDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_contribuzione
	 * @mbg.generated  Wed Mar 02 17:39:34 CET 2022
	 */
	long countByExample(RebuscTContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_contribuzione
	 * @mbg.generated  Wed Mar 02 17:39:34 CET 2022
	 */
	int deleteByExample(RebuscTContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_contribuzione
	 * @mbg.generated  Wed Mar 02 17:39:34 CET 2022
	 */
	int deleteByPrimaryKey(Long idContribuzione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_contribuzione
	 * @mbg.generated  Wed Mar 02 17:39:34 CET 2022
	 */
	int insert(RebuscTContribuzioneDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_contribuzione
	 * @mbg.generated  Wed Mar 02 17:39:34 CET 2022
	 */
	int insertSelective(RebuscTContribuzioneDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_contribuzione
	 * @mbg.generated  Wed Mar 02 17:39:34 CET 2022
	 */
	List<RebuscTContribuzioneDTO> selectByExample(RebuscTContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_contribuzione
	 * @mbg.generated  Wed Mar 02 17:39:34 CET 2022
	 */
	RebuscTContribuzioneDTO selectByPrimaryKey(Long idContribuzione);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_contribuzione
	 * @mbg.generated  Wed Mar 02 17:39:34 CET 2022
	 */
	int updateByExampleSelective(@Param("record") RebuscTContribuzioneDTO record,
			@Param("example") RebuscTContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_contribuzione
	 * @mbg.generated  Wed Mar 02 17:39:34 CET 2022
	 */
	int updateByExample(@Param("record") RebuscTContribuzioneDTO record,
			@Param("example") RebuscTContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_contribuzione
	 * @mbg.generated  Wed Mar 02 17:39:34 CET 2022
	 */
	int updateByPrimaryKeySelective(RebuscTContribuzioneDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_contribuzione
	 * @mbg.generated  Wed Mar 02 17:39:34 CET 2022
	 */
	int updateByPrimaryKey(RebuscTContribuzioneDTO record);
}