/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuscRVoceCostoFornituraDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuscRVoceCostoFornituraSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuscRVoceCostoFornituraDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_voce_costo_fornitura
	 * @mbg.generated  Thu Mar 31 15:59:58 CEST 2022
	 */
	long countByExample(RebuscRVoceCostoFornituraSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_voce_costo_fornitura
	 * @mbg.generated  Thu Mar 31 15:59:58 CEST 2022
	 */
	int deleteByExample(RebuscRVoceCostoFornituraSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_voce_costo_fornitura
	 * @mbg.generated  Thu Mar 31 15:59:58 CEST 2022
	 */
	int deleteByPrimaryKey(Long idVoceCostoFornitura);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_voce_costo_fornitura
	 * @mbg.generated  Thu Mar 31 15:59:58 CEST 2022
	 */
	int insert(RebuscRVoceCostoFornituraDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_voce_costo_fornitura
	 * @mbg.generated  Thu Mar 31 15:59:58 CEST 2022
	 */
	int insertSelective(RebuscRVoceCostoFornituraDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_voce_costo_fornitura
	 * @mbg.generated  Thu Mar 31 15:59:58 CEST 2022
	 */
	List<RebuscRVoceCostoFornituraDTO> selectByExample(RebuscRVoceCostoFornituraSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_voce_costo_fornitura
	 * @mbg.generated  Thu Mar 31 15:59:58 CEST 2022
	 */
	RebuscRVoceCostoFornituraDTO selectByPrimaryKey(Long idVoceCostoFornitura);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_voce_costo_fornitura
	 * @mbg.generated  Thu Mar 31 15:59:58 CEST 2022
	 */
	int updateByExampleSelective(@Param("record") RebuscRVoceCostoFornituraDTO record,
			@Param("example") RebuscRVoceCostoFornituraSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_voce_costo_fornitura
	 * @mbg.generated  Thu Mar 31 15:59:58 CEST 2022
	 */
	int updateByExample(@Param("record") RebuscRVoceCostoFornituraDTO record,
			@Param("example") RebuscRVoceCostoFornituraSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_voce_costo_fornitura
	 * @mbg.generated  Thu Mar 31 15:59:58 CEST 2022
	 */
	int updateByPrimaryKeySelective(RebuscRVoceCostoFornituraDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_voce_costo_fornitura
	 * @mbg.generated  Thu Mar 31 15:59:58 CEST 2022
	 */
	int updateByPrimaryKey(RebuscRVoceCostoFornituraDTO record);
}