/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusRAziendaAutobusDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebusRAziendaAutobusKey;
import it.csi.rebus.rebuscrus.integration.dto.RebusRAziendaAutobusSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusRAziendaAutobusDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_azienda_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	long countByExample(RebusRAziendaAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_azienda_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByExample(RebusRAziendaAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_azienda_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByPrimaryKey(RebusRAziendaAutobusKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_azienda_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insert(RebusRAziendaAutobusDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_azienda_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insertSelective(RebusRAziendaAutobusDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_azienda_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	List<RebusRAziendaAutobusDTO> selectByExample(RebusRAziendaAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_azienda_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	RebusRAziendaAutobusDTO selectByPrimaryKey(RebusRAziendaAutobusKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_azienda_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExampleSelective(@Param("record") RebusRAziendaAutobusDTO record, @Param("example") RebusRAziendaAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_azienda_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExample(@Param("record") RebusRAziendaAutobusDTO record, @Param("example") RebusRAziendaAutobusSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_azienda_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByPrimaryKeySelective(RebusRAziendaAutobusDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_azienda_autobus
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByPrimaryKey(RebusRAziendaAutobusDTO record);


}