/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusTUtentiDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebusTUtentiSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusTUtentiDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_utenti
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	long countByExample(RebusTUtentiSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_utenti
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	int deleteByExample(RebusTUtentiSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_utenti
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	int insert(RebusTUtentiDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_utenti
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	int insertSelective(RebusTUtentiDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_utenti
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	List<RebusTUtentiDTO> selectByExample(RebusTUtentiSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_utenti
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	int updateByExampleSelective(@Param("record") RebusTUtentiDTO record, @Param("example") RebusTUtentiSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_utenti
	 * @mbg.generated  Wed Dec 04 19:05:15 CET 2019
	 */
	int updateByExample(@Param("record") RebusTUtentiDTO record, @Param("example") RebusTUtentiSelector example);
}