/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuscTCostoFornituraDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuscTCostoFornituraSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuscTCostoFornituraDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_costo_fornitura
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	long countByExample(RebuscTCostoFornituraSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_costo_fornitura
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	int deleteByExample(RebuscTCostoFornituraSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_costo_fornitura
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	int deleteByPrimaryKey(Long idCostoFornitura);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_costo_fornitura
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	int insert(RebuscTCostoFornituraDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_costo_fornitura
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	int insertSelective(RebuscTCostoFornituraDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_costo_fornitura
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	List<RebuscTCostoFornituraDTO> selectByExample(RebuscTCostoFornituraSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_costo_fornitura
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	RebuscTCostoFornituraDTO selectByPrimaryKey(Long idCostoFornitura);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_costo_fornitura
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	int updateByExampleSelective(@Param("record") RebuscTCostoFornituraDTO record,
			@Param("example") RebuscTCostoFornituraSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_costo_fornitura
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	int updateByExample(@Param("record") RebuscTCostoFornituraDTO record,
			@Param("example") RebuscTCostoFornituraSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_costo_fornitura
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	int updateByPrimaryKeySelective(RebuscTCostoFornituraDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_costo_fornitura
	 * @mbg.generated  Thu Dec 16 16:16:59 CET 2021
	 */
	int updateByPrimaryKey(RebuscTCostoFornituraDTO record);
}