/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusTDepositiDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebusTDepositiSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusTDepositiDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_depositi
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	long countByExample(RebusTDepositiSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_depositi
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByExample(RebusTDepositiSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_depositi
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByPrimaryKey(Long idDeposito);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_depositi
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insert(RebusTDepositiDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_depositi
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insertSelective(RebusTDepositiDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_depositi
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	List<RebusTDepositiDTO> selectByExample(RebusTDepositiSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_depositi
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	RebusTDepositiDTO selectByPrimaryKey(Long idDeposito);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_depositi
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExampleSelective(@Param("record") RebusTDepositiDTO record, @Param("example") RebusTDepositiSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_depositi
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExample(@Param("record") RebusTDepositiDTO record, @Param("example") RebusTDepositiSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_depositi
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByPrimaryKeySelective(RebusTDepositiDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_t_depositi
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByPrimaryKey(RebusTDepositiDTO record);
}