/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusDProprietaDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebusDProprietaSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusDProprietaDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_proprieta
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	long countByExample(RebusDProprietaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_proprieta
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByExample(RebusDProprietaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_proprieta
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByPrimaryKey(Long idProprieta);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_proprieta
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insert(RebusDProprietaDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_proprieta
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insertSelective(RebusDProprietaDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_proprieta
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	List<RebusDProprietaDTO> selectByExample(RebusDProprietaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_proprieta
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	RebusDProprietaDTO selectByPrimaryKey(Long idProprieta);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_proprieta
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExampleSelective(@Param("record") RebusDProprietaDTO record, @Param("example") RebusDProprietaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_proprieta
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExample(@Param("record") RebusDProprietaDTO record, @Param("example") RebusDProprietaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_proprieta
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByPrimaryKeySelective(RebusDProprietaDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_proprieta
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByPrimaryKey(RebusDProprietaDTO record);
}