/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuspDTransizioneAutomaDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuspDTransizioneAutomaSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuspDTransizioneAutomaDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	long countByExample(RebuspDTransizioneAutomaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	int deleteByExample(RebuspDTransizioneAutomaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	int deleteByPrimaryKey(Long idTransizioneAutoma);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	int insert(RebuspDTransizioneAutomaDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	int insertSelective(RebuspDTransizioneAutomaDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	List<RebuspDTransizioneAutomaDTO> selectByExample(RebuspDTransizioneAutomaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	RebuspDTransizioneAutomaDTO selectByPrimaryKey(Long idTransizioneAutoma);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	int updateByExampleSelective(@Param("record") RebuspDTransizioneAutomaDTO record,
			@Param("example") RebuspDTransizioneAutomaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	int updateByExample(@Param("record") RebuspDTransizioneAutomaDTO record,
			@Param("example") RebuspDTransizioneAutomaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	int updateByPrimaryKeySelective(RebuspDTransizioneAutomaDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_d_transizione_automa
	 * @mbg.generated  Tue Jul 07 15:13:55 CEST 2020
	 */
	int updateByPrimaryKey(RebuspDTransizioneAutomaDTO record);
}