/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuscRFatturaBonificoKey;
import it.csi.rebus.rebuscrus.integration.dto.RebuscRFatturaBonificoSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuscRFatturaBonificoDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_fattura_bonifico
	 * @mbg.generated  Fri Mar 04 15:16:01 CET 2022
	 */
	long countByExample(RebuscRFatturaBonificoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_fattura_bonifico
	 * @mbg.generated  Fri Mar 04 15:16:01 CET 2022
	 */
	int deleteByExample(RebuscRFatturaBonificoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_fattura_bonifico
	 * @mbg.generated  Fri Mar 04 15:16:01 CET 2022
	 */
	int deleteByPrimaryKey(RebuscRFatturaBonificoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_fattura_bonifico
	 * @mbg.generated  Fri Mar 04 15:16:01 CET 2022
	 */
	int insert(RebuscRFatturaBonificoKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_fattura_bonifico
	 * @mbg.generated  Fri Mar 04 15:16:01 CET 2022
	 */
	int insertSelective(RebuscRFatturaBonificoKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_fattura_bonifico
	 * @mbg.generated  Fri Mar 04 15:16:01 CET 2022
	 */
	List<RebuscRFatturaBonificoKey> selectByExample(RebuscRFatturaBonificoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_fattura_bonifico
	 * @mbg.generated  Fri Mar 04 15:16:01 CET 2022
	 */
	int updateByExampleSelective(@Param("record") RebuscRFatturaBonificoKey record,
			@Param("example") RebuscRFatturaBonificoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_r_fattura_bonifico
	 * @mbg.generated  Fri Mar 04 15:16:01 CET 2022
	 */
	int updateByExample(@Param("record") RebuscRFatturaBonificoKey record,
			@Param("example") RebuscRFatturaBonificoSelector example);
}