/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuscDTipoDocQuietanzaDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuscDTipoDocQuietanzaSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuscDTipoDocQuietanzaDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_doc_quietanza
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	long countByExample(RebuscDTipoDocQuietanzaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_doc_quietanza
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int deleteByExample(RebuscDTipoDocQuietanzaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_doc_quietanza
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int deleteByPrimaryKey(Double idTipoDocQuietanza);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_doc_quietanza
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int insert(RebuscDTipoDocQuietanzaDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_doc_quietanza
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int insertSelective(RebuscDTipoDocQuietanzaDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_doc_quietanza
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	List<RebuscDTipoDocQuietanzaDTO> selectByExample(RebuscDTipoDocQuietanzaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_doc_quietanza
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	RebuscDTipoDocQuietanzaDTO selectByPrimaryKey(Double idTipoDocQuietanza);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_doc_quietanza
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int updateByExampleSelective(@Param("record") RebuscDTipoDocQuietanzaDTO record,
			@Param("example") RebuscDTipoDocQuietanzaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_doc_quietanza
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int updateByExample(@Param("record") RebuscDTipoDocQuietanzaDTO record,
			@Param("example") RebuscDTipoDocQuietanzaSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_doc_quietanza
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int updateByPrimaryKeySelective(RebuscDTipoDocQuietanzaDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_d_tipo_doc_quietanza
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int updateByPrimaryKey(RebuscDTipoDocQuietanzaDTO record);
}