/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuspCTipoProcTipoDocKey;
import it.csi.rebus.rebuscrus.integration.dto.RebuspCTipoProcTipoDocSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuspCTipoProcTipoDocDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_c_tipo_proc_tipo_doc
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    long countByExample(RebuspCTipoProcTipoDocSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_c_tipo_proc_tipo_doc
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    int deleteByExample(RebuspCTipoProcTipoDocSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_c_tipo_proc_tipo_doc
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    int deleteByPrimaryKey(RebuspCTipoProcTipoDocKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_c_tipo_proc_tipo_doc
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    int insert(RebuspCTipoProcTipoDocKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_c_tipo_proc_tipo_doc
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    int insertSelective(RebuspCTipoProcTipoDocKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_c_tipo_proc_tipo_doc
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    List<RebuspCTipoProcTipoDocKey> selectByExample(RebuspCTipoProcTipoDocSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_c_tipo_proc_tipo_doc
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    int updateByExampleSelective(@Param("record") RebuspCTipoProcTipoDocKey record, @Param("example") RebuspCTipoProcTipoDocSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusp_c_tipo_proc_tipo_doc
     *
     * @mbg.generated Mon Feb 03 16:50:41 CET 2020
     */
    int updateByExample(@Param("record") RebuspCTipoProcTipoDocKey record, @Param("example") RebuspCTipoProcTipoDocSelector example);
}