/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuscDSistemaLocalizzazioneDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuscDSistemaLocalizzazioneSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuscDSistemaLocalizzazioneDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    long countByExample(RebuscDSistemaLocalizzazioneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int deleteByExample(RebuscDSistemaLocalizzazioneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int deleteByPrimaryKey(Double idSistemaLocalizzazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int insert(RebuscDSistemaLocalizzazioneDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int insertSelective(RebuscDSistemaLocalizzazioneDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    List<RebuscDSistemaLocalizzazioneDTO> selectByExample(RebuscDSistemaLocalizzazioneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    RebuscDSistemaLocalizzazioneDTO selectByPrimaryKey(Double idSistemaLocalizzazione);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int updateByExampleSelective(@Param("record") RebuscDSistemaLocalizzazioneDTO record, @Param("example") RebuscDSistemaLocalizzazioneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int updateByExample(@Param("record") RebuscDSistemaLocalizzazioneDTO record, @Param("example") RebuscDSistemaLocalizzazioneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int updateByPrimaryKeySelective(RebuscDSistemaLocalizzazioneDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rebusc_d_sistema_localizzazione
     *
     * @mbg.generated Tue Jan 04 08:25:47 CET 2022
     */
    int updateByPrimaryKey(RebuscDSistemaLocalizzazioneDTO record);
}