/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuspTIterProcedimentoDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuspTIterProcedimentoSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuspTIterProcedimentoDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_iter_procedimento
	 * @mbg.generated  Tue Feb 25 12:16:12 CET 2020
	 */
	long countByExample(RebuspTIterProcedimentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_iter_procedimento
	 * @mbg.generated  Tue Feb 25 12:16:12 CET 2020
	 */
	int deleteByExample(RebuspTIterProcedimentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_iter_procedimento
	 * @mbg.generated  Tue Feb 25 12:16:12 CET 2020
	 */
	int deleteByPrimaryKey(Long idIterProcedimento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_iter_procedimento
	 * @mbg.generated  Tue Feb 25 12:16:12 CET 2020
	 */
	int insert(RebuspTIterProcedimentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_iter_procedimento
	 * @mbg.generated  Tue Feb 25 12:16:12 CET 2020
	 */
	int insertSelective(RebuspTIterProcedimentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_iter_procedimento
	 * @mbg.generated  Tue Feb 25 12:16:12 CET 2020
	 */
	List<RebuspTIterProcedimentoDTO> selectByExample(RebuspTIterProcedimentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_iter_procedimento
	 * @mbg.generated  Tue Feb 25 12:16:12 CET 2020
	 */
	RebuspTIterProcedimentoDTO selectByPrimaryKey(Long idIterProcedimento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_iter_procedimento
	 * @mbg.generated  Tue Feb 25 12:16:12 CET 2020
	 */
	int updateByExampleSelective(@Param("record") RebuspTIterProcedimentoDTO record,
			@Param("example") RebuspTIterProcedimentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_iter_procedimento
	 * @mbg.generated  Tue Feb 25 12:16:12 CET 2020
	 */
	int updateByExample(@Param("record") RebuspTIterProcedimentoDTO record,
			@Param("example") RebuspTIterProcedimentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_iter_procedimento
	 * @mbg.generated  Tue Feb 25 12:16:12 CET 2020
	 */
	int updateByPrimaryKeySelective(RebuspTIterProcedimentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusp_t_iter_procedimento
	 * @mbg.generated  Tue Feb 25 12:16:12 CET 2020
	 */
	int updateByPrimaryKey(RebuspTIterProcedimentoDTO record);
}