/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusDTipoAllestimentoDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebusDTipoAllestimentoSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusDTipoAllestimentoDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_allestimento
	 * @mbg.generated  Mon Dec 13 14:47:16 CET 2021
	 */
	long countByExample(RebusDTipoAllestimentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_allestimento
	 * @mbg.generated  Mon Dec 13 14:47:16 CET 2021
	 */
	int deleteByExample(RebusDTipoAllestimentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_allestimento
	 * @mbg.generated  Mon Dec 13 14:47:16 CET 2021
	 */
	int deleteByPrimaryKey(Long idTipoAllestimento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_allestimento
	 * @mbg.generated  Mon Dec 13 14:47:16 CET 2021
	 */
	int insert(RebusDTipoAllestimentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_allestimento
	 * @mbg.generated  Mon Dec 13 14:47:16 CET 2021
	 */
	int insertSelective(RebusDTipoAllestimentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_allestimento
	 * @mbg.generated  Mon Dec 13 14:47:16 CET 2021
	 */
	List<RebusDTipoAllestimentoDTO> selectByExample(RebusDTipoAllestimentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_allestimento
	 * @mbg.generated  Mon Dec 13 14:47:16 CET 2021
	 */
	RebusDTipoAllestimentoDTO selectByPrimaryKey(Long idTipoAllestimento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_allestimento
	 * @mbg.generated  Mon Dec 13 14:47:16 CET 2021
	 */
	int updateByExampleSelective(@Param("record") RebusDTipoAllestimentoDTO record,
			@Param("example") RebusDTipoAllestimentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_allestimento
	 * @mbg.generated  Mon Dec 13 14:47:16 CET 2021
	 */
	int updateByExample(@Param("record") RebusDTipoAllestimentoDTO record,
			@Param("example") RebusDTipoAllestimentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_allestimento
	 * @mbg.generated  Mon Dec 13 14:47:16 CET 2021
	 */
	int updateByPrimaryKeySelective(RebusDTipoAllestimentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_d_tipo_allestimento
	 * @mbg.generated  Mon Dec 13 14:47:16 CET 2021
	 */
	int updateByPrimaryKey(RebusDTipoAllestimentoDTO record);
}