/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebusRStoriaVarautobusDpKey;
import it.csi.rebus.rebuscrus.integration.dto.RebusRStoriaVarautobusDpSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebusRStoriaVarautobusDpDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_storia_varautobus_dp
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	long countByExample(RebusRStoriaVarautobusDpSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_storia_varautobus_dp
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByExample(RebusRStoriaVarautobusDpSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_storia_varautobus_dp
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int deleteByPrimaryKey(RebusRStoriaVarautobusDpKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_storia_varautobus_dp
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insert(RebusRStoriaVarautobusDpKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_storia_varautobus_dp
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int insertSelective(RebusRStoriaVarautobusDpKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_storia_varautobus_dp
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	List<RebusRStoriaVarautobusDpKey> selectByExample(RebusRStoriaVarautobusDpSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_storia_varautobus_dp
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExampleSelective(@Param("record") RebusRStoriaVarautobusDpKey record,
	        @Param("example") RebusRStoriaVarautobusDpSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebus_r_storia_varautobus_dp
	 * @mbg.generated  Mon Oct 21 17:24:13 CEST 2019
	 */
	int updateByExample(@Param("record") RebusRStoriaVarautobusDpKey record, @Param("example") RebusRStoriaVarautobusDpSelector example);
}