/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.RebuscTFonteFinanziamentoDTO;
import it.csi.rebus.rebuscrus.integration.dto.RebuscTFonteFinanziamentoSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RebuscTFonteFinanziamentoDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_fonte_finanziamento
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	long countByExample(RebuscTFonteFinanziamentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_fonte_finanziamento
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int deleteByExample(RebuscTFonteFinanziamentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_fonte_finanziamento
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int deleteByPrimaryKey(Long idFonteFinanziamento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_fonte_finanziamento
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int insert(RebuscTFonteFinanziamentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_fonte_finanziamento
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int insertSelective(RebuscTFonteFinanziamentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_fonte_finanziamento
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	List<RebuscTFonteFinanziamentoDTO> selectByExample(RebuscTFonteFinanziamentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_fonte_finanziamento
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	RebuscTFonteFinanziamentoDTO selectByPrimaryKey(Long idFonteFinanziamento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_fonte_finanziamento
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int updateByExampleSelective(@Param("record") RebuscTFonteFinanziamentoDTO record,
			@Param("example") RebuscTFonteFinanziamentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_fonte_finanziamento
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int updateByExample(@Param("record") RebuscTFonteFinanziamentoDTO record,
			@Param("example") RebuscTFonteFinanziamentoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_fonte_finanziamento
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int updateByPrimaryKeySelective(RebuscTFonteFinanziamentoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table rebusc_t_fonte_finanziamento
	 * @mbg.generated  Fri Nov 19 15:37:42 CET 2021
	 */
	int updateByPrimaryKey(RebuscTFonteFinanziamentoDTO record);
	
	

}