/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.SirtplaDNaturaGiuridicaDTO;
import it.csi.rebus.rebuscrus.integration.dto.SirtplaDNaturaGiuridicaSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirtplaDNaturaGiuridicaDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    long countByExample(SirtplaDNaturaGiuridicaSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int deleteByExample(SirtplaDNaturaGiuridicaSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int deleteByPrimaryKey(Long idDeposito);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int insert(SirtplaDNaturaGiuridicaDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int insertSelective(SirtplaDNaturaGiuridicaDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    List<SirtplaDNaturaGiuridicaDTO> selectByExample(SirtplaDNaturaGiuridicaSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    SirtplaDNaturaGiuridicaDTO selectByPrimaryKey(Long idDeposito);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int updateByExampleSelective(@Param("record") SirtplaDNaturaGiuridicaDTO record, @Param("example") SirtplaDNaturaGiuridicaSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int updateByExample(@Param("record") SirtplaDNaturaGiuridicaDTO record, @Param("example") SirtplaDNaturaGiuridicaSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int updateByPrimaryKeySelective(SirtplaDNaturaGiuridicaDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int updateByPrimaryKey(SirtplaDNaturaGiuridicaDTO record);
}