/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.SirtplaTSoggettoGiuridicoDTO;
import it.csi.rebus.rebuscrus.integration.dto.SirtplaTSoggettoGiuridicoSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirtplaTSoggettoGiuridicoDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_soggetto_giuridico
	 * @mbg.generated  Tue Mar 10 11:59:14 CET 2020
	 */
	long countByExample(SirtplaTSoggettoGiuridicoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_soggetto_giuridico
	 * @mbg.generated  Tue Mar 10 11:59:14 CET 2020
	 */
	int deleteByExample(SirtplaTSoggettoGiuridicoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_soggetto_giuridico
	 * @mbg.generated  Tue Mar 10 11:59:14 CET 2020
	 */
	int deleteByPrimaryKey(Long idSoggettoGiuridico);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_soggetto_giuridico
	 * @mbg.generated  Tue Mar 10 11:59:14 CET 2020
	 */
	int insert(SirtplaTSoggettoGiuridicoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_soggetto_giuridico
	 * @mbg.generated  Tue Mar 10 11:59:14 CET 2020
	 */
	int insertSelective(SirtplaTSoggettoGiuridicoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_soggetto_giuridico
	 * @mbg.generated  Tue Mar 10 11:59:14 CET 2020
	 */
	List<SirtplaTSoggettoGiuridicoDTO> selectByExampleWithBLOBs(SirtplaTSoggettoGiuridicoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_soggetto_giuridico
	 * @mbg.generated  Tue Mar 10 11:59:14 CET 2020
	 */
	List<SirtplaTSoggettoGiuridicoDTO> selectByExample(SirtplaTSoggettoGiuridicoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_soggetto_giuridico
	 * @mbg.generated  Tue Mar 10 11:59:14 CET 2020
	 */
	SirtplaTSoggettoGiuridicoDTO selectByPrimaryKey(Long idSoggettoGiuridico);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_soggetto_giuridico
	 * @mbg.generated  Tue Mar 10 11:59:14 CET 2020
	 */
	int updateByExampleSelective(@Param("record") SirtplaTSoggettoGiuridicoDTO record, @Param("example") SirtplaTSoggettoGiuridicoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_soggetto_giuridico
	 * @mbg.generated  Tue Mar 10 11:59:14 CET 2020
	 */
	int updateByExampleWithBLOBs(@Param("record") SirtplaTSoggettoGiuridicoDTO record, @Param("example") SirtplaTSoggettoGiuridicoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_soggetto_giuridico
	 * @mbg.generated  Tue Mar 10 11:59:14 CET 2020
	 */
	int updateByExample(@Param("record") SirtplaTSoggettoGiuridicoDTO record, @Param("example") SirtplaTSoggettoGiuridicoSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_soggetto_giuridico
	 * @mbg.generated  Tue Mar 10 11:59:14 CET 2020
	 */
	int updateByPrimaryKeySelective(SirtplaTSoggettoGiuridicoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_soggetto_giuridico
	 * @mbg.generated  Tue Mar 10 11:59:14 CET 2020
	 */
	int updateByPrimaryKeyWithBLOBs(SirtplaTSoggettoGiuridicoDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtpla_t_soggetto_giuridico
	 * @mbg.generated  Tue Mar 10 11:59:14 CET 2020
	 */
	int updateByPrimaryKey(SirtplaTSoggettoGiuridicoDTO record);
}