/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.SirtplcRSostSogContrRaggrDTO;
import it.csi.rebus.rebuscrus.integration.dto.SirtplcRSostSogContrRaggrSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirtplcRSostSogContrRaggrDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	long countByExample(SirtplcRSostSogContrRaggrSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	int deleteByExample(SirtplcRSostSogContrRaggrSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	int deleteByPrimaryKey(Long idSostSogContrRaggr);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	int insert(SirtplcRSostSogContrRaggrDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	int insertSelective(SirtplcRSostSogContrRaggrDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	List<SirtplcRSostSogContrRaggrDTO> selectByExample(SirtplcRSostSogContrRaggrSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	SirtplcRSostSogContrRaggrDTO selectByPrimaryKey(Long idSostSogContrRaggr);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	int updateByExampleSelective(@Param("record") SirtplcRSostSogContrRaggrDTO record, @Param("example") SirtplcRSostSogContrRaggrSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	int updateByExample(@Param("record") SirtplcRSostSogContrRaggrDTO record, @Param("example") SirtplcRSostSogContrRaggrSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	int updateByPrimaryKeySelective(SirtplcRSostSogContrRaggrDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sirtplc_r_sost_sog_contr_raggr
	 * @mbg.generated  Tue Jun 16 10:03:05 CEST 2020
	 */
	int updateByPrimaryKey(SirtplcRSostSogContrRaggrDTO record);
}