/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.SirtplcTContrattoDTO;
import it.csi.rebus.rebuscrus.integration.dto.SirtplcTContrattoSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirtplcTContrattoDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    long countByExample(SirtplcTContrattoSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    int deleteByExample(SirtplcTContrattoSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    int deleteByPrimaryKey(Long idContratto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    int insert(SirtplcTContrattoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    int insertSelective(SirtplcTContrattoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    List<SirtplcTContrattoDTO> selectByExample(SirtplcTContrattoSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    SirtplcTContrattoDTO selectByPrimaryKey(Long idContratto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    int updateByExampleSelective(@Param("record") SirtplcTContrattoDTO record, @Param("example") SirtplcTContrattoSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    int updateByExample(@Param("record") SirtplcTContrattoDTO record, @Param("example") SirtplcTContrattoSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    int updateByPrimaryKeySelective(SirtplcTContrattoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_t_contratto
     *
     * @mbg.generated Thu Jan 30 11:42:39 CET 2020
     */
    int updateByPrimaryKey(SirtplcTContrattoDTO record);
}