/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.SirtplRUtenteSogGiuridDTO;
import it.csi.rebus.rebuscrus.integration.dto.SirtplRUtenteSogGiuridSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirtplRUtenteSogGiuridDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_r_utente_sog_giurid
     *
     * @mbg.generated Mon Feb 03 12:51:15 CET 2020
     */
    long countByExample(SirtplRUtenteSogGiuridSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_r_utente_sog_giurid
     *
     * @mbg.generated Mon Feb 03 12:51:15 CET 2020
     */
    int deleteByExample(SirtplRUtenteSogGiuridSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_r_utente_sog_giurid
     *
     * @mbg.generated Mon Feb 03 12:51:15 CET 2020
     */
    int deleteByPrimaryKey(Long idUtenteSogGiurid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_r_utente_sog_giurid
     *
     * @mbg.generated Mon Feb 03 12:51:15 CET 2020
     */
    int insert(SirtplRUtenteSogGiuridDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_r_utente_sog_giurid
     *
     * @mbg.generated Mon Feb 03 12:51:15 CET 2020
     */
    int insertSelective(SirtplRUtenteSogGiuridDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_r_utente_sog_giurid
     *
     * @mbg.generated Mon Feb 03 12:51:15 CET 2020
     */
    List<SirtplRUtenteSogGiuridDTO> selectByExample(SirtplRUtenteSogGiuridSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_r_utente_sog_giurid
     *
     * @mbg.generated Mon Feb 03 12:51:15 CET 2020
     */
    SirtplRUtenteSogGiuridDTO selectByPrimaryKey(Long idUtenteSogGiurid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_r_utente_sog_giurid
     *
     * @mbg.generated Mon Feb 03 12:51:15 CET 2020
     */
    int updateByExampleSelective(@Param("record") SirtplRUtenteSogGiuridDTO record, @Param("example") SirtplRUtenteSogGiuridSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_r_utente_sog_giurid
     *
     * @mbg.generated Mon Feb 03 12:51:15 CET 2020
     */
    int updateByExample(@Param("record") SirtplRUtenteSogGiuridDTO record, @Param("example") SirtplRUtenteSogGiuridSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_r_utente_sog_giurid
     *
     * @mbg.generated Mon Feb 03 12:51:15 CET 2020
     */
    int updateByPrimaryKeySelective(SirtplRUtenteSogGiuridDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_r_utente_sog_giurid
     *
     * @mbg.generated Mon Feb 03 12:51:15 CET 2020
     */
    int updateByPrimaryKey(SirtplRUtenteSogGiuridDTO record);
}