/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.SirtplDComuneDTO;
import it.csi.rebus.rebuscrus.integration.dto.SirtplDComuneSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirtplDComuneDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_d_comune
     *
     * @mbg.generated Tue Mar 10 12:11:55 CET 2020
     */
    long countByExample(SirtplDComuneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_d_comune
     *
     * @mbg.generated Tue Mar 10 12:11:55 CET 2020
     */
    int deleteByExample(SirtplDComuneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_d_comune
     *
     * @mbg.generated Tue Mar 10 12:11:55 CET 2020
     */
    int deleteByPrimaryKey(Long idComune);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_d_comune
     *
     * @mbg.generated Tue Mar 10 12:11:55 CET 2020
     */
    int insert(SirtplDComuneDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_d_comune
     *
     * @mbg.generated Tue Mar 10 12:11:55 CET 2020
     */
    int insertSelective(SirtplDComuneDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_d_comune
     *
     * @mbg.generated Tue Mar 10 12:11:55 CET 2020
     */
    List<SirtplDComuneDTO> selectByExample(SirtplDComuneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_d_comune
     *
     * @mbg.generated Tue Mar 10 12:11:55 CET 2020
     */
    SirtplDComuneDTO selectByPrimaryKey(Long idComune);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_d_comune
     *
     * @mbg.generated Tue Mar 10 12:11:55 CET 2020
     */
    int updateByExampleSelective(@Param("record") SirtplDComuneDTO record, @Param("example") SirtplDComuneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_d_comune
     *
     * @mbg.generated Tue Mar 10 12:11:55 CET 2020
     */
    int updateByExample(@Param("record") SirtplDComuneDTO record, @Param("example") SirtplDComuneSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_d_comune
     *
     * @mbg.generated Tue Mar 10 12:11:55 CET 2020
     */
    int updateByPrimaryKeySelective(SirtplDComuneDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpl_d_comune
     *
     * @mbg.generated Tue Mar 10 12:11:55 CET 2020
     */
    int updateByPrimaryKey(SirtplDComuneDTO record);
}