/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.SirtplaTDepositoDTO;
import it.csi.rebus.rebuscrus.integration.dto.SirtplaTDepositoSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirtplaTDepositoDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    long countByExample(SirtplaTDepositoSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int deleteByExample(SirtplaTDepositoSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int deleteByPrimaryKey(Long idDeposito);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int insert(SirtplaTDepositoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int insertSelective(SirtplaTDepositoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    List<SirtplaTDepositoDTO> selectByExample(SirtplaTDepositoSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    SirtplaTDepositoDTO selectByPrimaryKey(Long idDeposito);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int updateByExampleSelective(@Param("record") SirtplaTDepositoDTO record, @Param("example") SirtplaTDepositoSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int updateByExample(@Param("record") SirtplaTDepositoDTO record, @Param("example") SirtplaTDepositoSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int updateByPrimaryKeySelective(SirtplaTDepositoDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtpla_t_deposito
     *
     * @mbg.generated Tue Aug 25 12:39:41 CEST 2020
     */
    int updateByPrimaryKey(SirtplaTDepositoDTO record);
}