/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.SirtplcRSostSogContrDTO;
import it.csi.rebus.rebuscrus.integration.dto.SirtplcRSostSogContrSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SirtplcRSostSogContrDAO extends ParentDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    long countByExample(SirtplcRSostSogContrSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    int deleteByExample(SirtplcRSostSogContrSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    int deleteByPrimaryKey(Long idSostSogContr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    int insert(SirtplcRSostSogContrDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    int insertSelective(SirtplcRSostSogContrDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    List<SirtplcRSostSogContrDTO> selectByExample(SirtplcRSostSogContrSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    SirtplcRSostSogContrDTO selectByPrimaryKey(Long idSostSogContr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    int updateByExampleSelective(@Param("record") SirtplcRSostSogContrDTO record, @Param("example") SirtplcRSostSogContrSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    int updateByExample(@Param("record") SirtplcRSostSogContrDTO record, @Param("example") SirtplcRSostSogContrSelector example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    int updateByPrimaryKeySelective(SirtplcRSostSogContrDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sirtplc_r_sost_sog_contr
     *
     * @mbg.generated Thu Jun 11 11:53:04 CEST 2020
     */
    int updateByPrimaryKey(SirtplcRSostSogContrDTO record);
}