/*
* SPDX-FileCopyrightText: (C) Copyright 2022 Regione Piemonte
* SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.rebus.rebuscrus.integration.dao;

import it.csi.rebus.rebuscrus.integration.dto.VExportRicercaContribuzioneDTO;
import it.csi.rebus.rebuscrus.integration.dto.VExportRicercaContribuzioneSelector;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VExportRicercaContribuzioneDAO extends ParentDAO {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_export_ricerca_contribuzione
	 * @mbg.generated  Fri Apr 08 14:30:08 CEST 2022
	 */
	long countByExample(VExportRicercaContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_export_ricerca_contribuzione
	 * @mbg.generated  Fri Apr 08 14:30:08 CEST 2022
	 */
	int deleteByExample(VExportRicercaContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_export_ricerca_contribuzione
	 * @mbg.generated  Fri Apr 08 14:30:08 CEST 2022
	 */
	int insert(VExportRicercaContribuzioneDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_export_ricerca_contribuzione
	 * @mbg.generated  Fri Apr 08 14:30:08 CEST 2022
	 */
	int insertSelective(VExportRicercaContribuzioneDTO record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_export_ricerca_contribuzione
	 * @mbg.generated  Fri Apr 08 14:30:08 CEST 2022
	 */
	List<VExportRicercaContribuzioneDTO> selectByExample(VExportRicercaContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_export_ricerca_contribuzione
	 * @mbg.generated  Fri Apr 08 14:30:08 CEST 2022
	 */
	int updateByExampleSelective(@Param("record") VExportRicercaContribuzioneDTO record,
			@Param("example") VExportRicercaContribuzioneSelector example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table v_export_ricerca_contribuzione
	 * @mbg.generated  Fri Apr 08 14:30:08 CEST 2022
	 */
	int updateByExample(@Param("record") VExportRicercaContribuzioneDTO record,
			@Param("example") VExportRicercaContribuzioneSelector example);
}